import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT.parent/'unpack_work/campaign_terminal_lifecycle_v1_candidate'));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler,Engine
from tools.chapter08_bsnake.screen_policy_v1 import providers
from ark_sim.tools.replay import replay
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
OUT=ROOT/'validation/campaign/chapter08_terminal_lifecycle_author_v1'
def package():
 p=json.loads((ROOT/'validation/campaign/chapter08_bsnake_rebirth_selfboost_counter_v1/report.json').read_bytes())['input'];boss=p['entities'][0];cfg=boss['components']['rebirth'];cfg['on_begin'][0].pop('condition');loop='ability/terminal/screen10';volley=next(a for a in p['abilities'] if a['id']=='ability/ch8/bsnake/firecommon');p['abilities'].append({'id':loop,'kind':'ability','activation':{'mode':'manual'},'duration_seconds':28,'timeline':[dict(x,at_seconds=2,repeat={'count':10,'interval_seconds':2}) for x in volley['timeline']]});boss['components']['abilities'].append(loop);cfg['zero_restore_lifecycle']={'mode':'terminal_active','counts':[2],'duration_seconds':28,'owned_abilities':[loop],'retained_buffs':[cfg['retain_buffs'][0]],'on_enter':[{'op':'trigger_ability','ability':loop,'target':'source'}]};p['entities'].append({'id':'unit/terminal/victim','kind':'entity','tags':['player'],'components':{'attributes':{'base':{'max_hp':100000,'def':999,'mres':40}},'resources':{'hp':{'initial':100000,'capacity':100000,'role':'health'}},'selection_state':{'side':0,'motion':1,'category':1,'unit_type':1},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle'}}});p['scenarioDraft']['initialEntities'] += [{'definition':'unit/terminal/victim','instanceAlias':'victim'+str(r),'position':{'row':r,'col':3}} for r in range(1,4)];return p

def test_source_second_restore0_28s_real30fireball_damage_onceEnd_CPP400_head():
 p=package();reg=providers();pr=Compiler(providers=reg).compile(p);s=Engine.create(pr,providers=reg,seed=817);s.submit({'action':'skill','source':'player','ability':'ability/counter/kill'},at=1);s.submit({'action':'skill','source':'player','ability':'ability/counter/kill'},at=160);s.advance(320);assert s.ctx.resources.current('boss','hp')==0 and s.ctx.active('boss') and s.ctx.alive('boss');assert s.ctx.get('boss',('runtime','rebirth','phase'))=='terminal_active';s.advance(80);OUT.mkdir(parents=True,exist_ok=True);f=OUT/'terminal400.json';h=write_ordered(f,s.checkpoint());r=Engine.restore(pr,load_bound(f,h),providers=reg);s.advance(760);r.advance(760);assert s.checkpoint()==r.checkpoint()==replay(pr,s.export_replay(),providers=reg).checkpoint();events=s.session.events;hits=[e for e in events if e['type']=='damage.accepted'];assert len(hits)==30 and all(e['payload']['amount']==693 for e in hits);assert len([e for e in events if e['type']=='entity.terminal.completed'])==1 and not s.ctx.alive('boss') and s.ctx.resources.current('boss','hp')==0;assert len([e for e in events if e['type']=='combat.kill' and e['payload']['target']==2])==1;(OUT/'source.json').write_text(json.dumps({'input':p,'cp_sha':h,'snapshot':s.snapshot()},indent=2),encoding='utf8')
