"""Source dmech owned one-shot cannon resource link; no Manfred binding."""
import copy,json,hashlib,math
from pathlib import Path
from tools.chapter10_stage17_ordinary_v1.build import source,SOURCE,BSON
from tools.chapter10_bloodline_v1 import build as blood
P='ch10/dmech/';BODY='unit/'+P+'body';CHARGE='ability/'+P+'charge';INTERRUPT='ability/'+P+'interrupt';FINISH='ability/'+P+'finish';LINK='attachment/'+P+'charge';OWN='buff/'+P+'interrupt';EFFECT='buff/'+P+'effect';TARGET='buff/'+P+'target'
ROOT=Path(__file__).resolve().parents[2]
def instant(inputs,params,context):return {'position':dict(inputs['positions'][0]['last_target']),'reached':True,'motion_state':{}}
def finish_amount(inputs,params,context):
    actor=context['source'];flags=set(actor['components'].get('selection_state',{}).get('abnormal_flags',[]));immunes=set(actor['components'].get('selection_state',{}).get('abnormal_immunes',[]))
    for b in actor['components'].get('buffs',{}).get('instances',[]):
        if b['definition'] not in params['status_definitions']:raise ValueError('Dmech callback missing status definition '+b['definition'])
        if (b['expires_at'] is not None and context['time']>=b['expires_at']) or not b.get('applicability',{}).get('active',True):continue
        d=params['status_definitions'][b['definition']];flags.update(d.get('abnormal_flags',[]));immunes.update(d.get('abnormal_immunes',[]))
    return inputs['current']+(params['delta'] if 12 in flags-immunes else 0)
def providers():
    from ark_sim.domains.providers import BUILTIN_PROVIDERS
    from ark_sim.domains.selection import eligibility_profile
    return {**BUILTIN_PROVIDERS,**blood.providers(),'source.ch10.dmech.instant':{'callable':instant,'version':'native-immediately-reach-next-kernel-step-v1'},'source.ch10.dmech.eligibility':{'callable':eligibility_profile,'version':'native-full-advanced-selector-relative-side-v1'},'source.ch10.dmech.finish_sp':{'callable':finish_amount,'version':'finish-silenced-live-native-status-closure-v1'}}
def bind_status_definitions(p):
    rows=p.get('definitions',p.get('buffs',[]));defs={x['id']:copy.deepcopy(x.get('selection_flags',{})) for x in rows if x.get('kind')=='buff'}
    rules=p.get('rules',[]) or [x for x in rows if x.get('kind')=='rule']
    next(x for x in rules if x['id']=='rule/'+P+'finish_sp')['parameters']['status_definitions']=defs
    return p
def build():
    from ark_sim.domains.selection import DEFAULT_STATE
    v,pref=source('enemy_1223_dmech');raw=v['native_enemy']['resolved'];a=raw['attributes'];skill=raw['skills'][0];bb={x['key']:x['value'] for x in skill['blackboard']};data=blood.build_all();p={k:copy.deepcopy(data.get(k,[])) for k in ['entities','abilities','buffs','rules','selectors','projectiles']};p['schemaVersion']=2;p['definitions']=[]
    cfg=next(c['raw'] for c in pref['components'].values() if c['native_class']=='AdvancedSelectorWithTagAndBuffKey');ranged=next(c['raw'] for c in pref['components'].values() if c['native_class']=='RangedAttack');delay=ranged['_preDelay'];post=ranged['_minPostDelayWhenProjectileInvalid'];projectile=json.loads(SOURCE.read_bytes())['projectiles']['projectile_enemy_dmech_charge'];lasso=next(c['raw'] for c in projectile['components'].values() if c['native_class']=='LassoProjectile');assert lasso['_linkDuration']==bb['hit_duration'] and next(c['raw'] for c in projectile['components'].values() if c['native_class']=='AttachToTarget')['_immediatelyReach']==1
    def rule(name,contract,provider,params=None):return {'id':'rule/'+P+name,'kind':'rule','contract':contract,'parameters':params or {},'implementation':{'type':'provider','provider':provider}}
    p['rules'] += [rule('motion','projectile.trajectory','source.ch10.dmech.instant'),rule('eligibility','targeting.eligibility','source.ch10.dmech.eligibility'),rule('finish_sp','resource.recovery','source.ch10.dmech.finish_sp',{'delta':bb['enemy_dmech_charge[sp_reduce].sp'],'status_definitions':{}})]
    sel='selector/'+P+'cannon';p['selectors'] += [{'id':sel,'kind':'selector','region':{'type':'all'},'filters':[{'state':'alive'},{'tag':cfg['_filterTag']}],'limit':cfg['_maxNum'],'eligibility':{'rule':'rule/'+P+'eligibility','parameters':{'source_configuration':{k:copy.deepcopy(val) for k,val in cfg.items() if k.startswith('_')},'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':copy.deepcopy(DEFAULT_STATE)}}},{'id':'selector/'+P+'blocker','kind':'selector','region':{'type':'all','blocked_only':True},'filters':[{'state':'alive'},{'tag':'player'}],'limit':1}]
    p['buffs'] += [{'id':OWN,'kind':'buff','metadata':{'native':'enemy_dmech_charge[interrupt]','BSON':json.loads(BSON.read_bytes())['templates']['enemy_dmech_charge[interrupt]']['parsed']}},{'id':EFFECT,'kind':'buff','metadata':{'native':'enemy_dmech_charge[effect]','template':'empty','visual':'enemy_dmech_skill_01'}},{'id':TARGET,'kind':'buff','stacking':{'mode':'independent'},'metadata':{'native':'dmech_charge modify_sp[start]','source_sp':bb['sp']}}]
    p['definitions'].append({'id':LINK,'kind':'attachment','duration_seconds':lasso['_linkDuration'],'flight_lifetime_seconds':1,'step_interval_seconds':1/30,'refresh_interval_seconds':bb['interval'],'hit_interval_seconds':bb['interval'],'damage_integral':False,'motion':{'rule':'rule/'+P+'motion','parameters':{}},'target_buff':TARGET,'effect':{'op':'modify_resource','resource':'sp','delta':bb['sp'],'parameters':{'respect_recovery_freeze':True}},'source_cancel_flags':[12,0,16],'ignored_owned_source_flags':[],'force_reach_on_timeout':True,'lifecycle':{'source_invalid':'cancel','target_invalid':'cancel','source_hidden':'cancel','target_hidden':'cancel'},'max_packets':None,'completion_blocking':True,'source_recovery_buff':None,'recovery_on':[]})
    pre_ticks=math.ceil(delay*30);post_ticks=math.ceil(post*30)
    p['abilities'] += [{'id':CHARGE,'kind':'ability','activation':{'mode':'manual','parameters':{'auto_only':True,'auto_when_ready':True},'condition':'inputs.resources.sp.current >= 5 and inputs.resources.native_skill_uses.current > 0','costs':[{'resource':'sp','amount':skill['spCost']},{'resource':'native_skill_uses','amount':1}],'on_start':[{'op':'apply_buff','target':'source','buff':OWN},{'op':'apply_buff','target':'source','buff':EFFECT}]},'selector':sel,'wait_for_channels':True,'cooldown_seconds':skill['cooldown'],'duration_seconds':(pre_ticks+1+post_ticks)/30+bb['hit_duration'],'timeline':[{'at_seconds':pre_ticks/30,'effect':{'op':'begin_attachment','attachment':LINK}}],'metadata':{'native_pre_seconds':delay,'native_post_seconds':post,'reference_quantum':1/30,'phase_policy':'Each float32 delay ceil at30Hz; native immediatelyReach mapped to next actual attachment step; post starts at contact+20sec.'}}, {'id':INTERRUPT,'kind':'ability','activation':{'mode':'passive','event':'ability.interrupted','condition':f"inputs.payload.source == inputs.source.id and inputs.payload.ability == '{CHARGE}'",'parameters':{'auto_only':True,'blocks_attacks':False}},'selector':sel,'timeline':[{'at':0,'effects':[{'op':'modify_resource','resource':'sp','delta':bb['enemy_dmech_charge[sp_reduce].sp']},{'op':'remove_buff','target':'source','buff':OWN},{'op':'remove_buff','target':'source','buff':EFFECT}]}]}, {'id':FINISH,'kind':'ability','activation':{'mode':'passive','event':'ability.finished','condition':f"inputs.payload.source == inputs.source.id and inputs.payload.ability == '{CHARGE}'",'parameters':{'auto_only':True,'blocks_attacks':False}},'selector':sel,'timeline':[{'at':0,'effects':[{'op':'modify_resource','resource':'sp','amount_rule':'rule/'+P+'finish_sp'},{'op':'remove_buff','target':'source','buff':OWN},{'op':'remove_buff','target':'source','buff':EFFECT}]}]}]
    # Native callback belongs to the actual Buff attached by this owned charge.
    # It must run while the source is controlled; a passive ability would be
    # rejected by generic control eligibility and is therefore not a substitute.
    owned=next(b for b in p['buffs'] if b['id']==OWN)
    owned['events']=[]
    for event,amount in [('ability.interrupted',{'delta':bb['enemy_dmech_charge[sp_reduce].sp']}),('ability.finished',{'amount_rule':'rule/'+P+'finish_sp'})]:
        owned['events'].append({'event':event,'condition':f"inputs.payload.source == context.owner.id and inputs.payload.ability == '{CHARGE}'",'effects':[{'op':'modify_resource','resource':'sp','selector':sel,**amount},{'op':'remove_buff','target':'source','buff':EFFECT},{'op':'remove_buff','target':'source','buff':OWN}]})
    p['abilities']=[a for a in p['abilities'] if a['id'] not in (INTERRUPT,FINISH)]
    node=v['modes'][0]['nodes']['_combat'];anim=node['animation_binding'];combat='ability/'+P+'combat';p['abilities'].append({'id':combat,'kind':'ability','activation':{'mode':'automatic_attack','interval_seconds':a['baseAttackTime']},'selector':'selector/'+P+'blocker','duration_seconds':anim['duration']['seconds'],'timeline':[{'at_seconds':anim['events'][0]['seconds'],'effect':{'op':'damage','damage_type':'physical','scale':node['raw']['_atkScale']}}],'metadata':{'native':node}})
    s=raw['spData'];body={'id':BODY,'kind':'entity','tags':['enemy','enemy_1223_dmech',*raw['enemyTags']],'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':1}},'resources':{'hp':{'role':'health','initial':a['maxHp'],'capacity':a['maxHp']},'sp':{'initial':s['initSp'],'capacity':s['maxSp'],'recovery_rate':s['increment']},'native_skill_uses':{'initial':1,'capacity':1}},'selection_state':{'side':1,'category':1,'motion':1,'unit_type':2},'spatial':{'motion_mode':0,'route_motion_mode':0},'abilities':[combat,CHARGE],'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':1}}};blood.attach_death_source(body,raw['talentBlackboard']);p['entities'].append(body)
    p['manifest']={'id':'package/'+P+'source_v1','metadata':{'source_sha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),'bson_sha256':hashlib.sha256(BSON.read_bytes()).hexdigest(),'native_variant':v,'native_prefab':pref,'native_projectile':projectile,'reference_policy':{'maxTriggerTime':'Explicit bounded one-use resource consumed atomically with native5SP; no empty marker authorization','callback':'Actual owned ability.interrupted/finished event starts possessed callback with original charge selector; native method-body equivalence remains unverified','clock':'Declared30Hz source reference; raw pre/post .6669999957 ceil21 ticks each; next attachment step immediate reach adds1; no .9 BB','control':'Lasso silenced12, EnemySkill stun/freeze cast interruption native source; callback all real interrupts -15, finish onlyactualsilence','dependency':'Actual bloodline death child dzoms after1s; gunctrl supplied via exact tag/masks, no Manfred endpoint'},'client_verified':False,'whole_consumer_complete':False}}
    return bind_status_definitions(p)
if __name__=='__main__':
    p=build();out=ROOT/'packages/campaign/chapter10_consumers/dmech/enemy_1223_dmech.module.v1.json';out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(out)
