import sys,json,hashlib,base64,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CAND=(ROOT/'../unpack_work/campaign_c9_duspfr_v1_candidate').resolve();PARENT=(ROOT/'../unpack_work/campaign_c9_pillar_channel_joint_v1_candidate').resolve();sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim.adapters.api import implementation_digest
from tools.chapter09_duspfr_v1.build import build,SOURCE
OUT=ROOT/'validation/campaign/chapter09_duspfr_v1';TOOLS=ROOT/'tools/chapter09_duspfr_v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
before=implementation_digest();reports=[];groups=0;cleanups=[]
for name in ['author.initial.json','author.restore.json','author.regression.json','author.domain46.json','author.performance.json']:
    path=OUT/name;r=json.loads(path.read_bytes());assert r['actual_exit']==0 and r['core_before']==r['core_after']==before
    count=len(r.get('results',[]));groups+=count;reports.append({'path':str(path.relative_to(ROOT)).replace('\\','/'),'sha256':sha(path),'actual_exit':r['actual_exit'],'groups':count,'core_before':r['core_before'],'core_after':r['core_after']});cleanups+=r.get('cleanup',[]) if isinstance(r.get('cleanup',[]),list) else [r['cleanup']]
author=json.loads((OUT/'author.initial.json').read_bytes());assert author['source_guard_equal'] and author['source_before']==author['source_after']
module=build();canonical=hashlib.sha256(json.dumps(module,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest();assert canonical==author['module_before']==author['module_after']
module_path=ROOT/'packages/campaign/chapter09_consumers/duspfr_v1/module.v1.json';module_path.parent.mkdir(parents=True,exist_ok=True);assert not module_path.exists();module_path.write_text(json.dumps(module,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
native=json.loads(SOURCE.read_bytes());bson=[]
for key in ['enemy_duspfr_t[deadboom]','enemy_duspfr_flame[cd]']:
    row=native['bson_templates']['templates'][key];actual=hashlib.sha256(base64.b64decode(row['document_base64'])).hexdigest();assert actual==row['document_sha256'];bson.append({'key':key,'document_sha256':actual})
delta=[]
for p in sorted((CAND/'ark_sim').rglob('*')):
    if not p.is_file() or '__pycache__' in p.parts or p.suffix=='.pyc':continue
    rel=p.relative_to(CAND);old=PARENT/rel
    if not old.exists() or p.read_bytes()!=old.read_bytes():
        target=TOOLS/'source_delta'/rel;target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,target);delta.append({'path':rel.as_posix(),'parent_sha256':sha(old) if old.exists() else None,'candidate_sha256':sha(p),'saved_delta_sha256':sha(target)})
assert before==implementation_digest()
r={'schema':'ark-sim/compact-freeze-receipt/v1','candidate':str(CAND),'parent':str(PARENT),'parent_core':'53ee67c10a664707d8b23bd1191bd5995085ed20cd92837bb8ab64c63f93ff7c','core_before':before,'core_after':implementation_digest(),'parent_whole_suite_passed':False,'parent_full107_failure_preserved':'validation/campaign/chapter09_pillar_channel_joint_v1/full.107.json','module':{'path':str(module_path.relative_to(ROOT)).replace('\\','/'),'sha256':sha(module_path),'canonical_sha256':canonical},'verified_bson':bson,'author_groups':groups,'original_domain_rules_tests':46,'reports':reports,'source_before':author['source_before'],'source_after':author['source_after'],'delta':delta,'helpers':[{'path':str(p.relative_to(ROOT)).replace('\\','/'),'sha256':sha(p)} for p in sorted(TOOLS.glob('*.py'))],'implemented_runtime_scope':['Native8000/500/400/.8,13/30 blocked-only normal attack, unblock/route movement','Independent typed radius1 ground-player trigger/radius2 Flame target','Native10.6/6/10/.5 clock: first and repeat full cast, current stats, source flags/target cancel, HP-first/EP skip on death','Unsilenced owned trait -> exactHP0 deadlike3s; five actual parallel source abilities; Damage/Pull/Kill at1s, Suicide nativefloat32 ceil34 ticks with sourceNone','PullDupilr real5000->4500 candead damage -> positive-health finite owned pillar collapse, no fakeHP','Full historical timing values moved to causal events with strict actor/ability/cast/gen/time/cause/FP and pure timing replay; static/foreign authority rejected','Optional isolated-context compatibility: original DomainRules46 unchanged passed'],'reference_policy':module['manifest']['metadata']['reference_policy'],'independent_review_passed':False,'promoted':False,'pending':['fresh independent review and merged full/baseline gates','client Collider/harpoon/ValidateTarget method equivalence','durable Buff distinction and visuals','whole native stage and Mandra outside scope'],'historical_counters_preserved':['parent.counter.json','parent.pillar_positive.counter.json','development.embedded_timing_growth.counter.json','development.init_positive_profile_failure.ffd0.json','development.fixture_silence_closure_failure.9b06.json','development.fire_fixture_contract_failure.8a48.json'],'raw_deleted':author['raw_deleted'] and json.loads((OUT/'author.regression.json').read_bytes())['raw_deleted'],'cleanup_deleted_bytes':sum(x['reclaimed_bytes'] for x in cleanups),'cleanup_remaining':sum(x['remaining_files'] for x in cleanups),'cleanup_errors':sum(x['error_count'] for x in cleanups)}
(OUT/'freeze.v1.json').write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf8');print(json.dumps({'core':before,'module_sha256':sha(module_path),'freeze_sha256':sha(OUT/'freeze.v1.json'),'delta_files':len(delta),'author_groups':groups,'domain46':46,'cleanup_deleted_bytes':r['cleanup_deleted_bytes'],'cleanup_remaining':r['cleanup_remaining'],'cleanup_errors':r['cleanup_errors']}))
