"""Data loading layer for Ark_emulator.

Consolidates the reverse-engineered data sources under
``ark_parser/enemy/data`` into in-memory structures consumed by the
simulation. All files are read-only; nothing here writes game data.

Sources:
  - stage_sim_bundle.json : levels[levelId] {options, runes, enemyDbRefs,
    enemies, routes (no checkpoints), map {rows, cols, cells}, waveTimeline,
    randomSeed}, stages[stageId] -> levelId, enemyRoster[enemyId] -> data
  - levels/<levelId>.json : full original level incl. mapData.tiles and
    routes[].checkpoints (calibration/complete reference)
  - enemy_database.json   : enemyId -> [{level, data}]
  - skill_behavior_catalog.json : enemyId -> skill behaviour params
"""

import io
import json
import os

_DEFAULT_DIR = r"G:\Arknights\ark_parser\enemy\data"
_CHAR_DIR = r"G:\Arknights\ark_parser\character\data"


def _load(path):
    """Load a JSON data file.  Data files may be regenerated by external
    extraction processes; retry briefly when the file is mid-write (the
    parse raises JSONDecodeError), then surface the real error."""
    last = None
    for _ in range(3):
        try:
            with io.open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except ValueError as ex:      # JSONDecodeError subclasses ValueError
            last = ex
            try:
                import time
                time.sleep(0.4)
            except Exception:
                break
    raise last


# Process-level caches for the heavy merged prefab catalog (each Simulator
# creates its own DataStore; the ~80MB base+current dump must only be
# parsed once per process).
_PREFAB_CATALOG_CACHE = None
_CURRENT_PREFAB_CACHE = None

# Process-level caches for the other heavy per-DataStore loads.  The stage
# bundle (~149MB JSON -> ~750MB in memory) and the raw level assets are
# read-only after parsing; sharing one parsed copy across every Simulator
# in the process keeps the footprint flat instead of growing ~750MB per
# battle (8 parallel scan workers previously spiked >6GB and pushed the
# system into MemoryError / killed unrelated processes).
_BUNDLE_CACHE = {}
_LEVELS_CACHE = {}
_ENV_SYSTEMS_CACHE = None


def _i2f(val):
    """Float bits (int32 stored in JSON) -> float (game blackboard values)."""
    import struct
    try:
        bits = int(val) & 0xFFFFFFFF
        return round(struct.unpack("<f", struct.pack("<I", bits))[0], 4)
    except (TypeError, ValueError, OverflowError):
        return val


# Prefab-key naming variants between enemy_database skill prefabKeys and
# the extracted GameObject names (verified in enm_pfb cabs):
#   cut_tree -> CutTree   (enemy_1512_mcmstr \u4f10\u6728: the prefab is
#                          named CutTree, the db key uses snake_case)
#   BoomAll  -> DeathBoomAll (enemy_1543_cstlrs \u514b\u4e3d\u65af\u817e:
#                          the full-map boom prefab is named DeathBoomAll)
PREFAB_KEY_ALIASES = {
    "cut_tree": "CutTree",
    "cuttree": "CutTree",   # older game builds named the GameObject cuttree
    "BoomAll": "DeathBoomAll",
}


class DataStore:
    """Lazy loader; data is loaded once and cached on first access."""

    # shared raw-level cache (class attribute: one copy per process, the
    # per-instance init below no longer shadows it)
    _levels = _LEVELS_CACHE

    def __init__(self, data_dir=_DEFAULT_DIR):
        self.data_dir = data_dir
        self._bundle = None
        self._enemy_db = None
        self._flying = None
        self._skill_catalog = None
        self._prefab_catalog = None
        self._characters = None
        self._skills = None
        self._op_prefabs = None
        self._char_dir = _CHAR_DIR if data_dir == _DEFAULT_DIR else \
            os.path.join(data_dir, "..", "character", "data")
        self._level_assets = None
        self._overrides = None
        self._prefab_overrides = None
        self._current_prefabs = None
        self._module_stats = None
        self._battle_equip = None
        self._trust = None
        self._go_name = None
        self._op_catalog = None
        self._comp_prefab = None
        self._shared_prefabs = None

    # ---- files ----
    @property
    def bundle(self):
        if self._bundle is None:
            key = os.path.normpath(self.data_dir)
            cached = _BUNDLE_CACHE.get(key)
            if cached is None:
                cached = _load(os.path.join(
                    self.data_dir, "stage_sim_bundle.json"))
                _BUNDLE_CACHE[key] = cached
            self._bundle = cached
        return self._bundle

    @property
    def enemy_database(self):
        if self._enemy_db is None:
            self._enemy_db = _load(os.path.join(self.data_dir, "enemy_database.json"))
        return self._enemy_db

    @property
    def flying_enemy_keys(self):
        """Enemy keys that are airborne (flight units)."""
        if self._flying is None:
            keys = set()
            for k, entries in self.enemy_database.items():
                if not isinstance(entries, list) or not entries:
                    continue
                first = entries[0] if isinstance(entries[0], dict) else {}
                desc = (first.get("data") or {}).get("description") or ""
                if isinstance(desc, str) and \
                        "\u98de\u884c\u5355\u4f4d" in desc:
                    keys.add(k)
            try:
                hb = _load(os.path.join(self.data_dir, "enemy_handbook.json"))
            except Exception:
                hb = {}
            for k, v in hb.items():
                if not isinstance(v, dict):
                    continue
                tags = v.get("13")
                if isinstance(tags, list) and any(
                        "\u98de\u884c" in str(t) for t in tags):
                    keys.add(k)
            self._flying = keys
        return self._flying

    def is_flying_enemy(self, enemy_key):
        if enemy_key in self.flying_enemy_keys:
            return True
        try:
            resolved = self.resolve_enemy_key(enemy_key)
        except Exception:
            resolved = enemy_key
        return resolved in self.flying_enemy_keys

    @property
    def skill_catalog(self):
        if self._skill_catalog is None:
            self._skill_catalog = _load(os.path.join(self.data_dir, "skill_behavior_catalog.json"))
        return self._skill_catalog

    @property
    def prefab_catalog(self):
        """Full skill prefab serialisation (4423 prefabs, 47802 components).
        Keyed by prefabKey; each value is {components:[{class, fields}]}.
        The current-version enemy prefab dump (data_enemy_prefab_catalog_current.json,
        from the 2026-08-01 enm_pfb bundles) is merged on top: same-name
        keys are replaced by the current data, new enemy prefab keys are
        added (e.g. enemy_2138_shdbjg / enemy_2140_shsgzd / enemy_4064_mupenb)."""
        global _PREFAB_CATALOG_CACHE, _CURRENT_PREFAB_CACHE
        if _PREFAB_CATALOG_CACHE is None:
            base_cat = _load(os.path.join(
                self.data_dir, "skill_prefab_catalog.json"))
            merged = dict(base_cat)
            prefs = dict(base_cat.get("prefabs") or {})
            try:
                if _CURRENT_PREFAB_CACHE is None:
                    _CURRENT_PREFAB_CACHE = _load(os.path.join(
                        os.path.dirname(os.path.abspath(__file__)),
                        "data_enemy_prefab_catalog_current.json"))
                cur_prefs = (_CURRENT_PREFAB_CACHE.get("prefabs") or {})
                prefs.update(cur_prefs)
            except Exception:
                pass
            merged["prefabs"] = prefs
            _PREFAB_CATALOG_CACHE = merged
        self._prefab_catalog = _PREFAB_CATALOG_CACHE
        return self._prefab_catalog

    def _resolve_prefab_key(self, prefab_key):
        """Resolve db prefabKey variants to the extracted GameObject name."""
        if prefab_key in PREFAB_KEY_ALIASES:
            return PREFAB_KEY_ALIASES[prefab_key]
        return prefab_key

    def _prefab_override(self, key):
        """Locally extracted prefab components for db prefabKeys that have
        no matching GameObject name in the base catalog (data extracted from
        the current enm_pfb bundles via ArknightsStudioCLI JSON export):
          - Shining   (enemy_2138/2139 \u6c49\u79d1 flare: projectile_
            enemy_shdbjg_shining + enemy_shsmok_disable reveal buff)
          - Countdown (enemy_4064 \u51b3\u80dc\u65f6\u523b\u7403 10s
            countdown buff applier)
        """
        if self._prefab_overrides is None:
            import io as _io
            _p = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "data_enemy_prefab_overrides.json")
            try:
                with _io.open(_p, encoding="utf-8") as _f:
                    self._prefab_overrides = json.load(_f)
            except Exception:
                self._prefab_overrides = {}
        return (self._prefab_overrides.get(key) or {}).get("components") or []

    def prefab_components(self, prefab_key):
        """All components of a prefab (list of {class, fields}). Prefab-key
        naming variants (cut_tree/CutTree, BoomAll/DeathBoomAll) resolve
        through PREFAB_KEY_ALIASES; db keys without a matching GameObject
        name fall back to the local override table."""
        key = self._resolve_prefab_key(prefab_key)
        comps = (self.prefab_catalog.get("prefabs") or {}).get(key, {}).get("components")
        if comps:
            return comps
        return self._prefab_override(prefab_key)

    def prefab_ability_fields(self, prefab_key):
        """Merge fields of Ability/AbilityStandard/AttackAbility/ProjectileAbility
        components into one dict (later components override earlier)."""
        out = {}
        for c in self.prefab_components(prefab_key):
            cls = c.get("class", "")
            if cls in ("Ability", "AbilityStandard", "AttackAbility",
                       "ProjectileAbility", "BuffAbility", "CompositeAbility"):
                out.update(c.get("fields") or {})
        return out

    def enemy_prefab_components(self, enemy_key, prefab_key):
        """Prefab components scoped to ONE enemy.

        The extracted catalog merges same-named prefabs used by several
        enemies under one key (e.g. "Invincible" carries the components of
        telex / faust / ymmons / xbmoth... all in one list).  When a merged
        list is detected, the owner's components are located by matching
        buffKeys that contain the enemy's code (enemy_7021_xbmoth ->
        "xbmoth", e.g. enemy_xbmoth_s[mode]) and only the cabins holding
        those components are kept, so a cast only applies the caster's own
        buffs/abilities instead of every enemy's.
        """
        comps = self.prefab_components(prefab_key)
        if len(comps) <= 8:
            return comps
        code = str(enemy_key).split("_", 2)[-1] if enemy_key else ""
        if not code:
            return comps
        # variant suffixes (_2/_3/_a/_b...) belong to the enemy LEVEL, not
        # the code: enemy_9013_acstmk_2's buffKeys mention "acstmk".
        codes = {code}
        tail = code
        while "_" in tail:
            suf = tail.rsplit("_", 1)[1]
            if suf.isdigit() or (len(suf) == 1 and suf.isalpha()):
                tail = tail.rsplit("_", 1)[0]
                codes.add(tail)
            else:
                break
        def _comp_bks(c):
            f = c.get("fields") or {}
            return [str(b.get("buffKey"))
                    for _k in ("_buffs", "_activeBuffs", "_passiveBuffs")
                    for b in (f.get(_k) or [])
                    if isinstance(b, dict) and b.get("buffKey")]
        # if no component can be attributed to this enemy (buffKeys use
        # inherited/shared names, e.g. mpbarr uses mpprme_spawn_mark),
        # keep the whole prefab: dropping would remove its real effects.
        if not any(enemy_key in _comp_bks(c) or
                   any(cd in bk for cd in codes for bk in _comp_bks(c))
                   for c in comps):
            return comps
        out = []
        for c in comps:
            f = c.get("fields") or {}
            bks = _comp_bks(c)
            if not bks:
                # unassignable component (pure ability / selector / anim):
                # keep it - dropping it would remove damage types etc.
                out.append(c)
                continue
            if enemy_key in bks or any(cd in bk
                                       for cd in codes for bk in bks):
                out.append(c)
                continue
            if ("_selfOption" in f or "_startEvent" in f or
                    "_endEvent" in f or "_forceFinishBuffOnCastEnd" in f):
                # capability container (aura / BuffToOwnerDuringAbility):
                # keep conservatively - it drives the caster's own effect
                out.append(c)
                continue
            # else: the component only carries buffs of OTHER enemies
            # sharing the same prefab key - drop it
        return out

    def enemy_prefab_ability_fields(self, enemy_key, prefab_key):
        """prefab_ability_fields scoped to one enemy (see
        enemy_prefab_components for the merged-prefab problem)."""
        out = {}
        for c in self.enemy_prefab_components(enemy_key, prefab_key):
            cls = c.get("class", "")
            if cls in ("Ability", "AbilityStandard", "AttackAbility",
                       "ProjectileAbility", "BuffAbility", "CompositeAbility"):
                out.update(c.get("fields") or {})
        return out

    def synthesize_skill_entry(self, enemy_key, skill):
        """Build a behavior-catalog-style entry straight from the full prefab
        catalog (mirrors ark_parser/enemy/build_skill_behavior.py) for skills
        whose prefabKey is not in skill_behavior_catalog.json but resolves in
        the prefab catalog (e.g. cut_tree -> CutTree, BoomAll -> DeathBoomAll).
        Returns None when the prefab is unavailable."""
        pk = skill.get("prefabKey")
        if not pk:
            return None
        comps = self.prefab_components(pk)
        if not comps:
            return None

        def _find(cls):
            return [c for c in comps if c.get("class") in
                    (cls if isinstance(cls, tuple) else (cls,))]

        eskill = _find("EnemySkill")
        es = {}
        if eskill:
            f = eskill[0].get("fields") or {}
            for k in ("_familyMask", "_maxTriggerTime", "_overwriteInitCooldown",
                      "_ignoreSilence", "_castLikeAttack",
                      "_resetMainAbilityCdWhenCastEnd", "_resetCdWaitFirstPeriod",
                      "_checkParentActive", "_spCost",
                      "_immuneStunWhenAffecting", "_addEnemyIdToSignalId"):
                if k in f:
                    es[k] = f[k]
        abilities = []
        for a in _find(("Ability", "AbilityStandard", "AttackAbility",
                        "ProjectileAbility", "CompositeAbility", "BuffAbility")):
            f = a.get("fields") or {}
            abilities.append({k: f[k] for k in (
                "_waitForAttackEvent", "_timeMode", "_preDelay", "_atkScale",
                "_interuptIfTargetDead", "_selectTargetTiming",
                "_selectTargetSource", "_allowNoTarget", "_alwaysIncludeTarget",
                "_attackBlackboardModeIndex", "_defaultModeIndex",
                "_extraCondition", "_maxTarget", "_onlyRunOnce",
                "_preDelayFactor", "_purposeMask", "_resetCdStrategy")
                if k in f})
        trigger = {}
        trig_ref = (eskill[0].get("fields") or {}).get("_trigger") if eskill else None
        if isinstance(trig_ref, dict):
            pid = trig_ref.get("m_PathID")
            pool = list(comps)
            # inline enemy skills' triggers live in the enemy's own prefab
            # (current catalog carries pathIDs); fall back to it
            if not any(c.get("pathID") == pid for c in pool):
                try:
                    pool += self.prefab_components(enemy_key)
                except Exception:
                    pass
            for c in pool:
                if c.get("pathID") == pid:
                    f = c.get("fields") or {}
                    if any(k in f for k in (
                            "_triggerType", "_targetRange", "_time",
                            "_hpRatio", "_damageTakenRatio", "_interval",
                            "_maxTriggerTime", "_normalSkillOnly",
                            "_condition", "_radius", "_target", "_minHpRatio",
                            "_keepTarget", "_minTargetNum")):
                        trigger = {k: f[k] for k in (
                            "_triggerType", "_targetRange", "_time",
                            "_hpRatio", "_damageTakenRatio", "_condition",
                            "_extraCondition", "_event", "_forcePredict",
                            "_normalSkillOnly", "_maxTriggerTime",
                            "_interval", "_radius", "_target", "_buffKeys",
                            "_minHpRatio", "_keepTarget", "_minTargetNum")
                            if k in f}
                    break
        buff_keys = set()
        for c in comps:
            def _walk(v):
                if isinstance(v, dict):
                    if isinstance(v.get("buffKey"), str) and v["buffKey"]:
                        buff_keys.add(v["buffKey"])
                    if isinstance(v.get("templateKey"), str) and v["templateKey"]:
                        buff_keys.add(v["templateKey"])
                    for x in v.values():
                        _walk(x)
                elif isinstance(v, list):
                    for x in v:
                        _walk(x)
            _walk(c.get("fields") or {})
        return {
            "prefabKey": pk,
            "enemyId": enemy_key,
            "blackboard": skill.get("blackboard"),
            "priority": skill.get("priority"),
            "cooldown": skill.get("cooldown"),
            "initCooldown": skill.get("initCooldown"),
            "spCost": skill.get("spCost"),
            "enemySkill": es,
            "trigger": trigger,
            "abilities": abilities,
            "buffKeys": sorted(buff_keys),
            "_synthesized": True,
        }

    @property
    def characters(self):
        """character/data/characters.json (operator base data)."""
        if self._characters is None:
            self._characters = _load(os.path.join(self._char_dir, "characters.json"))
        return self._characters

    @property
    def module_stats(self):
        """character/data/module_stats.json: moduleId -> phases[level] ->
        {bb: {stat: value}} (X/Y module attribute bonuses per level)."""
        if self._module_stats is None:
            try:
                self._module_stats = _load(os.path.join(
                    self._char_dir, "module_stats.json"))
            except Exception:
                self._module_stats = {}
        return self._module_stats

    @property
    def trust_bonuses(self):
        """character/data/trust_prts.json: charId -> {hp, atk, def} at 200%
        trust (\u4fe1\u8d56\u52a0\u6210\u4e0a\u9650)."""
        if self._trust is None:
            try:
                self._trust = _load(os.path.join(self._char_dir,
                                                 "trust_prts.json"))
            except Exception:
                self._trust = {}
        return self._trust

    @property
    def battle_equip(self):
        """character/data/battle_equip.json: moduleId -> phase talent
        upgrades / stat deltas (module trait/talent phases)."""
        if self._battle_equip is None:
            try:
                self._battle_equip = _load(os.path.join(
                    self._char_dir, "battle_equip.json"))
            except Exception:
                self._battle_equip = {}
        return self._battle_equip

    @staticmethod
    def _module_phases(be):
        """Sorted [(equip_level, phase_dict)] from battle_equip '0' phases,
        skipping malformed entries whose level field is not an int."""
        out = []
        for p in (be.get("0") or []):
            if not isinstance(p, dict):
                continue
            try:
                lv = int(p.get("0") or 0)
            except (TypeError, ValueError):
                continue
            out.append((lv, p))
        return sorted(out, key=lambda item: item[0])

    def module_talent_upgrades(self, module_id, level=3):
        """Module talent blackboard upgrades: list of
        {talent_index (1-based), name, values} for the given module level.

        battle_equip[moduleId]['0'] = phases [{0: level, 1: [entries]}];
        each upgrade entry's '1'[0]['0'] holds candidate dicts with
        '6' = 1-based talent index, '7' = talent name and '10' = ordered
        blackboard values (float bits). candidate[0] is the base module
        value (candidate[1] is the potential-upgraded variant)."""
        if not module_id:
            return []
        be = self.battle_equip.get(module_id)
        if not be:
            return []
        phases = self._module_phases(be)
        best = None
        for _ph_lv, ph in phases:
            if _ph_lv <= max(1, int(level or 1)):
                best = ph
        if best is None:
            return []
        out = []
        for entry in best.get("1") or []:
            lst = (entry or {}).get("1")
            if not isinstance(lst, list) or not lst:
                continue
            inner = lst[0]
            if not isinstance(inner, dict):
                continue
            cands = inner.get("0")
            if not isinstance(cands, list):
                continue
            for c in cands:
                if not isinstance(c, dict) or "6" not in c:
                    continue
                try:
                    ti = int(c.get("6"))
                except (TypeError, ValueError):
                    continue
                vals = []
                _v10 = c.get("10")
                if not isinstance(_v10, list):
                    _v10 = []
                for kv in _v10:
                    if not isinstance(kv, dict) or "1" not in kv:
                        continue
                    try:
                        vals.append(_i2f(int(kv.get("1"))))
                    except (TypeError, ValueError):
                        continue
                out.append({"talent_index": ti, "name": c.get("7"),
                            "values": vals})
        return out

    def module_trait_upgrades(self, module_id, level=3):
        """Module trait (\u7279\u6027) blackboard upgrades: list of
        {values} (one per overrideTraitDataBundle candidate) for the given
        module level.  Same phase selection as module_talent_upgrades;
        each phase part carries the trait bundle under ``6`` with candidates
        in ``6.0`` and the blackboard DataPair list in candidate ``3``
        (e.g. \u54c8\u6d1b\u5fb7 WDM-X: ep_heal_ratio 0.5 -> 0.6 at module
        level 1+)."""
        if not module_id:
            return []
        be = self.battle_equip.get(module_id)
        if not be:
            return []
        phases = self._module_phases(be)
        best = None
        for _ph_lv, ph in phases:
            if _ph_lv <= max(1, int(level or 1)):
                best = ph
        if best is None:
            return []
        out = []
        for part in best.get("1") or []:
            bundle = (part or {}).get("6")
            if not isinstance(bundle, dict):
                continue
            for c in (bundle.get("0") or []):
                if not isinstance(c, dict):
                    continue
                vals = []
                _bb = c.get("3")
                if not isinstance(_bb, list):
                    _bb = []
                for kv in _bb:
                    if not isinstance(kv, dict) or "1" not in kv:
                        continue
                    try:
                        vals.append(_i2f(int(kv.get("1"))))
                    except (TypeError, ValueError):
                        continue
                if vals:
                    out.append({"values": vals})
        return out

    def module_stat_bonus(self, module_id, level=3):
        """Module attribute bonus dict (bb keys: max_hp/atk/def/attack_speed/
        magic_resistance/cost/respawn_time/block_cnt) for the given level, or
        None when the module/level is unknown."""
        if not module_id:
            return None
        m = self.module_stats.get(module_id)
        if not m:
            return None
        phases = sorted(((ph or {}) for ph in (m.get("phases") or [])),
                        key=lambda ph: int(ph.get("level") or 0))
        best = None
        for ph in phases:
            if int(ph.get("level") or 0) <= max(1, int(level or 1)):
                best = ph
        if best is None:
            return None
        return dict(best.get("bb") or {})

    @property
    def character_skills(self):
        """character/data/skills.json (skillId -> {skillId, levels})."""
        if self._skills is None:
            self._skills = _load(os.path.join(self._char_dir, "skills.json"))
        return self._skills

    @property
    def skill_prefab_overrides(self):
        """skillId -> MainSkill.overridePrefabKey (characters.json).

        Token/summon skills often declare an empty runtime prefab override
        (e.g. sktok_phatm2_mndclv_3 -> sktok_empty); component lookups must
        use the override, not the LevelData.prefabId.
        """
        if self._overrides is None:
            self._overrides = {}
            try:
                for c in self.characters.values():
                    for ms in (c.get("skills") or []):
                        sid = ms.get("skillId")
                        ov = ms.get("overridePrefabKey")
                        if sid and ov:
                            self._overrides[sid] = ov
            except Exception:
                self._overrides = {}
        return self._overrides

    @property
    def _go_path_to_name(self):
        """GameObject pathID -> prefab name (from catalog meta; Composite
        Ability `_abilities` PPtrs resolve through this map)."""
        if self._go_name is None:
            self._go_name = {}
            try:
                meta = (self.operator_skill_catalog.get("meta") or {})
                m = meta.get("gameObjectPathIDToName") or {}
                self._go_name = {int(k): v for k, v in m.items()}
            except Exception:
                self._go_name = {}
        return self._go_name

    @property
    def operator_skill_catalog(self):
        """Full operator skill prefab catalog (per-component fields +
        GameObject pathID map)."""
        if self._op_catalog is None:
            p = os.path.join(self._char_dir,
                             "skill_prefab_catalog_operator.json")
            try:
                self._op_catalog = _load(p) if os.path.exists(p) else {}
            except Exception:
                self._op_catalog = {}
        return self._op_catalog

    @property
    def _shared_prefab_names(self):
        """Prefab names referenced by >=3 skills: shared ability templates
        (ExtraAbility0 / Aura / Attack ...) whose fields must not be
        attributed to individual skills."""
        if self._shared_prefabs is None:
            counter = {}
            comp_prefab = self._component_prefab_map
            prefabs = (self.operator_skill_catalog.get("prefabs") or {})
            for name, v in prefabs.items():
                if not (name.startswith("skchr_") or
                        name.startswith("sktok_")):
                    continue
                seen = set()

                def visit(n):
                    if n in seen:
                        return
                    seen.add(n)
                    for c in (prefabs.get(n, {}).get("components") or []):
                        for fk in ("_abilities", "_extraAbilities",
                                   "_wrappedAbilities"):
                            for ref in (c.get("fields", {}).get(fk) or []):
                                pid = (ref or {}).get("m_PathID")
                                sub = comp_prefab.get(pid) \
                                    if pid is not None else None
                                if sub:
                                    counter[sub] = counter.get(sub, 0) + 1
                                    visit(sub)
                visit(name)
            self._shared_prefabs = {k for k, n in counter.items() if n >= 3}
        return self._shared_prefabs

    @property
    def _component_prefab_map(self):
        """MonoBehaviour pathID -> prefab name (CompositeAbility._abilities
        PPtrs reference Ability *components*; their owner prefab is found
        through this map)."""
        if self._comp_prefab is None:
            m = {}
            for name, v in (self.operator_skill_catalog.get(
                    "prefabs") or {}).items():
                for c in (v.get("components") or []):
                    pid = c.get("pathID")
                    if pid is not None:
                        m.setdefault(pid, name)
            self._comp_prefab = m
        return self._comp_prefab

    def operator_prefab_for_skill(self, skill_id):
        """Runtime prefab components for a skill (override-aware),
        including components reachable through CompositeAbility._abilities
        PPtr references (sub-prefabs), deduped by prefab name."""
        ov = self.skill_prefab_overrides.get(skill_id or "")
        root = ov or skill_id or ""
        prefabs = self.operator_skill_prefabs
        comp_prefab = self._component_prefab_map
        shared = self._shared_prefab_names
        out = []
        seen = set()

        # PPtr-list fields that reference other Ability components
        _ABILITY_REF_FIELDS = ("_abilities", "_extraAbilities",
                               "_wrappedAbilities")
        # character code from "skchr_<code>_<n>" / "sktok_<code>..."
        _parts = (skill_id or "").split("_")
        _code = _parts[1] if len(_parts) > 1 else ""

        def _matches_skill(comp):
            """Shared templates carry per-operator assets (e.g. the generic
            'Attack' prefab holds Ling's projectile); only attribute them
            when the projectile key names this skill's operator."""
            pk = comp.get("_projectileKey")
            if not pk:
                return False
            return _code and _code in str(pk)

        def visit(name):
            if not name or name in seen:
                return
            if name in shared:
                # shared building block: include only the components whose
                # projectile belongs to this operator (e.g. horn_s1)
                keep = [c for c in (prefabs.get(name) or [])
                        if _matches_skill(c)]
                if not keep:
                    return
                seen.add(name)
                out.extend(keep)
                return
            seen.add(name)
            comps = prefabs.get(name) or []
            for c in comps:
                out.append(c)
                for fk in _ABILITY_REF_FIELDS:
                    for ref in (c.get(fk) or []):
                        pid = (ref or {}).get("m_PathID")
                        sub = comp_prefab.get(pid) if pid is not None \
                            else None
                        if sub:
                            visit(sub)
        visit(root)
        return out

    @property
    def operator_skill_prefabs(self):
        """character/data/operator_skill_prefab_summary.json, keyed by skill
        prefabId: [{class, namedAsAlias, _buffs, _activeBuffs, ...}]."""
        if self._op_prefabs is None:
            p = os.path.join(self._char_dir,
                             "operator_skill_prefab_summary.json")
            if os.path.exists(p):
                try:
                    self._op_prefabs = (_load(p).get("prefabs") or {})
                except Exception:
                    self._op_prefabs = {}
            else:
                self._op_prefabs = {}
        return self._op_prefabs

    def raw_level(self, level_id):
        """Full original level JSON (mapData.tiles + checkpoints).

        Prefers the freshly unpacked game asset (level_assets_full), which
        carries complete runes/globalBuffs/branches; falls back to the
        older extracted levels/<id>.json."""
        if level_id in self._levels:
            return self._levels[level_id]
        if self._level_assets is None:
            idx = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "data_level_assets_index.json")
            self._level_assets = _load(idx) if os.path.exists(idx) else {}
        asset = self._level_assets.get(level_id)
        if asset and os.path.exists(asset):
            try:
                sys_path_ok = _parse_level_asset(asset, level_id)
                if sys_path_ok:
                    return self._levels[level_id]
            except Exception:
                pass
        path = os.path.join(self.data_dir, "levels", f"{level_id}.json")
        self._levels[level_id] = _load(path)
        return self._levels[level_id]

    # ---- lookups ----
    def sim_level(self, level_id):
        return self.bundle["levels"].get(level_id)

    def stage_to_level(self, stage_id):
        return self.bundle["stages"].get(stage_id, {}).get("levelId") \
            if isinstance(self.bundle.get("stages"), dict) else None

    def env_system_config(self, env_key):
        """GlobalEnvSystem manager config (env_v060_mainline15_prtsCtrl).
        Extracted from [uc]envsystems AB (unpack_work) via UnityPy typetree
        - one parsed copy shared process-wide."""
        global _ENV_SYSTEMS_CACHE
        if _ENV_SYSTEMS_CACHE is None:
            try:
                _p = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                  "data_env_systems.json")
                _ENV_SYSTEMS_CACHE = _load(_p)
            except Exception:
                _ENV_SYSTEMS_CACHE = {}
        return _ENV_SYSTEMS_CACHE.get(env_key)

    def enemy_roster(self, enemy_key):
        return self.bundle["enemyRoster"].get(enemy_key)

    def enemy_db_entries(self, enemy_key):
        """enemy_database[enemy_key] -> list of {level, data}; base first."""
        return self.enemy_database.get(enemy_key) or []

    def enemy_skills(self, enemy_key):
        """Skill behaviour catalogue entries for an enemy. The catalogue is
        keyed by prefabKey with enemyId inside each entry, so we scan (it is
        loaded once and cached; ~682 keys). Skills whose prefabKey is missing
        from the behaviour catalog but resolves in the full prefab catalog
        (via PREFAB_KEY_ALIASES) are synthesized on the fly."""
        out = []
        for entries in self.skill_catalog.values():
            for e in entries:
                if e.get("enemyId") == enemy_key:
                    out.append(e)
        have = {e.get("prefabKey") for e in out}
        try:
            entries = self.enemy_db_entries(enemy_key)
        except Exception:
            entries = []
        for lv in entries:
            d = lv.get("data") or {}
            for sk in d.get("skills") or []:
                pk = sk.get("prefabKey")
                if pk and pk not in have:
                    syn = self.synthesize_skill_entry(enemy_key, sk)
                    if syn is not None:
                        out.append(syn)
                        have.add(pk)
        return out

    def resolve_enemy_key(self, enemy_key):
        """Resolve an enemy key to a key present in the database.

        The game's db contains base enemies; keys with variant suffixes
        (e.g. enemy_1346_ynshp_a -> enemy_1346_ynshp) fall back to the
        base entry, and wave-instance keys (enemy_1056_ganwar#1) drop the
        #N instance suffix. Returns the resolved key (or the original if
        none).
        """
        key = enemy_key or ""
        if "#" in str(key):
            key = str(key).split("#", 1)[0]
        if key in self.enemy_database or key in (
                self.bundle.get("enemyRoster") or {}):
            return key
        parts = str(key).split("_")
        for i in range(len(parts) - 1, 1, -1):
            cand = "_".join(parts[:i])
            if cand in self.enemy_database or cand in (
                    self.bundle.get("enemyRoster") or {}):
                return cand
        return key

    def build_merged_enemy(self, enemy_key, level=0, overwritten_data=None):
        """Merge enemy_database base + level deltas (+ optional overwritten
        data) into a single plain dict with 'data' contents."""
        resolved = self.resolve_enemy_key(enemy_key)
        if resolved != enemy_key:
            self._resolved_variants = getattr(self, "_resolved_variants", {})
            self._resolved_variants[enemy_key] = resolved
        entries = self.enemy_db_entries(resolved)
        if not entries:
            roster = self.enemy_roster(resolved)
            if roster is None:
                raise KeyError(f"no enemy data for {enemy_key}")
            return {"data": roster, "level": level}
        # entries are sorted with base (level null) first
        base = entries[0]["data"] or {}
        merged = json.loads(json.dumps(base))
        for ent in entries[1:]:
            if ent.get("level") == level:
                merged = _deep_merge(merged, ent["data"] or {})
        if overwritten_data:
            merged = _deep_merge(merged, overwritten_data)
        return {"data": merged, "level": level}


def _parse_level_asset(asset_path, level_id):
    """Parse a freshly unpacked level asset into the same shape as the
    extracted levels/<id>.json. Returns True on success."""
    import sys
    import importlib.util
    import os as _os
    spec = importlib.util.spec_from_file_location(
        "extract_level_data", r"G:\Arknights\ark_parser\enemy\extract_level_data.py")
    ext = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ext)
    out = ext.parse_level_file(asset_path)
    if not out or out[0] is None:
        return False
    DataStore._levels[level_id] = out[0]
    return True


def _deep_merge(base, delta):
    """Recursively overlay delta onto base (None values in delta ignored)."""
    out = dict(base)
    for k, v in (delta or {}).items():
        if v is None:
            continue
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def merged_map(store, level_id):
    """Merge sim bundle map (rows/cols/cells) with raw level tiles to return
    {rows, cols, cells, tiles}.

    ``mapData.tiles`` is a tile-definition array in the game's bottom-based
    grid order.  The compact sim bundle's ``cells`` array is the authoritative
    top-based, row-major lookup used by the renderer.  Returning the raw tile
    array directly used to mirror every official map vertically.
    """
    sim = store.sim_level(level_id)
    raw = store.raw_level(level_id)
    m = sim.get("map") or {}
    if not m:
        # metadata-only levels (script tables, placeholder entries) carry no
        # playable map; expose an empty grid so loading does not crash.
        m = {"rows": 0, "cols": 0, "cells": []}
    rows = int(m.get("rows") or 0)
    cols = int(m.get("cols") or 0)
    cells = m.get("cells") or []
    out = {
        "rows": rows,
        "cols": cols,
        "cells": cells,
        "tiles": raw.get("mapData", {}).get("tiles") or [],
    }
    return out


def merged_routes(store, level_id):
    """Merge routes and normalize game GridPosition rows for the web grid.

    Game ``GridPosition`` uses row 0 at the bottom, while ``GameMap`` and the
    browser use row 0 at the top.  Positions are converted exactly once here;
    all public deploy/action coordinates are consequently top-based.
    """
    sim = store.sim_level(level_id)
    raw = store.raw_level(level_id)
    sim_routes = sim.get("routes") or []
    raw_routes = raw.get("routes") or []
    rows = int((sim.get("map") or {}).get("rows") or 0)

    def top_based(pos):
        if not isinstance(pos, dict):
            return pos
        point = json.loads(json.dumps(pos))
        if rows > 0 and point.get("row") is not None:
            point["row"] = rows - 1 - int(point["row"])
        return point

    out = []
    for i, r in enumerate(sim_routes):
        if not isinstance(r, dict):
            # null route entries in the official gamedata levels keep their
            # list position; an inert empty route preserves the index
            out.append({"startPosition": {"row": 0, "col": 0},
                        "endPosition": {"row": 0, "col": 0},
                        "checkpoints": []})
            continue
        entry = json.loads(json.dumps(r))
        if i < len(raw_routes) and isinstance(raw_routes[i], dict):
            # DataStore caches parsed levels.  Deep-copy before coordinate
            # normalization so repeated Simulator instances never flip the
            # cached source data back and forth.
            entry["checkpoints"] = json.loads(json.dumps(
                raw_routes[i].get("checkpoints") or []))
        else:
            entry["checkpoints"] = []
        entry["startPosition"] = top_based(entry.get("startPosition"))
        entry["endPosition"] = top_based(entry.get("endPosition"))
        for checkpoint in entry["checkpoints"]:
            if isinstance(checkpoint, dict):
                checkpoint["position"] = top_based(
                    checkpoint.get("position"))
        out.append(entry)
    return out
