"""Exact simplest native C7 melee; no passive/skills/SP resource invented."""
import hashlib,json,sys
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RUNTIME=ROOT.parent/'unpack_work/campaign_chapter06_complete_base_v5_candidate';OUT=ROOT/'packages/campaign/chapter07_ordinary';sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
CORE='a7059989b9db7f4bc0de954b32cb5c5ba10e6b92ce040c57ea0a193549b9709a';VID='enemy_1077_sotihd@0/11aeb9d877d72938'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==CORE;source=ROOT/'packages/campaign/chapter07_sources/native.reference.json';assert sha(source)=='8bd457cc8f24d154b304a8cf0a946b9e2a83ae1dcfc01a08073a97364dc1119e';data=json.loads(source.read_bytes());v=data['variants'][VID];a=v['native_enemy']['resolved']['attributes'];prefab=data['prefabs'][v['prefab_key']];root=next(c for c in prefab['components'].values() if c['native_class']=='Enemy');mover=next(c for c in prefab['components'].values() if c['native_class']=='MoveController');combat=v['modes'][0]['nodes']['_combat'];raw=combat['raw'];assert len(v['modes'])==1 and not v['passive_and_skill_components'] and not v['native_enemy']['resolved'].get('skills') and not v['native_enemy']['resolved'].get('talentBlackboard');assert combat['native_class']=='MeleeAttack' and (raw['_selectTargetSource'],raw['_waitForAttackEvent'],raw['_damageType'],raw['_atkScale'],raw['_attackType'])==(2,1,1,1.0,1) and not raw['_activeBuffs'];on=[x for x in combat['animation_binding']['events'] if x['name']=='OnAttack'];assert len(on)==1 and on[0]['frame']==18;uid='unit/ch7/ordinary/sotihd/11aeb9d877d72938';sid='selector/ch7/ordinary/sotihd/blocked';aid='ability/ch7/ordinary/sotihd/normal';bid='behavior/ch7/ordinary/sotihd';base={'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':root['raw']['_blockVolume']}
 entity={'id':uid,'kind':'entity','tags':['enemy','ground'],'components':{'attributes':{'base':base},'resources':{'hp':{'initial':a['maxHp'],'capacity':a['maxHp'],'role':'health'}},'selection_state':{'side':1,'motion':1,'category':1,'unit_type':2,'abnormal_immunes':[8]},'spatial':{'motion_mode':0,'steering':{'rule':'rule/ch7/ordinary/steering','parameters':{'response_factor':mover['raw']['_steeringFactor'],'max_acceleration':mover['raw']['_maxSteeringForce'],'arrival_radius':.05}}},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':v['native_enemy']['resolved']['lifePointReduce']},'abilities':[aid],'behavior':{'machine':bid}},'metadata':{'native_variant':VID,'native_reference':v['native_reference'],'source_immunity':'silenceImmune true→AbnormalType SILENCE8; other undefined DB fields remain pending, no source claim'}}
 rules=[{'id':'rule/ch7/ordinary/steering','kind':'rule','contract':'movement.steering','implementation':{'type':'provider','provider':'ark.movement.steering_velocity'}}];selector={'id':sid,'kind':'selector','region':{'type':'all','blocked_only':True},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1};ability={'id':aid,'kind':'ability','selector':sid,'activation':{'mode':'automatic_attack','parameters':{'auto_only':True}},'target_capture':'at_cast','timeline':[{'at_seconds':on[0]['seconds'],'effect':{'op':'damage','damage_type':'physical','scale':1,'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False}}}],'metadata':{'source_combat':combat,'native_OnAttack18':True,'affected_by_ASPD_source':bool(raw['_affectedBySlowDown'])}}
 behavior={'id':bid,'kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/ark_behavior_decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'normal','selector':sid}],'cast_groups':[{'key':'normal','abilities':[aid]}],'parameters':{'target_key':'normal','blocked_target':True,'stop_on_target':False,'stop_cast_groups':['normal']}}]}}
 p={'schemaVersion':2,'manifest':{'id':'package/ch7/ordinary/sotihd/source_v1','requires':['preset/ark_standard'],'metadata':{'source_locks':{str(source):sha(source)},'required_runtime':CORE,'variant_bindings':[{'variant_id':VID,'unit_definition':uid,'native_reference':v['native_reference'],'native_resolved':v['native_enemy']['resolved'],'native_raw_rows':v['native_enemy']['raw_rows'],'combat_source':combat,'root_source':root,'mover_source':mover}],'unprovided_fields':{k:'undefined in exact DB merged attributes; no claim of default numeric source' for k in ('hpRecoveryPerSec','spRecoveryPerSec') if k not in a},'SP_scope':'No EnemySkill/SP costs/native charging driver declared, so model has no SP resource. Not a claim undefined source spRecovery==0.','reference_target_policy':'Exact source _selectTargetSource2 uses realtime blocked identity; no free/camo/name-derived ordinary target substitution.','whole_stage_executed':False,'independent_reviewed':False,'client_verified':False}},'entities':[entity],'abilities':[ability],'selectors':[selector],'behaviors':[behavior],'rules':rules};fixture=deepcopy(p);fixture['scenarioDraft']={'id':'scene/ch7/ordinary/compile','ruleset':'ruleset/ark_standard','map':{'rows':1,'cols':3},'objectives':{},'initialEntities':[{'definition':uid,'instanceAlias':'source','position':{'row':0,'col':1}}]};Compiler().compile(fixture);OUT.mkdir(parents=True,exist_ok=True);out=OUT/'sotihd.module.reference.json';assert not out.exists();out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(out),'core':CORE,'variant':VID,'frame':18,'HP':2900,'ATK':350,'DEF':150,'native_skills':0,'SPresource':False,'actual_compile':True}))
if __name__=='__main__':main()
