"""Explicit source current-stats/capture policy and real apply_buff scheduled effects."""
import hashlib,json,sys
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT.parent/'unpack_work/campaign_chapter06_complete_base_v5_candidate'));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler,Engine
from ark_sim.tools.replay import replay
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
from tools.chapter07_ordinary.test_sotihd_v2 import package as old_package,deploy
MODULE=ROOT/'packages/campaign/chapter07_ordinary/sotihd.module.v3.reference.json';OUT=ROOT/'validation/campaign/chapter07_ordinary_public_v3'
def package():
 fixture=old_package();new=json.loads(MODULE.read_bytes());assert hashlib.sha256(MODULE.read_bytes()).hexdigest()=='b14057a3383c3fac2bced98432135c0eb7999ec66f3215ad696fbd243eb0e9b0';new['entities'].append(fixture['entities'][-1]);new['scenarioDraft']=fixture['scenarioDraft'];return new
def hits(s):return [e for e in s.session.events if e['type']=='damage.accepted']
def test_real_apply_buff_ASPD3_18frame_source_event_to6_and_CP_head():
 p=package();p['buffs']=[{'id':'buff/author/speed3','kind':'buff','duration_seconds':5,'modifiers':[{'attribute':'attack_speed_ratio','layer':'flat','value':2}]}];p['selectors'].append({'id':'selector/author/source','kind':'selector','region':{'type':'all'},'filters':[{'tag':'enemy'},{'state':'alive'}],'limit':1});p['scenarioDraft']['scheduledEffects']=[{'at':0,'effect':{'op':'apply_buff','buff':'buff/author/speed3','selector':'selector/author/source'}}];s=Engine.create(Compiler().compile(p));deploy(s);s.session.advance(4);OUT.mkdir(parents=True,exist_ok=True);cp=OUT/'speed_pre_hit.cp.json';assert not cp.exists();h=write_ordered(cp,s.checkpoint());r=Engine.restore(s.program,load_bound(cp,h));s.session.advance(10);r.session.advance(10);assert s.snapshot()==r.snapshot()==replay(s.program,s.export_replay()).snapshot();starts=[e for e in s.session.events if e['type']=='ability.started'];assert len(hits(s))==1 and hits(s)[0]['time']-starts[0]['time']==6 and hits(s)[0]['payload']['amount']==250;assert 'sp' not in s.ctx.entity('source')['components']['resources'];(OUT/'speed_trace.json').write_text(json.dumps({'input':p,'checkpoint_sha':h,'snapshot':s.snapshot()},indent=2)+'\n',encoding='utf8',newline='')
def test_real_apply_buff_DEF300_at_hit_before18frame_and_CP_head():
 p=package();p['buffs']=[{'id':'buff/author/def300','kind':'buff','duration_seconds':5,'modifiers':[{'attribute':'def','layer':'flat','value':200}]}];p['selectors'].append({'id':'selector/author/blocker','kind':'selector','region':{'type':'all'},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1});p['scenarioDraft']['scheduledEffects']=[{'at':10,'effect':{'op':'apply_buff','buff':'buff/author/def300','selector':'selector/author/blocker'}}];s=Engine.create(Compiler().compile(p));deploy(s);s.session.advance(8);OUT.mkdir(parents=True,exist_ok=True);cp=OUT/'DEF_pre_hit.cp.json';assert not cp.exists();h=write_ordered(cp,s.checkpoint());r=Engine.restore(s.program,load_bound(cp,h));s.session.advance(18);r.session.advance(18);assert s.snapshot()==r.snapshot()==replay(s.program,s.export_replay()).snapshot();assert len(hits(s))==1 and hits(s)[0]['time']==19 and hits(s)[0]['payload']['amount']==50 and s.ctx.resources.current('source','hp')==2900;(OUT/'DEF_trace.json').write_text(json.dumps({'input':p,'checkpoint_sha':h,'snapshot':s.snapshot()},indent=2)+'\n',encoding='utf8',newline='')
def test_source_intrinsic_SILENCED12_projection_rejects_flag_without_guess8():
 p=package();p['buffs']=[{'id':'buff/author/silence','kind':'buff','duration_seconds':5,'selection_flags':{'abnormal_flags':[12]}}];p['entities'][0]['components']['buffs']={'initial':['buff/author/silence']};s=Engine.create(Compiler().compile(p));deploy(s);s.session.advance(25);from ark_sim.domains.selection import DEFAULT_STATE;state=s.ctx.spatial.selection_state('source',DEFAULT_STATE);assert state['abnormal_immunes']==[12] and 12 not in state['abnormal_flags'];assert len(hits(s))==1 and hits(s)[0]['payload']['amount']==250
def test_captured_TargetFree_midcast_current_model_behavior_is_reference_only():
 p=package();s=Engine.create(Compiler().compile(p));deploy(s);s.session.advance(10);s.ctx.set('blocker',('selection_state','target_free'),True);s.session.advance(15);assert len(hits(s))==1 and hits(s)[0]['payload']['amount']==250;assert p['manifest']['metadata']['capture_and_hit_reference_policy']['reference_scope_pending']
