"""Fresh independent quantities/times; no author fixture imports."""
from copy import deepcopy
def effect(track):return {'op':'finish_timeline_wave','target':'source','parameters':{'finish_and_skip':False,'track_source_at_next_wave':track,'track_source_wave_delta':0,'track_all_managed_at_next_wave':False}}
def package(fault=False,upgrade=False):
 source={'id':'unit/peer/foundation/source','kind':'entity','tags':['enemy','tracked'],'components':{'attributes':{'base':{'max_hp':1733,'atk':419,'def':193,'mres':37}},'resources':{'hp':{'initial':1733,'capacity':1733,'role':'health'}},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle'},'rebirth':{'resource':'hp','max_count':1,'delay_seconds':.7,'restore_ratio':.6,'restore_rule':'rule/peer/foundation/restore','retain_buffs':['buff/peer/foundation/track'],'on_begin':[{'op':'apply_buff','target':'source','buff':'buff/peer/foundation/track'}]}}}
 other=deepcopy(source);other['id']='unit/peer/foundation/other';other['tags']=['enemy'];other['components'].pop('rebirth')
 observer=[{'op':'modify_resource','target':'source','resource':'probe','delta':9},{'op':'random','stream':'peer.foundation.react','probability':1,'on_success':[{'op':'emit','event':'peer.foundation.beforefault'}],'on_failure':[]}]
 if fault:observer.append({'op':'modify_resource','target':'source','resource':'absent','delta':1})
 controller={'id':'unit/peer/foundation/director','kind':'entity','components':{'resources':{'probe':{'initial':17,'capacity':100}},'spatial':{},'buffs':{'initial':['buff/peer/foundation/watch']},'abilities':['ability/peer/foundation/kill','ability/peer/foundation/retire']}}
 def birth(definition,alias,delay=0,blocks=True):return {'kind':'spawn','count':1,'delay_seconds':delay/30,'managed':True,'blocks_wave':blocks,'blocks_fragment':False,'spawn':{'definition':definition,'instanceAlias':alias,'position':{'row':1,'col':2}}}
 return {'schemaVersion':2,'manifest':{'id':'package/peer/foundation','requires':['preset/ark_standard']},'entities':[source,other,controller],'abilities':[{'id':'ability/peer/foundation/'+name,'kind':'ability','selector':'selector/peer/foundation/source','activation':{'mode':'manual','on_start':[{'op':'instant_kill','parameters':{'cause':'independent_'+name,'skip_rebirth':name=='retire'}}]},'timeline':[]} for name in ['kill','retire']],'selectors':[{'id':'selector/peer/foundation/source','kind':'selector','region':{'type':'all'},'filters':[{'tag':'tracked'},{'state':'alive'}],'limit':1}],'rules':[{'id':'rule/peer/foundation/restore','kind':'rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.parameters.capacity * inputs.parameters.ratio'}}],'buffs':[{'id':'buff/peer/foundation/track','kind':'buff','duration_seconds':4/30,'on_remove':[effect(False),effect(True)] if upgrade else [effect(True)]},{'id':'buff/peer/foundation/watch','kind':'buff','events':[{'event':'timeline.source_transferred','effects':observer}]}],'scenarioDraft':{'id':'scene/peer/foundation','ruleset':'ruleset/ark_standard','objectives':{},'map':{'rows':3,'cols':5},'initialEntities':[{'definition':controller['id'],'instanceAlias':'director','position':{'row':0,'col':0}}],'timeline':{'policy':'managed_clear','negative_timeout_policy':'wait_for_clear','waves':[{'pre_delay_seconds':2/30,'post_delay_seconds':4/30,'max_wait_seconds':-1,'fragments':[{'pre_delay_seconds':1/30,'actions':[birth(source['id'],'source'),birth(other['id'],'old',13)]}]},{'pre_delay_seconds':7/30,'post_delay_seconds':0,'max_wait_seconds':-1,'fragments':[{'actions':[birth(other['id'],'next',blocks=False)]}]}]}}}
