import json
from pathlib import Path
from tools.chapter08_foundation_review.test_jt82_v3 import ROOT,load,proof
def test_current_stage_D12_dynamicResistance200_expiry558_preserves_native_parameters_CPP211_head():
 p=load();s=p['scenarioDraft'];s.pop('timeline');s.pop('branches',None);s['objectives']={};s['roster']=[];s['initialEntities']=[{'definition':'unit/peer/dynamic/source','instanceAlias':'source','position':{'row':0,'col':0}},{'definition':'unit/peer/dynamic/target','instanceAlias':'target','position':{'row':0,'col':1}}]
 for ident in ['source','target']:p['definitions'].append({'id':'unit/peer/dynamic/'+ident,'kind':'entity','components':{'attributes':{'base':{'max_hp':18000,'atk':77,'def':257,'mres':63,'one_minus_status_resistance':1}},'resources':{'hp':{'initial':18000,'capacity':18000,'role':'health'}},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle'},'abilities':['ability/peer/dynamic/apply'] if ident=='source' else ['ability/peer/dynamic/resist']}})
 p['definitions'].append({'id':'buff/peer/dynamic/resist','kind':'buff','modifiers':[{'attribute':'one_minus_status_resistance','layer':'final_ratio','value':-.5}]});p['definitions'] += [{'id':'ability/peer/dynamic/apply','kind':'ability','activation':{'mode':'manual','on_start':[{'op':'buff_application','target':3,'application_rule':'rule/ch8/dragon_fire/application','allowed':['buff/ch8/source/dragon_fire','buff/ch8/source/dragon_fire[damage]']}]},'timeline':[]},{'id':'ability/peer/dynamic/resist','kind':'ability','activation':{'mode':'manual','on_start':[{'op':'apply_buff','target':'source','buff':'buff/peer/dynamic/resist'}]},'timeline':[]}]
 from ark_sim import Compiler,Engine
 from ark_sim.tools.replay import replay
 from tools.campaign_ordered_checkpoint import write_ordered,load_bound
 from tools.chapter08_foundation_review.test_jt82_v3 import providers,OUT
 reg=providers();pr=Compiler(providers=reg).compile(p);sim=Engine.create(pr,providers=reg,seed=s['seed']);sim.submit({'action':'skill','source':'source','ability':'ability/peer/dynamic/apply'},at=0);sim.submit({'action':'skill','source':'target','ability':'ability/peer/dynamic/resist'},at=200);sim.advance(211);d=OUT/'current_dynamic_D12';d.mkdir(parents=True,exist_ok=True);f=d/'checkpoint.json';h=write_ordered(f,sim.checkpoint());r=Engine.restore(pr,load_bound(f,h),providers=reg);sim.advance(360);r.advance(360);assert sim.checkpoint()==r.checkpoint()==replay(pr,sim.export_replay(),providers=reg).checkpoint();target=sim.session.world.resolve('target');hits=[e for e in sim.session.events if e['type']=='damage.accepted' and e['payload']['target']==target];assert [(e['time'],e['payload']['amount']) for e in hits]==[(t,50+180*t/900) for t in range(30,541,30)];removed=[e for e in sim.session.events if e['type']=='buff.removed' and e['payload']['buff']=='buff/ch8/source/dragon_fire'];assert [e['time'] for e in removed]==[558];assert 'buff/ch8/source/dragon_fire[damage]' in [i['definition'] for i in sim.ctx.get('target',('buffs','instances'))];(d/'evidence.json').write_text(json.dumps({'input':p,'cp_sha':h,'checkpoint':sim.checkpoint()},indent=2),encoding='utf8')
