"""Fresh M96 source content stage on unchanged frozen M94 runtime."""
import hashlib,json,subprocess,sys
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];RUNTIME=ROOT.parent/'unpack_work/campaign_m94_complete_c4_candidate';OUT=ROOT/'validation/campaign/m94_complete_c4';PIN='cb321a851dc1ccb373477c73a522fc4ca8c35ce8b1c38d18bbee7e1e028358d7';SOURCE_PIN='2b3804fcd456e456b137b8145afe655d031db4dbf331a6115af3fded168f51e6'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 native=RUNTIME/'stage/level_main_04-09.m96.first_hit.source_circle.native_life.json';package=RUNTIME/'stage/level_main_04-09.m96.life99999.runthrough.prepared.json';receipt=OUT/'m96_stage_authoring.prepared.json'
 if any(p.exists() for p in (native,package,receipt)):raise ValueError('Fresh artifacts only')
 module=ROOT/'packages/campaign/chapter04_dmage/module.immunity_guard.reference.json';assert sha(module)==SOURCE_PIN
 subprocess.run([sys.executable,str(ROOT/'tools/build_chapter04_09_stage.py'),'--runtime-root',str(RUNTIME),'--expected-core',PIN,'--dmage-module',str(module),'--dmage-sha256',SOURCE_PIN,'--demon-phase','first_hit','--demon-sha256','39a96185a08a6f24015d7d60fd2694bba452d3a1f98997546e9f35c62b9ad08e','--range-policy','source_circle','--output',str(native)],cwd=ROOT,check=True)
 p=json.loads(native.read_bytes());original=deepcopy(p);s=p['scenarioDraft'];native_life=deepcopy(s['resources']['life']);s['resources']['life'].update(initial=99999,capacity=99999);s['metadata']['runthrough_profile']={'base_life_resource':'life','base_life':99999,'fixed12':deepcopy(s['roster']),'operator_enemy_HP':'Original selected actual module HP','source_births':49,'variants':7,'heatfields':8,'deploy_capacity':8,'policies':deepcopy(p['manifest']['metadata']['model_policies']),'client_verified':False}
 p['manifest']['metadata']['goal_base_life_authoring']={'native':native_life,'selected_initial':99999,'selected_capacity':99999,'only_authoring':'Campaign user base life policy'}
 compare=deepcopy(p);compare['scenarioDraft']['resources']['life']=native_life;del compare['scenarioDraft']['metadata']['runthrough_profile'];del compare['manifest']['metadata']['goal_base_life_authoring'];assert compare==original and s['parameters']['deploy_capacity']==8 and s['seed']==1693806226 and len(s['roster'])==12 and sum(t['tileKey']=='tile_volcano' for t in s['map']['tiles'])==8
 old=json.loads((RUNTIME/'stage/level_main_04-09.m94.runthrough.prepared.json').read_bytes());assert s['map']==old['scenarioDraft']['map'] and s['timeline']==old['scenarioDraft']['timeline'] and s['roster']==old['scenarioDraft']['roster'] and s['resources']==old['scenarioDraft']['resources'] and s['parameters']==old['scenarioDraft']['parameters']
 sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT));from ark_sim import Compiler;from ark_sim.adapters.api import implementation_digest;assert implementation_digest()==PIN;Compiler().compile(p)
 package.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');commands=OUT/'compact.commands.public_v5.prepared.json';launch=json.loads((OUT/'runthrough_launch.public_v5.prepared.json').read_bytes());launch.update(package=str(package),package_sha=sha(package),source_module=str(module),source_module_sha=SOURCE_PIN,status='Prepared M96 immunity-control source content + V5 public operations; original V3 complete proof remains separate and running',source_fix_policy='STUN0 active/control applicability follows actual projected flags; end-recovery21frame remains an independent recovery buff')
 nextlaunch=OUT/'runthrough_launch.m96_v5.prepared.json';nextlaunch.write_text(json.dumps(launch,indent=2)+'\n',encoding='utf8',newline='');result={'core':PIN,'module_sha':SOURCE_PIN,'native_stage_sha':sha(native),'package_sha':sha(package),'commands_sha':sha(commands),'launch_sha':sha(nextlaunch),'old_map_timeline_HP_DP_roster_slots_seed_unchanged':True,'full_stage_executed':False};receipt.write_text(json.dumps(result,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps(result))
if __name__=='__main__':main()
