"""Separate complete V6 process receipt; official registry remains Root-owned."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'validation/campaign/m94_complete_c4'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 path=OUT/'pending_registry_m94_v6_complete.json'
 if path.exists():raise ValueError('Preserve receipt')
 full=OUT/'full49_m96_v6.json';assert sha(full)=='d15d6167ddd3b0650ae4b91959ae60c2cc6560e5b81d72326423b5ac7cc228bc';r=json.loads(full.read_bytes());assert all(r[k] for k in ('passed','process_complete','checkpoint_equal','durable_checkpoint_equal','replay_equal','identity_stable'));suite=OUT/'full_v2_verification.json';assert sha(suite)=='3abf802dd762f8c82776ab6ce7ea12931014b5c0b4d20a2347f35ee56104dfa6';s=json.loads(suite.read_bytes());assert s['exitcode']==0 and len(s['cases'])==1211
 coverage=OUT/'m96_v6.original_coverage.json';assert sha(coverage)=='ee647df80df8d42ff5b15320ad6418e287ff2f311ed38f30fb051904a133f385';c=json.loads(coverage.read_bytes());assert c['all12_first_deploy_accepted_before_terminal'] and len(c['accepted_first_deploy_units'])==12 and sum(c['actual_enemy_births'].values())==49
 record={'role':'Complete model process receipt, pending Root official registration and promotion decision','core':r['implementation'],'full4_9':{'path':str(full),'sha256':sha(full),'actual_exit':0,'terminal_tick':r['terminal_tick'],'observed_end':r['end_tick'],'kills':r['state']['kills'],'leaks':r['state']['leaks'],'base_life':r['base_life_final'],'births':49,'fixed12_first_deploys_accepted':True,'events':r['journal']['events'],'bytes':r['journal']['bytes'],'journals':{name:r[name] for name in ('journal','continuation_journal','replayed_journal')},'checkpoint_equal':True,'durable_checkpoint_equal':True,'replay_equal':True,'source_guard_stable':True},'correct_input_full_suite':{'path':str(suite),'sha256':sha(suite),'passed':1211,'actual_exit':0,'canonical_input':'M12Projection with ARKSIM_M10_REVIEW_ROOT selected M94','catalog_clone':'Only92->96 count constant, all other assertions and original fixture path preserved'},'baseline':{'path':str(OUT/'baseline'),'sha256':sha(OUT/'baseline'),'passed':True,'actual_exit':0,'kills':11,'leaks':0,'events':181937,'custom_expected':[850,60],'CP_and_start_replay_equal':True},'coverage':{'path':str(coverage),'sha256':sha(coverage),'actual_refusals':c['rejected_commands'],'actual_skill_starts':c['actual_skill_started'],'mon_actor':c['mon3tr']['actor'],'mon_paid_DP':10,'mon_outgoing_damage_packets':len(c['mon3tr']['actual_outgoing_damage_packets']),'field_triggers':c['field_triggers'],'NoSource_packets':c['NoSource_damage_packets'],'not_all12_skills_triggered':True},'known_history_preserved':{'oldwrong_input_full_suite':'1205pass2fail1skip, original metadata/fixturecount identity preserved','oldM92_stageV3_full_pass_sha':'f47eb81b228f43571282343abb7f71a6bd386dda6883c61fee6efdcd1e0daa05','oldM92_content_gap':'Legacy STUN0 controls ignored immunity0; only new M96 content source is consumed in this V6 full receipt'},'followup':{'same_source_Kalts_boundary_public_short_session':13077,'purpose':'Wait actual1050 committed SP15, command1051; separate public-input lifecycle proof without changing V6','status':'Running after V6 full actualexit0'},'4_10_author_only':{'stage_sha':'7b5c062528c35bbdfe571763ec7065d75b002cf58bb722e760518eac078957d0','report_sha':'3f04c114365a6bec159a8e89062ea77a8345f4f13ee69f190d609adb0a7d325a','ticks':300,'events':4291,'birth_plan':43,'variants':7,'fixed_roster':12,'native_slots':10,'initial_DP':10,'move_multiplier':.5,'CP_start_replay_equal':True,'whole_stage_executed':False},'registry_modified':False,'primary_promotion_performed':False,'client_verified':False}
 path.write_text(json.dumps(record,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'receipt':str(path),'sha256':sha(path)}))
if __name__=='__main__':main()
