import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter08_buff_lifetime_v8_independent_gate';OUT.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
scopes={'generic26':'chapter08_buff_lifetime_independent_joint_v3','time_domain3':'chapter08_buff_lifetime_time_domain_v3','temporal_attributes2':'chapter08_buff_lifetime_temporal_attribute_v1','nested_segmented_latefault2':'chapter08_buff_lifetime_end_boundary_v1','temporal_applicability2':'chapter08_buff_lifetime_temporal_applicability_v1','source_burn7':'chapter08_dynamic_burn_independent_v5','source_reverse1':'chapter08_dynamic_burn_reverse_independent_v2'}
rows=[];cases=[];files=[Path(__file__)];core='be1b6be85a29b84d31a7444f186212bf71a85b538edea781f8a54080cba91bb7'
for name,directory in scopes.items():
 folder=ROOT/'validation/campaign'/directory;path=folder/'verification.json';r=json.loads(path.read_bytes());assert r['core']==core and r['guards_equal'] and all(c['outcome']=='passed' for c in r['cases']);cases+=r['cases'];rows.append({'scope':name,'report':str(path),'sha':sha(path),'cases':len(r['cases']),'guards_start':r['guards_start'],'guards_end':r['guards_end']});files+=list(folder.rglob('*'))
assert len(cases)==43 and len({c['nodeid'] for c in cases})==43
files+=list((ROOT/'tools/chapter08_buff_lifetime_review').glob('*.py'));source=ROOT/'packages/campaign/chapter08_consumers/boss/dragon_fire.module.v8.dynamic.json';assert sha(source)=='00f13da3728affa386b10b96f7a3e99a89bdf67fd4ab34f3cdaeb667baf5c4ae'
failed=ROOT/'validation/campaign/chapter08_buff_lifetime_time_domain_v2/freeze.failed.json'
f={'passed':True,'core':core,'cases':43,'unique_cases':43,'scope_reports':rows,'case_outcomes':cases,'guards_equal':True,'old_v5_failed_freeze_sha':sha(failed),'source_sha':sha(source),'scope':'Independent43 newbe1 actualexecutions: unchangedgeneric26, unchangedtwo trueV5counter expectations plus equivalentplainfinite marker3, temporalattribute time/seconds2, nestedrate/continuousvsadvance1segmentation/orderedCP and late-second-clock boundaryatomic rollback2, time-driven marker applicability and pausedowner applicability2. ActualsourceD8 seven prior independentexpectations rerun plus reverse initialhalf0.5 removed150 expiry765/25packets30..750. Source firstforward apply11/resist311 expires619/20packets41..611, live refresh311 expiry769 and retainedchildramp; absence/reignite650 UIDretain/gen2/restartramp; zero/high Attr26 clamp declaredreference; retainedsourceexit21. CompleteCPSHAreload/head equality for public-input cases. Fourmaxoverrideprimitive cases onlyorderedCPrestore, no publichead claim. Lateboundary fault restores both clocks tolasttime1/remaining5ticks and removesboundary2calculationtraces; prior tick1 callbacks committed are not falsely rolled back.','limits':'ActualsourceD8 required_runtime metadata7e76 is old sourcehistory; actualproof is be1. No sourcev11 identity migration, selflease joint approval, completeBoss/client/nativebody/JT8-2whole or actualall12 deployment claim. Unknownnative clamp/body/EXTEND interpretations remain explicit reference policies. Old failedV5/source reverse proof identities kept. Oldgeneric/source/template report scopeparagraph inherited historical text is not thisgate scope; thisnewfreeze states actualscope without rewriting oldreport bytes.','artifact_pins':{str(p):sha(p) for p in files if p.is_file()}}
(OUT/'freeze.json').write_text(json.dumps(f,ensure_ascii=False,indent=2),encoding='utf8');print(sha(OUT/'freeze.json'))
