import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter08_buff_lifetime_independent_joint_v2';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();r=json.loads((OUT/'verification.json').read_bytes())
assert r['guards_equal'] and len(r['cases'])==26 and len({x['nodeid'] for x in r['cases']})==26 and all(x['outcome']=='passed' for x in r['cases'])
assert r['core']=='7e76e49e8b196f1c7ec6d3a08c7760cbb4ebc7eaa02ef778f6e71c820549fef8'
files=list(OUT.rglob('*'))+list((ROOT/'tools/chapter08_buff_lifetime_review').glob('*.py'))
failed=ROOT/'validation/campaign/chapter08_buff_lifetime_independent_joint_v1/freeze.failed.json'
report={'passed':True,'core':r['core'],'cases':26,'unique_cases':26,'verification_sha':sha(OUT/'verification.json'),'guards_start':r['guards_start'],'guards_end':r['guards_end'],'guards_equal':True,'case_outcomes':r['cases'],'old_failed_freeze_sha':sha(failed),'scope':'Newcore7e76 independent26 unique checks, original19 assertions untouched and 7 newcases. Previous-rate and previous-counting integral, zero rate pause/resume, refresh/extend, maxshort/long at rate1 and actual rate2, samephase periodic expiry no tailpacket, real remove/reapply UID and stale/direct timer callbacks, runtime provider Bool/negative/NaN/Infinity atomic rejection, strictinactive policy compile rejection, controls exactexpiry before callback and pause atdue cannot revive, source retirement retain, on_remove latefault World/events/RNG rollback, bornDormant only initializes intrinsic Buff upon publicactivation5, and trueHP0 rebirth waiting with retained Buff/ownedability dispatch. CountTrue expires6 emits2/4; countTrue+on_beginrate2 expires4 emits2; CountFalse+on_beginrate2 waits1..11 and original expected14 now correct. Actualordered diskCP and SHArestore/publichead completecheckpoints+journals where publiccommands represent inputs. Four maxdurationoverride cases use direct Buffs.apply with actualorderedCP restore only, no headreplay claim for those. Schedulerconsumed fault task is not assumed requeued.','limits':'Genericclock permission/integration gate only. Does not approve sourceDragonFire newversion/Talula fullBoss, wholeJT8-2/currentlongrun/client/nativebody or all stacking modes. Prior sourceD6 two cases ab22 are oldda6 identity, not7e76; new source consumer must be newly bound and tested. Verification generictemplate scope paragraph inherited historicalOre text; thisfreeze actualscope supersedes that paragraph without altering report bytes.','artifact_pins':{str(p):sha(p) for p in files if p.is_file()}}
(OUT/'freeze.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8');print(sha(OUT/'freeze.json'))
