"""Pin newV2 independent proof; olde3 counter remains its own identity."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/campaign_owned_channel_phase_peer_v1';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def pin(p):return {'path':str(Path(p).resolve()),'sha256':sha(p),'bytes':Path(p).stat().st_size}
def main():
    file=OUT/'phase.v2.actual.v2.json';d=json.loads(file.read_bytes());assert d['actual_exit']==0 and len(d['results'])==7 and all(r['passed'] for r in d['results']) and d['source_equal'] and d['source_before']==d['source_after'] and all(sha(p)==h for p,h in d['source_after'].items())
    assert d['core_before']==d['core_after']=='da218736ae42600b5d80653b411508b13438e9002b18af3f04233285ac3cb226'
    receipts=[]
    for name in [*[f'owned_channel_phase_peer_old_e3_counter_v{i}' for i in range(1,6)],'owned_channel_phase_peer_v2_actual_v1','owned_channel_phase_peer_v2_actual_v2']:
        p=Path('E:/ArkSimLogs/receipts')/name/'completion.json';r=json.loads(p.read_bytes());assert r['cleanup_exit']==0 and r['raw_logs_removed_after_validation'];receipts.append({**pin(p),'worker_exit':r['worker_exit'],'cleanup':r['cleanup_result']})
    old=OUT/'old.e3.counter.v1.json';counter=json.loads(old.read_bytes());assert counter['actual_counter_observed'] and counter['permission_passed'] is False and counter['source_equal']
    result={'schema':'ark-sim/independent-owned-phase-peer-freeze/v2','core':d['core_after'],'source_freeze_sha256':'01856e38162f8c274e9186f6bee39a06b9f94c32ef26197b1f278e21dd7405cb','actual_report':pin(file),'source_guards_current':d['source_after'],'helpers':[pin(p) for p in sorted(Path(__file__).parent.glob('*.py'))],'groups_passed':7,'actual_CP_head_proofs':{k:v for k,v in d['facts'].items() if isinstance(v,dict) and v.get('CPP_head')},'clock_oracle':'quantum1/17, pre.4, post.23. Single last16=>finish20; multi last29=>finish33; legacy nominal35; source-declaredcontext-dependentrecovery due34.','permissions':'Directpre/active/post/late/repeat finish leaves5stores unchanged; realunownedfinishdue task and borrowedreal_task_dict no writes; same-tick afterrealstop opaque scope rejected.','timing_tamper':'8 basic task/scope/cause/clock/operand mutations + coherent World/issued/calculation-value/queue due forgery rejected specifically by pure selected-rule clock recomputation. Originalcache retained.','fault':'After actualpost lease+finish task+event creation, realRNG2 injected then fault. Full5stores equal actuallastatomicclock29; frameworkfailure separately preserved.','old_e3_actual_counter':pin(old),'old_counter_scope':'Actualactivechannel at10 directfinish False->True and same-tick16 completed-event reborrow; initialpre2 was correctlyunchanged and is not falselycounted as a bug.','prior_attempts_preserved':[pin(p) for p in sorted(OUT.glob('counter.*.json'))]+[pin(OUT/'phase.v2.actual.v1.json')],'cleanup':receipts,'deleted_bytes':sum(r['cleanup']['reclaimed_bytes'] for r in receipts),'remaining_raw':0,'errors':0,'candidate_or_primary_modified':False,'dmech_or_whole_or_client_approved':False,'comparison_exclusions':[]}
    path=OUT/'final.freeze.v2.json';assert not path.exists();path.write_text(json.dumps(result,indent=2)+'\n',encoding='utf8');print(json.dumps({'freeze':pin(path),'deleted_bytes':result['deleted_bytes']}))
if __name__=='__main__':main()
