import sys,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CAND=ROOT.parent/'unpack_work/campaign_area_projection_v2_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim.adapters.api import implementation_digest
from tools.chapter07_stage_join.build_718_native_v2 import build
from tools.chapter06_review.source_locks_v1 import verify

def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 draft=ROOT/'packages/campaign/chapter07_stage_models/level_main_07-16.native_draft.v2.json';a=json.loads(draft.read_bytes());verify(a);files=[draft]+list((ROOT/'tools/chapter07_stage_join').glob('*.py'))+[Path(x) for x in a['manifest']['metadata']['source_locks']]+list((CAND/'ark_sim').rglob('*.py'))+list((CAND/'ark_sim').rglob('*.json'));files += [Path(m.__file__) for m in sys.modules.values() if getattr(m,'__file__',None) and str(ROOT/'tools') in str(m.__file__) and str(m.__file__).endswith('.py')];before={str(p):sha(p) for p in files};b=build();assert a==b;native=json.loads((ROOT/'packages/campaign/chapter07_plans/source.plan.json').read_bytes())['stages']['level_main_07-16']['native_document'];scene=a['scenarioDraft'];story=next(x for x in a['definitions'] if x['id']=='control/ch7/main_07-16');assert len([s for s in story['steps'] if s['kind']=='ack'])==5;assert scene['seed']==native['randomSeed'];assert a['manifest']['metadata']['native_predefines']==native['predefines'];assert scene['resources']['life']['initial']==3 and len(scene['roster'])==12 and scene['parameters']['deploy_capacity']==9;after={str(p):sha(p) for p in files};assert before==after
 out=ROOT/'validation/campaign/chapter07_stage_718_compile_draft_v2/verification.json';out.parent.mkdir(parents=True,exist_ok=True);r={'passed':True,'actual_compile':True,'deterministic_fresh_build_value_equal':True,'core':implementation_digest(),'draft_path':str(draft),'draft_sha':sha(draft),'source_before':before,'source_after':after,'births':45,'exact_variant_count':8,'native_life':3,'native_DP':10,'native_slots':9,'native_seed':scene['seed'],'native_card_stock15_separate_roster':scene['cards'],'story_ack_count':5,'native_options':native['options'],'native_runes':native['runes'],'source_policy':'strict converter_v7 routes/actions/maps/options/raw predefines/no overlay; old source module proofs are distinct and not migrated; compile-only no stage admission.','whole_stage_executed':False,'client_verified':False,'formal_admitted':False};assert not out.exists();out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha':sha(out),'draft_sha':sha(draft),'pins':len(before)}))
if __name__=='__main__':main()
