"""Exact common-a705 four-file union, all other source files immutable."""
import hashlib,json,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];BASE=ROOT.parent/'unpack_work/campaign_chapter06_complete_base_v5_candidate';SELF=ROOT.parent/'unpack_work/campaign_buff_self_remove_v1_candidate';STATIC=ROOT.parent/'unpack_work/campaign_declared_static_tile_v1_candidate';OUT=ROOT.parent/'unpack_work/campaign_chapter06_static_selfremove_v1_candidate';REPORT=ROOT/'validation/campaign/chapter06_static_selfremove_v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def core(p):return subprocess.check_output([sys.executable,'-c','import sys;sys.path.insert(0,sys.argv[1]);from ark_sim.adapters.api import implementation_digest;print(implementation_digest())',str(p)],cwd=ROOT,text=True).strip()
def pins(p):return {str(x.relative_to(p/'ark_sim')):sha(x) for x in (p/'ark_sim').rglob('*') if x.is_file() and x.suffix in ('.py','.json')}
def main():
 base=pins(BASE);s=pins(SELF);t=pins(STATIC);composition=json.loads((ROOT/'validation/campaign/buff_self_remove_v1/composition.json').read_bytes());assert core(BASE)==composition['parent_core']=='a7059989b9db7f4bc0de954b32cb5c5ba10e6b92ce040c57ea0a193549b9709a';assert core(SELF)==composition['core'];assert core(STATIC)=='8c58a6b704da11c42540357f37331ef604ac737056c1baf40ca7b14e44578924';assert base.keys()==s.keys()==t.keys();sd={k for k in base if base[k]!=s[k]};td={k for k in base if base[k]!=t[k]};assert sd=={'content\\dependencies.py'} and len(td)==3 and not sd&td;assert not OUT.exists();shutil.copytree(BASE/'ark_sim',OUT/'ark_sim',ignore=shutil.ignore_patterns('__pycache__','*.pyc'))
 for key in sd:shutil.copyfile(SELF/'ark_sim'/key,OUT/'ark_sim'/key)
 for key in td:shutil.copyfile(STATIC/'ark_sim'/key,OUT/'ark_sim'/key)
 actual=pins(OUT);assert {k for k in base if actual[k]!=base[k]}==sd|td;assert all(actual[k]==(s[k] if k in sd else t[k] if k in td else base[k]) for k in base);assert pins(BASE)==base and pins(SELF)==s and pins(STATIC)==t;REPORT.mkdir(parents=True,exist_ok=True);r={'joint_core':core(OUT),'parent_core':core(BASE),'selfremove_core':core(SELF),'static_core':core(STATIC),'selfremove_delta':sorted(sd),'static_delta':sorted(td),'joint_delta_four':sorted(sd|td),'source_before':{'base':base,'self':s,'static':t},'source_after':{'base':pins(BASE),'self':pins(SELF),'static':pins(STATIC),'joint':actual},'all_other_files_exact_base':True,'source_candidates_mutated':False,'primary_or_live_modified':False,'inherited_fullsuite_baseline_acceptance':False};out=REPORT/'composition.json';assert not out.exists();out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'joint_core':r['joint_core'],'selfremove_core':r['selfremove_core'],'delta':r['joint_delta_four'],'sha':sha(out)}))
if __name__=='__main__':main()
