"""Actual new joint4file delivery; fullsuite/baseline/independent proofs not inherited."""
import hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter06_static_selfremove_v1';CAND=ROOT.parent/'unpack_work/campaign_chapter06_static_selfremove_v1_candidate';BASE=ROOT.parent/'unpack_work/campaign_chapter06_complete_base_v5_candidate'
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def main():
 composition=OUT/'composition.json';c=json.loads(composition.read_bytes());vpath=OUT/'verification.json';v=json.loads(vpath.read_bytes());assert v['passed'] and v['actual_exit']==0 and v['source_before']==v['source_after'];route=Path('E:/ArkSimEvidence/chapter06_environment_joint_v1/verification.json');r=json.loads(route.read_bytes());assert r['passed'] and r['CP_resume_equal'] and r['public_head_equal'] and r['source_before']==r['source_after'];assert all(sha(Path(p))==h for p,h in r['source_after'].items());delta=[]
 for rel in c['joint_delta_four']:
  src=CAND/'ark_sim'/rel;dst=OUT/'source_delta/ark_sim'/rel;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);assert sha(src)==sha(dst);delta.append({'file':rel,'base_sha':sha(BASE/'ark_sim'/rel),'joint_sha':sha(src),'archive':str(dst)})
 assert {str(p.relative_to(CAND/'ark_sim')) for p in (CAND/'ark_sim').rglob('*') if p.is_file() and p.suffix in ('.py','.json') and sha(p)!=sha(BASE/p.relative_to(CAND))}==set(c['joint_delta_four']);refs=[]
 for name,o in r['observations'].items():
  ref=o['export'];p=Path(ref['path']);assert p.stat().st_size==ref['bytes'] and sha(p)==ref['sha256'];refs.append(ref)
 selfproof=OUT/'selfremove_proof/verification.json';assert json.loads(selfproof.read_bytes())['passed'];noopt=OUT/'noopt.json';assert json.loads(noopt.read_bytes())['passed'];helpers={str(p):sha(p) for p in (ROOT/'tools/chapter06_environment_consumer').glob('*.py')};extra=[ROOT/'tools/chapter06/cold/policies.py',ROOT/'packages/campaign/chapter06_cold/model.json',ROOT/'packages/campaign/chapter06_units/melee_v2/model.json',ROOT/'packages/campaign/chapter06_environment_consumer/module.v2.reference.json'];helpers.update({str(p):sha(p) for p in extra});result={'joint_core':c['joint_core'],'common_parent_core':c['parent_core'],'composition_sha':sha(composition),'four_exact_deltas':delta,'all_unchanged_core_files_guarded':True,'actual_source_route_on_joint':{'report':str(route),'sha':sha(route),'actual_exit':0,'actual69457_events':True,'native_route_waits_offsets_unshortened':True,'actual_CP500_SHAreload_resume_publichead_equal':True,'three_full_journals_SHAbytes':refs,'six_source_portal_visibility_events':r['actual_portal_visibility_events'],'actor_source':'snsbr trueHP3400/ATK360/DEF100/speed1.1×.5 isolates boss route1 geometry; Boss mechanics not covered'},'actual48_static_spatial_tests':{'report':str(vpath),'sha':sha(vpath),'actual_exit':0},'actual5_selfremove_tests_CP_head':{'report':str(selfproof),'sha':sha(selfproof)},'actual_noopt_values_custom850_60_and_0_1prefix150':{'report':str(noopt),'sha':sha(noopt),'inherited_full0_1_acceptance':False},'source_before':r['source_before'],'source_after':r['source_after'],'all_new_helpers_and_content_pins':helpers,'source_version_conflicts':'Tile prefab default mask0 vs source native palette explicit masks retained separately; method bodies/client remain pending','independent_peer_passed':False,'new_joint_fullsuite_passed':False,'new_joint_baseline_passed':False,'primary_modified':False,'whole_stage_executed':False,'client_verified':False};out=OUT/'freeze.json';assert not out.exists();out.write_text(json.dumps(result,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(out),'joint_core':c['joint_core'],'route_sha':sha(route),'independent_pending':True}))
if __name__=='__main__':main()
