"""Limited V6 source shape/20 negatives; old V5 failure remains immutable."""
import hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'validation/trace_audit/delta_only_v6_freeze'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 paths=[ROOT/'tools/trace_audit/stream_oracle_v6.py',Path(__file__),ROOT/'tools/trace_audit/campaign_05_10/test_delta_v6.py',ROOT/'tools/trace_audit/campaign_05_10/prepare_delta_golden_v6.py',ROOT/'validation/trace_audit/delta_only_v6/actual_five_events.jsonl',ROOT/'validation/trace_audit/delta_only_v6/input_witness_pins.json',ROOT/'validation/trace_audit/delta_only_v6/author_corrected_capacity.log']+[ROOT/'tools/trace_audit'/name for name in ('stream_oracle_v5.py','stream_oracle_v5_identity.py','stream_oracle_v5_math.py')]+[ROOT/'tools/compare_campaign_trace.py',ROOT/'validation/trace_audit/simple_formulas_v5/oracle_pins.json'];assert '20 passed' in paths[6].read_text();w=json.loads(paths[5].read_bytes());assert all(sha(Path(f))==h for f,h in w['source_locks'].items());assert not OUT.exists();OUT.mkdir(parents=True)
 for p in paths:
  dst=OUT/'source'/p.relative_to(ROOT);dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dst);assert sha(p)==sha(dst)
 old=ROOT/'validation/trace_audit/05-10.sealed_original_full.v5.json';failed=ROOT/'validation/trace_audit/delta_only_v6/author.log';r={'helpers_and_inputs':{str(p):sha(p) for p in paths},'actual20_author_pass':True,'actual_source_delta_only_chain':{'owner':25,'source':28,'before_event':288586,'body_before':293316,'bounds_event':293332,'changed_event':293333,'post_body':293334,'resource':'shield_charge','before':1,'delta':-1,'after':0,'capacity':1},'source_locks':w['source_locks'],'old_V5_full_shape_failure':{'path':str(old),'sha':sha(old)},'first_capacity_same_output_miss_failure':{'path':str(failed),'sha':sha(failed)},'scope':'New resource delta-only typed shape, static source capacity and known bounds source/params/identity/raw/value plus actual before and post resource input witnesses. Unknown/custom/dynamic capacities missing witnesses pending. Lifecycle formula remains pending, no synthetic event.value. V5 parent identity/formula rules unchanged.','independent_reviewed':False,'whole_05_10_v6_audit_completed':False,'numeric_full':False,'client_verified':False};out=OUT/'freeze.json';out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'freeze_sha':sha(out)}))
if __name__=='__main__':main()
