from copy import deepcopy
AID='ability/owned_irq/hold';BID='buff/owned_irq/finite'
def package(kind='dead',optin=True,eligible=True):
 from ark_sim.domains.selection import DEFAULT_STATE
 from ark_sim.domains.providers import BUILTIN_PROVIDERS
 cfg={'_targetSide':2,'_targetCategory':1,'_targetMotion':3,'_ignoreTargetFree':0,'_onlyIgnoreSomeOfTargetFreeCase':0,'_excludeSomeAbnormalFlags':0,'_needProfessionMask':0,'_ignoreAllyTargetFree':0,'_ignoreHealFree':0,'_ignoreMotionMode':0,'_forceIgnoreCamouflage':0,'_checkUnitType':0}
 sub={'event':'ability.interrupted','condition':"inputs.payload.source == context.owner.id and inputs.payload.ability == '"+AID+"'",'effects':[{'op':'modify_resource','resource':'coil_q','delta':-7.25,'selector':'selector/owned_irq/live','parameters':{'respect_recovery_freeze':True}},{'op':'remove_buff','target':'source','buff':BID}]}
 if optin:sub['owned_callback']={'mode':'synchronous_interrupt','ability':AID,'allow_owner_inactive':True,'selector_timing':'live_at_event'}
 def unit(name,hp,side,tags,abilities=None):return {'id':'unit/owned_irq/'+name,'kind':'entity','tags':tags,'components':{'attributes':{'base':{'max_hp':hp,'atk':1103 if name=='killer' else 317,'def':119,'mres':37}},'resources':{'hp':{'role':'health','initial':hp,'capacity':hp}},'selection_state':{'side':side,'category':1,'motion':1,'unit_type':2 if side else 1},'abilities':abilities or [],'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle'}}}
 source=unit('source',503,1,['enemy','irq_source'],[AID]);source['components']['buffs']={'initial':[BID]};a=unit('a',9037,0,['player','a','coil_target']);b=unit('b',8039,0,['player','b','coil_target']);a['components']['resources']['coil_q']={'initial':43,'capacity':67,'recovery_rate':0};b['components']['resources']['coil_q']={'initial':19,'capacity':83,'recovery_rate':0};killer=unit('killer',9173,0,['player'],['ability/owned_irq/free','ability/owned_irq/kill','ability/owned_irq/control']);keeper=unit('keeper',9059,1,['enemy'])
 buff={'id':BID,'kind':'buff','duration_seconds':3.4,'events':[sub]}
 rules=[{'id':'rule/owned_irq/eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':'rule/owned_irq/inactive','kind':'rule','contract':'buff.applicability','implementation':{'type':'expression','expression':'False'}}]
 if not eligible:buff['active_rule']='rule/owned_irq/inactive'
 p={'schemaVersion':2,'rules':rules,'buffs':[buff,{'id':'buff/owned_irq/free','kind':'buff','selection_flags':{'abnormal_flags':[2]}},{'id':'buff/owned_irq/stun','kind':'buff','duration_seconds':1,'control':{'abilities':False,'attack':False,'move':False,'interrupt':True},'selection_flags':{'abnormal_flags':[0]}}],'selectors':[{'id':'selector/owned_irq/a','kind':'selector','region':{'type':'all'},'filters':[{'tag':'a'}],'limit':1},{'id':'selector/owned_irq/source','kind':'selector','region':{'type':'all'},'filters':[{'tag':'irq_source'}],'limit':1},{'id':'selector/owned_irq/live','kind':'selector','region':{'type':'all'},'filters':[{'tag':'coil_target'},{'state':'alive'}],'limit':1,'eligibility':{'rule':'rule/owned_irq/eligibility','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':deepcopy(DEFAULT_STATE)}}}],'abilities':[{'id':AID,'kind':'ability','activation':{'mode':'manual'},'selector':'selector/owned_irq/a','duration_seconds':4,'timeline':[{'at':0,'effect':{'op':'modify_resource','resource':'coil_q','delta':2}}]},{'id':'ability/owned_irq/free','kind':'ability','activation':{'mode':'manual'},'selector':'selector/owned_irq/a','timeline':[{'at':0,'effect':{'op':'apply_buff','buff':'buff/owned_irq/free'}}]},{'id':'ability/owned_irq/kill','kind':'ability','activation':{'mode':'manual'},'selector':'selector/owned_irq/source','timeline':[{'at':0,'effect':{'op':'damage','damage_type':'true','scale':1}}]},{'id':'ability/owned_irq/control','kind':'ability','activation':{'mode':'manual'},'selector':'selector/owned_irq/source','timeline':[{'at':0,'effect':{'op':'apply_buff','buff':'buff/owned_irq/stun'}}]}],'entities':[source,a,b,killer,keeper],'scenarioDraft':{'id':'scene/owned_irq/'+kind,'ruleset':'ruleset/ark_standard','map':{'rows':4,'cols':7},'resources':{'life':{'initial':99999,'capacity':99999}},'initialEntities':[{'definition':x['id'],'instanceAlias':name,'position':{'row':2,'col':i}} for i,(x,name) in enumerate([(source,'source'),(a,'a'),(b,'b'),(killer,'killer'),(keeper,'keeper')])],'commands':[{'at':4,'action':'skill','source':'source','ability':AID},{'at':10,'action':'skill','source':'killer','ability':'ability/owned_irq/free'},{'at':23,'action':'skill','source':'killer','ability':'ability/owned_irq/kill' if kind=='dead' else 'ability/owned_irq/control'}]}}
 return p
