"""Source-only two ordinary ranged variant closure; no runtime or stage approval."""
import hashlib,json
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'packages/campaign/chapter07_ranged_preparation/source.profile.v2.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 enemy=ROOT/'packages/campaign/chapter07_sources/native.reference.json';plan=ROOT/'packages/campaign/chapter07_consumption_plan/source.consumption.plan.json';freeze=ROOT/'validation/campaign/chapter07_consumption_plan_v1/freeze.json';assert sha(enemy)=='8bd457cc8f24d154b304a8cf0a946b9e2a83ae1dcfc01a08073a97364dc1119e' and sha(plan)=='298deaf0dc7ed9a1068d1dfe75c8b90a9e1c3f8ae0a967f3baa28ff3f87064f1';d=json.loads(enemy.read_bytes());cp=json.loads(plan.read_bytes());rows=[];inputs={str(p):sha(p) for p in (enemy,plan,freeze,Path(__file__))}
 for vid in ('enemy_1079_sotisp@0/13ad905feaa233c3','enemy_1082_soticn@0/304d5222d69cf371'):
  v=d['variants'][vid];r=next(r for r in cp['exact12_variants'] if r['variant_id']==vid);pf=d['prefabs'][v['prefab_key']];assert len(v['modes']) in (1,2);combat=v['modes'][0]['nodes']['_combat'];key=combat['raw']['_projectileKey'];projectile=d['projectiles'][key];assert key in r['source_projectile_dependencies'];events=[e for e in combat['animation_binding']['events'] if e['name']=='OnAttack'];assert events
  roots=[{'path_id':pid,**deepcopy(c)} for pid,c in pf['components'].items() if c['native_class'] in ('Enemy','MoveController','Talent','SelectorTrigger')];projectileclasses=[{'path_id':pid,'native_class':c['native_class'],'raw':c['raw']} for pid,c in projectile['components'].items()]
  sourcepath=Path(projectile['source']['path']);assert sha(sourcepath)==projectile['source']['sha256'];inputs[str(sourcepath)]=sha(sourcepath)
  rows.append({'variant_id':vid,'exact_DB_reference':v['native_reference'],'raw_DB_resolved':v['native_enemy']['resolved'],'raw_DB_rows':v['native_enemy']['raw_rows'],'prefab_source':pf['source'],'raw_root_and_movement_and_trigger':roots,'raw_mode':v['modes'][0],'all_source_modes':v['modes'],'per_mode_OnAttack_frames':[[e['frame'] for e in m['nodes']['_combat']['animation_binding']['events'] if e['name']=='OnAttack'] for m in v['modes']],'OnAttack_native_frames':events,'selectors_and_ranges':r['all_source_selectors_and_range_components'],'passive_components':v['passive_and_skill_components'],'literal_BSON_templates':r['literal_BSON_templates'],'all_inline_Buff_records':r['inline_Buff_records'],'projectile':projectile,'projectile_component_classes':projectileclasses,'source_SP_skills':r['source_skill_SP_cooldown_and_target_components'],'pending_execution_contracts':['AdvancedSelector target/state/distance/order and range exact boundary before capture; do not inherit melee blocked-only','projectile native movement/hit/geometry components consume every declared field; source retained at cast/launch/hit and origin PPtr binds','sotisp trigger/revert BSON and strengthened ASPD listener are conditional, not base-stat rewrite' if 'sotisp' in vid else 'mortar targeting trigger and global-strength listener, dynamic attack-type raw flag1/attackType0 require literal caller/SourceBB policy','projectile targetfree/camouflage/status eligibility after launch and splash membership/crosswall policy source-specific; preserve unresolved native bodies as explicit replaceable references','HP/DP/SP and source stats remain exact; public CP/head of consumer still required'],'runtime_authored':False,'client_verified':False})
 OUT.parent.mkdir(parents=True,exist_ok=True);assert not OUT.exists();p={'schema':'ark-sim/chapter07-ranged-source-closure/v1','source_locks':inputs,'two_exact_variants':rows,'source_version_conflicts':cp['source_version_conflicts'],'source_method_body_policy':cp['source_method_body_policy'],'runtime_created':False,'core_changed':False,'stage_created':False,'whole_stage_executed':False,'client_verified':False};OUT.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');assert all(sha(Path(f))==h for f,h in inputs.items());receipt=ROOT/'validation/campaign/chapter07_ranged_preparation_v2/audit.json';receipt.parent.mkdir(parents=True,exist_ok=True);assert not receipt.exists();r={'passed':True,'scope':'Source closure only; no runtime behavior or stage execution','profile_sha':sha(OUT),'source_before':inputs,'source_after':{f:sha(Path(f)) for f in inputs},'variants':[x['variant_id'] for x in rows],'nativeframes':[[e['frame'] for e in x['OnAttack_native_frames']] for x in rows],'projectile_keys':[x['raw_mode']['nodes']['_combat']['raw']['_projectileKey'] for x in rows],'whole_passed':False,'client_verified':False};receipt.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'profile_sha':sha(OUT),'audit_sha':sha(receipt),'variants':r['variants']}))
if __name__=='__main__':main()
