"""Minimal reusable invisible qualification interface, before actor admission."""
import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
from tools.chapter09_more_content.build_v1 import SOURCE,FREEZE,OUT,CORE,sha
def main():
 p={'schema':'ark-sim/c9-coupled-required-interface/v1','runtime':CORE,'source_locks':{str(x):sha(x) for x in (SOURCE,FREEZE)},'actual_counterexample':'validation/campaign/chapter09_coupled_author/invisible.counterexample.receipt.v1.json','module_admission':False,
 'minimal_generic_change':{'domain':'typed selection projection and targeting eligibility','source_status':{'enum':'AbnormalFlag.INVISIBLE','index':9},'state_fields':{'invisible':'strict boolean, default false; OR active status9','can_select_invisible':'strict boolean, default false; explicit reveal/detection permission'},'eligibility':'After relative side/category/motion qualification, reject invisible target unless source can_select_invisible. Keep camouflage17 and targetfree2 independent. Existing source_configuration cannot silently grant visibility.','scope':'Pure generic typed state/qualification model; no character or native unit ID branches. All consuming selectors share the same model profile.','lifecycle':'Buff apply/removal and dynamic toggle projection must update selectability immediately. Old projectile target capture is a separate declared lifecycle policy; invisibility does not imply retirement.','atomicity':'Extend known schema booleans and defaults explicitly; strict bool; malformed permission rejected before mutation; freeze current modules byte identity; generate new runtime evidence rather than relabel old82.'},
 'minimum_probes':['Flag9 rejected by ordinary target qualification while flag17 remains distinct','Explicit generic detection permission allows9; targetfree bypass alone does not','Marker disable on attack/block and exact half-open 90tick restore; attack pulses reset deadline','Invisibility source retirement and checkpoint restore during pending delay','Captured projectile retains separately declared target-hidden policy; no silent target death inference'],
 'existing_composition':{'peer_aura':'Actual source colliders radius1, self EXCLUDE2, same-side character ground|air and live opposite mask requirement, generic shared leases max1','trait_toggle':'Generic passive.toggle held-disabled when no active incoming peer Buff; delay0; independent owned trait child. Attach once while any peer lease remains, remove after last lease ends.','duholy_trait':'Owned child taunt_level flat0 and enemy-side aura ASPD flat -0.3, source traitAbility.attack_speed=-30/100. Blackboards stay separated from refracting.magic_resistance70 and Flame skill fields. Range-radius1.1 BB vs Collider1 is retained as unresolved native load policy, not silently overwritten.','dushdo_trait':'Owned child attack_interval flat-1.2 from traitAbility.base_attack_time; running recovery retiming requires separate source/model policy evidence','dushdo_invisible':'Owned child status9, initial true; generic blocked held condition; explicit actual-attack event pulse; restore3seconds. No17 substitution.'},
 'remaining_actor_closure':['duholy DB Flame skill source closure and actual ownership unresolved in this frozen ordinary prefab recipe','duholy traitAbility.range_radius1.1 must bind exact range initialization semantics before choosing BB vs native collider radius1','Dynamic attack_interval change during already running cooldown must retain declared sampled/continuous source policy; no source-backed retiming proof currently retained'],
 'unsupported_policy':'Full duholy/dushdo actors and coupled.module.v1 are not emitted as accepted actors before these actual source/model gaps close. No empty behavior or fake invisible Buff implementation.','whole_stage':False,'client_verified':False}
 path=OUT/'coupled.required.interface.v1.json';path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(path,sha(path))
if __name__=='__main__':main()
