"""Final isolated Aura scope, exact six-file delta and source waiting witness."""
import hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];CAND=ROOT.parent/'unpack_work/campaign_shared_aura_v10_candidate';OUT=ROOT/'validation/campaign/shared_aura_final_freeze_v2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 reports=[ROOT/'validation/campaign'/name/'verification.json' for name in ('shared_aura_guarded_final_v3','shared_aura_legacy_v3','shared_aura_patrt_self_source_v10','shared_aura_noopt_v2','shared_aura_legacy_alive_v10')];pins=[]
 for p in reports:
  r=json.loads(p.read_bytes());assert r['passed'] and r.get('actual_exit',0)==0 and r['source_before']==r['source_after'];assert all(sha(Path(f))==h for f,h in r['source_after'].items());pins.append({'path':str(p),'sha':sha(p),'elapsed':r.get('elapsed')})
 composition=ROOT/'validation/campaign/shared_aura_v1/composition_v10.json';c=json.loads(composition.read_bytes());assert c['core']=='b10290ea1d7f0cd4f1d49fa14f79579687e34d134743628a360371f18611216a' and c['parent_core']=='d509afe2cdd941dbaa75f4bb0cfa931b7869b29eff6753a7a571d0ef39f116d1';assert all(sha(CAND/f)==h for f,h in c['candidate_guards'].items());assert not OUT.exists();OUT.mkdir(parents=True);delta=[]
 for rel in c['changed']+c['added']:
  source=CAND/rel;dst=OUT/'delta'/rel;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(source,dst);assert sha(dst)==sha(source);delta.append({'file':rel,'parent_sha':c['parent_guards'].get(rel),'sha':sha(source)})
 helpers=list(Path(__file__).parent.glob('*.py'))
 for p in helpers:
  dst=OUT/'helpers'/p.relative_to(ROOT);dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dst);assert sha(dst)==sha(p)
 evidence=[]
 for name in ('shared_aura_final_v11','shared_aura_self_v10','shared_aura_patrt_self_source_v10'):
  for p in (ROOT/'validation/campaign'/name).glob('*'):
   if p.is_file():evidence.append({'path':str(p),'sha':sha(p),'bytes':p.stat().st_size})
 oldfail=[ROOT/'validation/campaign'/name for name in ('shared_aura_author_added_v1.log','shared_aura_author_callbacks_v2.log','shared_aura_author_v4.log','shared_aura_author_v5.log','shared_aura_patrt_source_v1.log','shared_aura_patrt_source_v2.log')];r={'core':c['core'],'parent_core':c['parent_core'],'candidate':str(CAND),'composition':{'path':str(composition),'sha':sha(composition)},'candidate_guards':c['candidate_guards'],'delta':delta,'actual_reports':pins,'actual51_current_cases_and43_originalAura_assertions':True,'actual_source_closure':{'path':str(ROOT/'packages/campaign/chapter07_boss/patrt/source.closure.json'),'sha':sha(ROOT/'packages/campaign/chapter07_boss/patrt/source.closure.json')},'source_waiting_required_counter':{'path':str(ROOT/'packages/campaign/chapter07_boss/patrt/required_waiting_counters/report.json'),'sha':sha(ROOT/'packages/campaign/chapter07_boss/patrt/required_waiting_counters/report.json')},'source_marker_ID_definition_not_changed':True,'actual_source_waiting_HP0_and_ATK120_DEF250_CP6_head_prefix51':True,'waiting_self_scope': 'Only target==Aura center, actual current retained waiting parent identity; old separate runtimeactive and alive gates remain exact. Source native selfDEFAULT0/excludeReborning0 reference declared. Own typedself source intrinsicATK1600 plusAura.2=1920 in this isolated noImmo input; expected2240 with extraRootownedwaitingAction buff belongs newjoint proof, not reused here.','source_policy':{'lease':'Explicit shared definition+target/oldest_live_lease/externalcollisionreject. Second parent never applies/refreshes/modifies stack. Last detach finishes once. Actual refresh/rebound/incarnations and callback stale handles re-read.','waiting':'Only opt-in Aura with actual real consume actor/generation/retained parent handle context finally cleared or actual same-gen scheduled rebirth finish job. HP0/aliveTrue/phasewaiting/nonterminal required. Queued target-inactive cleanup preserves only this authenticated Aura parent.','selection':'Scoped select/qualifies aura_parent actualUID/originalselector/currentparent realpolicy authorizes only source inactive gate. Typed candidate active, targetfree/camo/side/category/motion/range/hidden remain. No fake source.active and no actor-cast/projectile privilege.','source_methods':'Explicit replaceable source-reference policies; no full client equivalence claim.'},'actual_evidence':evidence,'helper_pins':{str(p):sha(p) for p in helpers},'historical_failures':{str(p):sha(p) for p in oldfail},'full_suite_passed':False,'full_baseline_passed':False,'independent_reviewed':False,'primary_modified':False,'C7_whole_executed':False,'client_verified':False};out=OUT/'freeze.json';out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'freeze_sha':sha(out),'core':c['core'],'delta':delta}))
if __name__=='__main__':main()
