"""Pin completed independent evidence and exact source-reference clock values."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter10_dmech_source_peer_v1';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
p=OUT/'actual.v3.json';r=json.loads(p.read_bytes());q=OUT/'frozen_recipient.actual.v1.json';extra=json.loads(q.read_bytes());assert r['actual_exit']==0 and len(r['results'])==5 and all(x['passed'] for x in r['results']) and r['source_equal'];assert extra['passed'] and extra['actual_exit']==0 and extra['source_equal'];assert all(sha(k)==v for data in [r,extra] for k,v in data['source_after'].items())
charge='ability/ch10/dmech/charge';full=r['facts']['full'];events=[(e['type'],e['time']) for e in full['events'] if e['payload'].get('ability')==charge];assert events==[('ability.started',150),('ability.finished',793)];assert full['link_clock']['born']==171 and full['link_clock']['held_until']==772 and full['link_clock']['packets']==20;assert [(e['type'],e['time']) for e in r['facts']['silence']['events'] if e['payload'].get('ability')==charge]==[('ability.started',150),('ability.finished',242)];assert extra['facts']['preSP']==46 and extra['facts']['postSP']==31 and extra['facts']['packets']==2
clean=[]
for run in ['dmech_source_peer_737_v1','dmech_source_peer_737_v2','dmech_source_peer_737_v3','dmech_source_peer_frozen_recipient_737_v1']:
 path=Path('E:/ArkSimLogs/receipts')/run/'completion.json';c=json.loads(path.read_bytes());assert c['cleanup_exit']==0 and c['raw_logs_removed_after_validation'] and c['cleanup_result']['remaining_files']==c['cleanup_result']['error_count']==0;clean.append({'path':str(path),'sha256':sha(path),'worker_exit':c['worker_exit'],'deleted_bytes':c['cleanup_result']['reclaimed_bytes'],'remaining':0,'errors':0})
files=[x for x in (ROOT/'tools/chapter10_dmech_source_peer_v1').glob('*.py')]+[x for x in OUT.glob('*.json')];receipt={'schema':'ark-sim/dmech-source-independent-peer-freeze/v1','core':r['core'],'actual_groups':6,'actual_exit':0,'actual_report':str(p),'actual_report_sha256':sha(p),'frozen_recipient_report_sha256':sha(q),'all_current_source_guards_equal':True,'full_disk_CPP_public_head_proofs':8,'comparison_exclusions':[],'files':{str(x):sha(x) for x in files},'source_reference_values':{'initial_source_SP':0,'payment':5,'one_use':1,'start':150,'OWN_and_attachment':171,'first_reach':172,'normal_last_owned_end':772,'normal_post_end':793,'silence_owned_post_end':242,'normal_recipient':{'initial':46,'20pack_final':66},'interruption_death_recipient':33,'actual_frozen_recipient_negative':31,'source_native_HP':6000,'death':215,'child_birth':245},'cleanup':clean,'total_deleted_bytes':sum(x['deleted_bytes'] for x in clean),'no_live_peer_process':True,'prior_failures_preserved':['actual.v1: true math/CPP followed by wrong all-Buffs-empty fixture expectation and invalid control field names; source bloodline Buffs must persist.','launch.failure.v2: reviewer indentation rejected before simulation; original wrapper receipt retained.'],'boundaries':['Native ON_ABILITY_FINISH to actual channel-end mapping and next-step reach are explicit source-reference policy; native method bodies/client equivalence unverified.','Float32 pre/post .6669999957 retained, ceil21 reference ticks; no .9 invented threshold.','Finite OWN20s callback remains finite; ordinary dead-source permission not granted.','Generic dead-callback late-fault/authority proof separate frozen peer; this report verifies source consumer numerical/selection/control/death paths.','Whole stage/production promotion unapproved.']}
dest=OUT/'final.freeze.v1.json';assert not dest.exists();dest.write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha':sha(dest),'actual_groups':6,'CPP_head':8,'deleted_bytes':receipt['total_deleted_bytes']}))
