"""Native negative callback bypasses actual positive SP recovery freeze."""
import hashlib,json,os,sys,traceback
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CAND=ROOT.parent/'unpack_work/campaign_owned_interrupt_callbacks_v1_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler,Engine
from ark_sim.adapters.api import implementation_digest
from ark_sim.tools.replay import replay
from tools.chapter10_dmech_source_v1 import build as source
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 assert implementation_digest()=='737e23225fd3c3b9f3d75d9f005a6a5f2ce4a28b0f29fd444276c805cca49e87';module=source.build();defs=[x for key in ['entities','abilities','buffs','rules','selectors','projectiles','definitions'] for x in module.get(key,[])];hold='ability/peer/cannon_busy'
 defs += [{'id':'unit/peer/frozen_cannon','kind':'entity','tags':['gunctrl'],'components':{'attributes':{'base':{'max_hp':9123,'atk':0,'def':0,'mres':0}},'resources':{'hp':{'role':'health','initial':9123,'capacity':9123},'sp':{'initial':46,'capacity':127,'parameters':{'freeze_while_cast':True,'freeze_cast_modes':['manual']}}},'selection_state':{'side':0,'category':2,'motion':1,'unit_type':1},'spatial':{},'abilities':[hold]}},{'id':hold,'kind':'ability','activation':{'mode':'manual'},'duration_seconds':4,'timeline':[]},{'id':'unit/peer/controller','kind':'entity','tags':['player'],'components':{'attributes':{'base':{'max_hp':6543,'atk':10000,'def':0,'mres':0}},'resources':{'hp':{'role':'health','initial':6543,'capacity':6543}},'selection_state':{'side':0,'category':1,'motion':1,'unit_type':1},'spatial':{},'abilities':['ability/peer/interrupt']}},{'id':'selector/peer/dmech','kind':'selector','region':{'type':'all'},'filters':[{'tag':'enemy_1223_dmech'},{'state':'alive'}],'limit':1},{'id':'buff/peer/interrupt','kind':'buff','duration_seconds':3,'selection_flags':{'abnormal_flags':[0]},'control':{'move':False,'attack':False,'abilities':False,'interrupt':True}},{'id':'ability/peer/interrupt','kind':'ability','activation':{'mode':'manual'},'selector':'selector/peer/dmech','timeline':[{'at':0,'effect':{'op':'apply_buff','target':'selected','buff':'buff/peer/interrupt'}}]}]
 p={'schemaVersion':2,'definitions':defs,'scenarioDraft':{'id':'scene/peer/frozen_recipient','ruleset':'ruleset/ark_standard','map':{'rows':4,'cols':7},'initialEntities':[{'definition':source.BODY,'instanceAlias':'artisan','position':{'row':0,'col':1}},{'definition':'unit/peer/frozen_cannon','instanceAlias':'cannon','position':{'row':3,'col':5}},{'definition':'unit/peer/controller','instanceAlias':'controller','position':{'row':2,'col':0}}],'commands':[{'at':160,'action':'skill','source':'cannon','ability':hold},{'at':220,'action':'skill','source':'controller','ability':'ability/peer/interrupt'}]}};source.bind_status_definitions(p);providers=source.providers();cp=lambda s:json.loads(json.dumps(s.checkpoint()));log=Path(os.environ['ARKSIM_RUN_DIR']);guard={str(x):sha(x) for x in [Path(__file__),Path(source.__file__)]+[x for x in (CAND/'ark_sim').rglob('*') if x.is_file() and x.suffix in ['.py','.json']]};facts={};ok=False
 try:
  s=Engine.create(Compiler(providers=providers).compile(p),providers=providers,seed=983);s.advance(210);facts['preSP']=s.ctx.resources.current('cannon','sp');assert facts['preSP']==46;facts['real_casts']=list(s.ctx.get('cannon',('runtime','casts')));assert facts['real_casts'];path=log/'frozen.checkpoint.json';path.write_text(json.dumps(cp(s)),encoding='utf8');r=Engine.restore(s.program,json.loads(path.read_bytes()),providers=providers);assert cp(s)==cp(r);s.advance(60);r.advance(60);h=replay(s.program,s.export_replay(),providers=providers);assert cp(s)==cp(r)==cp(h);facts.update({'full_CP_head_equal':True,'checkpoint_sha':sha(path),'postSP':s.ctx.resources.current('cannon','sp'),'packets':next(iter(s.ctx.attachments.state()['instances'].values()))['packets']});assert facts['postSP']==31 and facts['packets']==2;ok=True
 except Exception as e:facts.update({'error':str(e),'traceback':traceback.format_exc()})
 after={p:sha(p) for p in guard};report={'schema':'ark-sim/dmech-source-frozen-recipient-independent/v1','passed':ok and guard==after,'actual_exit':0 if ok and guard==after else 1,'core':implementation_digest(),'facts':facts,'source_before':guard,'source_after':after,'source_equal':guard==after,'whole_or_client_approved':False};dest=ROOT/'validation/campaign/chapter10_dmech_source_peer_v1/frozen_recipient.actual.v1.json';assert not dest.exists();dest.write_text(json.dumps(report,indent=2)+'\n',encoding='utf8');print(json.dumps({'passed':report['passed'],'facts':facts}));return report['actual_exit']
if __name__=='__main__':raise SystemExit(main())
