"""Freeze authored true frost device, with actual guarded7 checks and CP/public replay."""
import hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter06_predefined_consumer_freeze_v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 reportpath=ROOT/'validation/campaign/chapter06_predefined_consumer_final_v3/verification.json';r=json.loads(reportpath.read_bytes());assert r['passed'] and r['actual_exit']==0 and r['source_before']==r['source_after'];assert all(sha(Path(p))==h for p,h in r['source_after'].items());module=ROOT/'packages/campaign/chapter06_predefines_consumer/module.v2.reference.json';assert sha(module)==r['actual_module_sha'];source=module.parent/'source.profile.json';profile=json.loads(source.read_bytes());assert profile['source_before']==profile['source_after'] and all(sha(Path(p))==h for p,h in profile['source_after'].items());evidence=reportpath.parent;trace=json.loads((evidence/'actual_source_trace.json').read_bytes());cp=evidence/'actual_midcast.cp.json';assert sha(cp)==trace['checkpoint_sha'];assert trace['areas'][0]['time']-trace['casts'][0]['time']==25
 assert not OUT.exists();OUT.mkdir(parents=True);files=list((ROOT/'tools/chapter06_predefines').glob('*.py'))+list(module.parent.glob('*.json'))+[ROOT/'tools/chapter06/cold/policies.py'];archives=[]
 for p in files:
  dst=OUT/'source'/p.relative_to(ROOT);dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dst);assert sha(dst)==sha(p);archives.append({'path':str(p),'sha':sha(p)})
 result={'role':'Source-operated frost trap author candidate; independent peer and Boss actual trigger integration pending','core':r['core'],'module':{'path':str(module),'sha':sha(module)},'source_profile':{'path':str(source),'sha':sha(source)},'source_before':r['source_before'],'source_after':r['source_after'],'author':{'actual_exit':0,'checks':7,'elapsed':r['elapsed_seconds'],'report':str(reportpath),'sha':sha(reportpath)},'actual_evidence':[{ 'path':str(p),'sha':sha(p),'bytes':p.stat().st_size} for p in evidence.glob('*') if p.is_file()],'source_archives':archives,'actual_native_source_model':{'HP':100,'ATK':0,'SPcost':15,'SPinitial':0,'SPtimeRecovery':1,'native_predelay_seconds':profile['model_policies']['frame_quantization']['source_seconds'],'actual_predelay_ticks':25,'first_activation_at':100,'first_cast_at':trace['casts'][0]['time'],'first_Cold_area_at':trace['areas'][0]['time'],'range_cells':13,'Coldseconds':10,'two_sameframe_sources_cold_to_frozen_passed':True,'dormant_then_sameinstance_activation':True,'actual_midcast_CP_sourceSHAload_resume_publichead_equal':True,'true_owned_terrain_layer_release':True,'source_no_damage':True},'reference_policy_limits':profile['model_policies'],'missing_native_body_policy_explicit':True,'old_author_failures_preserved':True,'independent_review_passed':False,'actual_boss_trigger_join_verified':False,'whole_stage_executed':False,'runtime_modified':False,'primary_promotion':False,'client_verified':False};dest=OUT/'freeze.json';dest.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(dest),'module_sha':sha(module),'author7_actual_exit':0,'independent_pending':True}))
if __name__=='__main__':main()
