"""Exact source-operated frost device profile, with replaceable selector/frame policy."""
import hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'packages/campaign/chapter06_predefines_consumer'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 source=ROOT/'packages/campaign/chapter06_predefines/source.reference.json';plan=ROOT/'packages/campaign/chapter06_plans/source.plan.json';cold=ROOT/'packages/campaign/chapter06_cold/model.json';ranges=ROOT.parent/'unpack_work/campaign_tables/range_table.reference_56a.json';assert sha(ranges)=='a98344d688a8933c4dd7ddaae3cb76c4347295359a18b60b918042cc2542d9d9';d=json.loads(source.read_bytes());p=json.loads(plan.read_bytes());prefab=d['prefabs']['trap_010_frosts'];skill=d['skill_prefabs']['sktok_frosts'];components={c['native_class']:{'path_id':pid,'raw':c['raw']} for pid,c in skill['components'].items()};level=d['skill_tables']['sktok_frosts']['levels'][0];branch=d['stages']['level_main_06-14']['native_branches']['frstar_frosts'];aliases=[a['key'] for a in branch['phases'][0]['actions']];assert aliases==['trap_010_frosts#1','trap_010_frosts#2'];assert level['spData']['spCost']==15 and level['blackboard']==[{'key':'freeze','value':10.0,'valueStr':None}];duration=components['AnimatedActionToTargetAbility']['raw']['_preDelay'];range_source=json.loads(ranges.read_bytes())['x-1'];assert len(range_source['grids'])==13;paths=[source,plan,cold,ranges,ROOT/'packages/campaign/chapter06_cold/source.decoded.json'];locks={str(x.resolve()):sha(x) for x in paths}
 for n,h in d['source_locks'].items():assert sha(ROOT.parent/n)==h;locks[str((ROOT.parent/n).resolve())]=h
 result={'schema':'ark-sim/chapter06-predefined-frost-source/v1','source_before':locks,'source_after':{n:sha(Path(n)) for n in locks},'native_stage':'level_main_06-14','native_branch_key':'frstar_frosts','native_branch':branch,'native_predefines':d['stages']['level_main_06-14']['native_predefines'],'exact_aliases':aliases,'source_entity':prefab,'source_skill':skill,'source_components':components,'source_character':d['stages']['level_main_06-14']['instances'][0]['raw_character'],'selected_skill_level':level,'exact_range_source':range_source,'cold_source_module':{'path':str(cold),'sha':sha(cold)},'model_policies':{'activation':'Both native hidden registered real instances activated by one native branch, no replacement spawn','cadence':'Native time SP15/init0/recovery1; freeze during affecting cast. No externally scheduled recurring dummy effects','frame_quantization':{'source_seconds':duration,'quantum':1/30,'ceil_round12_ticks':math.ceil(round(duration/(1/30),12)),'note':'Source float0.800000011920929 preserved→25ticks. Client frame convention remains replaceable; do not silently rewrite .8 or24'},'AoE':'13 native x-1 cells, strict captured cell projection and source AdvancedSelector status/category/side/motion rules, no circle substitution','side_policy':'Native neutral SideIndex2 plus targetSide2 internals lack body. Explicit hostile-consumer side1 vs player0 using preserved relative AdvancedSelector2; replaceable and separately reviewed','cold':'Source freeze10 blackboard passed to actual typed Cold/Frozen application, including immunity/resistance/refresh/control behavior','terrain':'Owned TrapMode buildable0/passable2/height .40000000596; dormant no layer, activation adds layer, retire removes owned layer'},'missing_native_method_bodies':'Explicit source-reference policy, not a blocker or empty consumer','runtime_authored':False,'whole_stage_executed':False,'client_verified':False};assert result['source_before']==result['source_after'];OUT.mkdir(parents=True,exist_ok=True);out=OUT/'source.profile.json';assert not out.exists();out.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(out),'aliases':aliases,'SP':15,'cold_seconds':10,'predelay_ticks':25,'range_cells':13,'runtime':False}))
if __name__=='__main__':main()
