"""Actual current module identity author checks with full runtime/content/helper guards."""
import hashlib,importlib.util,json,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RUNTIME=ROOT.parent/'unpack_work/campaign_chapter06_complete_base_v5_candidate';OUT=ROOT/'validation/campaign/chapter06_predefined_consumer_final_v3';sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT))
import pytest,ark_sim
from ark_sim.adapters.api import implementation_digest
CORE='a7059989b9db7f4bc0de954b32cb5c5ba10e6b92ce040c57ea0a193549b9709a'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);sys.modules[name]=m;spec.loader.exec_module(m);return m
def main():
 assert implementation_digest()==CORE;OUT.mkdir(parents=True,exist_ok=True);module=ROOT/'packages/campaign/chapter06_predefines_consumer/module.v2.reference.json';assert sha(module)=='2e7e90422198000d401458e33075edc8f649771c39f82d623d553ab4dc6c5206';base=load('tools.chapter06_predefines.test_frost_consumer_final_v3',ROOT/'tools/chapter06_predefines/test_frost_consumer_final_v3.py');base.MODULE=module;base.OUT=OUT;advanced=load('tools.chapter06_predefines.test_frost_advanced_final_v3',ROOT/'tools/chapter06_predefines/test_frost_advanced_final_v3.py');paths=list((RUNTIME/'ark_sim').rglob('*.py'))+list((RUNTIME/'ark_sim').rglob('*.json'))+list((ROOT/'tools/chapter06_predefines').glob('*.py'))+list((ROOT/'packages/campaign/chapter06_predefines_consumer').glob('*.json'))+[ROOT/'tools/chapter06/cold/policies.py',ROOT/'packages/campaign/chapter06_cold/model.json',ROOT/'tools/campaign_ordered_checkpoint.py'];before={str(p):sha(p) for p in paths};started=time.monotonic();code=pytest.main([str(Path(base.__file__)),str(Path(advanced.__file__)),'-q']);after={str(p):sha(p) for p in paths};assert before==after and implementation_digest()==CORE;report={'actual_exit':code,'passed':code==0,'actual_module_sha':sha(module),'core':CORE,'actual_runtime_module':ark_sim.__file__,'elapsed_seconds':time.monotonic()-started,'source_before':before,'source_after':after,'7_original_assertions_unchanged_module_pin_only':True,'source_conditions':'Native single phase/2 registered sameinstance activations; naturalSP15/cost15 and25tick preDelay, no periodic externally emitted dummy application','scope':'C6 trap consumer model only; Boss trigger/NPC/source MethodBody/client/whole stage not verified','client_verified':False};dest=OUT/'verification.json';assert not dest.exists();dest.write_text(json.dumps(report,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'passed':code==0,'report_sha':sha(dest),'elapsed':report['elapsed_seconds']}));raise SystemExit(code)
if __name__=='__main__':main()
