"""Source-profile Mandra, four actual modes, owned beam and tile tokens."""
import json,copy,hashlib
from pathlib import Path
from tools.chapter09_pillar_lifecycle_v1 import build as pillar
ROOT=Path(__file__).resolve().parents[2];REQ=ROOT/'packages/campaign/chapter09_consumers/mandra/consumer.requirements.v1.json';SOURCE=ROOT/'packages/campaign/chapter09_source_prepare/enemies.native.v1.json';DETAIL=SOURCE.with_name('source.detail.v1.json');TOKEN=REQ.with_name('source.token047.v1.json')
PREFIX='ch9/mandra/';BODY='unit/'+PREFIX+'body';SHIELD='buff/'+PREFIX+'shield';RECOVERY='buff/'+PREFIX+'recovery';RAY='ability/'+PREFIX+'ray';RAYSTATE='buff/'+PREFIX+'ray_state';SLOW='buff/'+PREFIX+'ray_slow';SUMMON='ability/'+PREFIX+'summon';TILE='ability/'+PREFIX+'sealed_tile';PROFILE={'talent_prefix':{'invulnerable':3,'ray_cd':10,'summon_cd':20,'branch':'summon_dupilr'},'skill_prefix':{'invulnerable':5,'ray_cd':10,'summon_cd':10,'branch':'reborn_summon_dupilr'}}
def shield(inputs,params,context):
    result=copy.deepcopy(dict(inputs['effect']['settlement']));result['amount']*=.4
    source=inputs['source'];buffs=source.get('components',{}).get('buffs',{}).get('instances',[])
    if any(b['definition']==pillar.payload.TRAIT for b in buffs):result['events']=list(result.get('events',[]))+[{'type':'mandra.pillar_hit','payload':{'target':inputs['target']['id'],'source':source['id']}}]
    return result
def highest_atk(inputs,params,context):
    attrs=inputs['candidate']['components'].get('attributes',{})
    return -context.calculate('attributes.effective',{'base':attrs.get('base',{}).get('atk',0),'modifier_layers':[m for m in attrs.get('modifiers',[]) if m['attribute']=='atk'],'order':[{'layer':x} for x in attrs.get('layers',['flat','direct_ratio','final_ratio'])]}).value
def area_members(inputs,params,context):
    from math import hypot
    center=inputs['center_position'];states=context['area_selection_states']['candidates'];ids=[]
    for actor in inputs['candidates']:
        pos=actor['components'].get('spatial',{}).get('position');s=states[str(actor['id'])]
        if actor['id']==context['source']['id'] or pos is None or hypot(pos['row']-center['row'],pos['col']-center['col'])>1.7:continue
        if s['side']==0 and s['category']&1 and s['motion']&3 and not s['target_free'] and not s['camouflage'] and not s.get('invisible',False):ids.append(actor['id'])
    return ids
def providers():
    from ark_sim.domains.providers import BUILTIN_PROVIDERS
    from ark_sim.domains.selection import eligibility_profile
    from ark_sim.domains.projectile_profiles import trajectory
    return {**BUILTIN_PROVIDERS,**pillar.providers(),'reference.mandra.shield':{'callable':shield,'version':'accepted-pillar-hit-break-after-same-hit-resistance-v1'},'reference.mandra.max_atk':{'callable':highest_atk,'version':'raw-postfilter17-prts-max-current-atk-reference-v1'},'reference.mandra.area':{'callable':area_members,'version':'native-radius1.7-relative-player-v1'},'reference.mandra.eligibility':{'callable':eligibility_profile,'version':'raw-config-v1'},'reference.mandra.motion':{'callable':trajectory,'version':'source-homing10-reference-v1'}}
def build(profile='talent_prefix'):
    from ark_sim.domains.selection import DEFAULT_STATE
    req=json.loads(REQ.read_bytes());data=json.loads(SOURCE.read_bytes());cfg=PROFILE[profile];native=data['prefabs']['enemy_1523_mandra']['components'];p=pillar.build();p['manifest']={'id':'package/ch9/mandra/source_v1/'+profile,'metadata':{'source_locks':{str(x):hashlib.sha256(x.read_bytes()).hexdigest() for x in [REQ,SOURCE,DETAIL,TOKEN,Path(__file__)]},'source_requirements':req,'component_prefix_profiles':PROFILE,'selected_profile':profile,'reference_policy':{'target':'raw postfilter17 modeled as highest live ATK per PRTS; source masks retained','geometry':'native Collider centers, no recovered ValidateTarget body','beam':'homing10/contact-first/1s packets;7.1 source state,6pulse,15CD; current target HP for availability','pillar_break':'source native ON_TAKE_DAMAGE modeled after accepted same hit; that hit retains60% reduction, later hits no reduction','summon_null_branch':'Native named stage branch is null: explicitly declared real tile spawn reference, no fabricated empty branch; cell/direction policy row-major ahead of source','recovery_animation':'Source empty-actions skin animation is a finite25s pending owned request while stunned/busy; only ActivationRejected skips, actual ability.started/current owned cast clears request; shield and HP memory change once at actual finish, never each retry','selfstun_animation':'Empty-action C2_Stun20frames modeled as20/30 timed control; source raw ability remains in requirements','near_ground_flight':'target air in fly_stone, land in fly_open; locomotion remainsWALK','source047':'actual native static TrapMode, no health in prefab and fixed table key missing; no invented HP'},'reference_url':'https://prts.wiki/w/%E8%94%93%E5%BE%B7%E6%8B%89','whole_enemy_complete':True,'completion_scope':'All source-declared consumer entrypoints are implemented with explicit reference policies; native method-body and client fidelity remain unverified'}}
    def rule(name,contract,expression):return {'id':'rule/'+PREFIX+name,'kind':'rule','contract':contract,'implementation':{'type':'expression','expression':expression}}
    p['rules'] += [rule('capture','buff.capture',"{'hp_ratio':inputs.target.components.resources.hp.current / inputs.target.components.resources.hp.spec.capacity - .4}"),rule('restore','resource.recovery','inputs.parameters.capacity'),{'id':'rule/'+PREFIX+'shield','kind':'rule','contract':'damage.pipeline','implementation':{'type':'provider','provider':'reference.mandra.shield'}},{'id':'rule/'+PREFIX+'max_atk','kind':'rule','contract':'targeting.score','implementation':{'type':'provider','provider':'reference.mandra.max_atk'}},{'id':'rule/'+PREFIX+'area','kind':'rule','contract':'area.members','implementation':{'type':'provider','provider':'reference.mandra.area'}},{'id':'rule/'+PREFIX+'eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'reference.mandra.eligibility'}},{'id':'rule/'+PREFIX+'motion','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'reference.mandra.motion'}}]
    p['rules'].append({'id':'rule/'+PREFIX+'collision','kind':'rule','contract':'projectile.collision','implementation':{'type':'provider','provider':'model.projectile.collision'}})
    normal_projectile='projectile/'+PREFIX+'normal';p['projectiles']=[{'id':normal_projectile,'kind':'projectile','motion':{'rule':'rule/'+PREFIX+'motion','parameters':{'mode':'homing','speed':10}},'collision':{'rule':'rule/'+PREFIX+'collision','parameters':{'enabled':False}},'lifetime_seconds':10,'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'completion_blocking':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'metadata':{'native_projectile':data['projectiles']['projectile_enemy_mandra_p2'],'reference_policy':'Actual source homing10/life10/stopSourceInvalid0; current model endpoint/step selection explicitly reference'}}]
    selectorraw=next(c['raw'] for c in req['components'] if c['class']=='AdvancedSelector' and c['raw'].get('_postFilter')==17)
    def selector(sid,radius):return {'id':sid,'kind':'selector','region':{'type':'radius','radius':radius},'filters':[{'state':'alive'}],'limit':1,'eligibility':{'rule':'rule/'+PREFIX+'eligibility','parameters':{'source_configuration':selectorraw,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':DEFAULT_STATE}}}
    p['selectors']=[selector('selector/'+PREFIX+'ray',1.5),selector('selector/'+PREFIX+'range',1.5),{'id':'selector/'+PREFIX+'block','kind':'selector','region':{'type':'all','blocked_only':True},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1}]
    for entity in p['entities']:
        if entity['id']=='unit/ch9/pillar/ruin':entity['tags']=['ruin','terrain_mechanism'];entity['components']['selection_state']['side']=0
    def transition(state,condition=None):
        e={'op':'transition','state':state}
        if condition:e['condition']=condition
        return e
    def apply(buff):return {'op':'apply_buff','buff':buff,'target':'source'}
    def remove(buff):return {'op':'remove_buff','buff':buff,'target':'source'}
    stone2='buff/'+PREFIX+'stone_area';inv='buff/'+PREFIX+'invulnerable';selfstun='buff/'+PREFIX+'selfstun'
    p['buffs'] += [{'id':SHIELD,'kind':'buff','damage_hooks':[{'phase':'after','rule':'rule/'+PREFIX+'shield'}],'events':[{'event':'mandra.pillar_hit','condition':'inputs.payload.target == context.owner.id','effects':[remove(SHIELD),remove(RAYSTATE),{'op':'interrupt_ability','ability':RAY},apply(RECOVERY),transition('ground_open',"inputs.source.components.behavior.state == 'ground_stone'"),transition('fly_open',"inputs.source.components.behavior.state == 'fly_stone'"),{'op':'apply_buff','target':'source','buff':selfstun,'condition':"inputs.source.components.behavior.state == 'fly_open'"}]}]}, {'id':RECOVERY,'kind':'buff','duration_seconds':25,'capture':{'rule':'rule/'+PREFIX+'capture','refresh':'retain','parameters':{}},'events':[{'event':'damage.accepted','condition':'inputs.payload.target == context.owner.id and context.owner.components.resources.hp.current / context.owner.components.resources.hp.spec.capacity < inputs.buff.blackboard.hp_ratio','effects':[remove(RECOVERY)]}],'on_remove':[transition('ground_stone',"inputs.source.components.resources.hp.current > 0 and inputs.source.components.behavior.state == 'ground_open'"),transition('fly_stone',"inputs.source.components.resources.hp.current > 0 and inputs.source.components.behavior.state == 'fly_open'"),{'op':'apply_buff','target':'source','buff':'buff/'+PREFIX+'pending_skin','condition':"inputs.source.components.resources.hp.current > 0"}]},{'id':inv,'kind':'buff','duration_seconds':cfg['invulnerable'],'selection_flags':{'abnormal_flags':[5,15]}},{'id':selfstun,'kind':'buff','duration_seconds':20/30,'control':{'move':False,'attack':False,'abilities':False,'interrupt':True}},{'id':stone2,'kind':'buff','interval_seconds':1,'effects':[{'op':'area','center':'source','target':'source','membership_rule':'rule/'+PREFIX+'area','selection_projection':{'defaults':DEFAULT_STATE},'parameters':{},'effects':[{'op':'damage','damage_type':'arts','scale':.3}]}]}, {'id':RAYSTATE,'kind':'buff','duration_seconds':7.1,'interval_seconds':6,'control':{'move':False,'attack':False},'effects':[{'op':'set_ability_cooldown','ability':RAY,'duration_seconds':15}],'on_remove':[{'op':'interrupt_ability','ability':RAY},{'op':'set_ability_cooldown','ability':RAY,'duration_seconds':15}],'events':[{'event':'attachment.finished','condition':"inputs.payload.source == context.owner.id and inputs.payload.reason in ['target_invalid','source_flags','cast_interrupted']",'effects':[remove(RAYSTATE)]}]},{'id':SLOW,'kind':'buff','modifiers':[{'attribute':'attack_speed_ratio','layer':'final_ratio','value':-.7}],'on_remove':[{'op':'trigger_ability','target':'source','ability':TILE,'parameters':{'forward_input':True},'condition':"inputs.targets[0].components.runtime.alive == False"}]}]
    states={'ground_stone':{'on_enter':[apply(SHIELD),{'op':'set_motion_mode','value':0,'parameters':{'route_motion_mode':0}}]},'ground_open':{'on_enter':[remove(SHIELD)]},'fly_stone':{'on_enter':[apply(SHIELD),apply(stone2),{'op':'set_motion_mode','value':1,'parameters':{'route_motion_mode':0}}]},'fly_open':{'on_enter':[remove(SHIELD),remove(stone2),{'op':'set_motion_mode','value':0,'parameters':{'route_motion_mode':0}}]}}
    p['behaviors']=[{'id':'behavior/'+PREFIX+'modes','kind':'behavior','initial':'ground_stone','states':states,'transitions':[]}]
    for mode,state in enumerate(states):
        binding=next(a['binding'] for a in req['animations'] if a['mode']==mode and a['role']=='_attack');p['abilities'].append({'id':'ability/'+PREFIX+'normal_'+str(mode),'kind':'ability','activation':{'mode':'automatic_attack','interval_seconds':1.8,'condition':"inputs.source.components.behavior.state == '"+state+"'"},'selector':'selector/'+PREFIX+('block' if mode<2 else 'range'),'duration_seconds':binding['duration']['seconds'],'timeline':[{'at_seconds':binding['events'][0]['seconds'],'effect':{'op':'damage','damage_type':'arts','scale':1}}],'metadata':{'native_mode':mode,'resolved_animation':binding}})
        if mode>=2:p['abilities'][-1]['timeline'][0]['effect'].update(projectile_definition=normal_projectile,read_mode={'source_attributes':'at_hit','target_attributes':'at_hit'})
    p['abilities'].append({'id':RAY,'kind':'ability','initial_cooldown_seconds':5,'activation':{'mode':'manual','forbidden_source_flags':[0,12,16],'parameters':{'auto_only':True,'auto_when_ready':True,'requires_targets':True},'on_start':[{'op':'apply_buff','target':'source','buff':RAYSTATE,'bind_to_cast':True},{'op':'set_ability_cooldown','target':'source','ability':RAY,'duration_seconds':0}]},'selector':'selector/'+PREFIX+'ray','rules':{'targeting.score':'rule/'+PREFIX+'max_atk'},'duration_seconds':7.1,'wait_for_channels':True,'timeline':[{'at_seconds':.25,'effect':{'op':'begin_attachment','attachment':'attachment/'+PREFIX+'ray'}}]})
    p['definitions']=[{'id':'attachment/'+PREFIX+'ray','kind':'attachment','duration_seconds':7.1,'flight_lifetime_seconds':5,'step_interval_seconds':1/30,'hit_interval_seconds':1,'refresh_interval_seconds':1,'motion':{'rule':'rule/'+PREFIX+'motion','parameters':{'mode':'homing','speed':10}},'target_buff':SLOW,'effect':{'op':'damage','damage_type':'arts','scale':1,'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}},'damage_integral':False,'source_cancel_flags':[0,12,16],'ignored_owned_source_flags':[],'force_reach_on_timeout':False,'lifecycle':{'source_invalid':'cancel','target_invalid':'cancel','source_hidden':'cancel','target_hidden':'cancel'},'max_packets':None,'completion_blocking':False,'source_recovery_buff':None,'recovery_on':[]}]
    # Actual token047 follows its native TrapMode; it has no fabricated health.
    token=json.loads(TOKEN.read_bytes());mode=next(c['raw'] for c in token['native_prefab']['components'].values() if c['native_class']=='TrapMode')
    sealed='unit/'+PREFIX+'sealed_ground';p['entities'].append({'id':sealed,'kind':'entity','tags':['sealed_ground'],'components':{'spatial':{},'tile_occupancy':{'blocks_deployment':True,'exclusive':False,'targetable':False,'withdrawable':False},'terrain_overlays':[{'key':'sealed_ground','priority':1,'values':{'buildableType':mode['_tileOptions']['buildableType'],'passableMask':mode['_tileOptions']['passableMask'],'physicalHeight':mode['_rewriteHeight']},'preserve':[]}],'lifecycle':{'policy':'policy/ark_lifecycle'}},'metadata':{'native_token':token}})
    spawn={'op':'spawn_on_tiles','definition':sealed,'parameters':{'cells':'captured','recheck':True,'occupant_expression':'False','occupant_parameters':{},'instant_kill':{'cause':'mandra_tile','skip_rebirth':False},'on_owner_retire':'retain'}}
    p['abilities'].append({'id':TILE,'kind':'ability','activation':{'mode':'manual','parameters':{'auto_only':True,'blocks_attacks':False}},'tile_selector':{'require_owned_task':True,'accept_input':True,'eligibility_expression':'inputs.cell.row == round(inputs.input.position.row) and inputs.cell.col == round(inputs.input.position.col) and not inputs.deployment_blocked','parameters':{},'limit':1,'selection':'row_major','stream':None},'timeline':[{'at':0,'effect':spawn}]})
    auto='unit/'+PREFIX+'auto_pillar';bodypillar=copy.deepcopy(p['entities'][0]);bodypillar['id']=auto;timer='buff/'+PREFIX+'auto_collapse';bodypillar['components']['buffs']['initial'].append(timer);bodypillar['components']['tile_occupancy']={'blocks_deployment':True,'exclusive':False,'targetable':True,'withdrawable':True};p['entities'].append(bodypillar);p['buffs'].append({'id':timer,'kind':'buff','interval_seconds':5,'effects':[{'op':'trigger_ability','ability':'ability/ch9/pillar/collapse_right','target':'source'}]})
    spawnpillar=copy.deepcopy(spawn);spawnpillar['definition']=auto
    p['abilities'].append({'id':SUMMON,'kind':'ability','initial_cooldown_seconds':15,'cooldown_seconds':15,'activation':{'mode':'manual','parameters':{'auto_only':True,'auto_when_ready':True},'condition':"inputs.source.components.behavior.state in ['fly_stone','fly_open']"},'duration_seconds':40/30,'tile_selector':{'require_owned_task':True,'eligibility_expression':'inputs.cell.row == round(inputs.source.components.spatial.position.row) and inputs.cell.col > inputs.source.components.spatial.position.col and inputs.cell.col <= inputs.source.components.spatial.position.col + 2 and inputs.tile.buildableType != 0 and not inputs.deployment_blocked','parameters':{},'limit':1,'selection':'row_major','stream':None},'timeline':[{'at_seconds':20/30,'effect':spawnpillar}],'metadata':{'native_branch':cfg['branch'],'native_stage_branch':None,'owned_reference_spawn':True}})
    p['buffs'].append({'id':'buff/'+PREFIX+'pending_skin','kind':'buff','duration_seconds':25,'interval_seconds':1/30,'effects':[{'op':'trigger_ability','target':'source','ability':'ability/'+PREFIX+'restore_skin','parameters':{'on_rejection':'skip'}}],'events':[{'event':'ability.started','condition':"inputs.payload.source == context.owner.id and inputs.payload.ability == 'ability/ch9/mandra/restore_skin' and inputs.payload.cast in context.owner.components.runtime.casts",'effects':[{'op':'remove_buff','buff':'buff/'+PREFIX+'pending_skin','target':'source'}]}]})
    p['abilities'].append({'id':'ability/'+PREFIX+'restore_skin','kind':'ability','activation':{'mode':'manual','parameters':{'auto_only':True}},'duration_seconds':45/30,'timeline':[],'metadata':{'native_animation_by_mode':{'ground_stone':'C1_Skill_2','fly_stone':'C2_Skill_2'},'native_full_frames':45,'native_on_attack_frame':22,'native_actions':[],'policy':'Source onFinish creates StoneEffect before starting owned animation; source ability action table is empty, so no fabricated frame22 damage'}})
    ids=['ability/'+PREFIX+'normal_'+str(i) for i in range(4)]+[RAY,SUMMON,TILE,'ability/'+PREFIX+'restore_skin'];p['entities'].append({'id':BODY,'kind':'entity','tags':['enemy','boss'],'components':{'attributes':{'base':{'max_hp':50000,'atk':640,'def':520,'mres':35,'move_speed':.4,'mass_level':7,'block_cost':1,'attack_interval':1.8,'attack_speed_ratio':1}},'resources':{'hp':{'role':'health','initial':50000,'capacity':50000}},'selection_state':{'side':1,'motion':1,'category':1,'unit_type':2},'spatial':{'motion_mode':0,'route_motion_mode':0},'abilities':ids,'behavior':{'machine':'behavior/'+PREFIX+'modes'},'buffs':{'initial':[SHIELD]},'lifecycle':{'policy':'policy/ark_lifecycle'},'rebirth':{'resource':'hp','max_count':1,'delay_seconds':5,'restore_ratio':1,'restore_rule':'rule/'+PREFIX+'restore','reset_attack_clock':True,'on_begin':[transition('fly_stone'),apply(inv),{'op':'set_ability_cooldown','target':'source','ability':RAY,'duration_seconds':cfg['ray_cd']},{'op':'set_ability_cooldown','target':'source','ability':SUMMON,'duration_seconds':cfg['summon_cd']}],'on_finish':[]}}})
    return p
