import sys,json,hashlib,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CAND=(ROOT/'../unpack_work/campaign_c9_mandra_v1_candidate').resolve();PARENT=(ROOT/'../unpack_work/campaign_c9_duspfr_v1_candidate').resolve();sys.path.insert(0,str(CAND))
from ark_sim.adapters.api import implementation_digest
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();OUT=ROOT/'validation/campaign/chapter09_mandra_v1';delta=[]
for p in sorted((CAND/'ark_sim').rglob('*')):
    if not p.is_file() or '__pycache__' in p.parts or p.suffix=='.pyc':continue
    rel=p.relative_to(CAND);old=PARENT/rel
    if not old.exists() or p.read_bytes()!=old.read_bytes():
        target=ROOT/'tools/chapter09_mandra_v1/source_delta.primitive.v1'/rel;target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,target);delta.append({'path':rel.as_posix(),'parent_sha256':sha(old) if old.exists() else None,'candidate_sha256':sha(p),'saved_delta_sha256':sha(target)})
before=implementation_digest();reports=[]
for name in ['author.capture.initial.json','author.waiting_mode.json','author.domain46.json']:
    p=OUT/name;r=json.loads(p.read_bytes());assert r['actual_exit']==0 and r['core_before']==r['core_after']==before;reports.append({'path':str(p.relative_to(ROOT)).replace('\\','/'),'sha256':sha(p),'actual_exit':r['actual_exit']})
old=json.loads((PARENT/'ark_sim/rules/contracts.json').read_bytes());new=json.loads((CAND/'ark_sim/rules/contracts.json').read_bytes());assert new['contracts'][:-1]==old['contracts'] and new['types']==old['types']
receipt={'schema':'ark-sim/compact-development-progress/v1','candidate':str(CAND),'core_before':before,'core_after':implementation_digest(),'parent_core':'2c385c9c4a9e383988a3ff8d8d96827f0e473dde0630a3d6d92aa35c5f0dccb0','stage':'Generic capture and actual owned-rebirth mode primitive, preliminary author evidence','final_freeze':False,'full_mandra_consumer_implemented':False,'promoted':False,'catalog':{'current':108,'old107_structurally_unchanged':True,'appended':'buff.capture prototype v1'},'reports':reports,'delta':delta,'rock_motion_source':'validation/campaign/chapter09_rock_modes_v2/freeze.v2.json (four source hunks mechanically applied; no old green migrated)','token047_source':{'path':'packages/campaign/chapter09_consumers/mandra/source.token047.v1.json','sha256':sha(ROOT/'packages/campaign/chapter09_consumers/mandra/source.token047.v1.json'),'character_key_missing_in_fixed_table':True,'no_health_in_prefab':True},'pending':['Full source Mandra four-mode content','StoneSkin25s/currentHP ratio-.4 application and actual source pillar damage','PetrifiedRay/source target live state/current sampling and sealed-ground47 spawn','Two-life profiles3vs5 invulnerability/20vs10 Summon clocks','Actual native branch-null source/reference token placement and owned auto collapse5s','Full public command CPP/head and independent/final source freeze'],'raw_created_in_capture_and_waiting_tests':False,'domain46_cleanup':json.loads((OUT/'author.domain46.json').read_bytes())['cleanup']};(OUT/'primitive.progress.v1.json').write_text(json.dumps(receipt,indent=2),encoding='utf8');print(json.dumps({'core':before,'delta_files':len(delta),'receipt_sha256':sha(OUT/'primitive.progress.v1.json'),'final_freeze':False}))
