"""300-tick exact source prefix past the real 90-tick Frost birth and info action."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];RUNTIME=ROOT.parent/'unpack_work/campaign_frost_complete_v5_candidate';OUT=ROOT/'validation/campaign/chapter04_10_join_prepare';PIN='7a04c12a1a4224eecbd25b495d84c27da0096ceef7d01f50f1a1c8c9b8da7d90'
sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT));import ark_sim
from ark_sim import Compiler,Engine
from ark_sim.adapters.api import implementation_digest
from ark_sim.tools.replay import replay
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
from ark_sim.contracts import thaw
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==PIN and Path(ark_sim.__file__).resolve().parent==RUNTIME/'ark_sim';stage=RUNTIME/'stage/level_main_04-10.complete_frost.explicit.author_prepared.json';assert sha(stage)=='7b5c062528c35bbdfe571763ec7065d75b002cf58bb722e760518eac078957d0';p=json.loads(stage.read_bytes());paths=[stage,Path(__file__),ROOT/'tools/build_chapter04_10_stage.py',ROOT/'tools/build_reference_stage_scenario_v2.py',ROOT/'tools/campaign_content_composition.py',ROOT/'tools/campaign_ordered_checkpoint.py']+[Path(k) if Path(k).is_absolute() else ROOT/k for k in p['manifest']['metadata']['source_locks']]+[f for f in (RUNTIME/'ark_sim').rglob('*') if f.is_file() and f.suffix in ('.py','.json')];before={str(x):sha(x) for x in paths};program=Compiler().compile(p);s=Engine.create(program);s.advance(150);cp=OUT/'v5_stage150.ordered.json';h=write_ordered(cp,s.checkpoint());restored=Engine.restore(program,load_bound(cp,h));s.advance(150);restored.advance(150);assert s.snapshot()==restored.snapshot()==replay(program,s.export_replay()).snapshot();after={str(x):sha(x) for x in paths};assert before==after and implementation_digest()==PIN
 boss_def=next(r['unit_definition'] for r in p['manifest']['metadata']['variant_bindings'] if r['variant_id']=='enemy_1505_frstar@0/9d1e3d01ef79ae3e');boss=next(e for e in s.session.world.entities() if e['definition_id']==boss_def);births=[thaw(e) for e in s.session.events if e['type']=='entity.created' and e['payload']['definition']==boss_def];info=[thaw(e) for e in s.session.events if e['type']=='reference.enemy_info.observed'];assert len(births)==1 and births[0]['time']==90 and len(info)==1 and info[0]['time']==90 and s.ctx.resources.current(boss['id'],'hp')==25000
 final=OUT/'v5_stage300.final.json';final.write_text(json.dumps(s.snapshot(),indent=2)+'\n',encoding='utf8',newline='');record=OUT/'v5_stage300.replay.json';record.write_text(json.dumps(s.export_replay(),indent=2)+'\n',encoding='utf8',newline='');report={'role':'Author actual-spawned prefix only, no full-stage or independent acceptance claim','core':PIN,'stage_sha':sha(stage),'native_seed':p['scenarioDraft']['seed'],'tick':s.session.time,'events':len(s.session.events),'exact_source_boss_birth':births,'native_enemy_info_consumer':info,'actual_boss_hp':25000,'actual_boss_resources':thaw(s.ctx.get(boss['id'],('resources',))),'ordered150_diskCP_resume_equal':True,'start_public_replay_equal':True,'checkpoint_sha':h,'final_sha':sha(final),'replay_sha':sha(record),'guards_before':before,'guards_after':after,'native43birth_plan':43,'exact_variant_bindings':7,'fixed_roster':12,'native_slots':10,'initial_DP':10,'native_move_multiplier':.5,'source_runes_predefines_portals_preserved':True,'no_operator_deployments':True,'actual_portal_traversal_claimed':False,'whole_stage_executed':False,'client_verified':False};dest=OUT/'v5_spawned_short_verification.json'
 if dest.exists():raise ValueError('Preserve evidence')
 dest.write_text(json.dumps(report,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'core':PIN,'tick':s.session.time,'events':len(s.session.events),'boss_birth_at':90,'report_sha':sha(dest)}))
if __name__=='__main__':main()
