"""Exact ranged crossbow consumer with one PPtr, actual flight and targetFrozen passive."""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[3]
SOURCE=ROOT/'packages/campaign/chapter06_sources/native.reference.json'
COLD=ROOT/'packages/campaign/chapter06_cold/model.json'
OUT=ROOT/'packages/campaign/chapter06_units/snbow'
VID='enemy_1066_snbow@0/fc7412f7cf3aee2d'
UID='unit/ch6/snbow/fc7412f7cf3aee2d';AID='ability/'+UID;SID='selector/'+UID;PID='projectile/'+UID;BID='behavior/'+UID
CORE='a7059989b9db7f4bc0de954b32cb5c5ba10e6b92ce040c57ea0a193549b9709a'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_bytes((json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode('utf8'))
def provider(id,contract,name):return {'id':id,'kind':'rule','contract':contract,'implementation':{'type':'provider','provider':name}}
def defaults():return {'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False,'abnormal_immunes':[]}
def source():
    if sha(SOURCE)!='efbf42be4db3ee14b98dcbdba72a516b35e54e2540e77ce64e32b060e8e5e6f3' or sha(COLD)!='e610f9446b077c6df7a86922e6719226e5a352a3826d6fe40c49e3296437b4dc':raise ValueError('Frozen source drift')
    s=json.loads(SOURCE.read_bytes());v=s['variants'][VID];d=v['native_enemy']['resolved'];prefab=s['prefabs'][v['prefab_key']];nodes=v['modes'][0]['nodes'];normal=nodes['_combat'];r=normal['raw']
    if len(v['modes'])!=1 or normal['path_id']!=nodes['_attack']['path_id'] or normal['raw']!=nodes['_attack']['raw'] or v['additional_animation_drivers'] or d.get('skills') or d.get('spData'):raise ValueError('Extra or duplicate source dependency')
    if len(v['passive_and_skill_components'])!=1:raise ValueError('Only one passive required')
    passive=v['passive_and_skill_components'][0];buffs=passive['raw']['_buffs']
    if passive['class']!='PassiveBuffAbility' or len(buffs)!=1 or buffs[0]['templateKey']!='e2c_frozen_atkscale' or buffs[0]['isSilenceable']!=0 or any(buffs[0]['attributes'].values()) or d['talentBlackboard']!=[{'key':'atkup.atk_scale','value':1.5,'valueStr':None}]:raise ValueError('Actual targetFrozen passive differs')
    if (r['_selectTargetSource'],r['_selectTargetTiming'],r['_waitForAttackEvent'],r['_timeMode'],r['_affectedBySlowDown'],r['_damageType'],r['_atkScale'])!=(2,0,1,0,1,1,1) or r['_activeBuffs'] or r['_extraDamageType'] or r['_epDamageRatio']:raise ValueError('Exact normal projectile source differs')
    if [e['frame'] for e in normal['animation_binding']['events'] if e['name']=='OnAttack']!=[12]:raise ValueError('Exact frame12')
    components=prefab['components'];cfg=next(c for c in components.values() if c['native_class']=='AdvancedSelector');root=next(c for c in components.values() if c['native_class']=='Enemy');mover=next(c for c in components.values() if c['native_class']=='MoveController')
    projectile=s['projectiles'][r['_projectileKey']];simple=next(c for c in projectile['components'].values() if c['native_class']=='SimpleProjectile');motion=next(c for c in projectile['components'].values() if c['native_class']=='AdvancedMovement')
    if r['_projectileKey']!='projectile_crossbow' or simple['raw']['_lifeTime']!=5 or simple['raw']['_maxHitNum']!=1 or simple['raw']['_stopWhenSourceInvalid']!=0 or motion['raw']['_speed']!=10:raise ValueError('Actual crossbow source changed')
    if root['raw']['_delayToBorn']!=0 or d['attributes']['hpRecoveryPerSec']!=0 or d['attributes']['spRecoveryPerSec']!=0:raise ValueError('Unconsumed born/recovery')
    return {'schema':'ark-sim/ch6-snbow-source/v1','variant':v,'source_locks':s['source_locks'],'source_sha256':sha(SOURCE),'root':root,'mover':mover,'normal':normal,'selector':cfg,'passive':passive,'projectile':projectile,'dedupe':{'_combat':normal['path_id'],'_attack':nodes['_attack']['path_id'],'actual_payloads_per_cast':1},'policies':{'selection':'Native selectTargetTiming0 and source2 mapped to at_cast identity capture; captured target retained through windup/flight, new casting uses fresh eligibility; native methodbody replaceable','hatred':'postFilter4 HATRED_DES; taunt descending/latest actorID descending explicitreference; native body/tie client calibration pending','windup':'seconds/max(effectiveASPD,.01) thenceil; native affectedBySlowDown1/timeMode0 consumed; maximum animationclamp relation unverified','motion':'nativehoming speed10, life5/source_invalidretain, targetinvalid/hidden cancel; map-plane mount/body offsets explicitreplaceable','immunity':'Undefined wrappers preserved; omitted getter defaults reference, not nativeFalse','attack_mutual_exclusion':'Single samePPtr normal ability, genericblocking cast and next_attack72; no additionalpassive shot','damage':'Native physicalnormalscale1; targetFrozen buff1.5 at acceptedimpact beforeDEF, non-silenceable0; source ATK unaffected','no_cold_payload':'Native activeBuffs empty; this variant does not add Cold itself'}}
def build(src):
    a=src['variant']['native_enemy']['resolved']['attributes'];steer=src['mover']['raw'];cfg=src['selector']['raw'];windup='rule/'+UID+'/windup';score='rule/'+UID+'/hatred';trajectory='rule/'+UID+'/trajectory';collision='rule/'+UID+'/collision';eligibility='rule/'+UID+'/eligibility';steering='rule/'+UID+'/steering'
    rules=[provider(trajectory,'projectile.trajectory','model.projectile.trajectory'),provider(collision,'projectile.collision','model.projectile.collision'),provider(eligibility,'targeting.eligibility','model.targeting.eligibility'),provider(steering,'movement.steering','ark.movement.steering_velocity'),{'id':windup,'kind':'calculation_rule','contract':'ability.windup','parameters':{'minimum_speed':.01,'native_max_anim_scale':src['normal']['raw']['_maxAnimScale']},'implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio, params.minimum_speed)'}},{'id':score,'kind':'rule','contract':'targeting.score','implementation':{'type':'expression','expression':"-100000 * (inputs.candidate.components.attributes.base.taunt_level if 'taunt_level' in inputs.candidate.components.attributes.base else 0) - inputs.candidate.id"}}]
    unit={'id':UID,'kind':'entity','tags':['enemy','ground'],'metadata':{'native_variant_id':VID,'native_reference':src['variant']['native_reference']},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':src['root']['raw']['_blockVolume']}},'resources':{'hp':{'initial':a['maxHp'],'capacity':a['maxHp'],'role':'health'}},'selection_state':{**defaults(),'side':1,'unit_type':2},'spatial':{'motion_mode':0,'steering':{'rule':steering,'parameters':{'response_factor':steer['_steeringFactor'],'max_acceleration':steer['_maxSteeringForce'],'arrival_radius':.05}}},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':1},'abilities':[AID],'buffs':{'initial':['buff/ch6/cold/frozen_atkscale1.5']},'behavior':{'machine':BID}}}
    ability={'id':AID,'kind':'ability','selector':SID,'target_capture':'at_cast','rules':{'ability.windup':windup,'targeting.score':score},'activation':{'mode':'automatic_attack','parameters':{'auto_only':True}},'timeline':[{'at_seconds':.4,'effect':{'op':'damage','damage_type':'physical','scale':1,'projectile_definition':PID,'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}}]}
    selector={'id':SID,'kind':'selector','region':{'type':'radius','radius':1.9},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{'rule':eligibility,'parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}}
    projectile={'id':PID,'kind':'projectile','motion':{'rule':trajectory,'parameters':{'mode':'homing','speed':10}},'collision':{'rule':collision,'parameters':{'enabled':True,'radius':0}},'lifetime_seconds':5,'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'cancel','target_hidden':'cancel','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'on_invalid':[]}
    behavior={'id':BID,'kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/ark_behavior_decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'ranged','selector':SID}],'cast_groups':[{'key':'normal','abilities':[AID]}],'parameters':{'target_key':'ranged','stop_on_target':True,'stop_cast_groups':['normal']}}]}}
    return {'schemaVersion':2,'manifest':{'id':'package/ch6/snbow/source','requires':['preset/ark_standard'],'metadata':{'source_locks':{'packages/campaign/chapter06_sources/native.reference.json':sha(SOURCE),'packages/campaign/chapter06_cold/model.json':sha(COLD)},'builder_sha256':sha(Path(__file__)),'variant_bindings':[{'variant_id':VID,'unit_definition':UID,'native_reference':src['variant']['native_reference']}],'source_binding':src,'reference_policies':src['policies'],'complete_source_policies':False,'independent_reviewed':False,'whole_stage_executed':False,'client_verified':False}},'entities':[unit],'rules':rules,'abilities':[ability],'selectors':[selector],'projectiles':[projectile],'behaviors':[behavior]}
if __name__=='__main__':
    OUT.mkdir(parents=True,exist_ok=True);src=source();write(OUT/'source.reference.json',src);write(OUT/'model.json',build(src));print(json.dumps({'module_sha256':sha(OUT/'model.json'),'source_sha256':sha(OUT/'source.reference.json')}))
