"""Shared diagnostic log, notification journal and bounded asynchronous exports.

Qt snapshots context before a worker performs environment/ZIP I/O. Downloads
are restricted to artifacts generated by this session; callers never name paths.
"""
from collections import deque
import copy
import os
import subprocess
import threading
import uuid

from ..diagnostic_log import DiagnosticLogManager


class RuntimeDiagnostics:
    """Reuse the test logger; normal WebUI and isolated fixtures get the same API."""
    def __init__(self, window):
        self.window = window
        self.logger = getattr(window, '_diagnostic_logger', None)
        self._owns_logger = self.logger is None
        if self.logger is None:
            # A WebUI opened later from the desktop uses the same portable
            # default as --webui startup. Preferences are not a storage root;
            # fixtures inject an explicit isolated logger at this IO boundary.
            self.logger = DiagnosticLogManager()
        self._lock = threading.RLock()
        self._events = deque(maxlen=256)
        self._seq = 0
        self._jobs = {}
        self._thread = None
        self._closed = False
        self._working = False
        self._test_mode = bool(window._diagnostic_context().get('test_build'))
        self._unsubscribe = window._toast.subscribe(self._notification)

    def _notification(self, item):
        with self._lock:
            self._seq += 1
            self._events.append({'seq': self._seq, 'text': item.text, 'title': item.title,
                                 'level': item.level, 'semantic': item.semantic, 'duration': item.duration})
        self.logger.log(f'[{item.level.upper()}] {item.text}')

    def notifications(self):
        with self._lock:
            return {'sessionId': self.logger.session_id, 'lastSeq': self._seq,
                    'items': copy.deepcopy(list(self._events))}

    def metadata(self):
        return {'sessionId': self.logger.session_id, 'logPath': str(self.logger.log_path),
                'logRoot': str(self.logger.log_root), 'testMode': self._test_mode}

    def command(self, action, params):
        if action == 'logs-read':
            return self.logger.snapshot(params.get('after', 0), params.get('limit', 10000))
        if action == 'logs-job':
            with self._lock:
                job = self._jobs.get(params.get('id'))
                if job is None:
                    raise ValueError('日志任务已过期')
                return {key: copy.deepcopy(value) for key, value in job.items() if key != 'path'}
        if action == 'logs-folder':
            if os.name == 'nt':
                os.startfile(str(self.logger.log_root))
            else:
                subprocess.Popen(['xdg-open', str(self.logger.log_root)])
            return {'accepted': True, 'message': '已打开本机日志目录'}
        if action not in {'logs-export', 'logs-environment'}:
            raise ValueError('未知日志命令')
        if self._closed or (self._thread and self._thread.is_alive()):
            raise ValueError('上一项日志任务尚未结束，请稍后重试')
        output_format = params.get('format', 'zip')
        if output_format not in {'text', 'zip'}:
            raise ValueError('日志导出仅支持 text 或 zip')
        context = self.window._diagnostic_context()
        job_id = uuid.uuid4().hex
        job = {'id': job_id, 'status': 'running', 'result': None, 'message': '正在生成环境诊断或导出…'}
        with self._lock:
            # Keep the current session's last 32 artifact identities only.
            if len(self._jobs) >= 32:
                self._jobs.pop(next(iter(self._jobs)))
            self._jobs[job_id] = job
            self._working = True
        self._thread = threading.Thread(target=self._run, args=(job_id, action, output_format, context),
                                        name='timeline-webui-log-export', daemon=True)
        self._thread.start()
        return {'id': job_id, 'status': 'running', 'message': job['message']}

    def _run(self, job_id, action, output_format, context):
        try:
            result = None
            path = None
            if action == 'logs-environment':
                self.logger.append_environment_snapshot(context)
                message = '环境信息已追加到实时日志'
            elif output_format == 'zip':
                path = self.logger.build_package(self.logger.log_root / f'diagnostics_{job_id}.zip', context=context)
                message = '完整诊断包已生成（含会话日志、异常日志、环境及偏移信息）'
            else:
                # Copy the full disk session, not just the UI's 10,000-line tail.
                path = self.logger.log_root / f'session_export_{job_id}.log'
                self.logger.export_session(path)
                message = '完整会话日志已导出'
            if path is not None:
                result = {'url': f'/api/logs/download?id={job_id}', 'filename': path.name}
            with self._lock:
                if not self._closed:
                    self._jobs[job_id].update(status='done', message=message, result=result, path=path)
        except Exception as exc:
            with self._lock:
                if not self._closed:
                    self._jobs[job_id].update(status='error', message=str(exc))
        finally:
            with self._lock:
                self._working = False
                if self._closed and self._owns_logger:
                    self.logger.close()

    def download(self, job_id):
        with self._lock:
            job = self._jobs.get(job_id)
            path = job.get('path') if job and job['status'] == 'done' else None
        if path is None or not path.is_file() or path.resolve().parent != self.logger.log_root.resolve():
            raise ValueError('该日志导出不存在或尚未完成')
        return path

    def close(self):
        self._unsubscribe()
        # A bounded I/O worker may still be building a diagnostic package. It
        # owns the logger until it finishes; never close its streams underneath.
        with self._lock:
            self._closed = True
            if self._owns_logger and not self._working:
                self.logger.close()
