import sys,json
from pathlib import Path
from copy import deepcopy
import pytest
ROOT=Path(__file__).resolve().parents[3];RUNTIME=ROOT.parent/'unpack_work/campaign_m24_enemy_fsm_candidate';sys.path.insert(0,str(RUNTIME))
import ark_sim
from ark_sim import Compiler,Engine
from ark_sim.tools.replay import replay
from ark_sim.adapters.api import implementation_digest
CORE='c4fc6cb000208e2518c9bf55b742773c1276fc87bdca8241b58a95bd11e80f22'
def scene():
    return {'entities':[{'id':'unit/actor','kind':'entity','tags':['actor','enemy','ground'],'components':{'attributes':{'base':{'atk':30,'max_hp':500,'def':0,'move_speed':3,'attack_interval':1,'attack_speed_ratio':1}},'resources':{'hp':{'initial':500,'capacity':500,'role':'health'},'mode':{'initial':0,'capacity':1}},'spatial':{},'abilities':['ability/shot'],'behavior':{'machine':'behavior/probe'}}},{'id':'unit/target','kind':'entity','tags':['player','ground'],'components':{'attributes':{'base':{'max_hp':1000,'def':5}},'resources':{'hp':{'initial':1000,'capacity':1000,'role':'health'}},'spatial':{},'abilities':['ability/escape','ability/activate','ability/stun']}}],
    'abilities':[{'id':'ability/shot','kind':'ability','selector':'selector/targets','activation':{'mode':'automatic_attack'},'duration_seconds':.4,'timeline':[{'at_seconds':.2,'effect':{'op':'damage','damage_type':'physical'}}]},{'id':'ability/escape','kind':'ability','activation':{'mode':'manual','on_start':[{'op':'move','target':'source','position':{'row':1,'col':7}}]},'timeline':[]},{'id':'ability/activate','kind':'ability','activation':{'mode':'manual','on_start':[{'op':'activate_predefined','target':'battle','parameters':{'key':'dormant-actor'}}]},'timeline':[]},{'id':'ability/stun','kind':'ability','selector':'selector/actor','activation':{'mode':'manual','on_start':[{'op':'apply_buff','buff':'buff/stun'}]},'timeline':[]}],
    'buffs':[{'id':'buff/stun','kind':'buff','duration_seconds':.1,'control':{'move':False,'attack':False,'abilities':False}}],
    'selectors':[{'id':'selector/targets','kind':'selector','region':{'type':'radius','radius':1.5},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1},{'id':'selector/actor','kind':'selector','region':{'type':'all'},'filters':[{'tag':'actor'},{'state':'alive'}],'limit':1}],
    'behaviors':[{'id':'behavior/probe','kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/ark_behavior_decision','mode_resource':'mode','profiles':[{'mode':i,'selectors':[{'key':'target','selector':'selector/targets'}],'cast_groups':[{'key':'shots','abilities':['ability/shot']}],'parameters':{'target_key':'target','stop_cast_groups':['shots'],'stop_on_target':True}} for i in (0,1)]}}],
    'scenarioDraft':{'id':'scenario/peer_fsm','ruleset':'ruleset/ark_standard','map':{'rows':3,'cols':10},'resources':{'dp':{'initial':10,'capacity':20}},'objectives':{},'initialEntities':[{'definition':'unit/actor','registration_key':'dormant-actor','instanceAlias':'actor','position':{'row':1,'col':0},'route':{'motionMode':0,'startPosition':{'row':1,'col':0},'endPosition':{'row':1,'col':9},'checkpoints':[]}},{'definition':'unit/target','instanceAlias':'target','position':{'row':1,'col':1}}]}}
def make(p=None):
    assert implementation_digest()==CORE;s=Engine.create(Compiler().compile(p or scene()),seed=2411);assert Path(ark_sim.__file__).resolve().parent==RUNTIME/'ark_sim';return s
def pure(s):
    cp=s.checkpoint();ids=s.ctx.spatial.eligible('actor','selector/targets');assert cp==s.checkpoint();return ids
def proof(s):
    r=Engine.restore(s.program,s.checkpoint());s.advance(3);r.advance(3);assert s.snapshot()==r.snapshot()==replay(s.program,s.export_replay()).snapshot();assert implementation_digest()==CORE
def events(s,name):return [e for e in s.session.events if e['type']==name]
def test_target_escape_preserves_started_packet_stops_new_cast_and_resumes_after_finish():
    s=make();assert pure(s)==[s.session.world.resolve('target')];s.submit({'action':'skill','source':'target','ability':'ability/escape'},at=4);s.advance(13);assert not pure(s);assert s.ctx.get('actor',('spatial','position'))['col']==0;assert [(e['time'],e['payload']['amount']) for e in events(s,'damage.accepted')]==[(6,25)];s.advance(1);assert abs(s.ctx.get('actor',('spatial','position'))['col']-.1)<1e-8;assert len([e for e in events(s,'ability.started') if e['payload']['source']==s.session.world.resolve('actor')])==1;proof(s)
def test_dormant_source_activation_public_command_first_cast_actual():
    p=scene();p['scenarioDraft']['initialEntities'][0].update(active=False,registration_key='dormant-actor');s=make(p);s.submit({'action':'skill','source':'target','ability':'ability/activate'},at=5);s.advance(12);assert [e['time'] for e in events(s,'ability.started') if e['payload']['source']==s.session.world.resolve('actor')]==[5];assert [(e['time'],e['payload']['amount']) for e in events(s,'damage.accepted')]==[(11,25)];assert s.ctx.get('actor',('spatial','position'))['col']==0;proof(s)
def test_public_control_blocks_fresh_casts_without_cancelling_existing():
    s=make();s.submit({'action':'skill','source':'target','ability':'ability/stun'},at=1);s.advance(4);assert s.ctx.get('actor',('spatial','position'))['col']==0;assert not events(s,'damage.accepted');assert len([e for e in events(s,'ability.started') if e['payload']['source']==s.session.world.resolve('actor')])==1;proof(s)
def test_pure_eligibility_and_selected_identity_with_random_order_no_probe_draws():
    p=scene();p['selectors'][0].update(ordering='random',parameters={'random_stream':'imp'});s=make(p);before=s.checkpoint();ids=pure(s);assert s.checkpoint()==before;actual=s.ctx.spatial.select('actor','selector/targets');assert actual==ids;assert len(s.session.random.samples)==1
    # Direct actual select is an API witness only; no command replay claim.
def test_live_mode_switch_changes_pure_target_region_without_old_cache():
    p=scene();p['entities'][1]['components']['abilities'].append('ability/mode');p['abilities'].append({'id':'ability/mode','kind':'ability','selector':'selector/actor','activation':{'mode':'manual','on_start':[{'op':'modify_resource','resource':'mode','amount':1}]},'timeline':[]});p['selectors'].append({'id':'selector/far','kind':'selector','region':{'type':'radius','radius':.1},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1});p['behaviors'][0]['decision']['profiles'][1]['selectors'][0]['selector']='selector/far';s=make(p);s.submit({'action':'skill','source':'target','ability':'ability/mode'},at=0);s.advance(2);assert s.ctx.resources.current('actor','mode')==1;assert s.ctx.get('actor',('runtime','behavior_decision'))=={'move':True,'attack':False};assert abs(s.ctx.get('actor',('spatial','position'))['col']-.2)<1e-8;assert not [e for e in events(s,'ability.started') if e['payload']['source']==s.session.world.resolve('actor')];proof(s)
def test_real_rule_failure_after_payment_and_rng_entire_atomic_rollback():
    p=scene();p['rules']=[{'id':'rule/fail','kind':'rule','contract':'behavior.decision','implementation':{'type':'expression','expression':"{'move':False,'attack':True} if not inputs.casts else 1/0"}}];p['behaviors'][0]['decision']['rule']='rule/fail';p['abilities'][0]['activation']['costs']=[{'owner':'battle','resource':'dp','amount':1}];p['abilities'][0]['activation']['on_start']=[{'op':'random','stream':'imp','probability':1,'on_success':[{'op':'modify_resource','resource':'hp','amount':-1,'target':'source'}]}];s=make(p);before=s.checkpoint()
    with pytest.raises(Exception):s.ctx.abilities.start('actor','ability/shot',automatic=True)
    assert s.checkpoint()==before

def test_target_hidden_route_changes_query_and_reappears_without_probe_effects():
    p=scene();p['entities'][1]['components']['attributes']['base']['move_speed']=0;p['scenarioDraft']['initialEntities'][1]['route']={'motionMode':'WALK','endPosition':{'row':1,'col':1},'transition_policy':{'rule':'rule/m9_living_transition','parameters':{'hidden_effects':'reject','hidden_auras':'suspend','launched_source_effects':'retain','resource_timers':'continue'}},'checkpoints':[{'type':'DISAPPEAR'},{'type':'WAIT_FOR_SECONDS','time':.1},{'type':'APPEAR_AT_POS','position':{'row':1,'col':1}}]};s=make(p);s.advance(1);assert s.ctx.route_hidden('target');assert pure(s)==[];s.advance(3);assert not s.ctx.route_hidden('target');assert pure(s)==[s.session.world.resolve('target')];proof(s)
def native_fixture(level,unit,target_col):
    import hashlib
    pin={'01-11':'f641e67cf5cd503948f0d590a04579ba632c06d29ab327140cca551cbc042211','01-12':'4f1d5166ac835cc1996bdc21b25430a92b1d8a233d0d615ca0b98c2f22d5d4b9'}[level];path=ROOT/f'packages/campaign/chapter01_behavior/m24/level_main_{level}.decision.partial.json';assert hashlib.sha256(path.read_bytes()).hexdigest()==pin;p=json.loads(path.read_bytes());p['entities'].append({'id':'unit/peer_target','kind':'entity','tags':['player','ground'],'components':{'attributes':{'base':{'max_hp':2000,'def':10,'mres':0,'block_count':1}},'resources':{'hp':{'initial':2000,'capacity':2000,'role':'health'}},'spatial':{},'deployable':{'base_cost':0,'capacity':1,'terrain':'ground','cooldown_seconds':0},'abilities':[]}});p['scenarioDraft']={'id':'scenario/peer_native/'+unit,'ruleset':'ruleset/ark_standard','map':{'rows':7,'cols':10},'resources':{'lives':{'initial':99999,'capacity':99999}},'roster':[],'objectives':{},'initialEntities':[{'definition':unit,'instanceAlias':'actor','position':{'row':3,'col':3},'route':{'motionMode':0,'startPosition':{'row':3,'col':3},'endPosition':{'row':3,'col':9},'checkpoints':[]}},{'definition':'unit/peer_target','instanceAlias':'target','position':{'row':3,'col':target_col}}]};return p
@pytest.mark.parametrize('level,unit,expected',[('01-11','unit/enemy_1028_mocock',170),('01-12','unit/enemy_1028_mocock_2',240)])
def test_native_mocock_variants_actual_math_packet_and_no_travel(level,unit,expected):
    s=make(native_fixture(level,unit,4));s.advance(31);assert [(e['time'],e['payload']['amount']) for e in events(s,'damage.accepted')]==[(28,expected)];assert s.ctx.get('actor',('spatial','position'))=={'row':3,'col':3};assert s.ctx.resources.current('target','hp')==2000-expected;proof(s)
def test_native_W_two_full_profile_actual9_23_with_model_flight():
    s=make(native_fixture('01-11','unit/chapter01_w',4));s.advance(31);assert [(e['time'],e['payload']['amount']) for e in events(s,'damage.accepted')]==[(15,460),(29,460)];assert s.ctx.get('actor',('spatial','position'))=={'row':3,'col':3};proof(s)
def test_native_rogue_blocking_is_actual_runtime_not_setup():
    s=make(native_fixture('01-12','unit/enemy_1014_rogue',3));s.advance(26);assert s.ctx.spatial.blocked_by('actor')==s.session.world.resolve('target');assert [(e['time'],e['payload']['amount']) for e in events(s,'damage.accepted')]==[(13,165),(24,165)];assert s.ctx.get('actor',('spatial','position'))=={'row':3,'col':3};proof(s)
