"""Exact12 variant/pointer/SP/frame plan audit and explicit source mapping conflicts."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];PLAN=ROOT/'packages/campaign/chapter07_consumption_plan/source.consumption.plan.json';OUT=ROOT/'validation/campaign/chapter07_consumption_plan_v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=json.loads(PLAN.read_bytes());sources=json.loads((ROOT/'packages/campaign/chapter07_sources/native.reference.json').read_bytes());assert len(p['exact12_variants'])==12 and {v['variant_id'] for v in p['exact12_variants']}==set(sources['variants']);conflicts=[];counts={'variants':12,'modes':0,'bound_EnemySkill_components':0,'source_selectors_ranges':0,'inline_buffs':0,'BSON_template_bindings':0}
 for v in p['exact12_variants']:
  src=sources['variants'][v['variant_id']];prefab=sources['prefabs'][src['prefab_key']];assert v['exact_reference']==src['native_reference'] and v['raw_db_resolved']==src['native_enemy']['resolved'] and v['full_raw_component_pointer_closure']==prefab['components'];assert not v['missing_literal_BSON_templates'];counts['modes']+=len(v['source_modes']);counts['source_selectors_ranges']+=len(v['all_source_selectors_and_range_components']);counts['inline_buffs']+=len(v['inline_Buff_records']);counts['BSON_template_bindings']+=len(v['literal_BSON_templates'])
  for s in v['source_skill_SP_cooldown_and_target_components']:
   if s['matching_status']=='exact_name_matches_DB':counts['bound_EnemySkill_components']+=1
   else:
    options=[d for d in v['raw_db_resolved'].get('skills') or [] if d['prefabKey'].casefold()==s['native_gameobject_name'].casefold()];conflicts.append({'variant':v['variant_id'],'native_component_GO':s['native_gameobject_name'],'fixed_DB_candidates_by_case_only':options,'policy':'Native ThrowSpear[Rage] differs exact case from DB throwspear[Rage]. A unique case-only candidate is evidence for explicit replaceable name-binding policy, not an automatic/silent alias or executed consumer.'})
 report={'role':'Source capability decomposition only; actual consumer implementations pending','plan':{'path':str(PLAN),'sha':sha(PLAN)},'fixed_source_freeze':p['fixed_source_freeze'],'source_counts':counts,'source_conflicts':conflicts,'source_input_pins':p['source_inputs'],'task_splits':p['minimum_consumer_task_splits'],'existing_generic_interfaces_are_reuse_candidates_only':True,'possible_new_generic_capabilities_to_prove':[{'name':'Named lifetime/buff event transition listener with ordered CreateBuff/FinishBuff across active mode state','source':'enemy_strength_talent_start_listener/finish_listener and sotisp_trigger/revert BSON','existing_reuse':'Buff event hooks/effects/behavior/owned leases; prove callback/phase semantics before adding core'}, {'name':'Reborn handling ability interval and transient global buff application/source shield state','source':'Patriot RebornTalent(useAbilityToHandle Reborning)/60s source wait/15s invul/_hpRechargeRatio .8500000238418579 and ore blackboards','existing_reuse':'Rebirth + generic skill arbiter + aura/lifecycle effects; new source content coupling required, no demonstrated core deficit yet'}, {'name':'Ore/mines dormant modes/build-stock-trigger/self-retirement and source PURE damage','source':'trap_011_ore/trap_012_mine sourcePPtrs/BSON/stock15','existing_reuse':'Card/deploy stock/resources, tile ownership, cast BuffUID controls, NoSourceDamage; trigger target policy must be source-authored and independently tested'}],'conditions_for_actual_consumer_acceptance':['Exact native stats/selectedmode/OnAttack/cooldown/SP/cost and target masks/source immunity numeric checks','Normal/blocked/multiplecaster/control/death/retainedpayload mode transitions with actualpacket events','Actual ordered disk CP and public fromhead replay with complete event/source guards','Unknown source/formula/native body parameters remain explicit pending, no empty emit/module registration accepted as implementation'],'confirmed_new_core_feature_added':False,'consumer_or_stage_executed':False,'client_verified':False};OUT.mkdir(parents=True,exist_ok=True);dest=OUT/'audit.json';assert not dest.exists();dest.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(dest),'counts':counts,'mapping_conflicts':len(conflicts),'runtime':False}))
if __name__=='__main__':main()
