"""Source-only minimal consumer decomposition for exact12 chapter7 variants."""
import hashlib,json
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'packages/campaign/chapter07_consumption_plan'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 freeze=ROOT/'validation/campaign/chapter07_sources_v2/freeze.json';assert sha(freeze)=='540a8492846277b90c48f97ec4c9717abe3858ab955e25623e2bc6128b1f1478';f=json.loads(freeze.read_bytes());assert f['source_before']==f['source_after'];assert all(sha(Path(p))==h for p,h in f['source_after'].items());ep=ROOT/'packages/campaign/chapter07_sources/native.reference.json';pp=ROOT/'packages/campaign/chapter07_plans/source.plan.json';np=ROOT/'packages/campaign/chapter07_predefines/source.v4.reference.json';e=json.loads(ep.read_bytes());plan=json.loads(pp.read_bytes());npc=json.loads(np.read_bytes());rows=[]
 for vid,v in e['variants'].items():
  prefab=e['prefabs'][v['prefab_key']];component=deepcopy(prefab['components']);selectors=[{'path_id':pid,'class':c['native_class'],'raw':c['raw']} for pid,c in component.items() if 'Selector' in c['native_class'] or 'Range' in c['native_class']];skills=[];buffs=[];templates=set()
  def scan(x,path):
   if isinstance(x,dict):
    if x.get('templateKey'):templates.add(x['templateKey'])
    if x.get('buffKey'):buffs.append({'source_path':path,'raw':deepcopy(x)})
    for k,y in x.items():scan(y,path+'/'+k)
   elif isinstance(x,list):
    for i,y in enumerate(x):scan(y,path+'/'+str(i))
  scan(component,'prefabs/'+v['prefab_key']+'/components')
  for pid,c in component.items():
   if c['native_class']=='EnemySkill':
    go=c['gameobject_path_id'];siblings=[{'path_id':q,'class':r['native_class'],'raw':r['raw']} for q,r in component.items() if r['gameobject_path_id']==go];name=c['gameobject_name'];db=[s for s in v['native_enemy']['resolved'].get('skills') or [] if s['prefabKey']==name];skills.append({'component_path_id':pid,'native_gameobject_name':name,'EnemySkill_raw':c['raw'],'exact_DB_matching_skills':db,'related_components_on_exactGO':siblings,'matching_status':'exact_name_matches_DB' if len(db)==1 else 'source_name_mapping_pending','runtime_model':False})
  modes=[]
  for m in v['modes']:
   modes.append({'mode':m['index'],'raw_mode':m['raw'],'slots':{role:{'source_path_id':n.get('path_id'),'class':n.get('native_class'),'raw':n.get('raw'),'animation_binding':n.get('animation_binding'),'OnAttack_frames':[x['frame'] for x in (n.get('animation_binding') or {}).get('events',[]) if x['name']=='OnAttack'],'runtime_model':False} for role,n in m['nodes'].items()}})
  nativeid=v['native_enemy']['native_id'];classes=sorted({c['native_class'] for c in component.values()});common=['source-bound base stats/level/overrides and silence/immunity fields','mode-index exact selectors/ranges/block status and attack ownership','animation OnAttack count/frame and ASPD timing policy','source Buff blackboard binding and snapshot/lifecycle/CP/public replay']
  potential=['Compiler rule/effect/buff/behavior DSL','typed selection eligibility/projection + dynamic immunity','standard physical/arts pipeline and source attack flags','cast-owned Buff leases and callback-safe lifecycle']
  if any(c in classes for c in ('RangedAttack','MultiMeleeAttack')):potential+=['projectile trajectory/collision/source payload identity and multi-hit timeline']
  if 'GlobalAuraAbility' in classes:potential+=['owned aura membership/detach/rebirth/source loss hooks']
  if 'RebornTalent' in classes:potential+=['same-entity rebirth/generation, cast cancellation and maxHP/source-state reset']
  if skills:potential+=['typed skill arbiter priority/cooldown and source triggering']
  pending=[]
  if len(modes)>1:pending.append('source mode switching conditions and crossmode cooldown/attack timers require literal BSON event graph consumer')
  if buffs:pending.append('all inline listener/CreateBuff/FinishBuff/mode-switch templates and condition/stack/blackboard semantics need source-specific authoring and independent negatives')
  if skills:pending.append('EnemySkill triggering/checkParentActive/family/ignoreSilence/SP0/cooldown/name-bind boundary; no invented natural SP charging for sourceSP0')
  if 'RebornTalent' in classes:pending.append('Patriot maxRespawn1/mode1/_hpRechargeRatio .8500000238418579, sourceBB reborn60 and invincible15, useAbilityToHandle/Reborning and fourOnAttack19/22/25/28 must be coupled; cannot reuse Frost2 constants')
  if 'MultiMeleeAttack' in classes:pending.append('source19/22/25/28 multi packets, target recapture/eligibility/cancellation and loadSourceAttributeWhenAttack per actual raw flags')
  if 'GlobalAuraAbility' in classes:pending.append('GlobalAura target validator/selfOption/removeBuffWhenAbilityDetached/listenReborn/clearDisappear must be parameterized from raw source and tested')
  if not pending:pending.append('No new generic core gap demonstrated: author exact source melee+selector/frame and independently prove mechanics before counting reuse')
  sourceBB=v['native_enemy']['resolved'].get('talentBlackboard');rows.append({'variant_id':vid,'native_id':nativeid,'exact_reference':v['native_reference'],'source_stages':v['stages'],'prefab_key':v['prefab_key'],'prefab_asset_source':prefab['source'],'prefab_root_path_id':v['root_path_id'],'raw_db_resolved':v['native_enemy']['resolved'],'sourceBB':sourceBB,'raw_component_classes':classes,'full_raw_component_pointer_closure':component,'source_modes':modes,'source_skill_SP_cooldown_and_target_components':skills,'all_source_selectors_and_range_components':selectors,'inline_Buff_records':buffs,'literal_BSON_templates':{t:e['bson_templates']['templates'][t] for t in sorted(templates) if t in e['bson_templates']['templates']},'missing_literal_BSON_templates':sorted(templates-set(e['bson_templates']['templates'])),'source_projectile_dependencies':[k for k in e['projectiles'] if k in json.dumps(component)],'minimal_consumer_requirements':common,'generic_interface_reuse_candidates':potential,'reuse_verdict':'Candidate interface reuse only, source tests/descriptor compatibility not yet established','confirmed_new_generic_gap':'None demonstrated by executable counterexample in this source-only plan; source-specific content consumers still missing','mechanics_pending':pending,'runtime_authored':False,'client_verified':False})
 assert len(rows)==12;groups=[{'id':'ordinary_melee_taunt_statmods','variants':[r['variant_id'] for r in rows if r['native_id'] in ('enemy_1077_sotihd','enemy_1078_sotisc','enemy_1081_sotisd','enemy_1083_sotiab','enemy_1083_sotiab_2')],'minimum_author_work':'Exact base+mode0 melee frames/blocked qualifier/silence immunity/taunt or literal source stat listener Buffs. Independent HP/ATK/DEF/frame/damage/root-only scopes.'},
 {'id':'ranged_sotisp_mortar','variants':[r['variant_id'] for r in rows if r['native_id'] in ('enemy_1079_sotisp','enemy_1082_soticn')],'minimum_author_work':'Source projectiles and exact selector/PPtr, frames21/16, passive switch/mod listeners and both sotisp modes. Preserve reference min/free/camo/block qualifications, no death flags borrowed.'},
 {'id':'multi_mode_demon_casters','variants':[r['variant_id'] for r in rows if r['native_id'] in ('enemy_1084_sotidm','enemy_1085_sotiwz','enemy_1085_sotiwz_2')],'minimum_author_work':'Actual2modes/listener conditions/Immo trigger and skill source raw cooldown5/SP0, per-state selector/applicability; NeverTrigger ordinary path must remain inactive, not made auto.'},
 {'id':'source_global_support_aura','variants':[r['variant_id'] for r in rows if r['native_id']=='enemy_1080_sotidp'],'minimum_author_work':'Exact globalvalidator/source BB atk+.1/DEF+100 aura and detach/clear/rebirth handling, selfOption policy raw.'},
 {'id':'Patriot_complete_source_consumer','variants':[r['variant_id'] for r in rows if r['native_id']=='enemy_1506_patrt'],'minimum_author_work':'Source2modes/four melee packets/source throw spear/Immo/Rage/reborn60+15 invul/_hpRechargeRatio/rawshield/rally aura/ore interaction/wave release. No imported Frost timing or arbitrary shield assumptions.'},
 {'id':'ore_mine_predefines_and_native_controls','minimum_author_work':'Frozen20250327 mixed-version ore/mine realentities/stock15/cost/selectedskills/TrapMode/NoSourcePure damage and sourceBSON; 7-17#1/#2/7-18aliasnull; Story/preview/display/nativeroute full join after consumers.','source_package':str(np),'source_sha':sha(np)}]
 report={'schema':'ark-sim/chapter07-source-consumption-plan/v1','fixed_source_freeze':{'path':str(freeze),'sha':sha(freeze)},'source_inputs':{str(p):sha(p) for p in (ep,pp,np)},'target_native_display':plan['selected_display_ids'],'exact12_variants':rows,'minimum_consumer_task_splits':groups,'known_interface_source_snapshot':{'path':str(ROOT/'ark_sim/domains/providers.py'),'sha':sha(ROOT/'ark_sim/domains/providers.py'),'purpose':'Read-only current capability inventory, not source model acceptance'},'source_version_conflicts':'Fixed56aee DB/reference docs/local20260831 assets and official20250327 ore/mine entities separately locked; no assumed alignment','source_method_body_policy':'Missing native bodies remain pending; explicit reference mechanics can be authored and probed instead of empty emits/dummy registration','runnable_stage_created':False,'consumer_runtime_created':False,'confirmed_new_core_capabilities_implemented':False,'whole_stage_executed':False,'client_verified':False};OUT.mkdir(parents=True,exist_ok=True);dest=OUT/'source.consumption.plan.json';assert not dest.exists();dest.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(dest),'variants':len(rows),'task_splits':len(groups),'runtime':False}))
if __name__=='__main__':main()
