"""Explicit threshold/math interface; source conflict is never silently resolved."""
import json,hashlib,argparse
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'packages/campaign/chapter02_behavior/skulsr.conflict.reference.json';OUT=ROOT/'packages/campaign/chapter02_behavior/m28'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
CORE='cb0e7a97a2621aaf4b14dc942181686906733acbcc61f6a5a23ebae9448e997b'
def build(threshold_policy,same_frame_policy,require_native=False):
 if require_native:raise ValueError('native threshold/LoadData/family/physics bodies unresolved')
 if threshold_policy not in ('serialized','DB'):raise ValueError('explicit threshold_policy serialized or DB required')
 if same_frame_policy!='damage_then_attachment':raise ValueError('explicit supported same_frame_policy damage_then_attachment required; native order unknown')
 d=json.loads(SOURCE.read_bytes());r=d['actual_variant'];a=r['native_enemy']['resolved']['attributes'];bb={x['key']:x['value'] for x in r['native_enemy']['resolved']['talentBlackboard']}
 ratio=d['threshold_resolution']['serialized_max'] if threshold_policy=='serialized' else d['threshold_resolution']['DB_atkup_hp_ratio']
 parent=ROOT/'packages/campaign/chapter02_behavior/projectiles.partial.json';assert sha(parent)=='d1b8929579a01d2a3e1cc246eccb5f1a7f05fadd9a2d627b972c27874fca979b';library=json.loads(parent.read_bytes())
 projectile=d['actual_projectile'];simple=next(c for c in projectile['components'].values() if c['native_class']=='SimpleProjectile');motion=next(c for c in projectile['components'].values() if c['native_class']=='ParacurveMovement');sp=simple['raw'];mp=motion['raw'];assert sp['_hitNumType']==2 and sp['_maxHitNum']==1 and sp['_lifeTime']==10 and mp['_speed']==5
 checker=d['actual_checker'];assert d['threshold_resolution']['status']=='unresolved'
 modes=r['modes'];assert len(modes)==2
 p={'schemaVersion':2,'manifest':{'id':'chapter02/skulsr/'+threshold_policy,'requires':['preset/ark_standard'],'metadata':{'status':'partial_manual_state_interface','required_runtime':CORE,'builder_sha256':sha(__file__),'conflict_source_sha256':sha(SOURCE),'parent_library_sha256':sha(parent),'threshold_policy':threshold_policy,'threshold_ratio':ratio,'same_frame_policy':same_frame_policy,'source_conflict_unresolved':True,'source_locks':d['source_locks'],'profiles':{'HP':'event reaction; 0<hp<=source_base_max_hp*explicit ratio; heal above restores','sampling':'source/target at_hit','restartFSM':'cancel pending automatic attacks/reset clock; manual probe/in-flight projectiles retained; native dispatch unknown','dispatch':'manual public ATTACK or COMBAT, explicit mode guard, not native enemy AI','family':'role _attack=>ATTACK1/_combat=>COMBAT2 declared options adapter, native wrapper assignment pending','attachment':'ATTACK only, successful damage then DEF buff, native ordering unknown','collision':'trace-only declared math, source 3x3 box/multi-target physics NOT consumed'},'model_gaps':['native auto dispatch/FSM not reconstructed','source BoxCollider3x3 at-target overlap adapter not authored','source effective_max_hp threshold driver vs static source max_hp unknown'],'source_gap':['serialized_.4_vs_DB_.5_LoadData unresolved'],'client_pending':['native family options/attachment timing','animation speed/native callbacks','source version/physical axes correspondence'],'actual_game_correct':False,'formal_approved':False}},'entities':[],'abilities':[],'selectors':[],'buffs':[],'projectiles':[],'rules':[deepcopy(x) for x in library['rules'] if x['id'] in ('rule/chapter02/qualification','rule/projectile/trajectory','rule/projectile/collision')]}
 defaults=deepcopy(library['selectors'][0]['eligibility']['parameters']['defaults'])
 aid=[]
 for mode in modes:
  index=mode['index'];attack=mode['nodes']['_attack'];combat=mode['nodes']['_combat'];assert attack['native_class']=='RangedAttack' and combat['native_class']=='MeleeAttack'
  signals=[x for x in attack['animation_binding']['events'] if x['name']=='OnAttack'];melee=[x for x in combat['animation_binding']['events'] if x['name']=='OnAttack'];assert [x['frame'] for x in signals]==[14,17] and [x['frame'] for x in melee]==[53]
  raw=attack['raw'];assert raw['_waitForAttackEvent']==1 and raw['_atkScale']==0.25999999046325684 and raw['_damageType']==1
  trigger=mode['nodes']['_attackTrigger']['raw'];go=trigger['m_GameObject']['m_PathID'];sel=[x for x in r['components'].values() if x['native_class']=='AdvancedSelector' and x['raw']['m_GameObject']['m_PathID']==go];assert len(sel)==1
  prefab_geoms=r.get('prefab_key');native=json.loads((ROOT/'packages/campaign/chapter02_sources/native.reference.json').read_bytes());geoms=native['prefabs'][prefab_geoms]['geometry_sources'];circles=[g for g in geoms if g['gameobject_path_id']==go and g['unity_type']=='CircleCollider2D'];assert len(circles)==1
  sid=f'selector/skulsr_attack_{index}';p['selectors'].append({'id':sid,'kind':'selector','region':{'type':'radius','radius':circles[0]['raw']['m_Radius']},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{'rule':'rule/chapter02/qualification','parameters':{'source_configuration':sel[0]['raw'],'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults}},'metadata':{'native_mode_pointer':mode['mode_path_id'],'native_selector':sel[0],'native_collider':circles[0]}})
  csid=f'selector/skulsr_combat_{index}';p['selectors'].append({'id':csid,'kind':'selector','region':{'type':'all','blocked_only':True},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1})
  ranged=f'ability/skulsr_attack_{index}';close=f'ability/skulsr_combat_{index}';aid += [ranged,close]
  p['abilities'] += [{'id':ranged,'kind':'ability','selector':sid,'activation':{'mode':'manual','condition':f'inputs.resources.mode.current == {index}','parameters':{'counts_as_attack':True,'requires_targets':True}},'timeline':[{'at_seconds':e['seconds'],'effect':{'op':'damage','damage_type':'physical','scale':raw['_atkScale'],'projectile_definition':'projectile/skulsr','read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'on_success':[{'op':'apply_buff','buff':'buff/chapter02/skulsr_defdown'}]}} for e in signals],'metadata':{'native_family_mask':1,'role_family_profile':'ATTACK','native':attack}},
  {'id':close,'kind':'ability','selector':csid,'activation':{'mode':'manual','condition':f'inputs.resources.mode.current == {index}','parameters':{'requires_targets':True}},'timeline':[{'at_seconds':melee[0]['seconds'],'effect':{'op':'damage','damage_type':'physical','scale':combat['raw']['_atkScale'],'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}}],'metadata':{'role_family_profile':'COMBAT','attachment_excluded_by_declared_family_mask':True,'native':combat}}]
 p['buffs']=[deepcopy(x) for x in library['buffs'] if x['id']=='buff/chapter02/skulsr_defdown']+[{'id':'buff/skulsr_mode1','kind':'buff','modifiers':[{'attribute':'atk','layer':'direct_ratio','value':bb['atkup.atk']}],'on_remove':[{'op':'modify_resource','target':'source','resource':'mode','value':0}]}]
 hp=a['maxHp'];guard="inputs.payload.target == inputs.source.id and inputs.payload.resource == 'hp'";params={'hp_threshold':hp*ratio,'cancel_pending_attacks':True,'reset_attack_clock':True}
 p['abilities'] += [{'id':'ability/skulsr_enter','kind':'ability','activation':{'mode':'passive','event':'resource.changed','condition':guard+' and 0 < inputs.resources.hp.current <= params.hp_threshold and inputs.resources.mode.current == 0','parameters':params,'on_start':[{'op':'modify_resource','target':'source','resource':'mode','value':1},{'op':'apply_buff','target':'source','buff':'buff/skulsr_mode1'}]},'parameters':{'blocks_attacks':False},'timeline':[]}, {'id':'ability/skulsr_leave','kind':'ability','activation':{'mode':'passive','event':'resource.changed','condition':guard+' and inputs.resources.hp.current > params.hp_threshold and inputs.resources.mode.current == 1','parameters':params,'on_start':[{'op':'remove_buff','target':'source','buff':'buff/skulsr_mode1'}]},'parameters':{'blocks_attacks':False},'timeline':[]}]
 p['projectiles']=[{'id':'projectile/skulsr','kind':'projectile','motion':{'rule':'rule/projectile/trajectory','parameters':{'mode':'homing','speed':mp['_speed'],'raise_height':mp['_raiseHeight'],'height_threshold':mp['_noRaiseHeightThreshold']}},'collision':{'rule':'rule/projectile/collision','parameters':{'enabled':True,'radius':0}},'lifetime_seconds':10,'max_hits':None,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'cancel','target_hidden':'cancel','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'on_invalid':[],'metadata':{'raw_hit_type':2,'LifeType':'INFINITY','inactive_maxHitNum':1,'native_simple':simple,'native_movement':motion,'native_hit_geometry':projectile['geometry_sources'],'model_gap':'trace-only placeholder policy, source3x3 physical overlap unconsumed; not full projectile'}}]
 p['entities']=[{'id':'unit/skulsr_partial','kind':'entity','tags':['enemy','ground'],'metadata':{'native_id':'enemy_1500_skulsr','native_category':1},'components':{'attributes':{'base':{'max_hp':hp,'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'move_speed':a['moveSpeed'],'block_cost':1}},'resources':{'hp':{'initial':hp,'capacity':hp,'role':'health'},'mode':{'initial':0,'capacity':1}},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle'},'selection_state':{**deepcopy(defaults),'side':1},'abilities':aid+['ability/skulsr_enter','ability/skulsr_leave']}}]
 return p
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--threshold-policy',required=True,choices=['serialized','DB']);ap.add_argument('--same-frame-policy',required=True,choices=['damage_then_attachment']);ap.add_argument('--check',action='store_true');a=ap.parse_args();p=build(a.threshold_policy,a.same_frame_policy);OUT.mkdir(parents=True,exist_ok=True);out=OUT/f'skulsr.{a.threshold_policy}.partial.json';b=(json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode()
 if a.check:assert out.read_bytes()==b
 else:out.write_bytes(b)
 print(json.dumps({'passed':True,'check':a.check,'sha256':sha(out),'policy':a.threshold_policy,'native_correct':False}))
