"""Separate source producer data; M49 runtime/lurker/sensor bytes stay frozen."""
import json,hashlib,argparse
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'packages/campaign/chapter03_sources/native.reference.json';PIN='d6a1d5294e1419d6ee41022efa1ef93a0ad44b6effb80c4bdfcf7fc3e7cd1e35';BASE=ROOT/'packages/campaign/chapter03_visibility/lurker_sensor.model.json';BASEPIN='939ab55dea20624639a37d8a63c38cc015c2b8d9c214c0cdf6a3380f22821fe1';OUT=ROOT/'packages/campaign/chapter03_visibility/three_hidden_sensor.model.json';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def build():
 assert sha(SOURCE)==PIN and sha(BASE)==BASEPIN;d=json.loads(SOURCE.read_bytes());p=json.loads(BASE.read_bytes());locks=p['manifest']['metadata']['source_locks']
 for name,pin in d['source_locks'].items():assert sha(ROOT.parent/name)==pin;locks[name]=pin
 library=ROOT/'packages/campaign/chapter02_behavior/projectiles.partial.json';assert sha(library)=='d1b8929579a01d2a3e1cc246eccb5f1a7f05fadd9a2d627b972c27874fca979b';l=json.loads(library.read_bytes());p['rules'] += [deepcopy(r) for r in l['rules'] if r['id'] in ['rule/chapter02/qualification','rule/projectile/trajectory','rule/projectile/collision']];p['projectiles']=[]
 p['rules'].append({'id':'rule/visibility/ranged_decision','kind':'rule','contract':'behavior.decision','implementation':{'type':'expression','expression':"{'move':inputs.controls.move and inputs.blocked_by == None and inputs.cast_groups.normal == [] and inputs.eligible_ids.ranged == [],'attack':inputs.controls.attack and inputs.controls.abilities and inputs.cast_groups.normal == [] and ((inputs.blocked_by in inputs.eligible_ids.combat) if inputs.blocked_by != None else inputs.eligible_ids.ranged != [])}"}})
 state=deepcopy(p['entities'][0]['components']['selection_state']);bindings=[]
 for vid,v in d['variants'].items():
  if not any(x in vid for x in ['enemy_1019_jshoot@','enemy_1023_jmage@']):continue
  name=v['prefab_key'];prefab=d['prefabs'][name];comps=prefab['components'];toggle=next(c for c in comps.values() if c['native_class']=='ToggleablePassiveBuffAbility');checker=comps[str(toggle['raw']['_checker']['m_PathID'])];cr=checker['raw'];assert (cr['_isInitToggled'],cr['_disableWhenAttack'],cr['_disableWhenBlocked'],cr['_restoreDelay'])==(1,0,1,3)
  assert toggle['raw']['_buffs'][0]['attributes']['abnormalFlags']==[9];mover=next(c['raw'] for c in comps.values() if c['native_class']=='MoveController');root=next(c['raw'] for c in comps.values() if c['native_class']=='Enemy');assert root['_delayToBorn']==0
  a=v['native_enemy']['resolved']['attributes'];assert a['hpRecoveryPerSec']==0 and a['spRecoveryPerSec']==0 and a['stunImmune'] is False
  mode=v['modes'][0];attack=mode['nodes']['_attack'];combat=mode['nodes']['_combat'];assert attack['native_class']=='RangedAttack' and combat['native_class']=='MeleeAttack' and len(v['modes'])==1
  frame=16 if name=='enemy_1019_jshoot' else 19;assert [e['frame'] for e in attack['animation_binding']['events'] if e['name']=='OnAttack']==[frame];assert [e['frame'] for e in combat['animation_binding']['events'] if e['name']=='OnAttack']==[frame];assert attack['raw']['_atkScale']==combat['raw']['_atkScale']==1
  key=attack['raw']['_projectileKey'];projectile=d['projectiles'][key];simple=next(c for c in projectile['components'].values() if c['native_class']=='SimpleProjectile');movement=next(c for c in projectile['components'].values() if c['native_class']=='AdvancedMovement');assert movement['raw']['_speed']==10 and simple['raw']['_hitNumType']==1 and simple['raw']['_maxHitNum']==1
  suffix=name+'/'+vid.rsplit('/',1)[1];uid='unit/chapter03/'+suffix;controller='buff/visibility/controller/'+suffix;sid='selector/visibility/ranged/'+suffix;csid='selector/visibility/combat/'+suffix;aid='ability/visibility/ranged/'+suffix;caid='ability/visibility/combat/'+suffix;bid='behavior/visibility/'+suffix;pid='projectile/visibility/'+suffix
  p['buffs'].append({'id':controller,'kind':'buff','toggle':{'rule':'rule/visibility/held','buff':'buff/lurker/invisible','initial_enabled':True,'restore_delay_seconds':3,'events':[]},'metadata':{'source_checker':checker,'source_toggle':toggle,'source_policy':'disableWhenAttack0: firing does not reveal; only blocked hold/release3 seconds'}})
  trigger=mode['nodes']['_attackTrigger']['raw'];go=trigger['m_GameObject']['m_PathID'];rawsel=next(c['raw'] for c in comps.values() if c['native_class']=='AdvancedSelector' and c['raw']['m_GameObject']['m_PathID']==go)
  defaults=deepcopy(state);defaults['side']=0
  p['selectors'] += [{'id':sid,'kind':'selector','region':{'type':'radius','radius':v['native_enemy']['resolved']['rangeRadius']},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{'rule':'rule/chapter02/qualification','parameters':{'source_configuration':rawsel,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults}}},{'id':csid,'kind':'selector','region':{'type':'all','blocked_only':True},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1}]
  cond="('blocked_by' in inputs.source.components.runtime and inputs.source.components.runtime.blocked_by != None)";damage='physical' if attack['raw']['_damageType']==1 else 'arts';assert combat['raw']['_damageType']==attack['raw']['_damageType']
  p['abilities'] += [{'id':aid,'kind':'ability','selector':sid,'activation':{'mode':'automatic_attack','condition':'not '+cond,'parameters':{'auto_only':True}},'timeline':[{'at_seconds':frame/30,'effect':{'op':'damage','damage_type':damage,'scale':1,'projectile_definition':pid,'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}}],'metadata':{'source_attack':attack}},{'id':caid,'kind':'ability','selector':csid,'activation':{'mode':'automatic_attack','condition':cond,'parameters':{'auto_only':True}},'timeline':[{'at_seconds':frame/30,'effect':{'op':'damage','damage_type':damage,'scale':1,'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}}],'metadata':{'source_combat':combat}}]
  p['projectiles'].append({'id':pid,'kind':'projectile','motion':{'rule':'rule/projectile/trajectory','parameters':{'mode':'homing','speed':10}},'collision':{'rule':'rule/projectile/collision','parameters':{'enabled':True,'radius':0}},'lifetime_seconds':simple['raw']['_lifeTime'],'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'cancel','target_hidden':'cancel','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'on_invalid':[],'metadata':{'source_simple':simple,'source_movement':movement}})
  p['behaviors'].append({'id':bid,'kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/visibility/ranged_decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'ranged','selector':sid},{'key':'combat','selector':csid}],'cast_groups':[{'key':'normal','abilities':[aid,caid]}]}]}})
  p['entities'].append({'id':uid,'kind':'entity','tags':['enemy','ground'],'rules':{'targeting.availability':'rule/visibility/available'},'metadata':{'native_variant':vid,'native_reference':v['native_reference'],'native_motion':'WALK'},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'block_cost':root['_blockVolume'],'mass_level':a['massLevel']}},'resources':{'hp':{'initial':a['maxHp'],'capacity':a['maxHp'],'role':'health'}},'spatial':{'motion_mode':0,'steering':{'rule':'rule/visibility/steering','parameters':{'response_factor':mover['_steeringFactor'],'max_acceleration':mover['_maxSteeringForce'],'arrival_radius':.05}}},'selection_state':deepcopy(state),'buffs':{'initial':[controller]},'abilities':[aid,caid],'behavior':{'machine':bid},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':v['native_enemy']['resolved']['lifePointReduce']}}})
  bindings.append({'variant_id':vid,'native_reference':v['native_reference'],'native_motion':v['native_enemy']['resolved']['motion'],'unit_definition':uid,'source_checker':checker,'source_attack':attack,'source_combat':combat,'source_attributes':a})
 assert len(bindings)==2;p['manifest']['id']+='/three_hidden';p['manifest']['metadata'].update(hidden_ranged_builder_sha256=sha(__file__),hidden_ranged_source_sha256=PIN,parent_visibility_sha256=BASEPIN,hidden_ranged_bindings=bindings);p['manifest']['metadata']['source_locks'].update({str(SOURCE.relative_to(ROOT.parent)):PIN,str(BASE.relative_to(ROOT.parent)):BASEPIN,str(library.relative_to(ROOT.parent)):sha(library)})
 return p
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();p=build();raw=(json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode();OUT.parent.mkdir(parents=True,exist_ok=True)
 if a.check:assert OUT.read_bytes()==raw
 else:OUT.write_bytes(raw)
 print(json.dumps({'passed':True,'sha256':sha(OUT),'entities':len(p['entities'])}))
