"""Source-bound Mortar with a declared replaceable landing/qualification profile."""
import argparse,json,hashlib
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'packages/campaign/chapter03_sources/native.reference.json';OUT=ROOT/'packages/campaign/chapter03_models/mortar.reference.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 if sha(SOURCE)!='d6a1d5294e1419d6ee41022efa1ef93a0ad44b6effb80c4bdfcf7fc3e7cd1e35':raise ValueError('source drift')
 s=json.loads(SOURCE.read_bytes());v=next(v for v in s['variants'].values() if v['native_enemy']['native_id']=='enemy_1024_mortar');a=v['native_enemy']['resolved']['attributes'];prefab=s['prefabs'][v['prefab_key']];components=prefab['components'];mode=v['modes'][0];attack=mode['nodes']['_attack']['raw'];primary=next(c['raw'] for c in components.values() if c['native_class']=='AdvancedSelector')
 projectile=s['projectiles']['projectile_mortar'];pc=projectile['components'];simple=next(c['raw'] for c in pc.values() if c['native_class']=='SimpleProjectile');motion=next(c['raw'] for c in pc.values() if c['native_class']=='ParacurveMovement');hit=next(c['raw'] for c in pc.values() if c['native_class']=='HitBehaviour')
 assert mode['raw']['_combat']==mode['raw']['_attack'] and attack['_selectTargetSource']==1 and attack['_damageType']==1 and attack['_atkScale']==1
 assert (a['maxHp'],a['atk'],a['baseAttackTime'],v['native_enemy']['resolved']['rangeRadius'])==(3300,400,4.5,7)
 assert (simple['_hitNumType'],simple['_lifeTime'],motion['_speed'],motion['_raiseHeight'],hit['_targetOptions']['targetMotion'],hit['_targetOptions']['targetCategory'])==(2,10,4,1.5,3,1)
 events=s['animations']['enemy_1024_mortar']['parsed']['animations'][attack['_animKey']]['events'];assert [(x['name'],x['frame']) for x in events]==[('OnAttack',16)] and all(x['exact_authored_frame'] for x in events)
 assert hit['_targetOptions']['enableAdvancedOptions']==1 and hit['_targetOptions']['ignoreTargetSide']==0 and hit['_targetOptions']['containSomeAbnormalFlags']==0 and hit['_onlyCheckHitWhenReachTarget']==1 and hit['_goThroughWall']==1 and hit['_onlyTraceTarget']==0 and hit['_exceptTraceTarget']==0
 defaults={'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False}
 def qualification(config):
  c=deepcopy(primary);c.update(config)
  return {'rule':'rule/ch3/mortar/eligibility','parameters':{'source_configuration':c,'defaults':deepcopy(defaults),'side_policy':'relative_ally_enemy','neutral_policy':'reject'}}
 hitcfg={'_'+k:value for k,value in hit['_targetOptions'].items()};hitcfg['_forceIgnoreCamouflage']=hit['_ignoreCamouflage']
 base={'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':1}
 entity={'id':'unit/ch3/mortar','kind':'entity','tags':['enemy'],'components':{'spatial':{'motion_mode':0},'selection_state':{**defaults,'side':1},'attributes':{'base':base},'resources':{'hp':{'initial':3300,'capacity_attribute':'max_hp','role':'health'}},'abilities':['ability/ch3/mortar/attack'],'lifecycle':{'leak_loss':v['native_enemy']['resolved']['lifePointReduce']}}}
 area={'op':'area','center':'target','projectile_definition':'projectile/ch3/mortar','membership_rule':'rule/ch3/mortar/area','effects':[{'op':'damage','damage_type':'physical','scale':attack['_atkScale'],'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}]}
 return {'schemaVersion':2,'manifest':{'id':'package/chapter03/mortar/reference','requires':['preset/ark_standard'],'metadata':{'source_locks':{str(SOURCE.relative_to(ROOT)):sha(SOURCE)},'builder_sha256':sha(Path(__file__)),'native_variant':v['variant_id'],'raw_source':{'mode':mode['raw'],'attack':attack,'primary_selector':primary,'simple':simple,'motion':motion,'hit':hit,'geometry':projectile['geometry_sources']},'reference':{'url':'https://prts.wiki/w/%E7%82%AE%E6%89%8B','read_date':'2026-10-03','rules':['ground primary, range7','target cell plus8 neighbors','physical normal and physical splash; flying splash allowed; collision ignores camouflage']},'profiles':{'dispatch':'one source OnAttack frame16 per ordinary attack, interval4.5; FROM_OWNER1 selector, no forced blocker override','anchor':'replaceable planar homing/current available captured target position; invalid/hidden freezes last observed point; not claimed native parent body','landing':'single blast at reached/expiry point; projected9 typed sourceHit qualification; primary included if currently qualified','sampling':'live source/target attributes at_hit','invalid':'source retain, target retain last point, hidden retain last point; target itself excluded if unavailable','infinity':'source INFINITY hit quota null; single blast finish_on_reach; expiry fallback once'},'feedback_pending':['native Paracurve/collider/alwaysHit callbacks and ordering','FROM_OWNER selection method body','source target-free flags interpretation and neutral model','INVISIBLE9 availability requires M49 merge; forceIgnoreCamouflage17 does not grant9 immunity'],'client_verified':False,'formal_approved':False}},'entities':[entity],
 'selectors':[{'id':'selector/ch3/mortar','kind':'selector','region':{'type':'radius','radius':7},'filters':[{'tag':'player'},{'state':'alive'}],'ordering':'distance','limit':1,'eligibility':qualification({})}],
 'rules':[{'id':'rule/ch3/mortar/eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':'rule/ch3/mortar/area','kind':'rule','contract':'area.members','dependencies':['rule/ch3/mortar/eligibility'],'parameters':{'offsets':[[r,c] for r in (-1,0,1) for c in (-1,0,1)],'eligibility':qualification(hitcfg)},'implementation':{'type':'provider','provider':'ark.area.qualified_cell_offsets'}},{'id':'rule/ch3/mortar/motion','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'model.projectile.trajectory'}},{'id':'rule/ch3/mortar/collision','kind':'rule','contract':'projectile.collision','implementation':{'type':'provider','provider':'model.projectile.collision'}}],
 'abilities':[{'id':'ability/ch3/mortar/attack','kind':'ability','selector':'selector/ch3/mortar','activation':{'mode':'automatic_attack','parameters':{'auto_only':True,'requires_targets':True,'counts_as_attack':True}},'timeline':[{'at_seconds':16/30,'effect':area}]}],
 'projectiles':[{'id':'projectile/ch3/mortar','kind':'projectile','lifetime_seconds':simple['_lifeTime'],'max_hits':None,'attach_at_launch':False,'on_invalid':[],'can_hit_same_target':False,'stop_after_max':bool(simple['_stopAfterMaxHit']),'stop_after_first':bool(simple['_stopAfterFirstHit']),'motion':{'rule':'rule/ch3/mortar/motion','parameters':{'mode':'homing','speed':motion['_speed'],'raise_height':motion['_raiseHeight'],'height_threshold':motion['_noRaiseHeightThreshold']}},'collision':{'rule':'rule/ch3/mortar/collision','parameters':{'enabled':False}},'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True}}]}
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');args=ap.parse_args();raw=(json.dumps(build(),ensure_ascii=False,indent=2)+'\n').encode('utf8');OUT.parent.mkdir(exist_ok=True)
 if args.check:
  if OUT.read_bytes()!=raw:raise ValueError('stale Mortar')
 else:OUT.write_bytes(raw)
 print(json.dumps({'sha256':sha(OUT)}))
