import json,hashlib,argparse
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'packages/campaign/chapter03_visibility/source.reference.json';OUT=ROOT/'packages/campaign/chapter03_visibility/lurker_sensor.model.json';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def build():
 d=json.loads(SOURCE.read_bytes())
 for name,pin in d['source_locks'].items():assert sha(ROOT.parent/name)==pin
 p={'schemaVersion':2,'manifest':{'id':'package/chapter03/visibility','requires':['preset/ark_standard'],'metadata':{'source_locks':d['source_locks'],'visibility_source_sha256':sha(SOURCE),'builder_sha256':sha(__file__),'status':'declared visibility/skill partial device dependency','model_delivery_ready':False,'client_verified':False,'formal_approved':False,'feedback_pending':d['feedback_pending'],'model_gaps':['Sensor terrain/card/predefine integration is separate; retain original stage dependencies, do not delete Sensor/crate'] }},'entities':[],'buffs':[],'selectors':[],'abilities':[],'rules':[],'behaviors':[]}
 flags9=d['lurker']['toggle']['raw']['_buffs'][0]['attributes']['abnormalFlags'];assert flags9==[9]
 row=next(iter(d['lurker']['resolved_variants'].values()));a=row['native_enemy']['resolved']['attributes'];frames=d['lurker']['attack_binding']['events'];assert [x['frame'] for x in frames if x['name']=='OnAttack']==[12]
 standard={'side':1,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False}
 p['rules']=[{'id':'rule/visibility/held','kind':'rule','contract':'passive.toggle','implementation':{'type':'expression','expression':'inputs.blocked_by != None and inputs.blocker_active'}}, {'id':'rule/visibility/available','kind':'rule','contract':'targeting.availability','parameters':{'hidden_flag':9},'implementation':{'type':'expression','expression':"params.hidden_flag not in inputs.selection_states.candidate.abnormal_flags or inputs.selection_states.source.side == inputs.selection_states.candidate.side or ('parameters' in inputs.selector and 'visibility_bypass_flags' in inputs.selector.parameters and params.hidden_flag in inputs.selector.parameters.visibility_bypass_flags) or ('parameters' in inputs.effect and 'visibility_bypass_flags' in inputs.effect.parameters and params.hidden_flag in inputs.effect.parameters.visibility_bypass_flags)"}}, {'id':'rule/visibility/steering','kind':'rule','contract':'movement.steering','implementation':{'type':'provider','provider':'ark.movement.steering_velocity'}},{'id':'rule/sensor/invulnerable','kind':'rule','contract':'damage.pipeline','implementation':{'type':'graph','nodes':[{'id':'result','expression':"{'accepted':False,'amount':0,'allocations':[],'events':[]}"}],'output':'nodes.result'}}]
 p['buffs']=[{'id':'buff/lurker/controller','kind':'buff','toggle':{'rule':'rule/visibility/held','buff':'buff/lurker/invisible','initial_enabled':True,'restore_delay_seconds':3,'events':[{'event':'attack.accepted','owner_role':'source'}]},'metadata':{'source_checker':d['lurker']['checker'],'source_toggle':d['lurker']['toggle'],'pulse_profile':'first accepted attack packet, selectable event contract; native event dispatch body not recovered'}},{'id':'buff/lurker/invisible','kind':'buff','stacking':{'mode':'independent'},'selection_flags':{'abnormal_flags':[9]}},{'id':'buff/sensor/invulnerable','kind':'buff','selection_flags':{'abnormal_flags':[5]},'damage_hooks':[{'phase':'after','rule':'rule/sensor/invulnerable'}],'metadata':{'source_self_passive':d['sensor']['self_passive']}},{'id':'buff/sensor/reveal_member','kind':'buff','stacking':{'mode':'independent'},'selection_flags':{'abnormal_immunes':[9]}},{'id':'buff/sensor/reveal','kind':'buff','duration_seconds':20,'aura':{'selector':'selector/sensor/reveal','buff':'buff/sensor/reveal_member'},'metadata':{'source_aura':d['sensor']['skill_aura'],'source_target_validator':d['sensor']['target_validator'],'explicit_bypass':'9 only from actual abnormalImmunes[9] and ignoreTargetFree1; not all hidden flags'}}]
 p['selectors']=[{'id':'selector/lurker/combat','kind':'selector','region':{'type':'all','blocked_only':True},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1}]
 range_path=next(ROOT.parent/name for name in d['source_locks'] if 'range_table' in name);ranges=json.loads(range_path.read_bytes());r=ranges['x-3'];cells=r.get('grids',r.get('cells'));assert len(cells)==25
 offsets=[[x['row'],x['col']] for x in cells];p['selectors'].append({'id':'selector/sensor/reveal','kind':'selector','region':{'type':'grid_offsets','offsets':offsets,'rotate_with_facing':True},'filters':[{'tag':'enemy'},{'state':'alive'}],'parameters':{'visibility_bypass_flags':[9]},'limit':None,'metadata':{'source_range_id':'x-3','source_exact_grids':cells}})
 p['abilities']=[{'id':'ability/lurker/normal','kind':'ability','selector':'selector/lurker/combat','activation':{'mode':'automatic_attack','parameters':{'auto_only':True}},'timeline':[{'at_seconds':12/30,'effect':{'op':'damage','damage_type':'physical','scale':1}}],'metadata':{'source_attack':d['lurker']['attack'],'source_frame':frames}}, {'id':'ability/sensor/reveal','kind':'ability','activation':{'mode':'manual','costs':[{'resource':'sp','amount':15}],'duration_seconds':20,'on_start':[{'op':'apply_buff','target':'source','buff':'buff/sensor/reveal'}]},'timeline':[],'metadata':{'source_skill':d['sensor']['table']['skill']}}]
 p['behaviors']=[{'id':'behavior/lurker','kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/ark_behavior_decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'normal','selector':'selector/lurker/combat'}],'cast_groups':[{'key':'normal','abilities':['ability/lurker/normal']}],'parameters':{'target_key':'normal','blocked_target':True,'stop_cast_groups':['normal']}}]}}]
 p['entities']=[{'id':'unit/chapter03/enemy_1009_lurker/477247d885e1ebfe','kind':'entity','tags':['enemy','ground'],'rules':{'targeting.availability':'rule/visibility/available'},'metadata':{'native_variant':row['variant_id'],'native_motion':'WALK'},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'block_cost':1,'mass_level':a['massLevel']}},'resources':{'hp':{'initial':a['maxHp'],'capacity':a['maxHp'],'role':'health'}},'spatial':{'motion_mode':0,'steering':{'rule':'rule/visibility/steering','parameters':{'response_factor':8,'max_acceleration':10,'arrival_radius':.05}}},'selection_state':standard,'buffs':{'initial':['buff/lurker/controller']},'abilities':['ability/lurker/normal'],'behavior':{'machine':'behavior/lurker'},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':1}}}]
 base=d['sensor']['table']['character']['phases'][0]['attributesKeyFrames'][0]['data'];assert (base['maxHp'],base['atk'],base['cost'],base['respawnTime'])==(100,0,5,5)
 p['entities'].append({'id':'unit/chapter03/trap_005_sensor','kind':'entity','tags':['player','device'],'metadata':{'native_id':'trap_005_sensor','native_category':2,'source_version_gap':'official20250327 bundle versus fixed20260929 table'},'components':{'attributes':{'base':{'max_hp':100,'atk':0,'def':0,'mres':0,'block_count':base['blockCnt'],'taunt_level':base['tauntLevel']}},'resources':{'hp':{'initial':100,'capacity':100,'role':'health'},'sp':{'initial':0,'capacity':15,'recovery_rate':1,'recovery_rule':'rule/ark_resource_recovery','recovery_freeze_abilities':['ability/sensor/reveal']}},'spatial':{},'selection_state':{**deepcopy(standard),'side':0,'category':2},'buffs':{'initial':['buff/sensor/invulnerable']},'abilities':['ability/sensor/reveal'],'deployable':{'base_cost':5,'capacity':0,'cooldown_seconds':5,'terrain':'ground'},'lifecycle':{'policy':'policy/ark_lifecycle'}}})
 return p
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();p=build();raw=(json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode();OUT.parent.mkdir(parents=True,exist_ok=True)
 if a.check:assert OUT.read_bytes()==raw
 else:OUT.write_bytes(raw)
 print(json.dumps({'passed':True,'sha256':sha(OUT)}))
