"""M61 exact L0 operands/selected reference rebirth; other Boss dependencies explicit."""
import argparse,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'packages/campaign/chapter04_boss_plan/source.reference.json';PIN='7ad2fb46b3e281711b6faf8b7a3bacfb9df6bc11ff32212a8439d8925d6893ec';OUT=ROOT/'packages/campaign/chapter04_boss/m61/rebirth.reference_model.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 if sha(SOURCE)!=PIN:raise ValueError('Frozen FrostNova source plan drift')
 s=json.loads(SOURCE.read_bytes());v=s['native_enemy'];a=v['resolved']['attributes'];bb={x['key']:x['value'] for x in v['resolved']['talentBlackboard']};reborn=next(c['raw'] for c in s['boss_components'].values() if c['native_class']=='RebornTalent')
 original=ROOT/'packages/campaign/chapter04_sources/native.reference.json';assert sha(original)=='3e392d80d000e27a50f11f2f33b0fa0f6be35dc1e91d7e321e2b9cf9681c4603';reference=json.loads(original.read_bytes())['variants'][s['exact_variant']]['native_reference']
 assert s['exact_variant']=='enemy_1505_frstar@0/9d1e3d01ef79ae3e' and (a['maxHp'],a['atk'],bb['reborn.duration'],bb['reborn.atk'])==(25000,420,5,.5) and reborn['_maxRespawnCnt']==1
 unit={'id':'unit/ch4/frstar/level0','kind':'entity','tags':['enemy','ground','boss'],'metadata':{'native_variant_id':s['exact_variant'],'native_reference':reference,'source_immune_attributes':{k:value for k,value in a.items() if 'Immune' in k},'source_keepAlive_raw':reborn['_keepAlive'],'raw_hp_recharge_ratio':reborn['_hpRechargeRatio'],'declared_restore_ratio':1.0,'scope':'Only exact health/ATK/selected reference rebirth phase, not whole Boss skill/FSM/immunity/blackice'},
 'components':{'spatial':{'motion_mode':0},'selection_state':{'side':1,'motion':1,'category':1,'unit_type':2},'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':1}},'resources':{'hp':{'initial':a['maxHp'],'capacity_attribute':'max_hp','role':'health'}},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':v['resolved']['lifePointReduce']},'abilities':[],
 'rebirth':{'resource':'hp','max_count':reborn['_maxRespawnCnt'],'delay_seconds':bb['reborn.duration'],'restore_ratio':1.0,'restore_rule':'rule/ch4/frstar/restore','retain_buffs':[],'reset_attack_clock':True,'on_finish':[{'op':'apply_buff','target':'source','buff':'buff/ch4/frstar/reborn_atk'}]}}}
 return {'schemaVersion':2,'manifest':{'id':'package/ch4/frstar/rebirth/reference','requires':['preset/ark_standard'],'metadata':{'builder_sha256':sha(Path(__file__)),'source_locks':{str(SOURCE.relative_to(ROOT)):PIN},'native_variant_id':s['exact_variant'],'source_reborn':reborn,'selected_reference':s['reference_sources'],'profile':'First actual health0: same managed entity inactive5s; restore effective capacity100%; ATK direct+50%; second health0 true retirement. Raw.5/reference1.0 preserved. No fake HP1/no second birth.',
 'model_gaps':['normal Attack f17/f28 event dispatch and EnemySkill Arbiter not authored here','ArcticBlast and IceShield/tile RNG/blackice not authored here','stun/silence/frozen/levitate and initial sleep-combo immunity need M70 applicability/control contribution consumer','skill cooldown reset requires actual owned skill definitions; generic M61 reset interface tested independently, not falsely bound dummy abilities'],'client_verified':False,'formal_approved':False,'whole_stage_executed':False}},'entities':[unit],'rules':[{'id':'rule/ch4/frstar/restore','kind':'rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.parameters.capacity * inputs.parameters.ratio'}}],'buffs':[{'id':'buff/ch4/frstar/reborn_atk','kind':'buff','modifiers':[{'attribute':'atk','layer':'direct_ratio','value':bb['reborn.atk']}]}]}
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();raw=(json.dumps(build(),ensure_ascii=False,indent=2)+'\n').encode('utf8');OUT.parent.mkdir(parents=True,exist_ok=True)
 if a.check:
  if OUT.read_bytes()!=raw:raise ValueError('FrostNova rebirth model stale')
 else:OUT.write_bytes(raw)
 print(json.dumps({'sha256':sha(OUT),'source_hp':25000,'source_atk':420,'reborn_seconds':5,'reference_reborn_atk':630,'whole_boss':False}))
