"""Fixed DB aura values + source target-options adapter and live SILENCED12."""
import json,hashlib,argparse
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'packages/campaign/chapter02_sources/native.reference.json';PARENT=ROOT/'packages/campaign/chapter02_behavior/models.partial.json';OUT=ROOT/'packages/campaign/chapter02_units/defdrn.status.model.json'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def build():
 import UnityPy
 assert sha(SOURCE)=='97447895b3edc69f0f60113ea96bc240c25c0fe980897614e93a94dd75e0d492' and sha(PARENT)=='bda5488a79f44e195e23631f579d313de833f356f1decec6d6abd726800f9bc8'
 d=json.loads(SOURCE.read_bytes());p=json.loads(PARENT.read_bytes());row=next(r for r in d['variants'].values() if r['native_enemy']['native_id']=='enemy_1017_defdrn');native=d['prefabs'][row['prefab_key']];asset=ROOT.parent/native['source']['path'];assert sha(asset)==native['source']['sha256'];objects={o.path_id:o for o in UnityPy.load(str(asset)).objects}
 for pid,c in native['components'].items():assert objects[int(pid)].read_typetree()==c['raw']
 aura=next(c for c in row['components'].values() if c['native_class']=='AuraAbility');validator_id=aura['raw']['_targetValidator']['m_PathID'];validator=row['components'][str(validator_id)];assert validator['native_class']=='TargetValidator'
 option=validator['raw']['_targetOptions'];expected={'targetSide':1,'targetMotion':3,'targetCategory':3,'enableAdvancedOptions':1,'ignoreTargetFree':0,'ignoreAllyTargetFree':0,'ignoreHealFree':0,'ignoreMotionMode':0,'ignoreTargetSide':0,'excludeSomeAbnormalFlags':0,'containSomeAbnormalFlags':0,'excludeAbnormalFlag':0,'containAbnormalFlag':0,'purposeMask':0,'professionMask':0,'checkUnitType':0,'unitTypeMask':0,'onlyIgnoreSomeOfTargetFreeCase':0,'abnormalFlag':0,'abnormalCombo':0};assert option==expected
 talent=next(c for c in row['components'].values() if c['native_class']=='SilenceableTalent');assert talent['raw']['_isSilenceable']==1
 dump=ROOT.parent/'Ark_data/Il2CppDumper_current/dump.cs';text=dump.read_text(encoding='utf8');assert 'public const AbnormalFlag SILENCED = 12;' in text
 bb={r['key']:r['value'] for r in row['native_enemy']['resolved']['talentBlackboard']};assert bb=={'defup.def':300.0,'defup.range_radius':2.5}
 unit=next(e for e in p['entities'] if e['id']=='unit/chapter02/enemy_1017_defdrn');selector=next(s for s in p['selectors'] if s['id']=='selector/chapter02/defup')
 default={'side':1,'motion':1,'category':1,'profession':0,'unit_type':2,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False}
 c={'_targetSide':option['targetSide'],'_targetMotion':option['targetMotion'],'_targetCategory':option['targetCategory'],'_ignoreTargetFree':option['ignoreTargetFree'],'_onlyIgnoreSomeOfTargetFreeCase':option['onlyIgnoreSomeOfTargetFreeCase'],'_excludeSomeAbnormalFlags':option['excludeSomeAbnormalFlags'],'_needProfessionMask':0,'_ignoreAllyTargetFree':option['ignoreAllyTargetFree'],'_ignoreHealFree':option['ignoreHealFree'],'_ignoreMotionMode':option['ignoreMotionMode'],'_forceIgnoreCamouflage':0,'_checkUnitType':option['checkUnitType'],'_professionMask':option['professionMask'],'_unitTypeMask':option['unitTypeMask'],'_excludeAbnormalFlag':option['excludeAbnormalFlag'],'_abnormalFlag':option['abnormalFlag'],'_abnormalCombo':option['abnormalCombo']}
 selector['filters']=[{'tag':'enemy'},{'state':'alive'}];selector['eligibility']={'rule':'rule/defdrn/status_eligibility','parameters':{'source_configuration':c,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':default}}
 selector['metadata'].update(native_target_validator=validator,native_options=option,adapter_policy={'enemy_tag_is_declared_faction_filter':True,'unpatched_enemy_side_defaults1':True,'category/motion_real_state_overrides_defaults':True,'force_camouflage_default0':'TargetOptions has no explicit switch; declared standard capability policy'})
 unit['components']['selection_state']={**deepcopy(default),'motion':2};unit['metadata']['declared_mass_policy']={'value':0,'source_defined':False,'reason':'mass not defined in fixed DB; configurable reference-model fallback'};unit['components']['attributes']['base']['mass_level']=0;unit['components']['attributes']['base']['block_cost']=1
 p['entities']=[unit];p['abilities']=[];p['behaviors']=[];p['selectors']=[selector];p['buffs']=[b for b in p['buffs'] if b['id'] in ('buff/chapter02/defup_member','buff/chapter02/defup_emitter')]
 p['rules']=[{'id':'rule/defdrn/target_options','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},
 {'id':'rule/defdrn/status_eligibility','kind':'rule','contract':'targeting.eligibility','parameters':{'silence_enabled':True,'silence_flag':12},'implementation':{'type':'graph','nodes':[{'id':'option','rule':'rule/defdrn/target_options','inputs':{key:'inputs.'+key for key in ('source','candidate','selector','selection_states','parameters')}},{'id':'result','expression':"{'accepted':nodes.option.accepted and (not params.silence_enabled or params.silence_flag not in inputs.selection_states.source.abnormal_flags),'reason':'source_silenced' if params.silence_enabled and params.silence_flag in inputs.selection_states.source.abnormal_flags else nodes.option.reason}"}],'output':'nodes.result'}}]
 p['manifest']={'id':'chapter02/defdrn_live_status','requires':['preset/ark_standard'],'metadata':{'status':'source_bound_declared_aura_status_model','required_runtime':'c77ce7a46101cf903fd9c6c56dcabddf5775008d091365cd7486ddeb47b8d740','builder_sha256':sha(__file__),'source_locks':{str(SOURCE.relative_to(ROOT)):sha(SOURCE),str(PARENT.relative_to(ROOT)):sha(PARENT),'../'+native['source']['path']:sha(asset),'../Ark_data/Il2CppDumper_current/dump.cs':sha(dump)},'variant_id':row['variant_id'],'BB_values':bb,'source_silenceable_talent':talent,'source_target_validator':validator,'runtime_model_policy':'allied enemy-tag bodies, motion ground/fly and category1/2; enabled source switches exact; live SILENCED12 denies aura membership until expiry/removal; snapshot/pure selection, no new core','model_delivery_ready':True,'client_verified':False,'feedback_pending':['native TargetValidator getter/comparator/faction body and camouflage default capability','source collider1 toBB radius2.5 loader/physical axes','silence native callback timing/stacking source override; model uses immediate generic reconciliation','mass0 fallback not source data, configurable'],'formal_approved':False}}
 return p
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();p=build();b=(json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode()
 if a.check:assert OUT.read_bytes()==b
 else:OUT.write_bytes(b)
 print(json.dumps({'passed':True,'check':a.check,'sha256':sha(OUT),'silence_flag':12,'def':300,'radius':2.5}))
