"""Pin completed independent9 groups, preserve original failed receipts."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/campaign_resource_channel_peer_v1';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def pin(p):return {'path':str(Path(p).resolve()),'sha256':sha(p),'bytes':Path(p).stat().st_size}
def main():
    path=OUT/'actual.v6.json';report=json.loads(path.read_bytes());assert report['actual_exit']==0 and report['source_equal'] and report['source_before']==report['source_after'] and len(report['results'])==9 and all(r['passed'] for r in report['results'])
    assert report['core_before']==report['core_after']=='08b6eee3fff37f6f665da5154b204c29feadc1ad0c1cef5d1640ce56940c1878'
    assert all(sha(p)==h for p,h in report['source_after'].items())
    receipts=[]
    for name in ['campaign_resource_channel_peer_v1_actual_v1','campaign_resource_channel_peer_v1_actual_v2','campaign_resource_channel_peer_v1_actual_v3_probe','campaign_resource_channel_peer_v1_actual_v4','campaign_resource_channel_peer_v1_actual_v5','campaign_resource_channel_peer_v1_actual_v6']:
        p=Path('E:/ArkSimLogs/receipts')/name/'completion.json';r=json.loads(p.read_bytes());assert r['cleanup_exit']==0 and r['raw_logs_removed_after_validation'];receipts.append({**pin(p),'worker_exit':r['worker_exit'],'cleanup':r['cleanup_result']})
    checkpoint_ids={k:v for k,v in report['facts'].items() if k.endswith('_proof')}
    final={'schema':'ark-sim/independent-resource-channel-peer-freeze/v1','core':report['core_after'],'source_freeze_sha256':report['freeze_sha256'],'actual_report':pin(path),'helpers':[pin(p) for p in sorted(Path(__file__).parent.glob('*.py'))],'source_guards_current':report['source_after'],'independent_groups_passed':9,'actual_CP_head_identities':checkpoint_ids,'comparison_exclusions':[],'raw_checkpoint_files_deleted_after_full_validation':True,'cleanup':receipts,'deleted_bytes':sum(r['cleanup']['reclaimed_bytes'] for r in receipts),'remaining_raw':0,'cleanup_errors':0,'preserved_failed_reports':[pin(OUT/n) for n in ['actual.v1.json','actual.v2.json','actual.v3.probe.json','actual.v4.json']],'prior_passed_scope':pin(OUT/'actual.v5.json'),'fixture_corrections':['Recovery-freeze authority metadata was mandatory and added to synthetic peer rule.','Public withdrawal requires deployed actors and DP resource for refund; original rejections saved.','completion_blocking true deliberately prevents terminal until channel finishes; genuine terminal case uses explicitFalse.','Effect targets accept canonical numeric actor references rather than arbitrary alias strings; fixture assertsactual2/3 alias resolution.','Source DISAPPEAR interrupts currentcast before attachment-specific hidden reason; observedcast_interrupted and actualvisibility timeline preserved.'],'fault_boundary':'Actual current_task attachment handler outer atomic entrance. Resource was really11->18 then two RNG draws then fault; full World/jobs/RNG/events/attribute-cache equal at sameclock2. Framework failure-marker transition reported.','forged_task':'Actual unowned task at packetdue14 observed before/after realhandler and all5stores equal; scheduler dequeue is outside handler boundary.','author_fixture_imported':False,'candidate_or_primary_modified':False,'whole_stage_or_client_verified':False}
    out=OUT/'final.freeze.v1.json';assert not out.exists();out.write_text(json.dumps(final,indent=2)+'\n',encoding='utf8');print(json.dumps({'freeze':pin(out),'deleted_bytes':final['deleted_bytes'],'CP_head_proofs':len(checkpoint_ids)}))
if __name__=='__main__':main()
