"""Exact C6 ordinary FrostNova2 two modes, Cold, branch and tile skills."""
from pathlib import Path
from copy import deepcopy
import hashlib,json
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'packages/campaign/chapter06_boss/frstar2'
CLOSURE=OUT/'source.closure.json'
COLD=ROOT/'packages/campaign/chapter06_cold/model.json'
ICE=ROOT/'packages/campaign/chapter04_boss/ice_shield_v3/module.reference.json'
UID='unit/ch6/frstar2/3681c71c12a71fb0'
N=[f'ability/{UID}/normal{i}' for i in (0,1)]
B=[f'ability/{UID}/burst{i}' for i in (0,1)]
I=[f'ability/{UID}/ice{i}' for i in (0,1)]
SUM='ability/'+UID+'/summon'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def provider(id,contract,name):return {'id':id,'kind':'rule','contract':contract,'implementation':{'type':'provider','provider':name}}
def defaults():return {'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False,'abnormal_immunes':[]}
def build():
    src=json.loads(CLOSURE.read_bytes());v=src['variant'];d=v['native_enemy']['resolved'];a=d['attributes'];components=src['components'];anim=src['animation_summary']['parsed']['animations'];p={'schemaVersion':2,'manifest':{'id':'package/ch6/frstar2/ordinary','requires':['preset/ark_standard'],'metadata':{'source_locks':{str(CLOSURE.relative_to(ROOT)):sha(CLOSURE),str(COLD.relative_to(ROOT)):sha(COLD),str(ICE.relative_to(ROOT)):sha(ICE)},'builder_sha256':sha(Path(__file__)),'native_variant_id':v['variant_id'],'source_profile':src['profile'],'source_conflicts':src['source_conflicts'],'reference_policies':{'restore':'FullHP30000 after10s; rawhpRechargeRatio.5 preserved, explicitPRTS/reference restore policy','invulnerability':'FixedsourceBB20 wins currentPRTS25 versionconflict','skills_clock':'castLikeAttack0 mapped independent skillcooldown, normal111 clock; allcasts busy/fullsourceanimationfinish. Replaceablebodypolicy','tile_filter':'OriginalEXCEPT_CHARACTER/options preserved; deploymenteligible radius2 excluding currentdeploymentoccupancy, randomwithoutreplacement; point/tilebody boundariesreplaceable','timing':'NormalAttack28/full48; phase0BurstAttack28/full48; phase1BurstSkill3 87/full110; ShieldSkill1 55/full90. Normal+Burst ASPDscaled min.01, ShieldTIMEMODE1 fixedtime referencepolicy','mode':'Real rebirthcount1 selectsMode1; no arbitrary phase switch','sleep':'Both modes own permanentcombo0 immunity, restored after rebirthclear','branch':'SourceReborn-parent Summon priority10 max1 consumes actualfrstar_frosts branch, no fakeactivation'},'complete_source_policies':False,'independent_reviewed':False,'whole_stage_executed':False,'client_verified':False}},'entities':[],'rules':[],'abilities':[],'buffs':[],'selectors':[],'projectiles':[],'behaviors':[],'definitions':[]}
    stem='rule/'+UID;elig=stem+'/eligibility';score=stem+'/hate';traj=stem+'/trajectory';collision=stem+'/collision';steer=stem+'/steer';wind=stem+'/windup';restore=stem+'/restore'
    p['rules']=[provider(elig,'targeting.eligibility','model.targeting.eligibility'),provider(traj,'projectile.trajectory','model.projectile.trajectory'),provider(collision,'projectile.collision','model.projectile.collision'),provider(steer,'movement.steering','ark.movement.steering_velocity'),{'id':wind,'kind':'calculation_rule','contract':'ability.windup','parameters':{'minimum_speed':.01},'implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio, params.minimum_speed)'}},{'id':restore,'kind':'calculation_rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.parameters.capacity * inputs.parameters.ratio'}},{'id':score,'kind':'rule','contract':'targeting.score','implementation':{'type':'expression','expression':"-100000 * (inputs.candidate.components.attributes.base.taunt_level if 'taunt_level' in inputs.candidate.components.attributes.base else 0) - inputs.candidate.id"}}]
    atk='buff/'+UID+'/reborn_atk';inv='buff/'+UID+'/invulnerable';sleep='buff/'+UID+'/sleepimmune';cast='buff/'+UID+'/burst_frozen_scale'
    p['buffs']=[{'id':atk,'kind':'buff','modifiers':[{'attribute':'atk','layer':'direct_ratio','value':.5}]},{'id':inv,'kind':'buff','duration_seconds':20,'selection_flags':{'abnormal_flags':[5]},'damage_hooks':[{'phase':'after','rule':stem+'/invulnerable_request'}]},{'id':sleep,'kind':'buff','selection_flags':{'abnormal_combo_immunes':[0]}},{'id':cast,'kind':'buff','damage_hooks':[{'phase':'before','rule':stem+'/burst_frozen_scale'}]}]
    p['rules'].append({'id':stem+'/invulnerable_request','kind':'rule','contract':'damage.pipeline','implementation':{'type':'graph','nodes':[{'id':'result','expression':"{'accepted':False,'amount':0,'allocations':[],'events':[]}"}],'output':'nodes.result'}})
    p['rules'].append({'id':stem+'/burst_frozen_scale','kind':'rule','contract':'damage.request','implementation':{'type':'provider','provider':'reference.c6.frozen_atkscale'},'parameters':{'atk_scale':2}})
    cold=lambda seconds:{'op':'buff_application','application_rule':'rule/ch6/cold/application','allowed':['buff/ch6/cold/e2c_cold','buff/ch6/cold/e2c_freeze'],'parameters':{'duration_seconds':seconds}}
    pid='projectile/'+UID+'/normal';projectile=src['normal_projectile'];motion=next(c['raw'] for c in projectile['components'].values() if c['native_class']=='AdvancedMovement');simple=next(c['raw'] for c in projectile['components'].values() if c['native_class']=='SimpleProjectile')
    p['projectiles']=[{'id':pid,'kind':'projectile','motion':{'rule':traj,'parameters':{'mode':'homing','speed':motion['_speed']}},'collision':{'rule':collision,'parameters':{'enabled':True,'radius':0}},'lifetime_seconds':simple['_lifeTime'],'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'cancel','target_hidden':'cancel','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'on_invalid':[]}]
    entries=[];abilityids=[]
    for mode in (0,1):
        modecond="('rebirth' not in inputs.runtime or inputs.runtime.rebirth.count == 0)" if mode==0 else "('rebirth' in inputs.runtime and inputs.runtime.rebirth.count == 1)"
        normal=v['modes'][mode]['nodes']['_combat'];trigger=v['modes'][mode]['nodes']['_attackTrigger']['gameobject_path_id'];cfg=next(c['raw'] for c in components.values() if c['native_class']=='AdvancedSelector' and c['gameobject_path_id']==trigger)
        sid='selector/'+UID+'/normal'+str(mode);wrapper=elig+'/normal'+str(mode)
        p['rules'].append({'id':wrapper,'kind':'calculation_rule','contract':'targeting.eligibility','dependencies':[elig],'implementation':{'type':'graph','nodes':[{'id':'base','rule':elig,'inputs':{k:'inputs.'+k for k in ('source','candidate','selector','selection_states','parameters')}},{'id':'result','expression':"{'accepted':nodes.base.accepted and ('blocked_by' not in inputs.source.components.runtime or inputs.source.components.runtime.blocked_by == None or inputs.candidate.id == inputs.source.components.runtime.blocked_by),'reason':'native_input_target2'}"}],'output':'nodes.result'}})
        p['selectors'].append({'id':sid,'kind':'selector','region':{'type':'radius','radius':2},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{'rule':wrapper,'parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}})
        p['abilities'].append({'id':N[mode],'kind':'ability','selector':sid,'target_capture':'at_cast','rules':{'ability.windup':wind,'targeting.score':score},'duration_seconds':1.6,'activation':{'mode':'automatic_attack','settle_blocking':True,'parameters':{'auto_only':True}},'timeline':[{'at_seconds':28/30,'effect':{'op':'damage','damage_type':'arts','scale':1,'projectile_definition':pid,'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'on_success':[cold(5)]}}]})
        burstnode=components['988932605719683155' if mode==0 else '-6095939705393962925'];raw=burstnode['raw'];btrigger=raw['_selector']['m_PathID'];bcfg=components[str(btrigger)]['raw'];radius=2 if mode==0 else 3.299999952316284;bsid='selector/'+UID+'/burst'+str(mode);member=stem+'/burstmembers'+str(mode)
        p['rules'].append({'id':member,'kind':'rule','contract':'area.members','dependencies':[elig],'parameters':{'radius':radius,'eligibility':{'rule':elig,'parameters':{'source_configuration':bcfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}},'implementation':{'type':'provider','provider':'model.area.qualified_radius'}})
        p['selectors'].append({'id':bsid,'kind':'selector','region':{'type':'radius','radius':radius},'filters':[{'tag':'player'},{'state':'alive'}],'limit':None,'eligibility':{'rule':elig,'parameters':{'source_configuration':bcfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}})
        frame=28 if mode==0 else 87;duration=48/30 if mode==0 else 110/30
        p['abilities'].append({'id':B[mode],'kind':'ability','selector':bsid,'initial_cooldown_seconds':10.5,'cooldown_seconds':10.5,'duration_seconds':duration,'rules':{'ability.windup':wind},'activation':{'mode':'manual','forbidden_source_flags':[0,12],'parameters':{'auto_only':True,'auto_when_ready':True,'requires_targets':True},'on_start':[{'op':'apply_buff','target':'source','buff':cast,'bind_to_cast':True}]},'timeline':[{'at_seconds':frame/30,'effect':{'op':'area','center':'source','membership_rule':member,'filters':[{'tag':'player'}],'effects':[{'op':'damage','damage_type':'arts','scale':1,'damage_flags':{'source_attack_type':'SPLASH','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'on_success':[cold(10)]}]}}]})
        ice=deepcopy(json.loads(ICE.read_bytes())['definitions']);token=ice[0];token['id']='unit/'+UID+'/sealedfloor';token['metadata']['source_policy']='Borrowed exacttrap004localasset/referenceHP100, sourceIceShieldtokenprofile phase0level0skill-1';skill=ice[1];skill['id']=I[mode];skill['initial_cooldown_seconds']=35;skill['cooldown_seconds']=35;skill['duration_seconds']=3;skill['tile_selector']['limit']=2 if mode==0 else 3;skill['tile_selector']['stream']='ch6/frstar2/shield'+str(mode);skill['timeline'][0]['at']=55;skill['timeline'][0]['effect']['definition']=token['id'];skill['metadata']['source_plan_sha']=sha(CLOSURE);skill['metadata']['cooldown_policy']='35 fromfinish, initial35; source BB fixed';p['definitions'].append(skill)
        if mode==0:p['definitions'].append(token)
        for aid,priority,attack in [(I[mode],2,False),(B[mode],1,False),(N[mode],0,True)]:entries.append({'ability':aid,'priority':priority,'attack_clock':attack,'require_attack_control':attack,'condition':modecond,'parameters':{}});abilityids.append(aid)
    p['abilities'].append({'id':SUM,'kind':'ability','activation':{'mode':'manual','costs':[{'resource':'summon_uses','amount':1}],'parameters':{'auto_only':True,'auto_when_ready':True}},'timeline':[{'at':0,'effect':{'op':'advance_branch','parameters':{'branch':'frstar_frosts'}}}]})
    entries.insert(0,{'ability':SUM,'priority':10,'attack_clock':False,'require_attack_control':False,'condition':"'rebirth' in inputs.runtime and inputs.runtime.rebirth.count == 1 and 'frstar_frosts' in inputs.branches and inputs.branches.frstar_frosts.available",'parameters':{}});abilityids.append(SUM)
    mover=next(c['raw'] for c in components.values() if c['native_class']=='MoveController');root=next(c['raw'] for c in components.values() if c['native_class']=='Enemy')
    boss={'id':UID,'kind':'entity','tags':['enemy','ground','boss'],'metadata':{'native_variant_id':v['variant_id'],'native_reference':v['native_reference']},'components':{'attributes':{'base':{'max_hp':30000,'atk':440,'def':380,'mres':50,'move_speed':.5,'attack_interval':3.7,'attack_speed_ratio':1,'mass_level':6,'block_cost':root['_blockVolume']}},'resources':{'hp':{'initial':30000,'capacity_attribute':'max_hp','role':'health'},'summon_uses':{'initial':1,'capacity':1,'role':'finite_cast_count'}},'selection_state':{**defaults(),'side':1,'unit_type':2,'abnormal_immunes':[0,12,16,25]},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':2},'buffs':{'initial':[sleep]},'abilities':abilityids,'ability_arbitration':{'priority_order':'higher_first','busy':'all_casts','entries':entries},'spatial':{'motion_mode':0,'steering':{'rule':steer,'parameters':{'response_factor':mover['_steeringFactor'],'max_acceleration':mover['_maxSteeringForce'],'arrival_radius':.05}}},'rebirth':{'resource':'hp','max_count':1,'delay_seconds':10,'restore_ratio':1,'restore_rule':restore,'retain_buffs':[],'reset_attack_clock':True,'reset_cooldowns':[{'ability':aid,'initial_delay_seconds':35 if aid in I else 10.5} for aid in I+B],'on_finish':[{'op':'apply_buff','target':'source','buff':atk},{'op':'apply_buff','target':'source','buff':inv},{'op':'apply_buff','target':'source','buff':sleep}]},'behavior':{'machine':'behavior/'+UID}}}
    p['entities'].append(boss);p['behaviors']=[{'id':'behavior/'+UID,'kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/ark_behavior_decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'normal','selector':'selector/'+UID+'/normal0'},{'key':'normal1','selector':'selector/'+UID+'/normal1'}],'cast_groups':[{'key':'all','abilities':abilityids}],'parameters':{'target_key':'normal','stop_on_target':True,'stop_cast_groups':['all']}}]}}]
    return p
if __name__=='__main__':
    OUT.mkdir(parents=True,exist_ok=True);data=build();path=OUT/'model.json';path.write_bytes((json.dumps(data,ensure_ascii=False,indent=2)+'\n').encode('utf8'));print(json.dumps({'sha256':sha(path),'two_phases':True,'whole_stage_executed':False}))
