import json,hashlib
from pathlib import Path
from collections import Counter
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter08_firstscreen_source_peer_v1';OUT.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();base=ROOT/'packages/campaign/chapter08_consumers';source=base/'bsnake/source.closure.v1.json';screen=base/'bsnake/first_screen.module.v2.json';loop=base/'flame/loop.profile.v3.json';rows=base/'bsnake/first_screen.native7rows.v3.json';dump=ROOT.parent/'Ark_data/dump.cs';files=[Path(__file__),source,screen,loop,rows,dump];before={str(p):sha(p) for p in files};s=json.loads(source.read_bytes());p=json.loads(screen.read_bytes());l=json.loads(loop.read_bytes());r=json.loads(rows.read_bytes())
native=s['RebornTalent']['raw'];assert native['_hpRechargeRatio']==.5 and native['_maxRespawnCnt']==2
skill=next(x for x in s['variant']['native_enemy']['resolved']['skills'] if x['prefabKey']=='ScreenAttack');bb={x['key']:x['value'] for x in skill['blackboard']};assert bb=={'atk_scale':1,'duration':28,'interval':2,'trig_cnt':10,'invincible':15}
screenbuff=next(x for x in p['buffs'] if x['id']=='buff/ch8/source/bsnake_s[screen_attack]');inv=next(x for x in p['buffs'] if x['id']=='buff/ch8/source/reborn_up[invincible]');assert screenbuff['duration_seconds']==28 and screenbuff['interval_seconds']==2 and screenbuff['selection_flags']['abnormal_flags']==[22,5] and inv['duration_seconds']==15 and inv['selection_flags']['abnormal_flags']==[5]
template=s['BSON']['templates']['enemy_bsnake_s[screen_attack]']['parsed']['eventToActions'];assert template['ON_BUFF_FINISH'][0]['_modeIndex']==1 and template['ON_BUFF_FINISH'][0]['_restartFSM'] is True
assert template['ON_BUFF_FINISH'][1]['_buff']['attributes']['abnormalFlags']==['INVINCIBLE'] and template['ON_BUFF_FINISH'][2]['_abilityName']=='Hint'
text=dump.read_text(encoding='utf8');enum_evidence={name:next(line.strip() for line in text.splitlines() if 'public const AbnormalFlag '+name+' =' in line) for name in ('INVINCIBLE','INVISIBLE','UNMOVABLE_PRIVATE')};assert ' = 5;' in enum_evidence['INVINCIBLE'] and ' = 9;' in enum_evidence['INVISIBLE'] and ' = 22;' in enum_evidence['UNMOVABLE_PRIVATE']
phases=l['native_phase_keys'];assert l['runtime_branch']['bsnake_flame']['loop'] is True and l['native_summon_actions'][0]['_isLoop'] is True and l['native_branch_trigger']['raw']['_isLoop']==1
assert len(phases)==7 and all(len(x)==5 for x in phases);counts=Counter(key for i in range(21) for key in phases[i%7]);assert sum(counts.values())==105
assert all(item['reactivation']['max_activations']==counts[item['registration_key']] for item in l['initial_entities'])
assert r['manifest']['metadata']['source_native_map_dimensions']=={'rows':9,'cols':15} and r['manifest']['metadata']['source_screen_rows']==list(range(1,8)) and len(r['projectiles'])==28 and len(r['abilities'][0]['timeline'])==7
assert {x['motion']['parameters']['row'] for x in r['projectiles']}==set(range(1,8));after={str(p):sha(p) for p in files};assert before==after
report={'passed':True,'source_screen_values':bb,'source_reborn_ratio':.5,'enum_evidence':enum_evidence,'source_fields_mapped':['5s waiting','28s finiteBuff','2s timer+10packetbudget','mode1 restartFSM','15s Invincible','selfboost50percent MaxHP/ATK plusrestore50percent=37500','firstscreen22 movement-private/5invincible'], 'reference_policies':['INVINCIBLE selects target_free to model different-side unselectability; ignoreTargetFree1 may select butafterhook damage rejects','Sourcecaster screen ray geometry/RNG buckets declaredreference; first3row fixture notnative9x15 fullmap','NativeReborn .5 plusBoost .5 vsPRTS prose100percent conflict preservedliteralSource','Ordinarybound-selector witness verifiesattackcontrol only, fullnormal/general/nativeFSM mechanisms stillseparatelyneeded'], 'pending_consumer':['Hint ON_FINISH currentlyemitrequest only','Nativeanimation visualbinding andfull4mode Boss'], 'web_source_checked':{'url':'https://prts.wiki/w/%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9','claim':'INVINCIBLE5 cannot be selected by different faction, damage/element changes zero. Fixedraw source remainsprimary.'},'loop_scope':{'native_loop':True,'phase_count':7,'conservative_requests':21,'budget_sum':105,'budget_formula':'sum exactnative7x5 keys over3loops underdeclared maxTicks30000/50s conservativeceiling; nativeinit75/castwaitnotexecutedhere','native_stock':False,'device_duration_dummy_policy':'25s Buff thenwithdrawn mirrorsauthorflamefinish policy, doesnot signrawflameperpacketdamage'},'native7rows_source_static_verified':True,'native7rows_actual_exec':'Pending additional independent run; notmigratedfrom3row proof','guards_start':before,'guards_end':after,'guards_equal':True};(OUT/'verification.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8');print(sha(OUT/'verification.json'))
