"""Exact normal modes0/1 and both native protection profiles; no runtime edits."""
import sys,json,hashlib
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[2];RUNTIME=ROOT.parent/'unpack_work/campaign_chapter08_joint_v4_candidate';sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from ark_sim.domains.selection import DEFAULT_STATE
from tools.chapter08_bsnake_combat.policies_v1 import providers
CORE='20e8126120668fece832e8b6e23fd53a68fb013656a4476b5ad8e53850f6dd30';OWNER='unit/ch8/bsnake/cadb87696bef4de2';PROTECT='buff/ch8/source/bsnake_t[protect]';REBORN=PROTECT+'/reborn';D12=ROOT/'packages/campaign/chapter08_consumers/boss/dragon_fire.module.v12.joint.json';OUT=ROOT/'packages/campaign/chapter08_consumers/bsnake/combat.module.v2.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 assert implementation_digest()==CORE and sha(D12)=='a56cf27ee1c4e1a1a5a63343e90498e0a88120bea5800ed80c834d26cd25d7af'
 source=ROOT/'packages/campaign/chapter08_consumers/bsnake/source.closure.v1.json';s=json.loads(source.read_bytes());assert sha(source)=='742d78443641451c8b54bdf75281c33cd04c198eaee373ca95991e380f05469d';a=s['variant']['native_enemy']['resolved']['attributes'];c=s['prefab']['components'];cfg=c['-4945578191777925756']['raw'];assert cfg['_postFilter']==4 and cfg['_maxNum']==1;stem='rule/ch8/bsnake/normal/';base=json.loads((ROOT/'packages/campaign/chapter08_consumers/bsnake/firecommon.module.v2.json').read_bytes())['entities'][0];base['components']['resources']['hp']={'initial':50000,'capacity_attribute':'max_hp','role':'health'};base['components']['resources']['mode']={'initial':0,'capacity':3};base['components']['attributes']['base']['block_cost']=s['root']['raw']['_blockVolume'];base['components']['buffs']={'initial':[PROTECT]};base['components']['behavior']={'machine':'behavior/ch8/bsnake/normal'}
 p={'schemaVersion':2,'manifest':{'id':'package/ch8/bsnake/normal_v2','requires':['preset/ark_standard'],'metadata':{'required_runtime':CORE,'source_locks':{str(x):sha(x) for x in [source,D12,Path(__file__),Path(__file__).with_name('policies_v1.py')]},'variant_bindings':[{'variant_id':s['variant']['variant_id'],'unit_definition':OWNER,'native_reference':s['variant']['native_reference'],'native_resolved':s['variant']['native_enemy']['resolved']}],'partial_consumer_scope':'Normal modes0/1 PURE31+on accepted hit DragonFire and source-dependent protective hook. Four-mode Rebirth/screen/hint/loopbranch composed separately; no completeBoss claim.','profile_conflict':'PassiveBuffAbility all isSilenceable0 vs RebornTalent samekey isSilenceable1; two explicit definitions share damagehook group and max1 stacking. Join must remove old/apply chosen actualprofile; source normal0/1 installs passive0.','reference_policy':'postFilter4 HATRED_DES mapped effective taunt descending then newest actual ID; blocked identity eligibility AND all native state gates, not priorityweight. DB radius2 centre closed boundary; raw selector/body launch offsets nativebody unknown. TimeMode0 raw float32 OnAttack31 divided currentASPD with .01 reference clamp, native graphical max1 retained as unknown. Hit reads live attributes. Mode controller resource is projection, not modified native stats. D12 imported unmodified with caller runtime20e; olda6 D12 metadata/proof preserved.','whole_stage_executed':False,'client_verified':False}},'entities':[base],'abilities':[],'selectors':[],'rules':[],'behaviors':[],'buffs':[]}
 p['rules']=[{'id':stem+'base','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':stem+'qualified','kind':'rule','contract':'targeting.eligibility','dependencies':[stem+'base'],'parameters':{'base_rule':stem+'base'},'implementation':{'type':'provider','provider':'reference.c8.bsnake.normal_eligibility'}},{'id':stem+'selection','kind':'rule','contract':'targeting.selection','dependencies':['rule/ark_attribute_layers'],'implementation':{'type':'provider','provider':'reference.c8.bsnake.hatred'}},{'id':stem+'windup','kind':'rule','contract':'ability.windup','implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio,.01)'}},{'id':stem+'decision','kind':'rule','contract':'behavior.decision','implementation':{'type':'provider','provider':'reference.c8.bsnake.normal_decision'}},{'id':stem+'protect','kind':'rule','contract':'damage.pipeline','parameters':{'dragon_fire':'buff/ch8/source/dragon_fire','resistance':s['consumer_merged_BB12']['protect.bsnake_t[protect].damage_resistance']['value']},'implementation':{'type':'provider','provider':'reference.c8.bsnake.burned_source_protect'}},{'id':stem+'not_silenced','kind':'rule','contract':'buff.applicability','implementation':{'type':'expression','expression':'12 not in inputs.status.abnormal_flags'}}]
 p['rules'].append({'id':stem+'duration','kind':'rule','contract':'ability.duration','implementation':{'type':'expression','expression':'inputs.duration_parameters.seconds / max(inputs.attributes.attack_speed_ratio,.01)'}});p['rules'].append({'id':stem+'steer','kind':'rule','contract':'movement.steering','implementation':{'type':'provider','provider':'ark.movement.steering_velocity'}});mover=next(x['raw'] for x in c.values() if x['native_class']=='MoveController');base['components']['spatial']={'steering':{'rule':stem+'steer','parameters':{'response_factor':mover['_steeringFactor'],'max_acceleration':mover['_maxSteeringForce'],'arrival_radius':.05}}};profiles=[]
 for mode in (0,1):
  raw=s['source_hook_resolved_modes'][mode]['raw']['nodes']['_attack']['raw'];combat=s['source_hook_resolved_modes'][mode]['raw']['nodes']['_combat'];assert raw['_damageType']==3 and raw['_attackType']==1 and raw['_timeMode']==0 and raw['_atkScale']==1;assert combat['path_id']==s['source_hook_resolved_modes'][mode]['raw']['nodes']['_attack']['path_id'];frame=next(e for e in s['frames']['Attack_A' if mode==0 else 'Attack_B']['events'] if e['name']=='OnAttack');assert frame['frame']==31;aid='ability/ch8/bsnake/normal/phase'+str(mode);sid='selector/ch8/bsnake/normal/'+str(mode);p['selectors'].append({'id':sid,'kind':'selector','region':{'type':'radius','radius':s['variant']['native_enemy']['resolved']['rangeRadius']},'filters':[{'state':'alive'}],'limit':1,'eligibility':{'rule':stem+'qualified','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':deepcopy(DEFAULT_STATE)}}});p['abilities'].append({'id':aid,'kind':'ability','selector':sid,'target_capture':'at_cast','duration_seconds':s['frames']['Attack_A' if mode==0 else 'Attack_B']['duration']['source_seconds_float32'],'activation':{'mode':'automatic_attack','condition':'inputs.resources.mode.current == '+str(mode),'parameters':{'auto_only':True},'settle_blocking':True},'rules':{'ability.windup':stem+'windup','ability.duration':stem+'duration','targeting.selection':stem+'selection'},'timeline':[{'at_seconds':frame['source_seconds_float32'],'effect':{'op':'damage','damage_type':'true','scale':1,'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'on_success':[{'op':'buff_application','application_rule':'rule/ch8/dragon_fire/application','allowed':['buff/ch8/source/dragon_fire','buff/ch8/source/dragon_fire[damage]']}]}}],'metadata':{'source_node':s['source_hook_resolved_modes'][mode]['raw']['nodes']['_attack'],'native_OnAttack_frame':31}});profiles.append({'mode':mode,'selectors':[{'key':'normal','selector':sid}],'cast_groups':[{'key':'normal','abilities':[aid]}]})
 for mode in (2,3):profiles.append({'mode':mode,'selectors':[],'cast_groups':[]})
 base['components']['abilities']=[x['id'] for x in p['abilities']];p['behaviors']=[{'id':'behavior/ch8/bsnake/normal','kind':'behavior','initial':'normal','states':{'normal':{}},'transitions':[],'decision':{'rule':stem+'decision','mode_resource':'mode','profiles':profiles}}]
 for ident,silence in [(PROTECT,False),(REBORN,True)]:
  buff={'id':ident,'kind':'buff','stacking':{'mode':'refresh','max_stacks':1},'damage_hooks':[{'phase':'after','group':'native/bsnake_t[protect]','rule':stem+'protect'}],'metadata':{'native_buff_key':'bsnake_t[protect]','isSilenceable':int(silence),'BSON_document_sha':s['BSON']['templates']['enemy_bsnake_t[protect]']['document_sha256'],'source_profile':'RebornTalent' if silence else 'PassiveBuffAbility'}}
  if silence:buff['active_rule']=stem+'not_silenced'
  p['buffs'].append(buff)
 fixture=deepcopy(p);fixture['scenarioDraft']={'id':'scene/bsnake/normal/compile','ruleset':'ruleset/ark_standard','map':{'rows':2,'cols':4},'objectives':{},'initialEntities':[{'definition':OWNER,'instanceAlias':'boss','position':{'row':0,'col':0}}]};Compiler(providers=providers()).compile(fixture,packages=[str(D12)]);return p
if __name__=='__main__':
 p=build();OUT.parent.mkdir(parents=True,exist_ok=True);assert not OUT.exists();OUT.write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n',encoding='utf8');print(json.dumps({'sha':sha(OUT),'core':CORE,'actual_compile':True}))
