import json
from tools.chapter07_ranged_consumers.probe_soticn_v3 import ROOT,package,REG,Compiler,Engine
from ark_sim.adapters.api import implementation_digest
from ark_sim.tools.replay import replay
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
CORE='788f388ec892abca97c8d0cf6ca2329998768f273e66edef21bb000485492c8e';OUT=ROOT/'validation/campaign/chapter07_ranged_soticn_author_v4';MARKER='buff/ch7/source/enemy_9D0_talent_strength';DERIVED='buff/ch7/source/enemy_talent_strength[atk_speed]'
def make(p):assert implementation_digest()==CORE;program=Compiler(providers=REG).compile(p);return program,Engine.create(program,providers=REG)
def test_exact450_16frame_144cycle_speed4_continuous_corner339_and_CP22():
 p=package();program,s=make(p);s.session.advance(22);OUT.mkdir(parents=True,exist_ok=True);cp=OUT/'flight22.cp.json';assert not cp.exists();h=write_ordered(cp,s.checkpoint());r=Engine.restore(program,load_bound(cp,h),providers=REG);s.session.advance(180);r.session.advance(180);assert s.snapshot()==r.snapshot()==replay(program,s.export_replay(),providers=REG).snapshot();ev=s.snapshot()['events'];assert [e['time'] for e in ev if e['type']=='ability.started']==[0,144];assert [e['time'] for e in ev if e['type']=='projectile.launched']==[16,160];assert [(e['time'],e['payload']['target'],e['payload']['amount']) for e in ev if e['type']=='damage.accepted']==[(46,3,339),(46,4,339),(190,3,339),(190,4,339)];assert all(e['payload']['members']==[3,4] for e in ev if e['type']=='area.resolved');assert set(s.ctx.entity('mortar')['components']['resources'])=={'hp'};(OUT/'flight.trace.json').write_text(json.dumps({'input':p,'cp_sha':h,'snapshot':s.snapshot()},indent=2),encoding='utf8')
def test_real_strength_listener8_ratio1_5_revert24_CP7():
 p=package();p['selectors'].append({'id':'selector/mortar/self','kind':'selector','region':{'type':'all'},'filters':[{'field':{'path':['id'],'equals':2}}]});p['scenarioDraft']['scheduledEffects']=[{'at':1,'effect':{'op':'apply_buff','selector':'selector/mortar/self','buff':MARKER}},{'at':18,'effect':{'op':'remove_buff','selector':'selector/mortar/self','buff':MARKER}}];program,s=make(p);s.session.advance(7);cp=OUT/'listener7.cp.json';h=write_ordered(cp,s.checkpoint());r=Engine.restore(program,load_bound(cp,h),providers=REG);s.session.advance(4);assert any(m['attribute']=='attack_speed_ratio' and m['value']==.5 for m in s.ctx.entity('mortar')['components']['attributes']['modifiers']);s.session.advance(20);r.session.advance(24);assert s.snapshot()==r.snapshot()==replay(program,s.export_replay(),providers=REG).snapshot();ev=s.snapshot()['events'];assert [e['time'] for e in ev if e['type']=='buff.applied' and e['payload']['buff']==DERIVED]==[8];assert [e['time'] for e in ev if e['type']=='buff.removed' and e['payload']['buff']==DERIVED]==[24];assert not s.ctx.entity('mortar')['components']['attributes']['modifiers']

def test_actual_impact_TargetFree_excluded_camo_fly_included_and_enemyexcluded():
 for field,value in [('target_free',True),('side',1),('category',4)]:
  p=package();p['entities'][-1]['components']['selection_state'][field]=value;_,s=make(p);s.session.advance(60);assert [(e['payload']['target'],e['payload']['amount']) for e in s.snapshot()['events'] if e['type']=='damage.accepted']==[(3,339)]

def test_real_live_TargetFree_buff_before_impact_and_corner_DEF211():
 p=package();p['buffs'] += [{'id':'buff/mortar/free','kind':'buff','duration_seconds':2,'selection_flags':{'target_free':True}},{'id':'buff/mortar/DEF100','kind':'buff','duration_seconds':2,'modifiers':[{'attribute':'def','layer':'flat','value':100}]}]
 for name,i in [('primary',3),('corner',4)]:p['selectors'].append({'id':'selector/mortar/'+name,'kind':'selector','region':{'type':'all'},'filters':[{'field':{'path':['id'],'equals':i}}]})
 p['scenarioDraft']['scheduledEffects']=[{'at':20,'effect':{'op':'apply_buff','selector':'selector/mortar/primary','buff':'buff/mortar/free'}},{'at':20,'effect':{'op':'apply_buff','selector':'selector/mortar/corner','buff':'buff/mortar/DEF100'}}];_,s=make(p);s.session.advance(60);assert [(e['time'],e['payload']['target'],e['payload']['amount']) for e in s.snapshot()['events'] if e['type']=='damage.accepted']==[(46,4,239)]
