"""Spear and actual alive Immo added; waiting/sharedAura remain quarantined."""
from pathlib import Path
import json
from tools.chapter07_boss.build_mechanism_v1 import ROOT,OUT,UID,sha
SPEAR='ability/'+UID+'/spear';IMMO='ability/'+UID+'/immo_action';NAT='ability/'+UID+'/immo_natural';TIMER='buff/'+UID+'/rage_immo_timer'
def main():
 p=json.loads((OUT/'mechanism.v3.json').read_bytes());s=json.loads((OUT/'source.closure.json').read_bytes());cs=s['prefab']['components'];db=s['variant']['native_enemy']['resolved'];skills={x['prefabKey']:x for x in db['skills']};stem='rule/'+UID;base=stem+'/eligibility'
 cfg=cs['1386826373912127690']['raw'];template=next(x['eligibility'] for x in p['selectors'] if x['id'].endswith('/allies'));sid='selector/'+UID+'/spear';params=json.loads(json.dumps(template['parameters']));params['source_configuration']=cfg;wrapper=stem+'/spear_eligibility';score=stem+'/spear_distance';order=stem+'/spear_selection'
 p['rules'] += [{'id':wrapper,'kind':'rule','contract':'targeting.eligibility','dependencies':[base],'parameters':{'base_rule':base,'buildable_mask':2},'implementation':{'type':'provider','provider':'reference.ch7.patrt_spear_eligibility'}},{'id':score,'kind':'rule','contract':'targeting.score','implementation':{'type':'expression','expression':'-inputs.distance'}},{'id':order,'kind':'rule','contract':'targeting.selection','dependencies':['rule/ark_attribute_layers'],'parameters':{'attribute_rule':'rule/ark_attribute_layers','attribute_layers':['flat','direct_ratio','final_ratio'],'default_taunt':0},'implementation':{'type':'provider','provider':'reference.ch7.patrt_spear_selection'}}]
 p['selectors'].append({'id':sid,'kind':'selector','region':{'type':'radius','radius':20},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{'rule':wrapper,'parameters':params,'include_candidate_tile':True}})
 proj='projectile/'+UID+'/spear';raw=next(c['raw'] for c in s['projectile_spear']['components'].values() if c['native_class']=='SimpleProjectile')
 p['rules'] += [{'id':stem+'/trajectory','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'model.projectile.trajectory'}},{'id':stem+'/collision','kind':'rule','contract':'projectile.collision','implementation':{'type':'provider','provider':'model.projectile.collision'}}]
 p['projectiles']=[{'id':proj,'kind':'projectile','motion':{'rule':stem+'/trajectory','parameters':{'mode':'stationary'}},'collision':{'rule':stem+'/collision','parameters':{'enabled':False,'radius':0}},'lifetime_seconds':raw['_lifeTime'],'max_hits':raw['_maxHitNum'],'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'cancel','target_hidden':'cancel','finish_on_reach':False,'hit_on_reach':False,'force_reach_on_expire':False,'hit_on_expire':True},'on_invalid':[],'metadata':{'policy':'No nativeMover component/0.5lifetime/alwaysHitTraceTargetEnd1: fixedexpiry delivery reference, no inferredspeed. _alwaysReachInEnd0 preserved byforceReachfalse'}}]
 spear=skills['throwspear[Rage]'];scale=next(x['value'] for x in spear['blackboard'] if x['key']=='atk_scale')
 p['abilities'].append({'id':SPEAR,'kind':'ability','selector':sid,'target_capture':'at_cast','initial_cooldown_seconds':spear['initCooldown'],'cooldown_seconds':spear['cooldown'],'duration_seconds':103/30,'rules':{'ability.windup':stem+'/windup','ability.duration':stem+'/duration','targeting.score':score,'targeting.selection':order},'activation':{'mode':'manual','parameters':{'auto_only':True,'auto_when_ready':True,'requires_targets':True}},'timeline':[{'at_seconds':51/30,'effect':{'op':'damage','damage_type':'physical','scale':scale,'projectile_definition':proj,'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}}]})
 icfg=cs['-2297633667575125814']['raw'];mid='rule/'+UID+'/immo_members';iparams=json.loads(json.dumps(template['parameters']));iparams['source_configuration']=icfg
 p['rules'].append({'id':mid,'kind':'rule','contract':'area.members','dependencies':[base],'parameters':{'radius':1.75,'eligibility':{'rule':base,'parameters':iparams}},'implementation':{'type':'provider','provider':'model.area.qualified_radius'}})
 im=skills['Immo[Rage]'];iscale=next(x['value'] for x in im['blackboard'] if x['key']=='atk_scale')
 p['abilities'] += [{'id':IMMO,'kind':'ability','cooldown_seconds':0,'activation':{'mode':'manual','parameters':{'auto_only':True,'blocks_attacks':False}},'timeline':[{'at':0,'effect':{'op':'area','target':'source','center':'source','membership_rule':mid,'filters':[{'tag':'player'}],'effects':[{'op':'damage','damage_type':'true','scale':iscale,'damage_flags':{'source_attack_type':'SPLASH','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}]}}]},{'id':NAT,'kind':'ability','initial_cooldown_seconds':im['initCooldown'],'cooldown_seconds':im['cooldown'],'activation':{'mode':'manual','parameters':{'auto_only':True}},'timeline':[{'at':0,'effect':{'op':'trigger_ability','target':'source','ability':IMMO}}]}]
 p['buffs'].append({'id':TIMER,'kind':'buff','interval_seconds':.8,'effects':[{'op':'trigger_ability','target':'source','ability':IMMO}]})
 c=p['entities'][0]['components'];c['abilities'] += [SPEAR,IMMO,NAT];c['ability_arbitration']['entries'] += [{'ability':SPEAR,'priority':0,'attack_clock':False,'require_attack_control':False,'condition':"'rebirth' in inputs.runtime and inputs.runtime.rebirth.count == 1",'parameters':{}},{'ability':IMMO,'priority':0,'attack_clock':False,'require_attack_control':False,'condition':'False','parameters':{}},{'ability':NAT,'priority':0,'attack_clock':False,'require_attack_control':False,'condition':'True','parameters':{}}];c['rebirth']['reset_cooldowns']=[{'ability':SPEAR,'initial_delay_seconds':15}];c['rebirth']['on_finish'].append({'op':'apply_buff','target':'source','buff':TIMER})
 meta=p['manifest']['metadata'];meta['builder_sha256']=sha(Path(__file__));meta['policy_provider_sha256']=sha(ROOT/'tools/chapter07_boss/policies_v1.py');meta['reference_policies'].update({'spear_sort':'NativePostFilter25 currentenum HATRED_DES_DIST_FARTHER_FIRST; exacteffectiveHATE DESC thenfarthest thenstableID, no scalarpriorityconstants','spear_clock':'EnemySkill15init/20fromfinish resetuponRage attach reference; Immo natural9999 separatefrom action0','spear_projectile':'Native0.5seconds noMover, fixedexpiry payload; retainSource/targetcancel fromsourceflags, no invented speed'});meta['status']='quarantined_partial_with_alive_immo_and_spear';meta['unconsumed_required_mechanisms']=[x for x in meta['unconsumed_required_mechanisms'] if not x.startswith('Spear15') and not x.startswith('Rage Immo')];p['manifest']['id']='package/ch7/patrt/partial_mechanism_v4';path=OUT/'mechanism.v4.json';path.write_bytes((json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'sha256':sha(path),'stage_export_allowed':False}))
if __name__=='__main__':main()
