"""Quarantined Patriot core-mechanism probe; pending source systems explicit."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'packages/campaign/chapter07_boss/patrt'
UID='unit/ch7/patrt/a53a85a6d0cd714f'
N=[f'ability/{UID}/normal{i}' for i in (0,1)]
MARKER='buff/ch7/source/enemy_9D0_talent_strength'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def provider(id,contract,name):return {'id':id,'kind':'rule','contract':contract,'implementation':{'type':'provider','provider':name}}
def build():
 s=json.loads((OUT/'source.closure.json').read_bytes());v=s['variant'];db=v['native_enemy']['resolved'];a=db['attributes'];cs=s['prefab']['components'];bb={x['key']:x['value'] for x in db['talentBlackboard']};stem='rule/'+UID;shield='buff/'+UID+'/shield';taunt='buff/'+UID+'/taunt';rage='buff/'+UID+'/rage';sleep='buff/'+UID+'/sleep';ore='buff/ch7/source/ore_immune';inv='buff/'+UID+'/invulnerable';child='buff/'+UID+'/strength';parents=['buff/'+UID+'/strength_parent','buff/'+UID+'/marker_parent']
 pending=['ReleaseWave literalfinish_current_wave','GlobalAura retainwhiletrueHP0reborning (requiredcounter)','Reborning ownedImmo_Rage .8s sourceattributed trueDamage despiteinactiveowner/9999naturalclock','Rage Immo tick .8s/.0521 sourceBufftriggering','Spear15/20/highground-farthest1.35/projectile_spear','Ore/Mine fullsourceintegration; oreimmune markeronly quarantined']
 p={'schemaVersion':2,'manifest':{'id':'package/ch7/patrt/mechanism_probe_v1','requires':['preset/ark_standard'],'metadata':{'status':'mechanism_probe_only_not_complete_enemy','stage_export_allowed':False,'native_variant_id':v['variant_id'],'source_locks':{str((OUT/'source.closure.json').relative_to(ROOT)):sha(OUT/'source.closure.json')},'builder_sha256':sha(Path(__file__)),'unconsumed_required_mechanisms':pending,'reference_policies':s['reference_policies'],'aura_self_policy':'DEFAULT0 followseligibleally/self; referenceincludesSelf, rawsourceunchanged','aura_waiting_policy':'GlobalAura mustpersistduringtrueHP0waiting perdeclaredreference, genericparentsrepresentownedemitters; expectedgap retainedforcounter notsilentpass','native_reborn_retained_buffs':[],'typed_selector_envelope':'Mode0 rawselectorNULL preserved; exactmode1 config usedonlytypedcontract envelope, block_input rule solely actualblockedby identity. Validator missing switches envelope defaults borrowedmode1/rawtargetOptions override, notnativephase0 selectorclaim','generic_parent_storage_note':'Onlyvirtualemitterparents inretain_buffs; no nativegameBuffgrant/HPshortcut. Currentgeneric removes them anywaywhenownerinactive.','complete_source_policies':False,'independent_reviewed':False,'whole_stage_executed':False,'client_verified':False}},'entities':[],'rules':[],'buffs':[],'abilities':[],'selectors':[]}
 p['rules']=[provider(stem+'/eligibility','targeting.eligibility','model.targeting.eligibility'),{'id':stem+'/block_input','kind':'calculation_rule','contract':'targeting.eligibility','implementation':{'type':'expression','expression':"{'accepted':'blocked_by' in inputs.source.components.runtime and inputs.source.components.runtime.blocked_by == inputs.candidate.id,'reason':'nativeINPUT_TARGET2'}"}},{'id':stem+'/windup','kind':'calculation_rule','contract':'ability.windup','parameters':{'minimum_speed':.01},'implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio, params.minimum_speed)'}},{'id':stem+'/duration','kind':'calculation_rule','contract':'ability.duration','parameters':{'minimum_speed':.01},'implementation':{'type':'expression','expression':'inputs.duration_parameters.seconds / max(inputs.attributes.attack_speed_ratio, params.minimum_speed)'}},{'id':stem+'/restore','kind':'rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.parameters.capacity * inputs.parameters.ratio'}},{'id':stem+'/invul','kind':'rule','contract':'damage.pipeline','implementation':{'type':'graph','nodes':[{'id':'result','expression':"{'accepted':False,'amount':0,'allocations':[],'events':[]}"}],'output':'nodes.result'}}]
 p['buffs']=[{'id':shield,'kind':'buff','modifiers':[{'attribute':'atk','layer':'direct_ratio','value':bb['shield.atk']},{'attribute':'def','layer':'direct_ratio','value':bb['shield.def']},{'attribute':'mres','layer':'direct_ratio','value':bb['shield.magic_resistance']}]},{'id':taunt,'kind':'buff','modifiers':[{'attribute':'taunt_level','layer':'direct_add','value':bb['taunt.taunt_level']}]},{'id':rage,'kind':'buff','modifiers':[{'attribute':'atk','layer':'direct_ratio','value':bb['immo_trigger[rage].atk']},{'attribute':'def','layer':'direct_add','value':bb['immo_trigger[rage].def']},{'attribute':'move_speed','layer':'direct_add','value':bb['immo_trigger[rage].move_speed']},{'attribute':'attack_interval','layer':'direct_add','value':bb['immo_trigger[rage].base_attack_time']}],'selection_flags':{'abnormal_immunes':[0,12,16,25],'abnormal_combo_immunes':[0]}},{'id':sleep,'kind':'buff','selection_flags':{'abnormal_combo_immunes':[0]}},{'id':ore,'kind':'buff','metadata':{'native_empty_marker':'ore_immune','semantic_consumer':'ore_s CheckContainsBuff/IfNot externalrequired'}},{'id':inv,'kind':'buff','duration_seconds':bb['reborn.patrt_t_state_2[reborn_invincible].duration'],'selection_flags':{'abnormal_flags':[5]},'damage_hooks':[{'phase':'after','rule':stem+'/invul'}]},{'id':child,'kind':'buff','stacking':{'mode':'refresh','max_stacks':1,'identity':['definition','target']},'modifiers':[{'attribute':'atk','layer':'direct_ratio','value':bb['strength.atk']},{'attribute':'def','layer':'direct_add','value':bb['strength.def']}]},{'id':MARKER,'kind':'buff','metadata':{'source_role':'External source marker identity; emitter separate, no invented stat buff'}}]
 aura='selector/'+UID+'/allies'
 opts=cs['-2255859223802550070']['raw']['_targetOptions'];cfg=dict(cs['-2374019846914774838']['raw']);cfg.update({('_'+k):v for k,v in opts.items()});cfg['_postFilter']=0
 p['selectors'].append({'id':aura,'kind':'selector','region':{'type':'all'},'filters':[{'tag':'enemy'},{'state':'alive'}],'limit':None,'eligibility':{'rule':stem+'/eligibility','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':{'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False,'abnormal_immunes':[]}}}})
 for parent,childid in zip(parents,[child,MARKER]):p['buffs'].append({'id':parent,'kind':'buff','aura':{'selector':aura,'buff':childid},'metadata':{'nativeGlobalAuraDEFAULT':0,'reference_owner_included':True}})
 for mode in [0,1]:
  sid='selector/'+UID+'/normal'+str(mode);frames=[19,22,25,28] if mode==0 else [16];full=45 if mode==0 else 41
  p['selectors'].append({'id':sid,'kind':'selector','region':{'type':'all' if mode==0 else 'radius',**({} if mode==0 else {'radius':.8500000238418579})},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,**({'eligibility':{'rule':stem+'/block_input','parameters':{'source_configuration':cs['-2374019846914774838']['raw'],'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':{'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False,'abnormal_immunes':[]}}}} if mode==0 else {})})
  p['abilities'].append({'id':N[mode],'kind':'ability','selector':sid,'target_capture':'at_cast','duration_seconds':full/30,'rules':{'ability.windup':stem+'/windup','ability.duration':stem+'/duration'},'activation':{'mode':'automatic_attack','settle_blocking':True,'parameters':{'auto_only':True}},'timeline':[{'at_seconds':f/30,'effect':{'op':'damage','damage_type':'physical','scale':1,'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}} for f in frames]})
 reb=next(c['raw'] for c in v['passive_and_skill_components'] if c['class']=='RebornTalent');root=cs[v['root_path_id']]['raw']
 p['entities']=[{'id':UID,'kind':'entity','tags':['enemy','ground','boss','patriot_source'],'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':root['_blockVolume'],'taunt_level':0}},'resources':{'hp':{'initial':a['maxHp'],'capacity_attribute':'max_hp','role':'health'}},'selection_state':{'side':1,'motion':1,'category':1,'unit_type':1,'abnormal_immunes':[12]},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':db['lifePointReduce']},'buffs':{'initial':[shield,taunt,sleep,ore,*parents]},'abilities':N,'ability_arbitration':{'priority_order':'higher_first','busy':'all_casts','entries':[{'ability':N[i],'priority':0,'attack_clock':True,'require_attack_control':True,'condition':"('rebirth' not in inputs.runtime or inputs.runtime.rebirth.count == 0)" if i==0 else "'rebirth' in inputs.runtime and inputs.runtime.rebirth.count == 1",'parameters':{}} for i in [0,1]]},'rebirth':{'resource':'hp','max_count':reb['_maxRespawnCnt'],'delay_seconds':bb['reborn.duration'],'restore_ratio':reb['_hpRechargeRatio'],'restore_rule':stem+'/restore','retain_buffs':parents,'reset_attack_clock':True,'on_begin':[{'op':'apply_buff','target':'source','buff':x} for x in parents],'on_finish':[{'op':'apply_buff','target':'source','buff':x} for x in [rage,inv,sleep,ore,*parents]]}}}]
 return p
if __name__=='__main__':
 path=OUT/'mechanism.v1.json';path.write_bytes((json.dumps(build(),ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'sha256':sha(path),'stage_export_allowed':False}))
