"""Exact owned Reborning action on finite generic waiting timer lease."""
from pathlib import Path
import json
from tools.chapter07_boss.build_mechanism_v1 import OUT,UID,sha
IMMO='ability/'+UID+'/immo_action';NAT='ability/'+UID+'/immo_natural';TIMER='buff/'+UID+'/reborning_timer';STATS='buff/'+UID+'/reborning_stats'
def main():
 p=json.loads((OUT/'mechanism.v3.json').read_bytes());s=json.loads((OUT/'source.closure.json').read_bytes());cs=s['prefab']['components'];stem='rule/'+UID;cfg=cs['-2297633667575125814']['raw'];template=json.loads(json.dumps(next(x['eligibility'] for x in p['selectors'] if x['id'].endswith('/allies'))));template['parameters']['source_configuration']=cfg;member=stem+'/waiting_immo_members'
 p['rules'].append({'id':member,'kind':'rule','contract':'area.members','dependencies':[stem+'/eligibility'],'parameters':{'radius':1.75,'eligibility':template},'implementation':{'type':'provider','provider':'model.area.qualified_radius'}})
 p['abilities'] += [{'id':IMMO,'kind':'ability','cooldown_seconds':0,'duration_seconds':0,'activation':{'mode':'manual','parameters':{'auto_only':True,'blocks_attacks':False}},'timeline':[{'at':0,'effect':{'op':'area','target':'source','center':'source','membership_rule':member,'filters':[{'tag':'player'}],'effects':[{'op':'damage','damage_type':'true','scale':.0521,'damage_flags':{'source_attack_type':'SPLASH','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}]}}]},{'id':NAT,'kind':'ability','initial_cooldown_seconds':9999,'cooldown_seconds':9999,'activation':{'mode':'manual','parameters':{'auto_only':True}},'timeline':[{'at':0,'effect':{'op':'trigger_ability','target':'source','ability':IMMO}}]}]
 p['buffs'] += [{'id':STATS,'kind':'buff','modifiers':[{'attribute':'atk','layer':'direct_ratio','value':.2},{'attribute':'def','layer':'flat','value':200}]},{'id':TIMER,'kind':'buff','duration_seconds':60,'interval_seconds':.8,'removal':{'on_source_death':'retain','on_target_death':'retain'},'effects':[{'op':'trigger_ability','target':'source','ability':IMMO}]}]
 c=p['entities'][0]['components'];c['abilities'] += [IMMO,NAT];c['ability_arbitration']['entries'] += [{'ability':x,'priority':0,'attack_clock':False,'require_attack_control':False,'condition':'False','parameters':{}} for x in [IMMO,NAT]];c['rebirth']['retain_buffs'].append(TIMER);c['rebirth']['waiting_actions']={'abilities':[IMMO],'buffs':[TIMER]};c['rebirth']['on_begin'] += [{'op':'apply_buff','target':'source','buff':x} for x in [STATS,TIMER]];c['rebirth']['on_finish'].append({'op':'remove_buff','target':'source','buff':STATS})
 meta=p['manifest']['metadata'];meta['builder_sha256']=sha(Path(__file__));meta['status']='waiting_owned_action_source_probe_with_sharedAura_pending';meta['waiting_action_source']='NativeReborning ActiveBuffduration60/tick.8 BBability_nameImmo_Rage, rawactionCD0/timeMode2/ignoreDead1; separate natural9999. Virtualtimer retainedonlywithinactualwait, no nativegame retainedBuffclaim.';meta['unconsumed_required_mechanisms']=[x for x in meta['unconsumed_required_mechanisms'] if not x.startswith('Reborning ownedImmo')];meta['sharedAura_waiting_atk_note']='Actualsingleemitter partialkernel loses Aura inwaiting; sourceReborning+.2 gives1920. Fullsource2240 expectedonlyafterSourceAura continuity compose; no false112% policy';p['manifest']['id']='package/ch7/patrt/waiting_owned_action_probe_v1';path=OUT/'waiting.mechanism.v1.json';path.write_bytes((json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'sha256':sha(path),'stage_export_allowed':False}))
if __name__=='__main__':main()
