"""Final author inventory; preserve every proof's executed content/core identity."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'packages/campaign/chapter07_boss/patrt'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 groups={
  'source_and_content':['source.closure.json','source.consumer.v1.json','source.consumer.v1.notes.md','releasewave.mechanism.v1.json','release_wave.requirements.json','waiting.action.requirements.json'],
  'new_identity_exact_public_events':['source_bound_v2/report.json','source_bound_v2/waiting36.checkpoint.json','source_bound_v2/replay.json','source_bound_v2/observations.json'],
  'same_boss_ore_mine_joint':['ore_mine_joint_v4/report.json','ore_mine_joint_v4/input.json','ore_mine_joint_v4/reborn1806.checkpoint.json','ore_mine_joint_v4/replay.json','ore_mine_joint_v4/events.json'],
  'preserved_source_parent_receipts':['combined.source.v2.tests.json','releasewave.v2.tests.json','releasewave.supported.summary.json','spear.delivery.pins.json','waiting.delivery.pins.json','mechanism_evidence_v1/author.evidence.json'],
  'preserved_author_failures':['ore_mine_joint_v1/report.json','ore_mine_joint_v2/report.json','ore_mine_joint_v3/terrain.fixture.failure.json','ore_mine_joint_v3/cancelled.longrun.json','source_bound_v1/diagnostic.scope.note.json']}
 paths=[OUT/n for ns in groups.values() for n in ns]
 paths += [ROOT/'tools/chapter07_boss'/n for n in ['build_source_consumer_v1.py','verify_source_bound_v2.py','verify_ore_mine_joint_v4.py','verify_terrain_fixture_v1.py','freeze_source_final_v1.py','policies_v1.py','policies_v2.py']]
 joint=json.loads((OUT/'ore_mine_joint_v4/report.json').read_bytes());bound=json.loads((OUT/'source_bound_v2/report.json').read_bytes())
 assert joint['status']=='passed' and joint['guards_equal'] and joint['cp_equal'] and joint['head_equal'] and bound['status']=='passed'
 report={'schema':'ark-sim/patrt-final-author-source-inventory/v1','final_module':str(OUT/'source.consumer.v1.json'),'final_module_sha256':sha(OUT/'source.consumer.v1.json'),'variant':'enemy_1506_patrt@0/a53a85a6d0cd714f','parent_preserved':sha(OUT/'releasewave.mechanism.v1.json'),'actual_final_helper_exit':0,'module_definitions_changed_after_parent':False,'new_content_identity_bound':{'runtime':bound['runtime_sha256'],'cp_tick':36,'end_tick':61,'complete_events_compared':True,'current_atk_from_actual_record':2240,'immo':116.704,'guard_scope':'before/after source guards recorded; no diagnostic trace appended'},'joint_source_proof':{'runtime':joint['runtime_sha256'],'cp_tick':1806,'end_tick':1961,'restored_hp':joint['restored_hp'],'cp_equal':True,'head_equal':True,'comparison':'Simulation.snapshot includes all event records; actual original/disk-restored/from-head snapshots equal','mine_tick':1839,'mine_amount':3000,'mine_attack_type':'NORMAL','ore_tick':1916,'ore_amount':750,'ore_attack_type':'NONE','ignore_for_sp':False,'plain_invul_packet_at1806':'rejected','stock':14,'dp':5,'roster_count':12,'cards_count':1,'fixture_overrides':joint['fixtureOverrides']},'support_by_identity':{'phase0_four_hits_and_native_rebirth':'mechanism_evidence_v1 preserved d509 parent identity','high_tile_spear_and_projectile':'spear.delivery.pins preserved af16 / mechanism.v5 identity; not relabeled as a478 execution','waiting_owned_timer':'waiting.delivery.pins preserved4dc5 / waiting.mechanism.v2; joint source_bound_v2 gives real sharedAura2240 and116.704','shared_aura_waiting_typed_gates':'combined.source.v2.tests real4f16/combined1336 parent; source_bound_v2 new23fb identity','releasewave_on_finish_futurebirth_delays':'releasewave.v2.tests real4f16/e79 parent; new23fb short bound proves one real request','ore_mine_source_compatibility':'Actual478 joint with new23fb source definitions and Root pinned ore/mine/ordinary modules'},'metadata_scope':'The immutable module metadata records the pre-joint pending snapshot. This final external author receipt closes its ore/mine integration pending item; stage/control admission and independent review remain separate. No frozen bytes rewritten.','policies':'Explicit minimumASPD.01/timing rounding, self DEFAULT, relative side interpretation, fixed no-mover projectile expiry, source mode-detach timing and Root ore finish/cancel reference policy; native method bodies/client timing not certified','source_spear_new_combined_runtime_direct_retest':False,'independent_reviewed':False,'whole_stage_executed':False,'client_verified':False,'stage_admission_asserted':False,'groups':groups,'pins':{str(p.relative_to(ROOT)):sha(p) for p in paths}}
 path=OUT/'source.final.author.v1.json';assert not path.exists();path.write_bytes((json.dumps(report,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'path':str(path),'sha256':sha(path),'pins':len(paths)}))
if __name__=='__main__':main()
