"""Receipt inventory; never upgrades archived proofs to another identity."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'packages/campaign/chapter07_boss/patrt'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 paths=[OUT/n for n in ['source.closure.json','source.consumer.v1.json','releasewave.mechanism.v1.json','combined.mechanism.v2.json','releasewave.supported.summary.json','combined.source.v2.tests.json','releasewave.v2.tests.json','source_bound_v1/report.json','source_bound_v1/waiting36.checkpoint.json','source_bound_v1/replay.json','source_bound_v1/observations.json','ore_mine_joint_v1/input.json','ore_mine_joint_v1/report.json']]
 paths += [ROOT/'tools/chapter07_boss'/n for n in ['build_source_consumer_v1.py','verify_source_bound_v1.py','verify_ore_mine_joint_v1.py','freeze_source_consumer_v1.py']]
 receipt={'schema':'ark-sim/patrt-source-consumer-author-freeze/v1','source_variant':'enemy_1506_patrt@0/a53a85a6d0cd714f','content_sha256':sha(OUT/'source.consumer.v1.json'),'parent_content_sha256':sha(OUT/'releasewave.mechanism.v1.json'),'runtime_of_new_identity_bound_proof':'4f16ac4c8ec0c0080302dfa1b6b1b6cc4da90d383ae9a2da5f796551d630c346','new_identity_bound_proof_actual':True,'supported_mechanisms':['native phase0 four-hit frames 19/22/25/28','one true 60s rebirth ratio0.8500000238418579 and 15s invulnerability','shared nonstacking Strength/marker Aura at HP0 waiting','actual retained timer Immo currentATK2240*.0521=116.704 with typed target gates','phase1 source-tile/HATE/farthest Spear','literal phase0 ON_BUFF_FINISH finite timeline release','consider_unhurtable strictfalse bypasses only owned invulnerability hook'],'evidence_scope':{'new_identity':'Persistent CP36→61 and from-head equality; source/runtime guards before and after','long_wave_parent':'Original callback/futurebirth/post+pre delay and CP36/299→430 were actually tested under e79 identity; not relabeled as new content execution','ordinary_source_parent':'Earlier fourhit/rebirth/spear identities retain own runtime pins'},'pending':['Ore/mine joint same-source public proof: 4f16 rejects independently declared cards interface; actual required compiler failure saved','Independent author-source review','Whole stage and client comparison'],'fixture_scope':'New-bound controlled hero and planned existing-Myrtle testability are explicit isolated test fixtures, not native fixed12 skill fidelity','whole_stage_executed':False,'client_verified':False,'independent_reviewed':False,'stage_admission_asserted':False,'pins':{str(p.relative_to(ROOT)):sha(p) for p in paths}}
 path=OUT/'source.consumer.v1.freeze.json';assert not path.exists();path.write_bytes((json.dumps(receipt,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'path':str(path),'sha256':sha(path),'pins':len(paths)}))
if __name__=='__main__':main()
