"""Exact BuildableType2 spear gate currently lacks actual tile projection."""
from pathlib import Path
import json,hashlib,sys
ROOT=Path(__file__).resolve().parents[2]
def main():
 sys.path.insert(0,str(ROOT));sys.path.insert(0,str(ROOT.parent/'unpack_work/campaign_content_base_v2_candidate'))
 from ark_sim import Compiler,Engine
 from ark_sim.adapters.api import implementation_digest
 from ark_sim.contracts import thaw
 from tools.chapter07_boss.test_mechanism_v5 import package
 from tools.chapter07_boss.build_mechanism_v1 import OUT,UID
 p=package();s=json.loads((OUT/'source.closure.json').read_bytes());cfg=s['prefab']['components']['1386826373912127690']['raw'];sid='selector/'+UID+'/spear_tile_counter';aid='ability/'+UID+'/spear_tile_counter';rid='rule/'+UID+'/spear_farthest_counter';base=next(x for x in p['selectors'] if x['id'].endswith('/allies'))['eligibility'];base['parameters']['source_configuration']=cfg
 p['selectors'].append({'id':sid,'kind':'selector','region':{'type':'radius','radius':20},'filters':[{'tag':'spear_counter_player'},{'state':'alive'}],'limit':1,'eligibility':base});p['rules'].append({'id':rid,'kind':'rule','contract':'targeting.score','implementation':{'type':'expression','expression':'-inputs.distance'}});p['abilities'].append({'id':aid,'kind':'ability','selector':sid,'rules':{'targeting.score':rid},'activation':{'mode':'manual'},'timeline':[]});p['entities'][0]['components']['abilities'].append(aid);p['entities'][0]['components']['ability_arbitration']['entries'].append({'ability':aid,'priority':0,'attack_clock':False,'require_attack_control':False,'condition':'False','parameters':{}})
 for name,col in [('ground_far',6),('highground_near',4)]:
  p['entities'].append({'id':'unit/test/spear/'+name,'kind':'entity','tags':['player','spear_counter_player'],'components':{'attributes':{'base':{'max_hp':10000,'atk':0,'def':100,'mres':0,'taunt_level':0}},'resources':{'hp':{'initial':10000,'capacity':10000,'role':'health'}},'spatial':{},'selection_state':{'side':0,'motion':1,'category':1,'unit_type':1},'lifecycle':{'policy':'policy/ark_lifecycle'}}});p['scenarioDraft']['initialEntities'].append({'definition':'unit/test/spear/'+name,'instanceAlias':name,'position':{'row':2,'col':col}})
 p['scenarioDraft']['map']['tiles']=[{'buildableType':2 if (r,c)==(2,4) else 1,'passableMask':1} for r in range(5) for c in range(7)]
 folder=OUT/'required_spear_tile_counter';folder.mkdir(exist_ok=True);path=folder/'input.json';path.write_bytes((json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode());sim=Engine.create(Compiler().compile(path),seed=7187);ability=sim.program.definitions[aid];selected=sim.ctx.spatial.select('boss',sid,ability=ability)
 assert selected==[sim.session.world.resolve('ground_far')]
 report={'schema':'ark-sim/patrt-spear-actual-tile-required-counter/v1','core':implementation_digest(),'input_sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'native_selector_buildable_type':cfg['_buildableType'],'native_post_filter':cfg['_postFilter'],'actual_selected_alias':'ground_far','actual_selected_tile':sim.ctx.spatial.grid.tile(2,6),'expected_reference_selected_alias':'highground_near','expected_tile':sim.ctx.spatial.grid.tile(2,4),'required_generic_gap':True,'reason':'Currentpureeligibility context contains source/candidate/selectionstates but no currentcandidate tile; AdvancedSelectorWithBuildableType rawfield ignoredby standardmodel. Actorprofession/deployabletag isnot actualhighground tile.','proposed_generic_plan':'Read-only candidate_spatial_tile facts fromactualproject_cell and terrain-aware grid.tile in puretargeting inputs; optionalcontractextension, no actor/skillID branches. Sourceprovider ANDs actualtilebuildablemask2 with existingtypedeligibility.','scope':'Controlledselector-only counter with equalthreat to isolate actualtilequalification; notSpearphase/cooldown/exacthate ordering proof','events':thaw(tuple(sim.session.events)),'snapshot':sim.snapshot(),'runtime_modified':False,'whole_stage_executed':False};q=folder/'report.json';q.write_bytes((json.dumps(report,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'sha256':hashlib.sha256(q.read_bytes()).hexdigest(),'selected':'ground_far'}))
if __name__=='__main__':main()
