import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
OUT=ROOT/'validation/campaign/chapter08_jt82_input_admission_peer_v1';OUT.mkdir(exist_ok=False)
inputdir=ROOT/'validation/campaign/chapter08_jt82_input_peer_v3';volcanodir=ROOT/'validation/campaign/chapter08_volcano_independent_v1'
r=json.loads((inputdir/'verification.json').read_bytes());v=json.loads((volcanodir/'verification.json').read_bytes());assert r['passed'] is True and r['guards_equal'] and v['guards_equal'] and all(x['outcome']=='passed' for x in v['cases'])
files=[Path(__file__)]+list(inputdir.rglob('*'))+list(volcanodir.rglob('*'))+list((ROOT/'tools/chapter08_source_prepare/peer_review').glob('*.py'))+[ROOT/'tools/chapter08_environment_review/test_volcano_peer.py',ROOT/'tools/chapter08_environment_review/verify_volcano_peer_v1.py']
report={'passed':True,'core':r['core'],'source_input_reference_admitted':True,'complete_source_mechanisms':False,'source_package':r['package_sha'],'life_only_overlay':r['overlay_sha'],'commands':r['commands_sha'],'input_verification_sha':sha(inputdir/'verification.json'),'volcano_independent_sha':sha(volcanodir/'verification.json'),'actual_checks':{'source_variants':5,'native_births':32,'static_public_commands':28,'fixed_roster':12,'slots':9,'initial_dp':10,'native_life':3,'selected_life':99999,'nativeCP':7,'native_head_end':15,'volcano_cases':2,'volcanoCP':199,'volcano_head_end':401},'known_required_gap':r['known_required_gap'],'consumer_proof_scope':{'uterer':'Our independent6/freeze f4ee1be... exactsource stats/damage/ASPD/publicwithdraw+sourcekill/CPhead on3992; new9ad stage source field bindings+CP tested separately. No migration of oldbehavior proof to9ad.','infection':'Our author probe/full299packet300sec separate from Root independent7 c84961.../freeze12d1...; selected same source SHA0ffe995... pinned.','volcano':'New9ad independent2 selected cell+orthogonalcombat reference and currenthook500/currentCAMO17, realorderedCP199/head. Author6cells/random8..12/sourceflags7 c463... remains author proof separate.','uoffcr/empace/emppnt':'Actual compiled definitions/source stats and live required providers checked in new9ad input closure. Mechanism proofs authored/independently reviewed by their own assigned agents; this report does not independently approve all their native selector/listener details.','Talula':'All8 two-mode attack/combat/four source-derived skills present and keyed stageoverride retained, source50000baseHP, fixed rawroute. Parent extinction/reignite/dynamic resistance interpretation remains explicit reference; remaining-lifetime changes required in nextversion. No complete Boss/nativebody approval.'},'scope':'Read-only source input admission under declared executable reference profiles. Native map palette/top-down grid, route coordinate transformation/full checkpoints, originalactions/rawrunes/predefines/hardempty/unusedbranch preserved, exactfixed12/source stat mapping, onlylife overlay, static skill/terrain binding, activebranch/hardpayload negative rejection, nativeCP7/head15. Main/livewhole/registry unchanged. Not whole validation, client comparison, allnumeric/allsourcefields or actualall12 deployment coverage.','guards_start':r['guards_start'],'guards_end':r['guards_end'],'guards_equal':True,'artifact_pins':{str(p):sha(p) for p in files if p.is_file()},'fixture_history':'v1 map fixture compared raw native enum tile objects and reversed alreadytop-down grid; preserved failure. v2 reached all assertions+CP equality then JSON failed FrozenMapping capture; v3 only correct thaw serialization. Oldtool/output dirs retained.'}
(OUT/'freeze.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8');print(sha(OUT/'freeze.json'))
