import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();OUT=ROOT/'validation/campaign/chapter08_jt82_input_admission_peer_v2';OUT.mkdir(exist_ok=False)
DIR=ROOT/'validation/campaign/chapter08_jt82_input_peer_v4';r=json.loads((DIR/'verification.json').read_bytes());source=ROOT/'validation/campaign/chapter08_dynamic_burn_independent_v4/freeze.json';generic=ROOT/'validation/campaign/chapter08_buff_lifetime_independent_joint_v2/freeze.json'
assert r['passed'] is True and r['guards_equal'] and r['previous_dynamic_remaining_gap_closed'] and r['all_five_actor_definitions_unchanged'] and r['package_sha']=='f94e1d9fa30b2d12ddf686aeb84d68c9e9c2c28af48621f9ffe2338476f93a54'
assert r['overlay_sha']=='0ef8d6224a0f984ea13128008430c3f30d6aa934ff4c47fc893b008eef371982'
files=list(DIR.rglob('*'))+[source,generic,Path(__file__),ROOT/'tools/chapter08_source_prepare/peer_review/audit_jt82_v4.py']
report={'passed':True,'core':r['core'],'input_sha':r['package_sha'],'overlay_sha':r['overlay_sha'],'same28commands_sha':r['commands_sha'],'verification_sha':sha(DIR/'verification.json'),'source_input_reference_admitted':True,'all_selected_runtime_consumers_present':True,'confirmed_required_unsupported_fields':[],'complete_native_semantics':False,'whole_approved':False,'source_sourceclock_freeze':sha(source),'generic26_freeze':sha(generic),'old9ad_input_freeze':'4c74235557e630b2753e438df6ace90ff08c65eed2eff6ae651d6a2fdfaa968b','scope':'Independent exactnew7e76 packagef94e+onlylife0ef8+same28commands staticadmission, five sourcevariant DBfields+referenceddefinitions/rawmap/routes/actions/runes/predefs/unusedbranch/emptyhardprofile and fixed12 actualdefinitions checked; short actualnativeCP7->15 SHAreload/head wholecheckpoint equality. Source_dynamic_remaining missingfield fromoldinput is now implemented, independently checked7 actualnewsourcecases plus generic26. No newwhole, old9ad35050 remains untouched. Allfiveactor definitions byteequivalent data toold9ad stage; otherfour mechanism evidence remains oldercore scope, not migrated. Currentcompile/closure/newprefix verify their support undercurrentreference profile. Root owncurrentfull/baseline remains separate prerequisite.','policy_limits':r['remaining_limits'],'guards_start':r['guards_start'],'guards_end':r['guards_end'],'guards_equal':True,'changed_definition_ids_vs_old9ad_input':r['changed_definition_ids_vs_old9ad_input'],'artifact_pins':{str(p):sha(p) for p in files if p.is_file()}}
(OUT/'freeze.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8');print(sha(OUT/'freeze.json'))
