"""Read-only static 9-19 admission matrix, no engine or author fixture execution."""
from pathlib import Path
import json,hashlib,ast
from collections import Counter
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter09_stage919_matrix';SRC=ROOT/'packages/campaign/chapter09_source_prepare/source.plan.v1.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def pin(path):
 p=ROOT/path;return {'path':path,'sha256':sha(p)}
def receipt(path):
 p=ROOT/path
 if not p.exists():return {'path':path,'available':False}
 d=json.loads(p.read_bytes());r={'path':path,'sha256':sha(p),'available':True}
 for k in ['core','core_before','core_after','actual_exit','status','unique_cases','unique_independent_cases','effective_valid_gates','distinct_successful_gates','distinct_valid_successful_gates']:
  if k in d:r[k]=d[k]
 if isinstance(d.get('results'),list):r['cases']=[{'name':x.get('case'),'passed':x.get('passed')} for x in d['results']]
 return r
s=json.loads(SRC.read_bytes());row=s['stages']['level_main_09-17'];native=row['native_document'];counts=Counter(a['key'] for w in native['waves'] for f in w['fragments'] for a in f['actions'] if a['actionType']=='SPAWN' for _ in range(a['count']));variants=[]
paths={'enemy_1165_duhond':'ordinary/enemy_1165_duhond.module.v1.json','enemy_1166_dusbr':'ordinary/enemy_1166_dusbr.module.v1.json','enemy_1167_dubow':'ordinary/enemy_1167_dubow.module.v1.json','enemy_1170_dushld':'more_ordinary/enemy_1170_dushld.module.v1.json','enemy_1168_dumage':'more_ordinary/enemy_1168_dumage.module.v1.json'}
legacy_receipts={'enemy_1165_duhond':['validation/campaign/chapter09_ordinary_independent_final/freeze.json'],'enemy_1166_dusbr':['validation/campaign/chapter09_ordinary_independent_final/freeze.json'],'enemy_1167_dubow':['validation/campaign/chapter09_dubow_independent_final/freeze.json'],'enemy_1170_dushld':[],'enemy_1168_dumage':[]}
for vid in row['variant_ids']:
 raw=s['variants'][vid];key=raw['native_reference']['id'];item={'variant':vid,'native_reference':raw['native_reference'],'native_resolved_attributes':raw['native_enemy']['resolved']['attributes'],'native_spawn_count':counts[key],'source_variant_sha256':hashlib.sha256(json.dumps(raw,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest(),'profiles':[],'full_stage_executed':False}
 if key in paths:
  rel='packages/campaign/chapter09_consumers/'+paths[key];p=ROOT/rel;m=json.loads(p.read_bytes());meta=m['manifest']['metadata'];item['profiles'].append({'module':pin(rel),'name':'source_module_v1','required_author_core':meta.get('required_runtime'),'native_reference':meta.get('native_reference'),'reference_policy':meta.get('reference_policy'),'available_gate_receipts':[receipt(x) for x in legacy_receipts[key]],'fresh_combined_core_gate_required':True,'whole_module_or_stage_admission_not_inferred':True})
 elif key in ['enemy_1171_durokt','enemy_1172_dugago']:
  for profile in ['native_literal','prts_reference']:
   rel='packages/campaign/chapter09_consumers/rock_modes_v2/'+key+'.'+profile+'.json';p=ROOT/rel;m=json.loads(p.read_bytes());entry={'module':pin(rel),'name':profile,'source_policy':m['manifest']['metadata']['reference_policy'],'candidate_core':'ed5ad49acb134bf00b90b758d7cad0e95f4ec20125f70765ed591f90fef58af4','freeze':receipt('validation/campaign/chapter09_rock_modes_v2/freeze.v2.json'),'independent_gate':receipt('validation/campaign/chapter09_rock_modes_peer/peer.result.v2.json'),'fresh_combined_core_full_not_available':True,'pending':m['manifest']['metadata'].get('pending',[])}
   if key=='enemy_1172_dugago':
    rr='packages/campaign/chapter09_consumers/receiver_hooks_v2/dugago.'+profile+'.json';rmod=json.loads((ROOT/rr).read_bytes());entry['latest_receiving_module']=pin(rr);entry['latest_receiving_policy']=rmod['manifest']['metadata']['reference_policy'];entry['receiving_candidate_core']='77049fb9724675de47f4fb8bb72e5696b64f4737156acf513f1b7963015d9050';entry['receiving_independent_gate']=receipt('validation/campaign/chapter09_receiver_hooks_peer/peer.result.v2.json');entry['profile_ratio']=rmod['entities'][0]['components']['rebirth']['restore_ratio'];entry['native_same_modifier_mark_not_lingering_PRST1s']=True
   item['profiles'].append(entry)
 else:
  assert key=='enemy_1523_mandra';build=ROOT/'tools/chapter09_mandra_v1/build.py';tree=ast.parse(build.read_text(encoding='utf8'));profiles=next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='PROFILE' for t in n.targets));item['profiles']=[{'name':name,'source_prefix_policy':cfg,'builder':pin('tools/chapter09_mandra_v1/build.py'),'requirements':pin('packages/campaign/chapter09_consumers/mandra/consumer.requirements.v1.json'),'token047_source':pin('packages/campaign/chapter09_consumers/mandra/source.token047.v1.json'),'exported_frozen_module_available':False,'candidate_directory':str(ROOT.parent/'unpack_work/campaign_c9_mandra_v1_candidate'),'catalog':108,'status':'draft; latest author receipts must freeze with exact core before independent review','author_receipts':[receipt('validation/campaign/chapter09_mandra_v1/primitive.progress.v1.json'),receipt('validation/campaign/chapter09_mandra_v1/author.content.v3.json'),receipt('validation/campaign/chapter09_mandra_v1/author.content.v4.json')],'fresh_independent_full_source_and_protocol_required':True,'combined_core_full_passed':False} for name,cfg in profiles.items()]
 variants.append(item)
assert len(variants)==8 and sum(counts.values())==63
pre=native['predefines'];assert len(pre['tokenInsts'])==6 and len(pre['tokenCards'])==1 and pre['tokenCards'][0]['initialCnt']==1
native_map=native['mapData'];blackboards=[{'row':r,'col':c,'native_palette_index':index,'tileKey':native_map['tiles'][index]['tileKey'],'blackboard':native_map['tiles'][index]['blackboard']} for r,line in enumerate(native_map['map']) for c,index in enumerate(line) if native_map['tiles'][index]['blackboard']]
result={'schema':'ark-sim/independent-c9-919-admission-matrix/v1','static_only':True,'no_engine_simulation':True,'source':pin(str(SRC.relative_to(ROOT)).replace('\\','/')),'stage':'level_main_09-17','display_stage':'9-19','native_births':63,'native_routes':35,'variants':variants,'native_stage_options':native['options'],'native_predefines':pre,'hard_predefines_exact':native['hardPredefines'],'native_pillars':6,'native_demolition_stock':1,'native_map_blackboards':blackboards,'native_road_infection_consumer':{'field_definition':'unit/ch8/environment/infection_field','module':pin('packages/campaign/chapter08_consumers/environment/infection.module.v3.json'),'map_builder':pin('tools/chapter09_pillar_v1/build_map_profile.py'),'providers':pin('tools/chapter08_environment/policies_v1.py'),'source_operand':{'damage':180.0,'duration':300.0,'atk':0.5,'attack_speed':50.0},'already_implemented':True,'fresh_combined_core_actual_CP_gate_required':True},'latest_devices':[pin('packages/campaign/chapter09_consumers/ruin/module.v2.json'),pin('packages/campaign/chapter09_consumers/demolition/level_main_09-17.module.v2.json'),pin('packages/campaign/chapter09_consumers/pillar_lifecycle_v1/module.v1.json')],'admission':{'current2c38_full_generic_pass_does_not_supply_rock_route_receiver_or_mandra108':True,'must_assemble_latest_source_deltas_and_108_catalog_in_new_candidate':True,'no_silent_fallback_to_2c38_older_rock_or_empty_boss':True,'required_gates':['mechanical merge identity and original107 preserved plus108 exact newcontract','fresh source/protocol independent Mandra freeze','latest route-mode/receiving marker tests on combined candidate','scenario-owned ruin radius/blockstatus dispatcher and actual blockedTarget obstacle path','complete final status_definitions Buff closure','native road infection operand field and exact6pillar/stock1 registration','combined candidate full generic/baseline before whole','fresh source exactstage input and publicfixed12 commands CPP/head']},'whole_stage':False,'all_source_consumers_complete':False};OUT.mkdir(parents=True,exist_ok=True);path=OUT/'matrix.v1.json';path.write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf8');print(json.dumps({'variants':8,'births':63,'routes':35,'pillars':6,'stock':1,'matrix_sha':sha(path)}))
