import sys,json,hashlib
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RUNTIME=ROOT.parent/'unpack_work/campaign_campaign_foundation_v5_candidate';sys.path.insert(0,str(RUNTIME));sys.path.append(str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from tools.campaign_content_composition_v2 import compose_modules
from tools.chapter08_bsnake_combat.policies_v1 import providers as combat
from tools.chapter08_bsnake_skills.policies_v1 import providers as skills
from tools.chapter08_bsnake.screen_policy_v1 import providers as screen
from tools.chapter08_joint_v4.build_summon_hint_v2 import providers as hint
ROOT=Path(__file__).resolve().parents[2];CORE='82db6a9db5ddd3a4c3c58f05b04e773419312ae77d5fc086fbb98a7a984bf8ae';OUT=ROOT/'validation/campaign/chapter08_bsnake_full_input_v1';OUT.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def providers():return {**combat(),**skills(),**screen(),**hint()}
BOSS=ROOT/'packages/campaign/chapter08_consumers/bsnake/four_modes.wave_source.v5.json';FLAME=ROOT/'packages/campaign/chapter08_consumers/flame/module.v4.joint.json';LOOP=ROOT/'packages/campaign/chapter08_consumers/flame/loop.profile.v3.json';assert sha(BOSS)=='944c66226964c3eac64f6e00295e37839489a12da378377724e34f43cbe67613';assert implementation_digest()==CORE
boss=json.loads(BOSS.read_bytes());flame=json.loads(FLAME.read_bytes());loop=json.loads(LOOP.read_bytes());definitions,_=compose_modules([('bsnake',boss),('flame',flame)]);unit=next(x for x in definitions.values() if x['kind']=='entity' and 'bsnake' in x['id']);initial=deepcopy(loop['initial_entities'])
director='unit/peer/source_director';definitions[director]={'id':director,'kind':'entity','components':{'spatial':{},'abilities':['ability/peer/defeat']}};initial.append({'definition':director,'instanceAlias':'director','position':{'row':0,'col':0}})
for row in range(1,8):
 res=[17,37,53,73,17,37,53][row-1];eid='unit/peer/receiver/'+str(row);definitions[eid]={'id':eid,'kind':'entity','tags':['player','peer_receiver'],'components':{'attributes':{'base':{'max_hp':60000,'atk':0,'def':31,'mres':res}},'resources':{'hp':{'initial':60000,'capacity':60000,'role':'health'}},'selection_state':{'side':0,'motion':1,'category':1,'unit_type':1},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle'}}};initial.append({'definition':eid,'instanceAlias':'receiver'+str(row),'position':{'row':row,'col':4}})
# The public controller exists at11; sourceborn later is identity19 after10devices+controller+7receivers.
boss_ref=19;definitions['ability/peer/defeat']={'id':'ability/peer/defeat','kind':'ability','activation':{'mode':'manual','on_start':[{'op':'instant_kill','target':boss_ref,'parameters':{'cause':'peer_source_defeat','skip_rebirth':False}}]},'timeline':[]}
dummy='unit/peer/nonblocking_birth';definitions[dummy]={'id':dummy,'kind':'entity','components':{'spatial':{},'attributes':{'base':{'max_hp':100,'atk':0}},'resources':{'hp':{'initial':100,'capacity':100,'role':'health'}},'lifecycle':{'policy':'policy/ark_lifecycle'}}}
def spawn(eid,alias,delay,pos,blocks=False):return {'kind':'spawn','count':1,'delay_seconds':delay/30,'interval_seconds':0,'managed':True,'blocks_wave':blocks,'blocks_fragment':False,'spawn':{'definition':eid,'instanceAlias':alias,'position':pos}}
timeline={'policy':'managed_clear','negative_timeout_policy':'wait_for_clear','waves':[{'pre_delay_seconds':17/30,'post_delay_seconds':7/30,'max_wait_seconds':-1,'fragments':[{'pre_delay_seconds':3/30,'actions':[spawn(unit['id'],'boss',17,{'row':4,'col':10},True),spawn(dummy,'late0',90,{'row':0,'col':1})]}]},{'pre_delay_seconds':5/30,'post_delay_seconds':11/30,'max_wait_seconds':-1,'fragments':[{'pre_delay_seconds':9/30,'actions':[spawn(dummy,'late1',4400,{'row':0,'col':2})]}]},{'pre_delay_seconds':7/30,'post_delay_seconds':0,'max_wait_seconds':-1,'fragments':[{'pre_delay_seconds':3/30,'actions':[spawn(dummy,'next2',0,{'row':0,'col':3})]}]}]}
package={'schemaVersion':2,'manifest':{'id':'package/peer/bsnake75k_fullsource','requires':['preset/ark_standard'],'metadata':{'source_locks':{str(x):sha(x) for x in (BOSS,FLAME,LOOP)},'scope':'Controlledsourceproof notnative44stage. Boss50000HP770ATK unmodified, sevenfixedHP60000 recipientcontainers differentRES; real10nativeFlame andloopprofile, threecontrolledwaves. Base99999 policy notneeded no campaignbaseoverride; no fixedroster alterations.'}},'definitions':list(definitions.values()),'scenarioDraft':{'id':'scene/peer/bsnake75k_long','ruleset':'ruleset/ark_standard','seed':884500,'objectives':{},'map':{'rows':9,'cols':15},'initialEntities':initial,'branches':loop['runtime_branch'],'timeline':timeline}}
commands=[{'at':57,'action':'skill','source':'director','ability':'ability/peer/defeat'},{'at':4500,'action':'skill','source':'director','ability':'ability/peer/defeat'}];program=Compiler(providers=providers()).compile(package);(OUT/'input.json').write_text(json.dumps(package,ensure_ascii=False,indent=2),encoding='utf8');(OUT/'commands.json').write_text(json.dumps(commands,indent=2),encoding='utf8');receipt={'passed':True,'actual_compile':True,'core':CORE,'input_sha':sha(OUT/'input.json'),'commands_sha':sha(OUT/'commands.json'),'boss_definition':unit['id'],'boss_expected_ref':boss_ref,'controlled_births':4,'source_flame10':True,'source_loop':True,'expected_source_clock':{'born':37,'first_defeat':57,'first_restore':207,'first_maxHP':75000,'first_HP':75000,'first_ATK':1155,'screen_end':1047,'invincible_end':1497,'summon_ready_no_busy':3297,'second_defeat':4500,'final_start':4650,'final_end':5490,'expected_screen_rays':140},'scope':'Preparedauthor-independent controlledfixture; no Roottestfixtures/expected imported. Nativebodyclock/capture/ray andfirst100percent selectedreference fields explicit; actualrun pending.'};(OUT/'input.freeze.json').write_text(json.dumps(receipt,indent=2),encoding='utf8');print(json.dumps(receipt))
