"""Exact source two-mode sniper with real .25 trigger/revert and target projectile."""
import hashlib,json,sys
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CAND=ROOT.parent/'unpack_work/campaign_finish_timeline_wave_v4_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from ark_sim.domains.selection import DEFAULT_STATE
from tools.chapter07_ranged_consumers.policies_v1 import providers
CORE='4f16ac4c8ec0c0080302dfa1b6b1b6cc4da90d383ae9a2da5f796551d630c346';VID='enemy_1079_sotisp@0/13ad905feaa233c3';MARKER='buff/ch7/source/enemy_9D0_talent_strength';MODE='buff/model/c7/sotisp/mode1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==CORE;source=ROOT/'packages/campaign/chapter07_sources/native.reference.json';plan=ROOT/'packages/campaign/chapter07_consumption_plan/source.consumption.plan.json';markerModule=ROOT/'packages/campaign/chapter07_strength_melee/module.enemy_1078_sotisc.v5.json';d=json.loads(source.read_bytes());v=d['variants'][VID];pf=d['prefabs'][v['prefab_key']];row=next(r for r in json.loads(plan.read_bytes())['exact12_variants'] if r['variant_id']==VID);a=v['native_enemy']['resolved']['attributes'];root=next(c for c in pf['components'].values() if c['native_class']=='Enemy');mover=next(c for c in pf['components'].values() if c['native_class']=='MoveController');uid='unit/ch7/ranged/sotisp/13ad905feaa233c3';behavior='behavior/ch7/ranged/sotisp';p={'schemaVersion':2,'manifest':{'id':'package/ch7/ranged/sotisp/v2','requires':['preset/ark_standard'],'metadata':{'required_runtime':CORE,'source_locks':{str(f):sha(f) for f in (source,plan,markerModule,Path(__file__),Path(__file__).with_name('policies_v1.py'))},'variant_bindings':[{'variant_id':VID,'native_reference':v['native_reference'],'native_resolved':v['native_enemy']['resolved'],'source_modes':v['modes'],'source_passives':v['passive_and_skill_components'],'literal_BSON':row['literal_BSON_templates'],'source_projectile':d['projectiles']['projectile_sotisp']}],'reference_policy':'Exact marker CheckContainsBuff trigger8/revert8 and sourceBB mode1/0 represented private zero-stat mode Buff with real behavior.transition. Normal/enhanced captured targets 1/2, source21frame/75interval, source projectile homing10/life5/retained source/target endpoint hit. Missing method bodies/postfilter4 comparator/ASPD animationclamp/targetfree midflight remain explicit replacement reference, client not verified. Internal mode Buff is controller state, not native extra stat or SP resource.','whole_stage_executed':False,'client_verified':False}},'rules':[],'entities':[],'abilities':[],'selectors':[],'behaviors':[],'buffs':[],'projectiles':[]}
 p['rules']=[{'id':'rule/ch7/ranged/eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':'rule/ch7/ranged/live_taunt','kind':'rule','contract':'targeting.score','implementation':{'type':'provider','provider':'reference.c7.ranged_live_taunt'}},{'id':'rule/ch7/ranged/windup','kind':'rule','contract':'ability.windup','implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio, .01)'}},{'id':'rule/ch7/ranged/steer','kind':'rule','contract':'movement.steering','implementation':{'type':'provider','provider':'ark.movement.steering_velocity'}},{'id':'rule/ch7/ranged/motion','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'model.projectile.trajectory'}},{'id':'rule/ch7/ranged/collision','kind':'rule','contract':'projectile.collision','implementation':{'type':'provider','provider':'model.projectile.collision'}},{'id':'rule/ch7/ranged/behavior','kind':'rule','contract':'behavior.decision','implementation':{'type':'provider','provider':'reference.c7.ranged_mode_behavior'}}]
 abilities=[];selector_ids=[]
 for mode in v['modes']:
  node=mode['nodes']['_combat'];sel=pf['components'][str(node['raw']['_selector']['m_PathID'])]['raw'];sid='selector/ch7/ranged/sotisp/mode'+str(mode['index']);selector_ids.append(sid);aid='ability/ch7/ranged/sotisp/mode'+str(mode['index']);abilities.append(aid);p['selectors'].append({'id':sid,'kind':'selector','region':{'type':'radius','radius':v['native_enemy']['resolved']['rangeRadius']},'filters':[{'tag':'player'},{'state':'alive'}],'limit':sel['_maxNum'],'eligibility':{'rule':'rule/ch7/ranged/eligibility','parameters':{'source_configuration':sel,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':deepcopy(DEFAULT_STATE)}},'metadata':{'native_selector':sel,'postfilter4':'Reference live integer taunt then distance/stable ID; native comparator pending'}});state='enhanced' if mode['index']==1 else 'normal';p['abilities'].append({'id':aid,'kind':'ability','selector':sid,'rules':{'ability.windup':'rule/ch7/ranged/windup','targeting.score':'rule/ch7/ranged/live_taunt'},'activation':{'mode':'automatic_attack','condition':"inputs.source.components.behavior.state == '"+state+"'",'parameters':{'auto_only':True}},'timeline':[{'at_seconds':.7,'effect':{'op':'damage','damage_type':'physical','scale':1,'projectile_definition':'projectile/ch7/sotisp','read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False}}}],'metadata':{'native_RangedAttack':node,'source_OnAttack_frame':21}})
 p['behaviors']=[{'id':behavior,'kind':'behavior','initial':'normal','states':{'normal':{},'enhanced':{}},'transitions':[],'decision':{'rule':'rule/ch7/ranged/behavior','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'mode0','selector':selector_ids[0]},{'key':'mode1','selector':selector_ids[1]}],'cast_groups':[{'key':'normal','abilities':abilities}]}]}}]
 marker=next(b for b in json.loads(markerModule.read_bytes())['buffs'] if b['id']==MARKER);p['buffs']=[marker,{'id':MODE,'kind':'buff','effects':[{'op':'transition','state':'enhanced','condition':'inputs.source.components.runtime.alive'}],'on_remove':[{'op':'transition','state':'normal','condition':'inputs.source.components.runtime.alive'}],'metadata':{'controller_state_only':True}}];parents=[]
 for passive in v['passive_and_skill_components']:
  b=passive['raw']['_buffs'][0];which='start' if b['buffKey']=='sotisp_trigger' else 'finish';assert b['triggerInterval']==.25;assert b['blackboard']==[{'key':'mode','value':1.0 if which=='start' else 0.0,'valueStr':''}];rid='rule/ch7/sotisp/'+which;bid='buff/ch7/source/'+b['buffKey'];parents.append(bid);p['rules'].append({'id':rid,'kind':'rule','contract':'buff.application','implementation':{'type':'provider','provider':'reference.c7.ranged_mode_application'},'parameters':{'marker':MARKER,'mode_buff':MODE,'listener':which}});p['buffs'].append({'id':bid,'kind':'buff','interval_seconds':.25,'effects':[{'op':'buff_application','application_rule':rid,'allowed':[MODE]}],'metadata':{'native_inline':b,'native_BSON':row['literal_BSON_templates'][b['templateKey']]}})
 p['entities']=[{'id':uid,'kind':'entity','tags':['enemy','ground'],'metadata':{'native_variant':VID,'native_reference':v['native_reference']},'components':{'attributes':{'base':{'max_hp':3000,'atk':340,'def':300,'mres':20,'move_speed':.9,'attack_interval':2.5,'attack_speed_ratio':1,'mass_level':1,'block_cost':root['raw']['_blockVolume']}},'resources':{'hp':{'initial':3000,'capacity':3000,'role':'health'}},'selection_state':{**deepcopy(DEFAULT_STATE),'side':1,'motion':1,'category':1,'unit_type':2,'abnormal_immunes':[12]},'spatial':{'steering':{'rule':'rule/ch7/ranged/steer','parameters':{'response_factor':mover['raw']['_steeringFactor'],'max_acceleration':mover['raw']['_maxSteeringForce'],'arrival_radius':.05}}},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':1},'abilities':abilities,'buffs':{'initial':parents},'behavior':{'machine':behavior,'state':'normal'}}}];p['projectiles']=[{'id':'projectile/ch7/sotisp','kind':'projectile','motion':{'rule':'rule/ch7/ranged/motion','parameters':{'mode':'homing','speed':10}},'collision':{'rule':'rule/ch7/ranged/collision','parameters':{'enabled':False}},'lifetime_seconds':5,'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'completion_blocking':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'metadata':{'native_SimpleProjectile':d['projectiles']['projectile_sotisp']}}];fixture=deepcopy(p);fixture['scenarioDraft']={'id':'scene/sotisp/compile','ruleset':'ruleset/ark_standard','map':{'rows':1,'cols':4},'objectives':{},'initialEntities':[{'definition':uid,'instanceAlias':'sniper','position':{'row':0,'col':0}}]};Compiler(providers=providers()).compile(fixture);out=ROOT/'packages/campaign/chapter07_ranged_consumers/sotisp.module.v2.json';out.parent.mkdir(parents=True,exist_ok=True);assert not out.exists();out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(out),'actual_compile':True}))
if __name__=='__main__':main()
