"""Prepared exact mortar consumer; requires explicit new projection candidate pins."""
import argparse,hashlib,json,sys
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[2]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--runtime',required=True);ap.add_argument('--core',required=True);ap.add_argument('--output',required=True);args=ap.parse_args();runtime=Path(args.runtime).resolve();sys.path.insert(0,str(runtime));sys.path.insert(1,str(ROOT))
 from ark_sim import Compiler
 from ark_sim.adapters.api import implementation_digest
 from ark_sim.domains.selection import DEFAULT_STATE
 from ark_sim.domains.providers import BUILTIN_PROVIDERS
 from tools.chapter07_ranged_consumers.policies_v1 import live_taunt_score,strength_application
 from tools.chapter07_ranged_consumers.mortar_box_v2 import mortar_box
 assert implementation_digest()==args.core
 source=ROOT/'packages/campaign/chapter07_sources/native.reference.json';plan=ROOT/'packages/campaign/chapter07_consumption_plan/source.consumption.plan.json';markerModule=ROOT/'packages/campaign/chapter07_strength_melee/module.enemy_1078_sotisc.v5.json';d=json.loads(source.read_bytes());vid='enemy_1082_soticn@0/304d5222d69cf371';v=d['variants'][vid];pf=d['prefabs'][v['prefab_key']];row=next(r for r in json.loads(plan.read_bytes())['exact12_variants'] if r['variant_id']==vid);sel=next(c['raw'] for c in pf['components'].values() if c['native_class']=='AdvancedSelector');hit=next(c['raw'] for c in d['projectiles']['projectile_mortar']['components'].values() if c['native_class']=='HitBehaviour');a=v['native_enemy']['resolved']['attributes'];marker='buff/ch7/source/enemy_9D0_talent_strength';derived='buff/ch7/source/enemy_talent_strength[atk_speed]';uid='unit/ch7/ranged/soticn/304d5222d69cf371';prefix='rule/ch7/soticn/';sid='selector/ch7/soticn/normal';aid='ability/ch7/soticn/normal'
 rules=[{'id':prefix+'eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':prefix+'score','kind':'rule','contract':'targeting.score','implementation':{'type':'provider','provider':'reference.c7.ranged_live_taunt'}},{'id':prefix+'windup','kind':'rule','contract':'ability.windup','implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio, .01)'}},{'id':prefix+'motion','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'model.projectile.trajectory'}},{'id':prefix+'collision','kind':'rule','contract':'projectile.collision','implementation':{'type':'provider','provider':'model.projectile.collision'}},{'id':prefix+'box','kind':'rule','contract':'area.members','dependencies':[prefix+'eligibility'],'implementation':{'type':'provider','provider':'reference.c7.mortar_box'}}]
 eligibility=lambda raw:{'rule':prefix+'eligibility','parameters':{'source_configuration':raw,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':deepcopy(DEFAULT_STATE)}}
 impact={'op':'area','center':'target','membership_rule':prefix+'box','selection_projection':{'defaults':deepcopy(DEFAULT_STATE)},'parameters':{'half_extent':1.5,'eligibility':eligibility({'_targetOptions':hit['_targetOptions'],'_forceIgnoreCamouflage':1})},'projectile_definition':'projectile/ch7/soticn','effects':[{'op':'damage','damage_type':'physical','scale':1,'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False}}]}
 buffs=[next(b for b in json.loads(markerModule.read_bytes())['buffs'] if b['id']==marker),{'id':derived,'kind':'buff','modifiers':[{'attribute':'attack_speed_ratio','layer':'flat','value':next(x['value'] for x in v['native_enemy']['resolved']['talentBlackboard'] if x['key']=='strength.attack_speed')/100}],'metadata':{'nativeStrengthBB':v['native_enemy']['resolved']['talentBlackboard'],'nativeADDITION':'50/100 normalized flat+.5'}}];parents=[]
 for passive in v['passive_and_skill_components']:
  for b in passive['raw'].get('_buffs',[]):
   mode='start' if 'start_listener' in b['buffKey'] else 'finish';rid=prefix+mode;bid='buff/ch7/source/'+b['buffKey'];parents.append(bid);rules.append({'id':rid,'kind':'rule','contract':'buff.application','parameters':{'mode':mode,'marker':marker,'derived':derived},'implementation':{'type':'provider','provider':'reference.c7.ranged_strength'}});buffs.append({'id':bid,'kind':'buff','interval_seconds':b['triggerInterval'],'effects':[{'op':'buff_application','application_rule':rid,'allowed':[derived]}],'metadata':{'native_inline':b,'nativeBSON':row['literal_BSON_templates'][b['templateKey']]}})
 p={'schemaVersion':2,'manifest':{'id':'package/ch7/ranged/soticn/v2','requires':['preset/ark_standard'],'metadata':{'required_runtime':args.core,'variant_bindings':[{'variant_id':vid,'native_reference':v['native_reference'],'source':v,'projectile':d['projectiles']['projectile_mortar']}],'source_locks':{str(f):sha(f) for f in [source,plan,markerModule,Path(__file__),Path(__file__).with_name('mortar_box_v2.py'),Path(__file__).with_name('policies_v1.py')]},'reference_policy':'Exact source continuous3x3 impact Box with domain projected live status. Acquisition ground/camo0 and impact ground+fly/ignorecamo1/free0 separate. Source16/144frames; marker conditional ASPD+.5 real listener8 and revert24. Native graphical clamp/dynamicattacktype method body/comparator and projectile trajectory reference policy require client calibration. No numeric or whole stage claim.'}},'rules':rules,'entities':[{'id':uid,'kind':'entity','tags':['enemy','ground'],'components':{'attributes':{'base':{'max_hp':5500,'atk':450,'def':550,'mres':20,'move_speed':.6,'attack_interval':4.8,'attack_speed_ratio':1,'mass_level':2,'block_cost':1}},'resources':{'hp':{'initial':5500,'capacity':5500,'role':'health'}},'selection_state':{**deepcopy(DEFAULT_STATE),'side':1,'motion':1,'category':1,'unit_type':2,'abnormal_immunes':[12]},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':1},'abilities':[aid],'buffs':{'initial':parents}}}],'selectors':[{'id':sid,'kind':'selector','region':{'type':'radius','radius':15},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':eligibility(sel)}],'abilities':[{'id':aid,'kind':'ability','selector':sid,'rules':{'ability.windup':prefix+'windup','targeting.score':prefix+'score'},'activation':{'mode':'automatic_attack','parameters':{'auto_only':True}},'timeline':[{'at_seconds':16/30,'effect':impact}],'metadata':{'sourceAttack':v['modes'][0]['nodes']['_combat']}}],'buffs':buffs,'projectiles':[{'id':'projectile/ch7/soticn','kind':'projectile','motion':{'rule':prefix+'motion','parameters':{'mode':'homing','speed':4,'raise_height':1.5,'height_threshold':1.2999999523162842}},'collision':{'rule':prefix+'collision','parameters':{'enabled':False}},'lifetime_seconds':10,'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'completion_blocking':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True}}]}
 reg={**BUILTIN_PROVIDERS,'reference.c7.ranged_live_taunt':{'callable':live_taunt_score,'version':'1'},'reference.c7.ranged_strength':{'callable':strength_application,'version':'1'},'reference.c7.mortar_box':{'callable':mortar_box,'version':'2'}};fixture=deepcopy(p);fixture['scenarioDraft']={'id':'scene/soticn/compile','ruleset':'ruleset/ark_standard','map':{'rows':1,'cols':5},'objectives':{},'initialEntities':[{'definition':uid,'instanceAlias':'mortar','position':{'row':0,'col':0}}]};Compiler(providers=reg).compile(fixture);out=Path(args.output);assert not out.exists();out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'actual_compile':True,'module_sha':sha(out),'core':args.core}))
if __name__=='__main__':main()
