import json
from tools.chapter07_ranged_consumers.test_sotisp_v2 import package,make,ROOT
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
from ark_sim import Engine
from ark_sim.tools.replay import replay
OUT=ROOT/'validation/campaign/chapter07_ranged_sotisp_dynamic_v2'
def test_current_DEF_after_launch_and_actual_source_ASPD2():
 p=package();p['buffs'].append({'id':'buff/sniper/defplus','kind':'buff','duration_seconds':2,'modifiers':[{'attribute':'def','layer':'flat','value':100}]});p['selectors'].append({'id':'selector/sniper/player1','kind':'selector','region':{'type':'all'},'filters':[{'field':{'path':['id'],'equals':3}}]});p['scenarioDraft']['scheduledEffects']=[{'at':22,'effect':{'op':'apply_buff','buff':'buff/sniper/defplus','selector':'selector/sniper/player1'}}];program,s,reg=make(p);s.session.advance(22);OUT.mkdir(parents=True,exist_ok=True);cp=OUT/'projectile22.cp.json';assert not cp.exists();h=write_ordered(cp,s.checkpoint());r=Engine.restore(program,load_bound(cp,h),providers=reg);s.session.advance(10);r.session.advance(10);assert s.snapshot()==r.snapshot()==replay(program,s.export_replay(),providers=reg).snapshot();hits=[e for e in s.snapshot()['events'] if e['type']=='damage.accepted'];assert [(e['time'],e['payload']['amount']) for e in hits]==[(24,129)];(OUT/'current_DEF.trace.json').write_text(json.dumps({'input':p,'cp_sha':h,'snapshot':s.snapshot()},indent=2),encoding='utf8')
 p=package();p['buffs'].append({'id':'buff/sniper/ASPD2','kind':'buff','duration_seconds':2,'modifiers':[{'attribute':'attack_speed_ratio','layer':'flat','value':1}]});p['selectors'].append({'id':'selector/sniper/self','kind':'selector','region':{'type':'all'},'filters':[{'field':{'path':['id'],'equals':2}}]});p['scenarioDraft']['scheduledEffects']=[{'at':0,'effect':{'op':'apply_buff','buff':'buff/sniper/ASPD2','selector':'selector/sniper/self'}}];_,s,_=make(p);s.session.advance(30);ev=s.snapshot()['events'];starts=[e for e in ev if e['type']=='ability.started'];launch=[e for e in ev if e['type']=='projectile.launched'];assert len(starts)==len(launch)==1 and launch[0]['time']-starts[0]['time']==11;assert [(e['time'],e['payload']['amount']) for e in ev if e['type']=='damage.accepted']==[(14,229)]
