import hashlib,json,time
from pathlib import Path
from tools.chapter07_ranged_consumers.probe_soticn_v3 import ROOT
from ark_sim.adapters.api import implementation_digest
import pytest,ark_sim
CAND=ROOT.parent/'unpack_work/campaign_area_projection_v1_candidate'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 module=ROOT/'packages/campaign/chapter07_ranged_consumers/soticn.module.v3.json';m=json.loads(module.read_bytes());files=[ROOT/'tools/chapter07_ranged_consumers'/n for n in ['build_sotisp_v2.py','policies_v1.py','probe_soticn_v3.py','test_sotisp_v2.py','verify_sotisp_v2.py']]+[module,ROOT/'tools/chapter07_strength_melee/policies_v2.py',ROOT/'tools/campaign_ordered_checkpoint.py']+list((CAND/'ark_sim').rglob('*.py'))+list((CAND/'ark_sim').rglob('*.json'))+[Path(p) for p in m['manifest']['metadata']['source_locks']];before={str(p):sha(p) for p in files};start=time.monotonic();code=pytest.main([str(ROOT/'tools/chapter07_ranged_consumers/test_soticn_final_v6.py'),'-q']);after={str(p):sha(p) for p in files};assert before==after;out=ROOT/'validation/campaign/chapter07_ranged_soticn_guarded_v6/verification.json';out.parent.mkdir(parents=True,exist_ok=True);assert not out.exists();r={'actual_exit':code,'passed':code==0,'core':implementation_digest(),'runtime':ark_sim.__file__,'module_sha':sha(module),'source_before':before,'source_after':after,'elapsed':time.monotonic()-start,'scope':'Actual mortar450/111DEF=339,16frame/144cycle/speed4/life10; exact continuous3x3 box corner included/outside excluded; impact fly+camo admitted/free+side+category excluded; liveTargetFree20/currentDEF211→239. Marker8+.5 ASPD/revert24, first cooldown captured144 before marker8, subsequent96cycle/11windup. CP7+CP22 exact disk/head. Historical one-sided query trace failure preserved. Prior sniper reference scope not this module: Exact340atk/111DEF=229 normal21windup/75cycle/speed10/life5; native marker trigger8/revert24, mode1two real projectilehits99/102, typedcamo/TargetFree/fly/range excluded, noSP. CP7 bound disk restore/publichead exact. Capture-live/endpoint/prefilter/comparator/animationclamp native missing bodies declared replacement policies, client/stage pending.','whole_stage_executed':False,'client_verified':False,'independent_reviewed':False};out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha':sha(out),'actual_exit':code}));raise SystemExit(code)
if __name__=='__main__':main()
