import hashlib,json,time
from pathlib import Path
from tools.chapter07_ranged_consumers.probe_sotisp_v2 import ROOT
from ark_sim.adapters.api import implementation_digest
import pytest,ark_sim
CAND=ROOT.parent/'unpack_work/campaign_finish_timeline_wave_v4_candidate'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 module=ROOT/'packages/campaign/chapter07_ranged_consumers/sotisp.module.v2.json';m=json.loads(module.read_bytes());files=[ROOT/'tools/chapter07_ranged_consumers'/n for n in ['build_sotisp_v2.py','policies_v1.py','probe_sotisp_v2.py','test_sotisp_v2.py','verify_sotisp_dynamic_v1.py','test_sotisp_dynamic_guarded_v2.py']]+[module,ROOT/'tools/chapter07_strength_melee/policies_v2.py',ROOT/'tools/campaign_ordered_checkpoint.py']+list((CAND/'ark_sim').rglob('*.py'))+list((CAND/'ark_sim').rglob('*.json'))+[Path(p) for p in m['manifest']['metadata']['source_locks']];before={str(p):sha(p) for p in files};start=time.monotonic();code=pytest.main([str(ROOT/'tools/chapter07_ranged_consumers/test_sotisp_dynamic_guarded_v2.py'),'-q']);after={str(p):sha(p) for p in files};assert before==after;out=ROOT/'validation/campaign/chapter07_ranged_sotisp_dynamic_guarded_v2/verification.json';out.parent.mkdir(parents=True,exist_ok=True);assert not out.exists();r={'actual_exit':code,'passed':code==0,'core':implementation_digest(),'runtime':ark_sim.__file__,'module_sha':sha(module),'source_before':before,'source_after':after,'elapsed':time.monotonic()-start,'scope':'Dynamic after-launch DEF111+100 gives129 at24; ASPD2 via public buff quantizes21frame to11, actualhit14. CP22/head exact. Exact340atk/111DEF=229 normal21windup/75cycle/speed10/life5; native marker trigger8/revert24, mode1two real projectilehits99/102, typedcamo/TargetFree/fly/range excluded, noSP. CP7 bound disk restore/publichead exact. Capture-live/endpoint/prefilter/comparator/animationclamp native missing bodies declared replacement policies, client/stage pending.','whole_stage_executed':False,'client_verified':False,'independent_reviewed':False};out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha':sha(out),'actual_exit':code}));raise SystemExit(code)
if __name__=='__main__':main()
