import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'validation/campaign/chapter08_joint20_independent_gate';OUT.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();core='20e8126120668fece832e8b6e23fd53a68fb013656a4476b5ad8e53850f6dd30';rows=[];cases=[];files=[Path(__file__)]
for name,path,count in [('terminal9','chapter08_terminal_joint20_independent_v1',9),('dynamic_selflease_reuse16','chapter08_joint20_independent_v1',16)]:
 folder=ROOT/'validation/campaign'/path;r=json.loads((folder/'verification.json').read_bytes());assert r['core']==core and r['guards_equal'] and len(r['cases'])==count and all(c['outcome']=='passed' for c in r['cases']);rows.append({'scope':name,'verification':str(folder/'verification.json'),'sha':sha(folder/'verification.json'),'cases':count,'guards_start':r['guards_start'],'guards_end':r['guards_end']});cases+=r['cases'];files+=list(folder.rglob('*'))
assert len(cases)==25 and len({x['nodeid'] for x in cases})==25
files+=list((ROOT/'tools/chapter08_terminal_review').glob('*.py'))+list((ROOT/'tools/chapter08_joint_review_v2').glob('*.py'))
oldfail=ROOT/'validation/campaign/chapter08_terminal_independent_v3/freeze.failed.json';olda6=ROOT/'validation/campaign/chapter08_joint_independent_v5/freeze.json'
f={'passed':True,'core':core,'cases':25,'unique_cases':25,'scope_reports':rows,'case_outcomes':cases,'guards_equal':True,'old_terminal_v3_failed_freeze_sha':sha(oldfail),'old_a6_independent16_freeze_sha':sha(olda6),'terminal_scope':'Originalnine independentfixtures/assertions unchanged, actualnewcoreexec. Secondactualzero restore4 remainsHP0active untilbounded14. CompletionTTL6 from4 expires10: emit-onlyremoval requiresfallback14; genuineownnativeInstantKill10 once. Noncompletion nestedon_remove InstantKill cannotborrowparent authorizedstack andremains14 (originalfailedexpect repaired). Nestednoncompletion return leavesgenuineoutercompletionauthorized10. Samephaseexpiry deadline14 removescapturedrealBuff, emits14, defaultkills14 once/no backwardphase. TypedBoolgen rejects; publicmanual/foreigntriggerrejects realinternalauthority bypass. Nestedandfallback on_remove latefault restoresWorld/events/RNG andclearsprivate stacks/currenttask. PublicCP6 SHArestore/head completecheckpoint/journal equal; predicate/faulttests primitiveonly.','joint_scope':'Original16 independentfixtures/assertions unchanged, actualnewcoreexec. ActualHP0 on_begin selfBoost+finiteClock leases/maxHP75000ATK1155/first37500 restore6. InactivecountTrue clock5/False10, nestedactualowner/sampletime0-rate waits untilactive ->10. Publicforeign/no duplicateBoost, directself/foreignrefreshreject; Bool/oldgeneration copies, withdrawcancel, expiryfault. Realfinish latefault clearsprivatefinishingstack androllsHP0World/events/RNG; pendingjob legitimatelykeepslease untilactualcancel(job), thenFalse. Reusablepredefined2->5 actualfreshHP50000/no oldBoost/Clock/lease; newATK1000 doesnotrebind oldlaunchedpacket source2/ATK700 ->one687physicaldamage toDEF13 recipient4. Actualbudget2 rejectedextra publicactivation. Staleoldlease andmodifiedfreshrefcopyinvalid. PublicorderedCPrestore/head fullcheckpoint/journal matches; privatepredicate/cancel/fault notpublicheadclaimed.','source_bounds':'SourceBSON literalReborn2/.5/extra0 and genuineON_BUFF_FINISH TARGET InstantKill skipRebornFalse/noSourceFalse previouslyread/locked inclclosure742d...; synthetictest clocks aredeclared1/30 restore and6/30 Buff,10/30 terminal to distinguishauthority. Not proof ofcomplete28s native sourcechannel/tenvolleys/fullBoss/whole/client. Root ownsseparatefull/base/sourceruns; this25passdoesnot overwrite their outcomes. No standalone0b executionclaimed; terminalfileV4 repairedsemantics independently exercised inside20e exactjoint.','artifact_pins':{str(p):sha(p) for p in files if p.is_file()}}
(OUT/'freeze.json').write_text(json.dumps(f,ensure_ascii=False,indent=2),encoding='utf8');print(sha(OUT/'freeze.json'))
