"""Actual fixed 4f16 source consumer guards including unlike-Patriot identity interaction."""
import hashlib,json,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CAND=ROOT.parent/'unpack_work/campaign_finish_timeline_wave_v4_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
import pytest,ark_sim
from ark_sim.adapters.api import implementation_digest
CORE='4f16ac4c8ec0c0080302dfa1b6b1b6cc4da90d383ae9a2da5f796551d630c346'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==CORE;module=ROOT/'packages/campaign/chapter07_global_support/sotidp.module.v2.json';p=json.loads(module.read_bytes());assert p['manifest']['metadata']['required_runtime']==CORE;files=list(Path(__file__).parent.glob('*.py'))+list((CAND/'ark_sim').rglob('*.py'))+list((CAND/'ark_sim').rglob('*.json'))+[module,ROOT/'tools/campaign_ordered_checkpoint.py',ROOT/'validation/campaign/shared_aura_patrt_self_source_v10/input.json']+[Path(f) for f in p['manifest']['metadata']['source_locks']];before={str(f):sha(f) for f in files};start=time.monotonic();code=pytest.main([str(Path(__file__).with_name(n)) for n in ('test_source_guarded_v3.py','test_interaction_v2.py','test_normal_v2.py')]+['-q']);after={str(f):sha(f) for f in files};assert before==after and implementation_digest()==CORE;out=ROOT/'validation/campaign/chapter07_global_support_guarded_v3/verification.json';out.parent.mkdir(parents=True,exist_ok=True);assert not out.exists();r={'passed':code==0,'actual_exit':code,'core':CORE,'runtime':ark_sim.__file__,'source_before':before,'source_after':after,'elapsed':time.monotonic()-start,'module':str(module),'module_sha':sha(module),'source_variant':'enemy_1080_sotidp@0/ec07f90cc02c1801','source_4cases_plus_normal_and_unlikePatriot':True,'scope':'Exact7000/300/120/50/1/2.7/SPabsence/silence12, source12frame&81cycle two230/currentown330atk/DP7. Native disableOverride1/maxStack-1 modeled one independent .1/+100 attribute contribution per commander; shared marker max1. Two sources120/250, detach/death removes only its contribution, unlikePatriot source .2/+200 adds130/350 and one marker+twoleases. Typedcamo/side, actualsourceCP5/head. Explicit stacking/self/getter/unknownnativebody replacement policies; no stage/client claim.','primary_modified':False,'whole_stage_executed':False,'independent_reviewed':False,'client_verified':False};out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(out),'actual_exit':code,'elapsed':r['elapsed']}));raise SystemExit(code)
if __name__=='__main__':main()
