from tools.chapter09_ruin_peer.common import *
from tools.chapter09_stage_assembly_v1.providers_v6 import providers as providers6
REG=providers6();V6=ROOT/'packages/campaign/chapter09_stage_models/level_main_09-16.native_draft.v6.life99999.json';stage6=json.loads(V6.read_bytes());assert sha(V6)=='a169a5a1b32dd6a6829c0e7ab1dfcd16aca8de0dd896c17fb5ace92034d06044'
def make(epsilon):
 r=math.sqrt(root['_blockRadiusSquare']);col=.499;dr=math.sqrt((r+epsilon)**2-col*col);p=scene(position=(3+dr,4+col));p['definitions']=deepcopy(stage6['definitions']);p['scenarioDraft']['rules']=deepcopy(stage6['scenarioDraft']['rules']);uid=p['scenarioDraft']['initialEntities'][1]['definition'];a=next(d for d in p['definitions'] if d['id']==uid);a['components'].pop('behavior',None);a['components']['abilities']=[];a['components']['attributes']['base']['move_speed']=0;return p

def create6(p):return Engine.create(Compiler(providers=REG).compile(p),providers=REG,seed=4729287)
facts=[];artifacts=[]
for epsilon,want in [(-.00001,True),(.00001,False)]:
 p=make(epsilon);a=create6(p);a.advance(1);actual=a.ctx.spatial.blocked_by('enemy') is not None;rows=[thaw(e) for e in a.session.events if e['type']=='calculation' and e['payload']['calculation_id']=='blocking.eligibility'];ids={e['payload']['rule_id'] for e in rows};facts.append({'epsilon':epsilon,'actual_blocked':actual,'actual_position':a.ctx.get('enemy',('spatial','position')),'actual_route':a.ctx.get('enemy',('spatial','route')),'runtime':a.ctx.get('enemy',('runtime',)),'actual_rule_ids':list(ids),'calculations':rows});(REPORT/'radius.v6.probe.json').write_text(json.dumps({'facts':facts},indent=2),encoding='utf8');assert actual==want;assert ids=={'rule/ch9/scenario_blocking'};path=LOG/('radius_'+str(epsilon)+'.checkpoint.json');pin=write_ordered(path,a.checkpoint());b=Engine.restore(a.program,load_bound(path,pin),providers=REG);a.advance(2);b.advance(2);h=replay(a.program,a.export_replay(),providers=REG);assert a.checkpoint()==b.checkpoint()==h.checkpoint();artifacts.append({'path':str(path),'sha256':pin,'bytes':path.stat().st_size,'full_CPP_head_equal':True})
assert guard()==START;report={'core':CORE,'actual_exit':0,'v6_sha':sha(V6),'scenario_rule_binding_actual':True,'facts':facts,'artifacts':artifacts,'source_guard_equal':True,'v5_scope_counter_preserved':'radius.scope.actual.counter.json','whole_stage':False};(REPORT/'radius.v6.actual.json').write_text(json.dumps(report,indent=2),encoding='utf8');print(json.dumps({'actual_exit':0,'cases':2,'full_CPP_head':True}))
