"""Consume exact required source counter with explicit lease policy, public HP0/CP/head."""
import hashlib,json,sys,time
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];CAND=ROOT.parent/'unpack_work/campaign_chapter07_foundation_v1_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler,Engine
from ark_sim.adapters.api import implementation_digest
from ark_sim.tools.replay import replay
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
CORE='43d8dc974b4a914aabc3dc4315b4178d4516913edbb2a5e80ce0e7c629c8d73a';OUT=ROOT/'validation/campaign/shared_aura_patrt_joint_source_v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==CORE;src=ROOT/'packages/campaign/chapter07_boss/patrt/required_waiting_counters/aura.input.json';closure=src.parent.parent/'source.closure.json';assert sha(src)=='53f3438c211f9d4094acdb6e1a44950f4ab9915acc4eff9aa98aa575913028d7';p=json.loads(src.read_bytes());original=deepcopy(p)
 required=ROOT/'packages/campaign/chapter07_boss/patrt/required.aura.compiler.input.json';assert sha(required)=='619ea0a4bd3531f46a28921442d79be5b456e1df9fb91723ded96d320b433f23';required_data=json.loads(required.read_bytes());marker_definition=next(b for b in required_data['buffs'] if b['id']=='buff/ch7/source/enemy_9D0_talent_strength');marker_parent=next(b for b in required_data['buffs'] if b['id'].endswith('/marker_parent'));p['buffs'] += [deepcopy(marker_definition),deepcopy(marker_parent)];boss=p['entities'][0]['components'];boss['buffs']['initial'].append(marker_parent['id']);boss['rebirth']['retain_buffs'].append(marker_parent['id']);boss['rebirth']['on_begin'].append({'op':'apply_buff','target':'source','buff':marker_parent['id']});boss['rebirth']['on_finish'].append({'op':'apply_buff','target':'source','buff':marker_parent['id']});marker=next(b for b in p['buffs'] if b['id']=='buff/ch7/source/enemy_9D0_talent_strength');before_marker=deepcopy(marker)
 for b in p['buffs']:
  if b.get('aura'):b['aura']['lease_policy']={'mode':'shared','identity':['definition','target'],'source_binding':'oldest_live_lease','external_child_collision':'reject','owner_activity':'active_or_rebirth_waiting'}
 for buff in p['buffs']:
  if buff['id'].endswith('/strength'):buff['stacking']={'mode':'refresh','identity':['definition','target'],'max_stacks':1}
 assert marker==before_marker;assert p['entities'][0]['components']['attributes']==original['entities'][0]['components']['attributes'] and p['abilities']==original['abilities'];paths=[src,closure,required,Path(__file__),ROOT/'tools/campaign_ordered_checkpoint.py']+list((CAND/'ark_sim').rglob('*.py'))+list((CAND/'ark_sim').rglob('*.json'));before={str(f):sha(f) for f in paths};OUT.mkdir(parents=True,exist_ok=True);inputpath=OUT/'input.json';assert not inputpath.exists();inputpath.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');program=Compiler().compile(p);s=Engine.create(program);s.submit({'action':'deploy','entity':'unit/test/patrt/hero','alias':'hero','row':2,'col':2},at=0);s.submit({'action':'skill','source':'hero','ability':'ability/test/patrt/kill'},at=5);s.session.advance(6);assert s.ctx.resources.current('boss','hp')==0 and not s.ctx.active('boss') and s.ctx.alive('boss');assert s.ctx.attributes.value('ally','atk')==120 and s.ctx.attributes.value('ally','def')==250;children=[i for i in s.ctx.entity('ally')['components']['buffs']['instances'] if i['definition'] in ('buff/ch7/source/enemy_9D0_talent_strength','buff/unit/ch7/patrt/a53a85a6d0cd714f/strength')];assert len(children)==2 and all(i['stacks']==1 and i['expires_at'] is None for i in children)
 # Source stat sampling above is legitimate but unrecorded public-query events;
 # recreate clean public process for exact CP/head evidence, preserving same input.
 del s;s=Engine.create(program);s.submit({'action':'deploy','entity':'unit/test/patrt/hero','alias':'hero','row':2,'col':2},at=0);s.submit({'action':'skill','source':'hero','ability':'ability/test/patrt/kill'},at=5);s.session.advance(6);cp=OUT/'waiting6.cp.json';assert not cp.exists();h=write_ordered(cp,s.checkpoint());r=Engine.restore(program,load_bound(cp,h));s.session.advance(45);r.session.advance(45);assert s.snapshot()==r.snapshot()==replay(program,s.export_replay()).snapshot();assert s.ctx.alive('boss') and not s.ctx.active('boss') and s.ctx.resources.current('boss','hp')==0;assert len([i for i in s.ctx.entity('ally')['components']['buffs']['instances'] if i['definition'] in ('buff/ch7/source/enemy_9D0_talent_strength','buff/unit/ch7/patrt/a53a85a6d0cd714f/strength')])==2;assert not s.ctx.rebirth._aura_waiting_begins;after={str(f):sha(f) for f in paths};assert before==after;actual=OUT/'actual.json';actual.write_text(json.dumps({'checkpoint_sha':h,'snapshot':s.snapshot()},indent=2)+'\n',encoding='utf8',newline='');report=OUT/'verification.json';assert not report.exists();v={'passed':True,'actual_exit':0,'core':CORE,'source_before':before,'source_after':after,'source_required_input_sha':sha(src),'new_explicit_policy_input_sha':sha(inputpath),'source_marker_definition_unchanged':True,'source_HP45000_restore_ratio_8500000238418579_unchanged':True,'actual_publickill5_HP0_waiting_at51':True,'actual_ally_ATK120_DEF250_with_one_each_child':True,'actual_waiting_CP6_disk_SHAload_resume_publichead_equal':True,'actual_evidence_sha':sha(actual),'primary_modified':False,'scope':'Required source global Aura/marker + explicit replaceable shared lease/waiting policy. Only short waiting prefix; full Patriot phases/Immo/Spear/Ore and stage not claimed.'};report.write_text(json.dumps(v,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'report_sha':sha(report),'actual_input_sha':sha(inputpath)}))
if __name__=='__main__':main()
