"""First closed screen fire-common volley using actual projectiles/qualified impacts."""
import sys,json,hashlib
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[2];CAND=ROOT.parent/'unpack_work/campaign_selection_context_clock_v2_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from ark_sim.domains.selection import DEFAULT_STATE
from tools.chapter08_bsnake.screen_policy_v1 import providers
CORE='07bb47ae46dbe530ecbe19eba5ebcc79cca050d277eb0325d171204b848e8345'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build(rows=5):
 assert implementation_digest()==CORE;src=ROOT/'packages/campaign/chapter08_consumers/bsnake/source.closure.v1.json';d=json.loads(src.read_bytes());native=d['variant']['native_enemy']['resolved'];rawpr=d['projectile_bsnake'];simple=next(c['raw'] for c in rawpr['components'].values() if c['native_class']=='SimpleProjectile');motion=next(c['raw'] for c in rawpr['components'].values() if c['native_class']=='FarthestPointMovement');hit=next(c['raw'] for c in rawpr['components'].values() if c['native_class']=='HitBehaviour');screen=next(c['raw'] for c in d['prefab']['components'].values() if c['native_class']=='BsnakeScreenAttack');radius=next(c['raw']['m_Radius'] for c in rawpr['geometry_sources'] if c['unity_type']=='CircleCollider2D');assert radius==.25 and motion['_speed']==2.5 and simple['_hitNumType']==1 and simple['_maxHitNum']==1 and screen['_damageType']==2;attrs=native['attributes'];uid='unit/ch8/bsnake/cadb87696bef4de2';aid='ability/ch8/bsnake/firecommon';prefix='rule/ch8/bsnake/firecommon/';config={'_'+k:v for k,v in hit['_targetOptions'].items()};config.update(_forceIgnoreCamouflage=hit['_ignoreCamouflage'],_needProfessionMask=0);par={'source_configuration':config,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':deepcopy(DEFAULT_STATE)}
 p={'schemaVersion':2,'manifest':{'id':'package/ch8/bsnake/firecommon_v2','requires':['preset/ark_standard'],'metadata':{'required_runtime':CORE,'source_locks':{str(src):sha(src),str(Path(__file__)):sha(Path(__file__)),str(Path(__file__).with_name('screen_policy_v1.py')):sha(Path(__file__).with_name('screen_policy_v1.py'))},'variant':d['variant']['variant_id'],'native_stats':native,'source_projectile':rawpr,'source_screen_node':screen,'scope':'First closed BsnakeScreenAttack volley component only, not completeBoss/auto28s screen/reborn/branch/dragon_fire consumer. ActualHP50000/ATK770/DEF800/RES50 and declaredimmunities retained.','reference_policy':'borderPeel1 modeled launchleft→right rows1..rows-2 and col1→cols-2 with source actor unchanged; heightOverHighland.5 isvisual only. One actual namedRNG draw perrow, uniform0..1×source.1 authored startup quantized0/1/2/3 frames; source float32 raw .10000000149 retained. Per-row CPPdefinitions finite, initial puretrajectory chooses native-style projectileposition, no fakeActor/casterposition edit. Native launchgeometry/delayquantization remain explicitly replaceable clientpolicy.','whole_stage_executed':False,'client_verified':False}},'entities':[{'id':uid,'kind':'entity','tags':['enemy','ground','boss'],'components':{'attributes':{'base':{'max_hp':50000,'atk':770,'def':800,'mres':50,'move_speed':.5,'attack_interval':4.5,'attack_speed_ratio':1,'mass_level':6}},'resources':{'hp':{'initial':50000,'capacity':50000,'role':'health'}},'selection_state':{**deepcopy(DEFAULT_STATE),'side':1,'motion':1,'category':1,'unit_type':2,'abnormal_immunes':[0,12,16,25],'abnormal_combo_immunes':[0]},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':2},'abilities':[aid]}}],'rules':[{'id':prefix+'motion','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'reference.bsnake.screen_row'}},{'id':prefix+'eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':prefix+'collision','kind':'rule','contract':'projectile.collision','dependencies':[prefix+'eligibility'],'implementation':{'type':'provider','provider':'model.projectile.qualified_swept_ray'}}],'projectiles':[],'abilities':[]};effects=[]
 for row in range(screen['_borderToPeel'],rows-screen['_borderToPeel']):
  children=[]
  for delay,condition in [(0,'params.random_sample == 0'),(1,'params.random_sample > 0 and params.random_sample <= 1/3'),(2,'params.random_sample > 1/3 and params.random_sample <= 2/3'),(3,'params.random_sample > 2/3')]:
   pid=f'projectile/ch8/bsnake/firecommon/r{row}/d{delay}';p['projectiles'].append({'id':pid,'kind':'projectile','motion':{'rule':prefix+'motion','parameters':{'row':row,'border':screen['_borderToPeel'],'height':screen['_heightOverHighland'],'delay_seconds':delay/30,'speed':motion['_speed'],'extent_policy':'map_bounds'}},'collision':{'rule':prefix+'collision','allow_other_targets':True,'parameters':{'qualified_ray':True,'radius':radius,'exclude_source':True,'eligibility':{'rule':prefix+'eligibility','parameters':par}}},'lifetime_seconds':simple['_lifeTime'],'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'completion_blocking':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':False,'force_reach_on_expire':False,'hit_on_expire':False}});children.append({'op':'damage','damage_type':'arts','scale':screen['_atkScale'],'projectile_definition':pid,'condition':condition,'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False}})
  effects.append({'at_seconds':0,'effect':{'op':'random','target':'source','stream':'bsnake.screen.birth','probability':1,'on_success':children,'on_failure':[]}})
 p['abilities']=[{'id':aid,'kind':'ability','activation':{'mode':'manual'},'timeline':effects}];return p
if __name__=='__main__':
 p=build();test=deepcopy(p);test['scenarioDraft']={'id':'scene/bsnake/firecommon_compile','ruleset':'ruleset/ark_standard','map':{'rows':5,'cols':8},'objectives':{},'initialEntities':[{'definition':p['entities'][0]['id'],'instanceAlias':'boss','position':{'row':2,'col':6}}]};Compiler(providers=providers()).compile(test);out=ROOT/'packages/campaign/chapter08_consumers/bsnake/firecommon.module.v2.json';assert not out.exists();out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha':sha(out),'actual_compile':True,'fire_rows':3,'projectile_prototypes':len(p['projectiles'])}))
