import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def audit():
 source=ROOT/'packages/campaign/chapter09_source_prepare/enemies.native.v1.json';data=json.loads(source.read_bytes());assert hashlib.sha256(source.read_bytes()).hexdigest()=='592afac29cc32d1aeaba3ea739eb6da5a218055e255a42f53315f4a2ca0962ff';rows=[]
 for key in ['enemy_1165_duhond','enemy_1166_dusbr']:
  m=json.loads((ROOT/'packages/campaign/chapter09_consumers/ordinary'/(key+'.module.v1.json')).read_bytes());vid=m['manifest']['metadata']['native_variant'];raw=data['variants'][vid];stats=raw['native_enemy']['resolved']['attributes'];c=m['entities'][0]['components'];base=c['attributes']['base'];assert (base['max_hp'],base['atk'],base['def'],base['mres'],base['move_speed'],base['attack_interval'])==(stats['maxHp'],stats['atk'],stats['def'],stats['magicResistance'],stats['moveSpeed'],stats['baseAttackTime']);assert c['resources']['hp']['initial']==stats['maxHp'];assert stats['silenceImmune'] is False and stats['stunImmune'] is False and c['selection_state']['abnormal_immunes']==[]
  mode=raw['modes'][0];combat=mode['nodes']['_combat'];assert mode['nodes']['_attack']['status']==mode['nodes']['_attackTrigger']['status']=='native_null';assert combat['native_class']=='MeleeAttack' and combat['raw']['_activeBuffs']==[] and combat['raw']['_selector']['m_PathID']==0;anim=combat['animation_binding'];event=next(e for e in anim['events'] if e['name']=='OnAttack');ability=m['abilities'][0];assert event['frame']==18 and ability['timeline'][0]['at_seconds']==event['seconds'] and ability['duration_seconds']==anim['duration']['seconds'];passive=raw['passive_and_skill_components'][0]['raw']['_buffs'][0];assert (passive['loadFromDB'],passive['lifeTimeType'],passive['isSilenceable'])==(0,2,1);mod=passive['attributes']['attributeModifiers'][0];assert (mod['attributeType'],mod['formulaItem'],mod['loadFromBlackboard'])==(3,0,1);bb={x['key']:x['value'] for x in raw['native_enemy']['resolved']['talentBlackboard']};assert bb['refracting.magic_resistance']==70;mresmod=m['buffs'][0]['modifiers'][0];assert mresmod=={'attribute':'mres','layer':'flat','value':70.0};assert m['rules'][1]['implementation']['expression']=='12 not in inputs.status.abnormal_flags';rows.append({'key':key,'variant':vid,'relative_hit_frames':18,'full_frames':anim['duration']['frame'],'source_BB_mres_addition':70,'silenceable':True,'native_undefined_other_immunities_not_claimed':True})
 return rows
