"""Literal source strength marker transitions with public effects and disk replay."""
import json,sys
from copy import deepcopy
from pathlib import Path
import pytest
ROOT=Path(__file__).resolve().parents[2];RUNTIME=ROOT.parent/'unpack_work/campaign_chapter06_complete_base_v5_candidate';sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler,Engine
from ark_sim.tools.replay import replay
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
from tools.chapter07_strength_melee.policies_v1 import providers
OUT=ROOT/'validation/campaign/chapter07_strength_melee_author_v1'
CASES=[('enemy_1078_sotisc','move_speed',1.1,.3,12,60,200),('enemy_1083_sotiab','atk',360,.5,13,57,260),('enemy_1083_sotiab_2','atk',430,.8,13,57,330)]
def package(name):
 p=json.loads((ROOT/'packages/campaign/chapter07_strength_melee'/('module.'+name+'.v2.json')).read_bytes());unit=p['entities'][0]['id'];p['selectors'].append({'id':'selector/author/strength/source','kind':'selector','region':{'type':'all'},'filters':[{'tag':'enemy'}]});p['scenarioDraft']={'id':'scene/ch7/strength/'+name,'ruleset':'ruleset/ark_standard','seed':71718,'map':{'rows':1,'cols':5},'objectives':{},'initialEntities':[{'definition':unit,'instanceAlias':'source','position':{'row':0,'col':0}}],'dependencies':['selector/author/strength/source']};return p
@pytest.mark.parametrize('name,stat,base,ratio,frame,interval,damage',CASES)
def test_literal_strength_first8_tick_only_marker_then_remove_and_disk_head(name,stat,base,ratio,frame,interval,damage):
 p=package(name);marker='buff/ch7/source/enemy_9D0_talent_strength';derived='buff/ch7/source/enemy_talent_strength['+stat+']';p['scenarioDraft']['scheduledEffects']=[{'at':1,'effect':{'op':'apply_buff','buff':marker,'selector':'selector/author/strength/source'}},{'at':18,'effect':{'op':'remove_buff','buff':marker,'selector':'selector/author/strength/source'}}];reg=providers();program=Compiler(providers=reg).compile(p);s=Engine.create(program,providers=reg);s.session.advance(7);assert not any(i['definition']==derived for i in s.ctx.entity('source')['components']['buffs']['instances']);s.session.advance(3);assert any(i['definition']==derived for i in s.ctx.entity('source')['components']['buffs']['instances']);OUT.mkdir(parents=True,exist_ok=True);cp=OUT/(name+'.10.cp.json');assert not cp.exists();h=write_ordered(cp,s.checkpoint());r=Engine.restore(program,load_bound(cp,h),providers=reg);s.session.advance(20);r.session.advance(20);assert s.snapshot()==r.snapshot()==replay(program,s.export_replay(),providers=reg).snapshot();assert not any(i['definition']==derived for i in s.ctx.entity('source')['components']['buffs']['instances']);(OUT/(name+'.trace.json')).write_text(json.dumps({'input':p,'cp_sha':h,'snapshot':s.snapshot()},indent=2)+'\n',encoding='utf8',newline='')
 # Values sampled in a separate identical process avoid unrecorded calculation
 # queries contaminating the public command replay evidence above.
 q=Engine.create(program,providers=reg);q.session.advance(7);assert q.ctx.attributes.value('source',stat)==base;q.session.advance(3);assert q.ctx.attributes.value('source',stat)==base*(1+ratio);q.session.advance(20);assert q.ctx.attributes.value('source',stat)==base
@pytest.mark.parametrize('name,stat,base,ratio,frame,interval,damage',CASES)
def test_real_source_normal_frame_cycle_damage_DP_and_no_marker_no_strength(name,stat,base,ratio,frame,interval,damage):
 p=package(name);p['entities'].append({'id':'unit/author/strength/blocker','kind':'entity','tags':['player','ground'],'components':{'attributes':{'base':{'max_hp':10000,'atk':0,'def':100,'mres':0,'block_count':1}},'resources':{'hp':{'initial':10000,'capacity':10000,'role':'health'}},'selection_state':{'side':0,'motion':1,'category':1,'unit_type':1},'spatial':{},'deployable':{'base_cost':7,'capacity':1,'cooldown_seconds':0,'terrain':'ground'},'lifecycle':{'policy':'policy/ark_lifecycle'}}});p['scenarioDraft']['roster']=['unit/author/strength/blocker'];p['scenarioDraft']['resources']={'dp':{'initial':20,'capacity':99}};p['scenarioDraft']['initialEntities'][0]['route']={'motionMode':'WALK','startPosition':{'row':0,'col':0},'endPosition':{'row':0,'col':4},'checkpoints':[]};reg=providers();s=Engine.create(Compiler(providers=reg).compile(p),providers=reg);s.submit({'action':'deploy','definition':'unit/author/strength/blocker','alias':'blocker','position':{'row':0,'col':0}},at=0);s.session.advance(frame+interval+4);h=[e for e in s.session.events if e['type']=='damage.accepted'];assert len(h)==2 and h[0]['time']==frame+1 and h[1]['time']-h[0]['time']==interval and [e['payload']['amount'] for e in h]==[damage,damage];assert s.ctx.resources.current('system/battle','dp')==13 and set(s.ctx.entity('source')['components']['resources'])=={'hp'};assert s.ctx.attributes.value('source',stat)==base
