"""Story FrostNova source content. Requires explicit BUFF no-source support."""
from pathlib import Path
from copy import deepcopy
import hashlib,json
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'packages/campaign/chapter06_boss/frstar2_s'
COLD=ROOT/'packages/campaign/chapter06_cold/model.json'
ICE=ROOT/'packages/campaign/chapter04_boss/ice_shield_v3/module.reference.json'
UID='unit/ch6/frstar2_s/2ca10c3158df0a8d'
B='ability/'+UID+'/burst';I='ability/'+UID+'/shield'
BLOOD='buff/'+UID+'/blood';SLEEP='buff/'+UID+'/sleepimmune'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rule(id,contract,provider):return {'id':id,'kind':'rule','contract':contract,'implementation':{'type':'provider','provider':provider}}
def defaults():return {'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False,'abnormal_immunes':[]}
def build():
 s=json.loads((OUT/'source.closure.json').read_bytes());v=s['variant'];d=v['native_enemy']['resolved'];a=d['attributes'];c=s['prefab']['components'];an=s['animation']['parsed']['animations'];stem='rule/'+UID
 p={'schemaVersion':2,'manifest':{'id':'package/ch6/frstar2_s/story','requires':['preset/ark_standard'],'metadata':{'native_variant_id':v['variant_id'],'source_locks':{str((OUT/'source.closure.json').relative_to(ROOT)):sha(OUT/'source.closure.json'),str(COLD.relative_to(ROOT)):sha(COLD),str(ICE.relative_to(ROOT)):sha(ICE)},'builder_sha256':sha(Path(__file__)),'reference_policies':s['reference_policies'],'normal_never_trigger':True,'requires_generic_buff_no_source':True,'independent_reviewed':False,'whole_stage_executed':False,'client_verified':False}},'entities':[],'rules':[],'abilities':[],'buffs':[],'selectors':[],'definitions':[]}
 elig=stem+'/eligibility';member=stem+'/members';cast='buff/'+UID+'/burst_frozen_scale';pipeline=stem+'/blood_pipeline';steer=stem+'/steering'
 raw=c['-974341646982001114']['raw'];cfg=c[str(raw['_selector']['m_PathID'])]['raw'];radius=3.299999952316284
 p['rules']=[rule(elig,'targeting.eligibility','model.targeting.eligibility'),rule(steer,'movement.steering','ark.movement.steering_velocity'),{'id':member,'kind':'rule','contract':'area.members','dependencies':[elig],'parameters':{'radius':radius,'eligibility':{'rule':elig,'parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}},'implementation':{'type':'provider','provider':'model.area.qualified_radius'}},{'id':stem+'/frozen_scale','kind':'rule','contract':'damage.request','parameters':{'atk_scale':2},'implementation':{'type':'provider','provider':'reference.c6.frozen_atkscale'}},{'id':pipeline,'kind':'rule','contract':'damage.pipeline','implementation':{'type':'graph','nodes':[{'id':'result','expression':"{'accepted':True,'amount':inputs.effect.fixed_amount,'allocations':[],'events':[]}"}],'output':'nodes.result'}}]
 blood=s['bson']['periodic_damage_without_modify']['parsed']['eventToActions']['ON_BUFF_TRIGGER'][0]
 p['buffs']=[{'id':BLOOD,'kind':'buff','interval_seconds':1,'removal':{'on_source_death':'remove','on_target_death':'remove'},'effects':[{'op':'no_source_damage','fixed_amount':2000,'damage_type':'true','attack_type':blood['_attackType'],'damage_without_modify':blood['_damageWithoutModify'],'ignore_for_sp':blood['_ignoreForSp'],'node_is_env_damage':blood['_isEnvDamage'],'env_blackboard_injected':False,'environmental':False,'origin':{'native_buff':'frstar2_s_periodic_damage','native_template':'periodic_damage_without_modify','source_document_sha256':s['bson']['periodic_damage_without_modify']['document_sha256']},'rules':{'damage.pipeline':pipeline}}]},{'id':SLEEP,'kind':'buff','selection_flags':{'abnormal_combo_immunes':[0]}},{'id':cast,'kind':'buff','damage_hooks':[{'phase':'before','rule':stem+'/frozen_scale'}]}]
 sid='selector/'+UID+'/burst'
 p['selectors']=[{'id':sid,'kind':'selector','region':{'type':'radius','radius':radius},'filters':[{'tag':'player'},{'state':'alive'}],'limit':None,'eligibility':{'rule':elig,'parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}}]
 skill={x['prefabKey']:x for x in d['skills']};burst=skill['IceBurst'];shield=skill['IceShield'];frame=an['Skill_3']['events'][0]['frame']
 p['abilities']=[{'id':B,'kind':'ability','selector':sid,'initial_cooldown_seconds':burst['initCooldown'],'cooldown_seconds':burst['cooldown'],'duration_seconds':an['Skill_3']['duration']['seconds'],'activation':{'mode':'manual','forbidden_source_flags':[0,12],'parameters':{'auto_only':True,'auto_when_ready':True,'requires_targets':True},'on_start':[{'op':'apply_buff','target':'source','buff':cast,'bind_to_cast':True}]},'timeline':[{'at':frame,'effect':{'op':'area','center':'source','membership_rule':member,'filters':[{'tag':'player'}],'effects':[{'op':'damage','damage_type':'arts','scale':1,'damage_flags':{'source_attack_type':'SPLASH','ignore_for_sp':False},'on_success':[{'op':'buff_application','application_rule':'rule/ch6/cold/application','allowed':['buff/ch6/cold/e2c_cold','buff/ch6/cold/e2c_freeze'],'parameters':{'duration_seconds':10}}]}]}}]}]
 defs=deepcopy(json.loads(ICE.read_bytes())['definitions']);token,ice=defs;token['id']='unit/'+UID+'/sealedfloor';token['metadata']['source_policy']='Exact trap004 borrowed source asset and explicit HP100 reference; no ordinary Boss input';ice['id']=I;ice['initial_cooldown_seconds']=shield['initCooldown'];ice['cooldown_seconds']=shield['cooldown'];ice['duration_seconds']=an['Skill_1']['duration']['seconds'];ice['tile_selector']['limit']=3;ice['tile_selector']['stream']='ch6/frstar2_s/shield';ice['timeline'][0]['at']=an['Skill_1']['events'][0]['frame'];ice['timeline'][0]['effect']['definition']=token['id'];ice['metadata']['source_plan_sha']=sha(OUT/'source.closure.json');ice['metadata']['cooldown_policy']='Source init23/cooldown1000; independent timer from cast finish reference';p['definitions']=defs
 root=c[v['root_path_id']]['raw'];m=next(x['raw'] for x in c.values() if x['native_class']=='MoveController')
 immunes=[flag for key,flag in [('stunImmune',0),('silenceImmune',12),('frozenImmune',16),('levitateImmune',25)] if a.get(key) is True]
 p['entities']=[{'id':UID,'kind':'entity','tags':['enemy','ground','boss','story_boss'],'metadata':{'native_variant_id':v['variant_id'],'native_reference':v['native_reference'],'undefined_immunity_rows_retained_in_source':True},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':root['_blockVolume']}},'resources':{'hp':{'role':'health','initial':a['maxHp'],'capacity_attribute':'max_hp'}},'selection_state':{'side':1,'motion':1,'category':1,'unit_type':1,'abnormal_immunes':immunes},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':d['lifePointReduce']},'buffs':{'initial':[BLOOD,SLEEP]},'abilities':[I,B],'ability_arbitration':{'priority_order':'higher_first','busy':'all_casts','entries':[{'ability':I,'priority':2,'attack_clock':False,'require_attack_control':False,'condition':'True','parameters':{}},{'ability':B,'priority':1,'attack_clock':False,'require_attack_control':False,'condition':'True','parameters':{}}]},'spatial':{'motion_mode':0,'steering':{'rule':steer,'parameters':{'response_factor':m['_steeringFactor'],'max_acceleration':m['_maxSteeringForce'],'arrival_radius':.05}}}}}]
 return p
if __name__=='__main__':
 p=OUT/'model.json';p.write_bytes((json.dumps(build(),ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'sha256':sha(p),'required_generic_pending':True}))
