"""Independent fresh NoSource/Buff/tile delta review; excludes own Infinity review."""
import hashlib,json,sys,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];CAND=ROOT.parent/'unpack_work/campaign_content_base_v1_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
import pytest,ark_sim
from ark_sim.adapters.api import implementation_digest
CORE='d81334d340034732a1840f16612073f7ae56e41a9727584ea38c74c61943439e'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==CORE and Path(ark_sim.__file__).resolve().is_relative_to(CAND.resolve());tests=[Path(__file__).with_name(x) for x in ('test_no_source_guarded_v3.py','test_tile_guarded_v2.py')];paths=list(Path(__file__).parent.glob('*.py'))+list((CAND/'ark_sim').rglob('*.py'))+list((CAND/'ark_sim').rglob('*.json'))+[ROOT/'tools/campaign_ordered_checkpoint.py'];before={str(p):sha(p) for p in paths};start=time.monotonic();code=pytest.main([str(p) for p in tests]+['-q']);after={str(p):sha(p) for p in paths};assert before==after and implementation_digest()==CORE;out=ROOT/'validation/campaign/content_base_peer_guarded_v1/verification.json';out.parent.mkdir(parents=True,exist_ok=True);assert not out.exists();r={'passed':code==0,'actual_exit':code,'core':CORE,'runtime':ark_sim.__file__,'elapsed':time.monotonic()-start,'source_before':before,'source_after':after,'reviewed_delta_files':['ark_sim/domains/no_source_damage.py','ark_sim/domains/buffs.py','ark_sim/domains/tile_targets.py'],'own_buffApplication_not_self_peer':True,'expected_values_independent_literal_not_same_calculator':True,'Root_probe_not_imported':True,'cases':25,'scope':'NoSource actorNone PUREBUFF modifications2*.25=15 vs bypass30; targetdodge1sample vs bypass0; bounds and lethal claims; late allocation/RNG/trace atomic rollback; real timer refresh-generation/remove/inactive/dead and origin CP/head; typed side0/1 Character1/Token4/compound5/zero unit and query no writes/no RNG/bool/int validation plus CP/head. Limited synthetic generic interface boundary review, not client/stage-source proof.','whole_stage_executed':False,'client_verified':False,'full_suite_passed':False};out.write_text(json.dumps(r,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'actual_exit':code,'sha':sha(out),'elapsed':r['elapsed']}));raise SystemExit(code)
if __name__=='__main__':main()
