"""Exact uoffcr source dual blocked melee/unblocked marker projectile consumer."""
import sys,json,hashlib
from pathlib import Path
from copy import deepcopy
ROOT=Path(__file__).resolve().parents[2];CAND=ROOT.parent/'unpack_work/campaign_area_projection_v2_candidate';sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from ark_sim.domains.selection import DEFAULT_STATE
from tools.chapter08_ranged.policies_v1 import providers
CORE='3992a0e6726dd7128b9ee36e542be38376f7488d2d8165af33bdc9c662a79000';VID='enemy_1107_uoffcr@0/8744707cad2d0fa6';MARKER='buff/ch8/source/mark_neutral[effect]'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==CORE;source=ROOT/'packages/campaign/chapter08_source_prepare/integration/enemies.native.v1.json';data=json.loads(source.read_bytes());v=data['variants'][VID];pf=data['prefabs'][v['prefab_key']];a=v['native_enemy']['resolved']['attributes'];root=next(c for c in pf['components'].values() if c['native_class']=='Enemy');mover=next(c for c in pf['components'].values() if c['native_class']=='MoveController');selector=next(c for c in pf['components'].values() if c['native_class']=='AdvancedSelectorWithTagAndBuffKey');sel=selector['raw'];go=sel['m_GameObject']['m_PathID'];collider=next(c['raw'] for c in pf['geometry_sources'] if c['unity_type']=='CircleCollider2D' and c['raw']['m_GameObject']['m_PathID']==go);transform=next(c['raw'] for c in pf['geometry_sources'] if c['unity_type']=='Transform' and c['raw']['m_GameObject']['m_PathID']==go);assert transform['m_LocalScale']=={'x':1.0,'y':1.0,'z':1.0};radius=collider['m_Radius'];assert sel['_buffKey']=='mark_neutral[effect]' and sel['_buffKeyExcluded']==0 and not sel['_filterTag'] and not sel['_filterTagList'];assert not v['passive_and_skill_components'] and not v['native_enemy']['resolved'].get('skills');uid='unit/ch8/uoffcr/8744707cad2d0fa6';stem='rule/ch8/uoffcr/';behavior='behavior/ch8/uoffcr';abilities=[];selectors=[];p={'schemaVersion':2,'manifest':{'id':'package/ch8/uoffcr/source_v1','requires':['preset/ark_standard'],'metadata':{'required_runtime':CORE,'source_locks':{str(source):sha(source),str(Path(__file__)):sha(Path(__file__)),str(Path(__file__).with_name('policies_v1.py')):sha(Path(__file__).with_name('policies_v1.py'))},'variant_bindings':[{'variant_id':VID,'unit_definition':uid,'native_reference':v['native_reference'],'native_resolved':v['native_enemy']['resolved'],'native_raw_rows':v['native_enemy']['raw_rows'],'source_mode':v['modes'][0],'selector':selector,'range_collider':collider,'range_transform':transform,'root':root,'mover':mover}],'reference_policy':'NativeUnitMode _combat Melee15 versus _attack Ranged15, realtime blocking choosescombat; unblocked ranged requires actual live mark_neutral Buff. Native side2/ground1/category1/free0/camo0/max1/1.2000000477 collider. Captured-live target/currentattributes, shared actor attackclock60; homing10/life5/stopSourceInvalid0 retainedflight. Source marker is zero-stat witness pending original NPCmarker full definition; source name mapping native key explicit. Missing body trigger sorting/movementstop/ASPDgraphic clamp/captured targetfree/interruption remain replaceable reference policy. No sourceSilence immunity copied (DB not defined).','whole_stage_executed':False,'client_verified':False}},'rules':[],'entities':[],'abilities':[],'selectors':[],'behaviors':[],'projectiles':[],'buffs':[{'id':MARKER,'kind':'buff','metadata':{'native_buff_key':'mark_neutral[effect]','scope':'selection-only marker witness; original NPC stats/marker effects source not yet consumed; no attributes or state immunity fabricated'}}]}
 p['rules']=[{'id':stem+'base','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':stem+'qualified','kind':'rule','contract':'targeting.eligibility','dependencies':[stem+'base'],'parameters':{'base_rule':stem+'base','require_marker':True,'marker':MARKER},'implementation':{'type':'provider','provider':'reference.c8.qualification'}},{'id':stem+'score','kind':'rule','contract':'targeting.score','implementation':{'type':'provider','provider':'reference.c8.taunt'}},{'id':stem+'windup','kind':'rule','contract':'ability.windup','implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio,.01)'}},{'id':stem+'behavior','kind':'rule','contract':'behavior.decision','implementation':{'type':'provider','provider':'reference.c8.dual_combat'}},{'id':stem+'steer','kind':'rule','contract':'movement.steering','implementation':{'type':'provider','provider':'ark.movement.steering_velocity'}},{'id':stem+'motion','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'model.projectile.trajectory'}},{'id':stem+'collision','kind':'rule','contract':'projectile.collision','implementation':{'type':'provider','provider':'model.projectile.collision'}}]
 for role in ['combat','attack']:
  node=v['modes'][0]['nodes']['_'+role];raw=node['raw'];assert raw['_damageType']==1 and raw['_attackType']==1 and raw['_selectTargetSource']==2;an=node['animation_binding'];event=next(e for e in an['events'] if e['name']=='OnAttack');assert event['frame']==15;sid='selector/ch8/uoffcr/'+role;aid='ability/ch8/uoffcr/'+role;abilities.append(aid);selectors.append({'key':role,'selector':sid});s={'id':sid,'kind':'selector','region':{'type':'all','blocked_only':True} if role=='combat' else {'type':'radius','radius':radius},'filters':[{'state':'alive'}],'limit':1};
  if role=='attack':s['eligibility']={'rule':stem+'qualified','parameters':{'source_configuration':sel,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':deepcopy(DEFAULT_STATE)}}
  p['selectors'].append(s);effect={'op':'damage','damage_type':'physical','scale':raw['_atkScale'],'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False}}
  if role=='attack':effect['projectile_definition']='projectile/ch8/uoffcr'
  p['abilities'].append({'id':aid,'kind':'ability','selector':sid,'activation':{'mode':'automatic_attack','condition':'inputs.source.components.runtime.blocked_by '+('!=' if role=='combat' else '==')+' None','parameters':{'auto_only':True}},'target_capture':'at_cast','rules':{'ability.windup':stem+'windup','targeting.score':stem+'score'},'timeline':[{'at_seconds':event['seconds'],'effect':effect}],'metadata':{'source_node':node}})
 p['entities']=[{'id':uid,'kind':'entity','tags':['enemy','ground'],'metadata':{'native_variant':VID,'native_reference':v['native_reference']},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':root['raw']['_blockVolume']}},'resources':{'hp':{'initial':a['maxHp'],'capacity':a['maxHp'],'role':'health'}},'selection_state':{**deepcopy(DEFAULT_STATE),'side':1,'motion':1,'category':1,'unit_type':2},'spatial':{'steering':{'rule':stem+'steer','parameters':{'response_factor':mover['raw']['_steeringFactor'],'max_acceleration':mover['raw']['_maxSteeringForce'],'arrival_radius':.05}}},'abilities':abilities,'behavior':{'machine':behavior},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':1}}}];p['behaviors']=[{'id':behavior,'kind':'behavior','initial':'normal','states':{'normal':{}},'transitions':[],'decision':{'rule':stem+'behavior','default_mode':0,'profiles':[{'mode':0,'selectors':selectors,'cast_groups':[{'key':'normal','abilities':abilities}]}]}}];pr=data['projectiles']['projectile_enemy_uoffcr'];simple=next(c['raw'] for c in pr['components'].values() if c['native_class']=='SimpleProjectile');motion=next(c['raw'] for c in pr['components'].values() if c['native_class']=='AdvancedMovement');p['projectiles']=[{'id':'projectile/ch8/uoffcr','kind':'projectile','motion':{'rule':stem+'motion','parameters':{'mode':'homing','speed':motion['_speed']}},'collision':{'rule':stem+'collision','parameters':{'enabled':False}},'lifetime_seconds':simple['_lifeTime'],'max_hits':simple['_maxHitNum'],'can_hit_same_target':bool(simple['_canHitSameTargetMultipleTimes']),'stop_after_max':bool(simple['_stopAfterMaxHit']),'stop_after_first':bool(simple['_stopAfterFirstHit']),'attach_at_launch':False,'completion_blocking':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':bool(motion['_forceReachedWhenTimeup']),'hit_on_expire':bool(simple['_alwaysHitTraceTargetInTheEnd'])},'metadata':{'native_projectile':pr}}];fixture=deepcopy(p);fixture['scenarioDraft']={'id':'scene/uoffcr/compile','ruleset':'ruleset/ark_standard','map':{'rows':1,'cols':3},'objectives':{},'initialEntities':[{'definition':uid,'instanceAlias':'source','position':{'row':0,'col':0}}]};Compiler(providers=providers()).compile(fixture);out=ROOT/'packages/campaign/chapter08_consumers/ranged/uoffcr.module.v1.json';assert not out.exists();out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha':sha(out),'actual_compile':True,'native_block_cost':root['raw']['_blockVolume'],'source_radius':radius}))
if __name__=='__main__':main()
