"""Preserve source graph and explicit reference conflicts for L0 FrostNova."""
import json,hashlib,argparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'packages/campaign/chapter04_boss/frost_combat_v1/source.audit.json'
PINS={'packages/campaign/chapter04_boss_plan/source.reference.json':'7ad2fb46b3e281711b6faf8b7a3bacfb9df6bc11ff32212a8439d8925d6893ec','packages/campaign/chapter04_sources/native.reference.json':'3e392d80d000e27a50f11f2f33b0fa0f6be35dc1e91d7e321e2b9cf9681c4603','packages/campaign/chapter04_boss/m86/rebirth_immunity.reference_model.json':'41bfb7ff3e7dc2cf9efadcdcf2007c7e70cdcb311b5a9712eda8232eca64c5d0'}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 for name,pin in PINS.items():assert sha(ROOT/name)==pin
 plan=json.loads((ROOT/next(iter(PINS))).read_bytes());native=json.loads((ROOT/'packages/campaign/chapter04_sources/native.reference.json').read_bytes());variant=next(v for v in native['variants'].values() if v['native_reference']['id']=='enemy_1505_frstar')
 return {'schema':'ark-sim/frost-combat-source-audit/v1','source_locks':PINS,'variant':variant,'native_enemy':plan['native_enemy'],'components':plan['boss_components'],'modes':plan['boss_modes'],'animations':plan['boss_animation']['parsed'],'projectiles':plan['boss_projectiles'],'sealed_floor_closure':plan['sealed_floor_native'],'enums':plan['enums'],'native_method_bodies_recovered':False,
  'facts':{'normal_animation_OnAttack_frames':[17,28],'normal_waitForAttackEvent':True,'blast_waitForAttackEvent':False,'blast_predelay_raw':.9330000281333923,'blast_quantized_predelay_frame':28,'blast_priority':1,'blast_initial_and_periodic_cooldown':8.5,'blast_scale':1.5,'blast_bb_duration':8,'blast_raw_buff_lifetime':4,'blast_attack_speed_points':-50,'blast_trigger_radius':2.5,'blast_source_center_splash_radius':2,'blast_raw_hit_motion':3,'intrinsic_abnormal_immunes':[0,12,16,25],'initial_sleep_combo_immune':0,'initial_sleep_immunity_removed_by_real_rebirth':True},
  'reference_checked':{'checked_date':'2026-10-03','frost_url':'https://prts.wiki/w/%E9%9C%9C%E6%98%9F','floor_url':'https://prts.wiki/w/%E5%B0%81%E5%8D%B0%E7%9A%84%E5%9C%B0%E9%9D%A2','frost_claims':['L0 HP25000 ATK420 DEF250 RES50, rebirth full health and ATK+50%','Blast trigger2.5, captured target plus source radius2,150% arts, ground only,AS-50 for8s','Enemy skills share attack clock, CD pauses during cast and resets on rebirth','IceShield30s chooses2 deployment eligible cells in radius2, forcibly knocks down occupants'],'floor_claims':['HP100, no hitbox or terrain rewrite; occupies deployment cell','Cannot manually withdraw; source death retention is a declared policy']},
  'model_policies':{'normal_event':'first17 default reference policy; last28/both17_28 alternatives retained. Two raw events alone do not prove two normal damage packets.','blast':'Independent explicit preDelay28, not normal frame17 or double execution of both animation events. Zero-flight source-centered area with captured primary union is reference timing; native collision callbacks remain unknown.','duration':'BB8 reference versus serialized4 seconds selectable','motion':'Reference ground-only versus raw HitBehaviour motion3 selectable','speed':'V2 attack_speed_ratio uses -50/100=-.5 flat; native AttributeType7 ADDITION remains preserved','cooldown':'Initial8.5 activation-relative; cast occupies48-frame Attack animation and periodic CD8.5 pauses until finish, shared normal111tick clock. Interrupt keeps accepted cast clock; rebirth resets8.5. Explicit replaceable time/duration/recovery rules.','targeting':'Normal SOURCE_INPUT_TARGET2 guarded by actual blocker plus original selector. Blast SOURCE_SELECTOR1 uses independently qualified trigger, declared hatred comparator approximation. Native hatred/body logic remains pending.'},
  'ice_shield_audit':{'priority':2,'initial_and_cooldown_seconds':30,'spawn_event_frame':55,'tile_selector':next(v for v in plan['boss_components'].values() if v['native_class']=='TileSelector'),'spawn_token':next(v for v in plan['boss_components'].values() if v['native_class']=='SpawnTokenOnTileAbility'),'source_filter2':'EXCEPT_CHARACTER conflicts with reference occupied-cell knockout capability; preserve raw filter and selectable policy','instant_kill_skip_rebirth':False,'token':'trap_004_iceblock level0','required_generic_input':{'pure_query':['map buildable/passable/options, advanced masks, actual unit/token occupancy, source position/radius, source rule parameters'],'accepted_cast':['ordered eligible tile list captured at cast, RNG stream/counter and uniform no-replacement choice min(2,n), World selected tiles and owned task/generation'],'effect':['55-frame callback revalidates tiles, genuine InstantKill skip_rebirth=False, paid-free token spawn preserving canonical ownership/occupancy and no terrain rewrite/no hitbox']}},
  'missing_runtime_capabilities':['IceShield generic tile-target accepted-cast query/selection and persistent typed tile targets','RNG-backed no-replacement tile selection and actual token occupancy/no-hitbox placement','No exact native animation event routing/body reconstruction'], 'whole_stage_executed':False,'client_verified':False}
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');args=ap.parse_args();raw=(json.dumps(build(),ensure_ascii=False,indent=2)+'\n').encode('utf8')
 if args.check:assert OUT.read_bytes()==raw
 else:OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_bytes(raw) if not OUT.exists() else (_ for _ in ()).throw(FileExistsError('Preserve source audit'))
 print(json.dumps({'path':str(OUT),'sha256':sha(OUT)}))
