"""Partial L0 Frost combat, explicit source/reference policies; IceShield absent."""
from pathlib import Path
from copy import deepcopy
import json,hashlib,argparse
ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'packages/campaign/chapter04_boss/frost_combat_v6';AUDIT=ROOT/'packages/campaign/chapter04_boss/frost_combat_v1/source.audit.json';BASE=ROOT/'packages/campaign/chapter04_boss/m86/rebirth_immunity.reference_model.json'
AUDIT_PIN='3202824733c3f49e4404b5c168a546171b69e636dcf8866802293b5c92791029';BASE_PIN='41bfb7ff3e7dc2cf9efadcdcf2007c7e70cdcb311b5a9712eda8232eca64c5d0'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
NORMAL='ability/frost/normal';BLAST='ability/frost/blast';SLOW='buff/frost/arctic_slow';SN='selector/frost/normal';SB='selector/frost/blast'
DEFAULTS={'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False}
def provider(ident,contract,name,params=None):return {'id':ident,'kind':'rule','contract':contract,'implementation':{'type':'provider','provider':name},'parameters':params or {}}
def build(normal_event='first17',duration='bb8',hit_motion='reference_ground'):
 assert sha(AUDIT)==AUDIT_PIN and sha(BASE)==BASE_PIN
 if normal_event not in ['first17','last28','both17_28'] or duration not in ['bb8','raw4'] or hit_motion not in ['reference_ground','source_motion3']:raise ValueError('Explicit Frost policy required')
 audit=json.loads(AUDIT.read_bytes());p=json.loads(BASE.read_bytes());unit=p['entities'][0];a=audit['variant']['native_enemy']['resolved'];raw=audit['modes'][0]['nodes']['_attack']['raw'];components=audit['components']
 normal_cfg=next(v['raw'] for v in components.values() if v['native_class']=='AdvancedSelector' and v['gameobject_path_id']==audit['modes'][0]['nodes']['_attackTrigger']['gameobject_path_id'])
 blast_raw=next(v['raw'] for v in components.values() if v['native_class']=='RangedAttack' and v['gameobject_name']=='ArcticBlast');blast_cfg=next(v['raw'] for v in components.values() if v['native_class']=='AdvancedSelector' and v['gameobject_path_id']!=audit['modes'][0]['nodes']['_attackTrigger']['gameobject_path_id'])
 assert raw['_waitForAttackEvent']==1 and raw['_selectTargetSource']==2 and blast_raw['_waitForAttackEvent']==0 and blast_raw['_selectTargetSource']==1
 assert [e['frame'] for e in audit['animations']['animations']['Attack']['events']]==[17,28]
 assert a['skills'][0]['cooldown']==a['skills'][0]['initCooldown']==8.5 and a['skills'][0]['priority']==1
 bb={b['key']:b['value'] for b in a['skills'][0]['blackboard']};assert bb=={'duration':8,'attack_speed':-50,'atk_scale':1.5,'range_radius':2.5}
 hit=next(v['raw'] for v in audit['projectiles']['projectile_frstar_s1']['components'].values() if v['native_class']=='HitBehaviour')
 hit_cfg=deepcopy(blast_cfg);hit_cfg.update({'_'+key:value for key,value in hit['_targetOptions'].items() if '_'+key in hit_cfg});hit_cfg['_targetMotion']=1 if hit_motion=='reference_ground' else 3;hit_cfg['_forceIgnoreCamouflage']=hit['_ignoreCamouflage']
 def eligibility(cfg):return {'rule':'rule/frost/eligibility','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':DEFAULTS}}
 p['rules'].extend([provider('rule/frost/eligibility','targeting.eligibility','model.targeting.eligibility'),provider('rule/frost/trajectory','projectile.trajectory','model.projectile.trajectory'),provider('rule/frost/collision','projectile.collision','model.projectile.collision'),provider('rule/frost/steering','movement.steering','ark.movement.steering_velocity'),provider('rule/frost/radius','area.members','model.area.qualified_radius',{'radius':2,'include_primary':True,'eligibility':eligibility(hit_cfg)}),
 {'id':'rule/frost/combat_guard','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'graph','nodes':[{'id':'base','rule':'rule/frost/eligibility','inputs':{name:'inputs.'+name for name in ['source','candidate','selector','selection_states','parameters']}},{'id':'answer','expression':"{'accepted':nodes.base.accepted and (inputs.source.components.runtime.blocked_by == None or inputs.source.components.runtime.blocked_by == inputs.candidate.id),'reason':nodes.base.reason}"}],'output':'nodes.answer'}},
 {'id':'rule/frost/priority','kind':'rule','contract':'targeting.score','implementation':{'type':'expression','expression':"-100000*(inputs.candidate.components.attributes.base.taunt_level if 'taunt_level' in inputs.candidate.components.attributes.base else 0)-inputs.candidate.id"}},
 {'id':'rule/frost/decision','kind':'rule','contract':'behavior.decision','implementation':{'type':'graph','nodes':[{'id':'ready','expression':"inputs.clock.time >= inputs.source.components.runtime.cooldowns['ability/frost/blast']"},{'id':'target','expression':'(inputs.eligible_ids.normal != []) or (nodes.ready and (inputs.eligible_ids.blast != []))'},{'id':'live','expression':'inputs.visibility.alive and inputs.visibility.active and not inputs.visibility.hidden'},{'id':'busy','expression':'(inputs.cast_groups.normal != []) or (inputs.cast_groups.blast != [])'},{'id':'answer','expression':"{'move':nodes.live and inputs.controls.move and inputs.blocked_by == None and not nodes.busy and not nodes.target,'attack':nodes.live and inputs.controls.attack and inputs.controls.abilities and not nodes.busy and nodes.target}"}],'output':'nodes.answer'}}])
 p['selectors'].extend([{'id':SN,'kind':'selector','region':{'type':'radius','radius':a['rangeRadius']},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{**eligibility(normal_cfg),'rule':'rule/frost/combat_guard'}},{'id':SB,'kind':'selector','region':{'type':'radius','radius':bb['range_radius']},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':eligibility(blast_cfg)}])
 p['rules'].append({'id':'rule/frost/status_active','kind':'rule','contract':'buff.applicability','implementation':{'type':'expression','expression':'True'}})
 p['buffs'].append({'id':SLOW,'kind':'buff','active_rule':'rule/frost/status_active','duration_seconds':bb['duration'] if duration=='bb8' else blast_raw['_activeBuffs'][0]['lifeTime'],'modifiers':[{'attribute':'attack_speed_ratio','layer':'flat','value':bb['attack_speed']/100}],'stacking':{'mode':'refresh','max_stacks':1},'metadata':{'native_AttributeType':7,'native_formula_item':0,'source_points':-50,'ratio_conversion':100,'raw_lifetime4':4,'selected_duration_policy':duration,'not_cast_owned':True,'applicability_policy':'Always active native isSilenceable0; explicit M84 boundary expiry observer opt-in'}})
 timeline_frames={'first17':[17],'last28':[28],'both17_28':[17,28]}[normal_event]
 p['abilities'].extend([{'id':NORMAL,'kind':'ability','selector':SN,'rules':{'targeting.score':'rule/frost/priority'},'activation':{'mode':'automatic_attack','parameters':{'auto_only':True}},'duration_seconds':48/30,'timeline':[{'at':frame,'effect':{'op':'damage','damage_type':'arts','scale':1,'projectile_definition':'projectile/frost/normal','damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}} for frame in timeline_frames]},
 {'id':BLAST,'kind':'ability','selector':SB,'rules':{'targeting.score':'rule/frost/priority'},'initial_cooldown_seconds':8.5,'duration_seconds':48/30,'cooldown_seconds':8.5,'activation':{'mode':'manual','forbidden_source_flags':[0,12],'parameters':{'auto_only':True,'auto_when_ready':True,'replace_attack':True,'requires_targets':True}},'timeline':[{'at':28,'effect':{'op':'area','center':'source','membership_rule':'rule/frost/radius','filters':[{'tag':'player'}],'effects':[{'op':'damage','damage_type':'arts','scale':bb['atk_scale'],'damage_flags':{'source_attack_type':'SPLASH','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'},'on_success':[{'op':'apply_buff','buff':SLOW}]}]}}]}])
 normal_proj=audit['projectiles']['projectile_frstar'];simple=next(v['raw'] for v in normal_proj['components'].values() if v['native_class']=='SimpleProjectile');movement=next(v['raw'] for v in normal_proj['components'].values() if v['native_class']=='AdvancedMovement')
 assert simple['_lifeTime']==10 and movement['_speed']==10
 p['projectiles']=[{'id':'projectile/frost/normal','kind':'projectile','motion':{'rule':'rule/frost/trajectory','parameters':{'mode':'homing','speed':movement['_speed']}},'collision':{'rule':'rule/frost/collision','parameters':{'enabled':True,'radius':0}},'lifetime_seconds':simple['_lifeTime'],'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'cancel','target_hidden':'cancel','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'on_invalid':[]}]
 p['behaviors']=[{'id':'behavior/frost/combat','kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/frost/decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'normal','selector':SN},{'key':'blast','selector':SB}],'cast_groups':[{'key':'normal','abilities':[NORMAL]},{'key':'blast','abilities':[BLAST]}],'parameters':{}}]}}]
 unit['components'].update(abilities=[BLAST,NORMAL],behavior={'machine':'behavior/frost/combat'});unit['components']['spatial']['steering']={'rule':'rule/frost/steering','parameters':{'response_factor':8,'max_acceleration':10,'arrival_radius':.05}};unit['components']['rebirth']['reset_cooldowns']=[{'ability':BLAST,'initial_delay_seconds':8.5}]
 p['manifest']['id']='package/frost/combat/'+normal_event+'/'+duration+'/'+hit_motion
 p['manifest']['metadata'].update(source_locks={str(AUDIT.relative_to(ROOT)):AUDIT_PIN,str(BASE.relative_to(ROOT)):BASE_PIN},frost_combat_builder_sha256=sha(Path(__file__)),normal_event_policy=normal_event,blast_duration_policy=duration,blast_motion_policy=hit_motion,source_audit=audit,implemented=['M86 real rebirth/intrinsic and sleep immunity','normal source ranged policy and ArcticBlast partial consumer'],missing_runtime_capabilities=audit['missing_runtime_capabilities'],whole_stage_executed=False,client_verified=False)
 return p
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');args=ap.parse_args()
 OUT.mkdir(parents=True,exist_ok=True)
 for policies in [('first17','bb8','reference_ground'),('last28','bb8','reference_ground'),('both17_28','bb8','reference_ground'),('first17','raw4','source_motion3')]:
  raw=(json.dumps(build(*policies),ensure_ascii=False,indent=2)+'\n').encode('utf8');dest=OUT/('.'.join(policies)+'.json')
  if args.check:assert dest.read_bytes()==raw
  else:
   with dest.open('xb') as f:f.write(raw)
  print(json.dumps({'path':str(dest),'sha256':sha(dest)}))
