"""Exact stage eligibility scope and primary source selector evidence; not an NPC producer clone."""
import hashlib,json
from pathlib import Path
from collections import Counter
from tools.chapter08_special.build_closure_v1 import walk
ROOT=Path(__file__).resolve().parents[2];SOURCE=ROOT/'packages/campaign/chapter08_source_prepare/integration';OUT=ROOT/'packages/campaign/chapter08_consumers/special/uoffcr_marker_gate_v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 plan=json.loads((SOURCE/'source.plan.v1.json').read_bytes());enemies=json.loads((SOURCE/'enemies.native.v1.json').read_bytes());stage=plan['stages']['level_main_08-16'];vid='enemy_1107_uoffcr@0/8744707cad2d0fa6';v=enemies['variants'][vid];selector=next(c for c in enemies['prefabs'][v['prefab_key']]['components'].values() if c['native_class']=='AdvancedSelectorWithTagAndBuffKey');r=selector['raw'];assert r['_buffKey']=='mark_neutral[effect]' and r['_buffKeyExcluded']==r['_tagExcluded']==r['_checkOrInsteadOfAnd']==0 and r['_buffs']==[] and r['_filterTag']=='' and r['_filterTagList']==[]
 selected=[enemies['variants'][i]['prefab_key'] for i in stage['variant_ids']];buff_defs=[];buff_consumers=[]
 for key in selected:
  for pointer,node in walk(enemies['prefabs'][key]):
   if not isinstance(node,dict):continue
   if node.get('buffKey')=='mark_neutral[effect]':buff_defs.append({'prefab':key,'pointer':pointer,'raw':node})
   if node.get('_buffKey')=='mark_neutral[effect]':buff_consumers.append({'prefab':key,'pointer':pointer})
 dump=ROOT.parent/'Ark_data/Il2CppDumper_current/dump.cs';text=dump.read_text(encoding='utf8');start=text.index('public class AdvancedSelectorWithTagAndBuffKey :');stop=text.index('// Namespace:',start+100)
 actors=[x['native'] for x in stage['actions'] if x['native']['actionType']=='SPAWN'];assert sum(a['count'] for a in actors)==32
 result={'schema':'ark-sim/uoffcr-native-marker-stage-gate/v1','variant':vid,'source_guards':{str(p):sha(p) for p in [SOURCE/'source.plan.v1.json',SOURCE/'enemies.native.v1.json',SOURCE/'predefines.native.v2.json',SOURCE/'environment.native.v1.json']},'native_DB_description':v['native_enemy']['resolved']['description'],'source_selector':selector,'native_mode_nodes':v['modes'][0]['nodes'],'native_schema':{'path':str(dump),'sha256':sha(dump),'declaration_excerpt':text[start:stop],'body_verified':False},'source_interpretation':{'single_buff':'Positive include marker condition from native _buffKeyExcluded0, specific nonempty buffKey; this class performs ConditionFilter/_CheckBuff before/within OnPostFilter, not SecondaryFilter preference enum.','multi_buff':'Empty _buffs does not turn off legacy scalar _buffKey. _checkOrInsteadOfAnd0 only governs combination when multi-list populated (Inspect buffsNotEmpty source); no tags specified. Exact implementation unavailable, reference rule explicit.','qualified_targets':'Only source ground/relative-enemy/category1/free/camo gates AND actual current marker. FilterSource0 means any issuer; filterTokenHost0 imposes no host condition.','normal_combat':'Separate source MeleeAttack has no marker dependency; an actual blocking ordinary player remains eligible.','native_description_support':'Fixed DB explicitly limits remote weapon targets to Ursus civilians and fighter Talula; current PRTS corroborates. No derivation by enemy name.'},'selected_stage_inventory':{'stage':'JT8-2/level_main_08-16','SPAWN_births':32,'actor_spawn_keys':dict(Counter(a['key'] for a in actors)),'all_SPAWN_records':actors,'normal_predefines':stage['predefines'],'hard_predefines':stage['hard_predefines'],'globalBuffs':stage['native_document']['globalBuffs'],'normal_runes':stage['normal_runes'],'selected_prefabs':selected,'marker_definition_producers_in_selected_prefabs':buff_defs,'marker_reference_consumers':buff_consumers},'stage_policy':'No native NPC/predefined character/card/token or producer of this marker is present in selected JT8-2. Therefore its ranged selector legitimately has no ordinary-roster targets; only regular combat behavior is required there. Positive mark fixtures remain validation witnesses, not stage NPC/source production. All selected roster buffs must also be checked before final join.', 'external_reference':{'url':'https://prts.wiki/w/%E6%84%9F%E6%9F%93%E8%80%85%E7%BA%A0%E5%AF%9F%E5%AE%98','retrieved':'2026-10-04','paraphrase':'Current reference identifies ordinary melee and remote attacks against Ursus civilians/fighter Talula; fixed DB already supplies this qualification. No web values override fixed source.'},'native_method_body_verified':False,'whole_stage_executed':False,'client_verified':False,'source_marker_witness_is_not_a_complete_NPC_module':True}
 OUT.mkdir(exist_ok=True);out=OUT/'source.audit.json';assert not out.exists();out.write_bytes((json.dumps(result,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'path':str(out),'sha256':sha(out),'marker_producer_count':len(buff_defs),'spawn_births':sum(a['count'] for a in actors)}))
if __name__=='__main__':main()
