"""Exact frozen emppnt/empace content; generic kernel stays read-only."""
import hashlib,json,sys
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CAND=ROOT.parent/'unpack_work/campaign_area_projection_v2_candidate'
sys.path.insert(0,str(CAND));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from ark_sim.domains.selection import DEFAULT_STATE,SWITCHES
from tools.chapter08_special.policies_v1 import providers
CORE='3992a0e6726dd7128b9ee36e542be38376f7488d2d8165af33bdc9c662a79000'
OUT=ROOT/'packages/campaign/chapter08_consumers/special';SOURCE=OUT/'source.closure.v1.json'
MARKER='buff/ch8/source/mark_neutral[effect]'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def typed(raw):
 return {'source_configuration':{**{k:False for k in SWITCHES},**{k:v for k,v in raw.items() if k in SWITCHES or k in ['_targetSide','_targetMotion','_targetCategory','_professionMask','_abnormalFlag','_abnormalCombo','_excludeAbnormalFlag','_unitTypeMask']}},'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':deepcopy(DEFAULT_STATE)}
def rule(identifier,contract,provider=None,expression=None,parameters=None,dependencies=None):
 r={'id':identifier,'kind':'rule','contract':contract,'implementation':{'type':'provider','provider':provider} if provider else {'type':'expression','expression':expression}}
 if parameters:r['parameters']=parameters
 if dependencies:r['dependencies']=dependencies
 return r
def build(name,vid):
 data=json.loads(SOURCE.read_bytes());v=data['variants'][vid];pf=data['prefabs'][v['prefab_key']];cs=pf['components'];a=v['native_enemy']['resolved']['attributes'];root=next(c for c in cs.values() if c['native_class']=='Enemy');mover=next(c for c in cs.values() if c['native_class']=='MoveController');sel=next(c for c in cs.values() if c['native_class']=='SecondaryFilterAdvancedSelector')['raw'];mode=v['modes'][0];stem='rule/ch8/'+name;uid='unit/ch8/'+name+'/'+vid.split('/')[-1];aid='ability/ch8/'+name;sid='selector/ch8/'+name
 assert sel['_secondaryFilter']==3 and sel['_postFilter']==4 and sel['_buffKey']=='mark_neutral[effect]' and sel['_sortByTauntAtLast']==1
 p={'schemaVersion':2,'manifest':{'id':'package/ch8/'+name+'/source_v1','requires':['preset/ark_standard'],'metadata':{'required_runtime':CORE,'source_locks':{str(SOURCE):sha(SOURCE),str(Path(__file__)):sha(Path(__file__)),str(Path(__file__).with_name('policies_v1.py')):sha(Path(__file__).with_name('policies_v1.py'))},'variant_bindings':[{'variant_id':vid,'unit_definition':uid,'native_reference':v['native_reference'],'native_resolved':v['native_enemy']['resolved'],'native_raw_rows':v['native_enemy']['raw_rows'],'native_mode':mode}],'reference_policy':{'secondary_selector':'SPECIFIED_BUFF3 interpreted as marked group first, then HATRED_DES4 effective current taunt descending, then stable ID. No finite priority constant. Missing native body: explicitly replaceable preference/fallback policy.','undefined_immunities':'Absent m_defined fields are recorded as undefined, not proved false; explicit model defaults use no immunities.','timing':'TimeMode0 affectedSlow1: each native windup and full busy duration divided by max(currentASPD,.01), ceil to quantum. Graphic clamp/minimum.01 remain reference policies.','combat':'Empace INPUT_TARGET2 uses actual current blocker when blocked and original ranged target when unblocked; only one normal cast at a time. Emppnt src1/time1 uses own selector refreshed at OnAttack and is not forcibly bound to blocker.','projectile_reads':'Emppnt useCachedAtkOnly1: source at_cast, target at_hit. Empace0: source/target at_hit; generic retained-source launch snapshot fallback remains explicit reference policy.','client_verified':False},'whole_stage_executed':False,'independent_reviewed':False}},'entities':[],'abilities':[],'selectors':[],'behaviors':[],'buffs':[{'id':MARKER,'kind':'buff','metadata':{'native_buff_key':'mark_neutral[effect]','scope':'selection-only marker witness; original NPC stats/marker effects source not yet consumed; no attributes or state immunity fabricated'}}],'projectiles':[],'rules':[]}
 p['rules']=[rule(stem+'/eligibility','targeting.eligibility','model.targeting.eligibility'),rule(stem+'/selection','targeting.selection','reference.c8.special.selection',parameters={'marker':MARKER,'layers':['flat','direct_ratio','final_ratio'],'attribute_rule':'rule/ark_attribute_layers'},dependencies=['rule/ark_attribute_layers']),rule(stem+'/windup','ability.windup',expression='inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio,.01)'),rule(stem+'/duration','ability.duration',expression='inputs.duration_parameters.seconds / max(inputs.attributes.attack_speed_ratio,.01)'),rule(stem+'/motion','projectile.trajectory','model.projectile.trajectory'),rule(stem+'/collision','projectile.collision','model.projectile.collision'),rule(stem+'/steer','movement.steering','ark.movement.steering_velocity')]
 unit={'id':uid,'kind':'entity','tags':['enemy','ground'],'metadata':{'native_variant':vid,'native_reference':v['native_reference']},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'mass_level':a['massLevel'],'block_cost':root['raw']['_blockVolume']}},'resources':{'hp':{'initial':a['maxHp'],'capacity_attribute':'max_hp','role':'health'}},'selection_state':{**deepcopy(DEFAULT_STATE),'side':1,'motion':1,'category':1,'unit_type':2},'spatial':{'steering':{'rule':stem+'/steer','parameters':{'response_factor':mover['raw']['_steeringFactor'],'max_acceleration':mover['raw']['_maxSteeringForce'],'arrival_radius':.05}}},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':v['native_enemy']['resolved']['lifePointReduce']},'abilities':[],'buffs':{'initial':[]},'ability_arbitration':{'busy':'all_casts','entries':[]}}};p['entities']=[unit]
 roles=['attack'] if name=='emppnt' else ['combat','attack'];selector_params=typed(sel)
 for role in roles:
  node=mode['nodes']['_'+role];raw=node['raw'];an=node['animation_binding'];event=next(e for e in an['events'] if e['name']=='OnAttack');identifier=aid+'/'+role;selector=sid+'/'+role
  assert raw['_timeMode']==0 and raw['_affectedBySlowDown']==1 and raw['_activeBuffs']==[]
  selector_def={'id':selector,'kind':'selector','region':{'type':'all','blocked_only':True} if role=='combat' else {'type':'radius','radius':v['native_enemy']['resolved']['rangeRadius']},'filters':[{'state':'alive'}],'limit':1,'eligibility':{'rule':stem+'/eligibility','parameters':deepcopy(selector_params)}};p['selectors'].append(selector_def)
  effect={'op':'damage','damage_type':'physical','scale':raw['_atkScale'],'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_cast' if raw.get('_useCachedAtkOnly')==1 else 'at_hit','target_attributes':'at_hit'}}
  if role=='attack':effect['projectile_definition']='projectile/ch8/'+name
  if name=='emppnt':
   pr=data['projectiles'][raw['_projectileKey']];hit=next(c['raw'] for c in pr['components'].values() if c['native_class']=='HitBehaviour');go=hit['m_GameObject']['m_PathID'];collider=next(g['raw'] for g in pr['geometry_sources'] if g['unity_type']=='CircleCollider2D' and g['raw']['m_GameObject']['m_PathID']==go);options={'_'+k:v for k,v in hit['_targetOptions'].items()};options['_forceIgnoreCamouflage']=hit['_ignoreCamouflage'];options['_needProfessionMask']=bool(options.get('_professionMask',0));options['_excludeSomeAbnormalFlags']=False;params=typed(options)
   p['rules'].append(rule(stem+'/area','area.members','reference.c8.special.area',parameters={'radius':collider['m_Radius'],'eligibility':{'rule':stem+'/eligibility','parameters':params}},dependencies=[stem+'/eligibility']))
   effect={'op':'area','target':'source','center':'source','projectile_definition':'projectile/ch8/'+name,'membership_rule':stem+'/area','selection_projection':{'defaults':deepcopy(DEFAULT_STATE)},'effects':[{k:v for k,v in effect.items() if k!='projectile_definition'}]}
  activation={'mode':'automatic_attack','settle_blocking':True,'parameters':{'auto_only':True}}
  if name=='empace':activation['condition']='inputs.source.components.runtime.blocked_by '+('!=' if role=='combat' else '==')+' None'
  p['abilities'].append({'id':identifier,'kind':'ability','selector':selector,'target_capture':'each_hit' if raw['_selectTargetTiming']==1 else 'at_cast','activation':activation,'duration_seconds':an['duration']['seconds'],'rules':{'ability.windup':stem+'/windup','ability.duration':stem+'/duration','targeting.selection':stem+'/selection'},'timeline':[{'at_seconds':event['seconds'],'effect':effect}],'metadata':{'native_component':node,'native_OnAttack_frame':event['frame']}})
  unit['components']['abilities'].append(identifier);unit['components']['ability_arbitration']['entries'].append({'ability':identifier,'priority':0,'attack_clock':True,'require_attack_control':True})
 pr=data['projectiles']['projectile_enemy_'+name];simple=next(c['raw'] for c in pr['components'].values() if c['native_class']=='SimpleProjectile')
 projectile={'id':'projectile/ch8/'+name,'kind':'projectile','collision':{'rule':stem+'/collision','parameters':{'enabled':False}},'lifetime_seconds':simple['_lifeTime'],'max_hits':None if simple['_hitNumType']==2 else simple['_maxHitNum'],'can_hit_same_target':bool(simple['_canHitSameTargetMultipleTimes']),'stop_after_max':bool(simple['_stopAfterMaxHit']),'stop_after_first':bool(simple['_stopAfterFirstHit']),'attach_at_launch':False,'completion_blocking':False,'metadata':{'native_projectile':pr}}
 if name=='emppnt':
  attach=next(c['raw'] for c in pr['components'].values() if c['native_class']=='AttachToTarget');p['rules'].append(rule(stem+'/delayed_point','projectile.trajectory','reference.c8.special.delayed_point'));projectile['motion']={'rule':stem+'/delayed_point','parameters':{'delay_seconds':attach['_delayToStart']}};projectile['lifecycle']={'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':False,'hit_on_reach':True,'force_reach_on_expire':bool(simple['_alwaysReachInTheEnd']),'hit_on_expire':False};p['manifest']['metadata']['reference_policy']['attach']='Captured map point at launch, follow0/keepUpdate0; delay3 before one reach AoE, retain original10s lifetime. HitNumType INFINITY2 does not become raw maxHit1. No forced trace hit when target moves/dies.'
  passive=next(c for c in cs.values() if c['native_class']=='PassiveBuffAbility');assert passive['gameobject_name']=='ScanRange'
  for b in passive['raw']['_buffs']:
   assert b['templateKey']=='empty' and not b['loadFromDB'] and b['attributes']['attributeModifiers']==[];bid='buff/ch8/emppnt/'+b['buffKey'];p['buffs'].append({'id':bid,'kind':'buff','metadata':{'native_inline_buff':b,'actual_empty_bson_sha256':data['bson_empty']['document_sha256'],'semantic_scope':'Persist original visual marker Buff instance; native empty template has no gameplay action/stat modifier'}});unit['components']['buffs']['initial'].append(bid)
 else:
  motion=next(c['raw'] for c in pr['components'].values() if c['native_class']=='AdvancedMovement');projectile['motion']={'rule':stem+'/motion','parameters':{'mode':'homing','speed':motion['_speed']}};projectile['lifecycle']={'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':bool(motion['_forceReachedWhenTimeup']),'hit_on_expire':bool(simple['_alwaysHitTraceTargetInTheEnd'])}
  parent=next(c for c in cs.values() if c['native_class']=='ToggleablePassiveBuffAbility');checker=cs[str(parent['raw']['_checker']['m_PathID'])]['raw'];buff=parent['raw']['_buffs'][0];bb={r['key']:r['value'] for r in v['native_enemy']['resolved']['talentBlackboard']};assert checker['_toggleOnce']==checker['_useLTForMax']==0 and checker['_maxHpRatio']==.5 and bb['atkup.atk']==1
  p['rules'].append(rule(stem+'/half','buff.applicability','reference.c8.special.half_hp',parameters={'attribute_rule':'rule/ark_attribute_layers','layers':['flat','direct_ratio','final_ratio'],'minimum_ratio':checker['_minHpRatio'],'maximum_ratio':checker['_maxHpRatio']},dependencies=['rule/ark_attribute_layers']));bid='buff/ch8/empace/'+buff['buffKey'];p['buffs'].append({'id':bid,'kind':'buff','active_rule':stem+'/half','modifiers':[{'attribute':'atk','layer':'direct_ratio','value':bb['atkup.atk']}],'metadata':{'native_parent':parent,'native_checker':checker,'native_inline_buff':buff,'source_empty_bson_sha256':data['bson_empty']['document_sha256']}});unit['components']['buffs']['initial'].append(bid);p['manifest']['metadata']['reference_policy']['threshold']='Dynamic current HP / effective standard-layer maxHP <=.5 including equality, restoreDelay0 and toggleOnce0; heal above threshold deactivates, can reactivate. BuffisSilenceable0 means no silence suppression. Boundary reconciliation is reference timing.'
 p['projectiles'].append(projectile)
 # Movement uses original selector-qualified ranged targets; melee choice is actor-owned arbitration.
 unit['components']['behavior']={'machine':'behavior/ch8/'+name};p['rules'].append(rule(stem+'/decision','behavior.decision','reference.c8.special.dual'))
 p['behaviors']=[{'id':'behavior/ch8/'+name,'kind':'behavior','initial':'normal','states':{'normal':{}},'decision':{'rule':stem+'/decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'combat','selector':sid+('/combat' if name=='empace' else '/attack')},{'key':'attack','selector':sid+'/attack'}],'cast_groups':[{'key':'normal','abilities':unit['components']['abilities']}]}]}}]
 return p
def main():
 assert implementation_digest()==CORE
 for name,vid in [('emppnt','enemy_1112_emppnt@0/4f469bc1099e78dd'),('empace','enemy_1113_empace@0/1fc76d096d0bb1df')]:
  p=build(name,vid);arb=p['entities'][0]['components']['ability_arbitration'];arb['priority_order']='higher_first'
  for entry in arb['entries']:entry.update(condition='True',parameters={})
  q=deepcopy(p);q['scenarioDraft']={'id':'scene/ch8/'+name+'/compile','ruleset':'ruleset/ark_standard','map':{'rows':5,'cols':5},'objectives':{},'initialEntities':[{'definition':p['entities'][0]['id'],'instanceAlias':'source','position':{'row':2,'col':2}}]};Compiler(providers=providers()).compile(q);out=OUT/(name+'.module.v1.json');assert not out.exists();out.write_bytes((json.dumps(p,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'name':name,'sha256':sha(out),'actual_compile':True}))
if __name__=='__main__':main()
