"""Primary serialized Bena/bleeding relations and versioned external reference notes."""
import hashlib,json
from pathlib import Path
from tools.build_chapter01_enemy_sources import bson_source
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'packages/campaign/chapter08_consumers/special/dragon_fire_independent_v2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 b=bson_source({'dragon_fire[timer]','dragon_fire[damage]','bena_switchbegin','bena_switchend','bena_tr','bena_standin[switch]','bena_stand[resetblock]','bena_s_2'});dump=ROOT.parent/'Ark_data/Il2CppDumper_current/dump.cs';text=dump.read_text(encoding='utf8');start=text.index('public enum BuffData.OverrideType');stop=text.index('\n}',start)+2
 result={'schema':'ark-sim/dragon-fire-independent-source-review/v1','bson':b,'enum_source':{'path':str(dump),'sha256':sha(dump),'override_excerpt':text[start:stop]},'primary_source_relationships':['Parent ON_START only creates derived child when child not already present; finishDerivedBuffIfParentFinishFalse keeps child through parent expiry. This does not prove no damage-rate reset.','Child ON_START is BleedingDamageIncreasingReset; trigger1s/infinite lifetime, PURE BUFF ignoreSPtrue and skipModifierfalse. Exact first tick arithmetic/body is not recovered.','Bena switchbegin/switchend ClearAllBuffs retain only named Bena keys and alsoRemoveDurableFalse. Both dragon_fire and derived child are isDurableFalse, so their infinity lifetime is not immunity to clear. New child after such clearing necessarily re-enters ON_START reset.','Bena_s_2 uses DamageViaMaxHpRatio with skipModifiertrue, separate from dragon_fire skipModifierfalse; do not infer identical modifier bypass or source attribution.'], 'external_reference':{'url':'https://prts.wiki/w/%E5%A1%94%E9%9C%B2%E6%8B%89','retrieved_date':'2026-10-04','evidence_origin':'web search page excerpt; not an asserted raw HTML byte snapshot','paraphrase':'The current reference page describes a nonstacking burn that refreshes its duration on repeated application, fixed damage rising from50 to230 over30 seconds, and damage-rate reset when the effect ends. Resistance changes duration while tick and ramp intervals remain fixed.','version_policy':'External current-page behavior corroborates fixed source enum/BB, but native body and exact packet phase remain replaceable and client-unverified.'},'source_policy_assessment':{'v1_v2':'Rejected repeat-noop and permanent230 after a timer gap by exact EXTEND3 plus reference behavior; actual full counters saved in peer report.','v3':'Corrected refresh/reset tested under3992 in six fresh independent scenes and complete CP/head/event domain. Same-child refresh generation restart is a reference translation of reset; not native ON_START invocation certified.','remaining':'Dynamic status changes to remaining timer lifetime and first packet/phase native body unresolved; no complete Boss/stage assertion.'},'actual_report':{'path':str(OUT/'report.json'),'sha256':sha(OUT/'report.json')},'guards':{'root_v3':sha(ROOT/'packages/campaign/chapter08_consumers/boss/dragon_fire.module.v3.json')},'client_verified':False}
 out=OUT/'sources.review.json';assert not out.exists();out.write_bytes((json.dumps(result,ensure_ascii=False,indent=2)+'\n').encode());pins={str(p.relative_to(ROOT)):sha(p) for p in OUT.rglob('*') if p.is_file()};freeze=OUT/'freeze.json';assert not freeze.exists();freeze.write_bytes((json.dumps({'schema':'ark-sim/dragon-fire-independent-freeze/v1','status':'passed_declared_corrected_source_policies','report_sha256':sha(OUT/'report.json'),'source_review_sha256':sha(out),'pins':pins,'whole_boss_approved':False,'client_verified':False},ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'sources_sha256':sha(out),'freeze_sha256':sha(freeze),'pins':len(pins)}))
if __name__=='__main__':main()
