"""Freeze two authored consumers without granting stage/client/independent admission."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'packages/campaign/chapter08_consumers/special'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 dump=ROOT.parent/'Ark_data/Il2CppDumper_current/dump.cs';text=dump.read_text(encoding='utf-8');snippets={}
 for name,start,end in [('secondary_selector','public enum SecondaryFilterAdvancedSelector.SecondaryFilterType','public struct SecondaryFilterAdvancedSelector.BuffKeyPair'),('LifeType','public enum LifeType','public enum AttributeType')]:
  a=text.index(start);b=text.index(end,a);snippets[name]=text[a:b]
 enum={'source':str(dump),'sha256':sha(dump),'snippets':snippets,'postfilter4':'HATRED_DES =4 observed at line432136','version_policy':'Current IL2CPP enum/schema evidence is separately versioned from fixed56 tables/assets; no native method body equivalence asserted.'}
 ep=OUT/'enum.source.v1.json';assert not ep.exists();ep.write_bytes((json.dumps(enum,ensure_ascii=False,indent=2)+'\n').encode())
 paths=[p for p in OUT.rglob('*') if p.is_file() and p.suffix in ['.json','.jsonl']];paths += list((ROOT/'tools/chapter08_special').glob('*.py'))
 author=json.loads((OUT/'author.v3.tests.json').read_bytes());bounds=json.loads((OUT/'boundaries.v2.tests.json').read_bytes());proof=json.loads((OUT/'durable.proofs.v1.json').read_bytes())
 assert author['actual_exit']==bounds['actual_exit']==0 and author['guards_equal'] and bounds['guards_equal'] and proof['guards_equal']
 report={'schema':'ark-sim/chapter08-special-author-final/v1','core':'3992a0e6726dd7128b9ee36e542be38376f7488d2d8165af33bdc9c662a79000','final_modules':{'enemy_1112_emppnt@0/4f469bc1099e78dd':{'path':str(OUT/'emppnt.module.v3.json'),'sha256':sha(OUT/'emppnt.module.v3.json')},'enemy_1113_empace@0/1fc76d096d0bb1df':{'path':str(OUT/'empace.module.v3.json'),'sha256':sha(OUT/'empace.module.v3.json')}},'actual_passed_tests':18,'durable_public_proofs':3,'supported':{'emppnt':'One shared native ranged PPtr, cast-source cachedATK/currentDEF, selector OnAttack refresh, marks/HATE lex preference, sourceground+air qualifiers,3s frozen point/1.2 collider all-current-member AoE including camo, targetmove miss/source retire retain, native10s lifetime/infinitehit type, two actually empty ScanRange Buff instances','empace':'True blocker melee15/full45 vs unblocked homing ranged31/full62 at50% scale, original135tick attackclock/ASPDwindup+busy scaling/onecast, HP<=50% reversible+100%ATK with effective maxHP andsilence immunity of passive, target invalid/source lethaldeath, public deploy/withdraw, exact native one-life route exit'},'replaceable_policies':['Secondary SPECIFIED_BUFF preference with fallback; native body unavailable','Stable-ID tie after native HATE descending; no finite scalar priority constants','ASPD minimum.01/frame quantization/graphic clamp','Melee default typed qualification inferred from same-unit ranged options, retained-current blocker is strict','AttachToTarget3s delayed captured point reach/lifecycle translation; exact native stop timing body unavailable','Empace retained-source attribute fallback after owner invalidation follows generic launch snapshot; not native body certified','Undefined DB immunity fields have explicit model defaults and are not provedFalse'], 'fixtures':'Independent targets/controllers/public test skills and explicit external maxHP/speed Buffs; not native operator skill/whole-stage evidence','historical_failures':['author.v1.tests.json','author.v2.tests.json','boundaries.v1.tests.json','failure.author.arbitration.schema.v1.json','failure.author.pytest.plugin.v1.json'],'whole_stage_executed':False,'independent_reviewed':False,'client_verified':False,'stage_admission_asserted':False,'pins':{str(p.relative_to(ROOT)):sha(p) for p in paths}}
 out=OUT/'final.author.v1.json';assert not out.exists();out.write_bytes((json.dumps(report,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'path':str(out),'sha256':sha(out),'pins':len(paths)}))
if __name__=='__main__':main()
