"""Actual selected native roster initialization/Buffs and true burn interaction, no metadata-only green."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT.parent/'unpack_work/campaign_buff_lifetime_v5_candidate'));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler,Engine
from ark_sim.adapters.api import implementation_digest
from tools.campaign_content_composition_v2 import compose_modules
from tools.chapter08_boss.dragon_fire_policies_v3 import providers as fire
from tools.chapter08_buff_lifetime.policies_v1 import providers as clocks
from ark_sim.tools.replay import replay
from ark_sim.contracts import thaw
from tools.campaign_ordered_checkpoint import write_ordered,load_bound
OUT=ROOT/'packages/campaign/chapter08_consumers/special/dynamic_roster_independent_v3';ROSTER=ROOT/'packages/campaign/roster/fixed12.m26.reference_module.json';BURN=ROOT/'packages/campaign/chapter08_consumers/boss/dragon_fire.module.v10.dynamic.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def domain(s):return {'world':s.session.world.snapshot(),'scheduler':s.session.scheduler.snapshot(),'random':s.session.random.snapshot(),'time':s.session.time}
def main():
 before={str(p):sha(p) for p in [ROSTER,BURN]};r=json.loads(ROSTER.read_bytes());b=json.loads(BURN.read_bytes());defs,provenance=compose_modules([('fixed12',r),('dynamic_burn',b)]);timer,child=[d['id'] for d in b['buffs']];app=next(d['id'] for d in b['rules'] if d['contract']=='buff.application');selected=r['manifest']['metadata']['roster'];assert len(selected)==12
 source='unit/peer/dynamic/roster_controller';skill='ability/peer/dynamic/roster_fire';selector='selector/peer/dynamic/roster';defs[source]={'id':source,'kind':'entity','tags':['enemy'],'components':{'attributes':{'base':{'max_hp':50000,'atk':1500}},'resources':{'hp':{'initial':50000,'capacity':50000,'role':'health'}},'selection_state':{'side':1,'motion':1,'category':1,'unit_type':2},'spatial':{},'abilities':[skill],'lifecycle':{'policy':'policy/ark_lifecycle'}}};defs[selector]={'id':selector,'kind':'selector','region':{'type':'all'},'filters':[{'tag':'player'}]};defs[skill]={'id':skill,'kind':'ability','selector':selector,'activation':{'mode':'manual','on_start':[{'op':'buff_application','application_rule':app,'allowed':[timer,child]}]},'timeline':[]};reg={**fire(),**clocks()};rows=[];OUT.mkdir(exist_ok=True)
 for uid in selected:
  p={'schemaVersion':2,'manifest':{'requires':['preset/ark_standard'],'metadata':{'scope':'Actual fixed12 native definitions with one initial selected actor per isolated scene; no original source stat/Buff/skill modified; not whole stage deployment proof'}},'definitions':list(defs.values()),'scenarioDraft':{'id':'scene/peer/roster_burn/'+uid.rsplit('/',1)[-1],'ruleset':'ruleset/ark_standard','map':{'rows':8,'cols':8},'objectives':{},'resources':{'dp':{'initial':10,'capacity':99}},'roster':selected,'initialEntities':[{'definition':source,'instanceAlias':'source','position':{'row':0,'col':0}},{'definition':uid,'instanceAlias':'target','position':{'row':7,'col':7}}]}}
  s=Engine.create(Compiler(providers=reg).compile(p),providers=reg,seed=8126);initial=thaw(s.ctx.entity('target'));declared=defs[uid]['components'];assert initial['components']['attributes']['base']==declared['attributes']['base'];assert set(declared.get('buffs',{}).get('initial',[])) <= {i['definition'] for i in initial['components'].get('buffs',{}).get('instances',[])}
  folder=OUT/uid.rsplit('/',1)[-1];folder.mkdir(exist_ok=True);s.submit({'action':'skill','source':'source','ability':skill},at=0);s.session.advance(31);cp=folder/'checkpoint.json';pin=write_ordered(cp,s.checkpoint());restored=Engine.restore(s.program,load_bound(cp,pin),providers=reg);s.session.advance(34);restored.session.advance(34);head=replay(s.program,s.export_replay(),providers=reg);assert domain(s)==domain(restored)==domain(head) and tuple(s.session.events)==tuple(restored.session.events)==tuple(head.session.events)
  hits=[(e['time'],e['payload']['amount']) for e in s.session.events if e['type']=='damage.accepted' and e['payload'].get('target')==s.session.world.resolve('target')];assert hits==[(30,56),(60,62)],(uid,hits)
  row={'native_definition':uid,'native_base_preserved':True,'original_initial_buff_ids':declared.get('buffs',{}).get('initial',[]),'actual_initial_buff_ids':[i['definition'] for i in initial['components'].get('buffs',{}).get('instances',[])],'actual_initial_selection_state':initial['components'].get('selection_state'),'burn_packets':hits,'actual_HP_after65':s.ctx.resources.current('target','hp'),'CP31_to65':True,'head':True,'full_events_equal':True,'cp_sha256':pin};(folder/'replay.json').write_bytes((json.dumps(s.export_replay(),ensure_ascii=False,indent=2)+'\n').encode());row['pins']={str(q):sha(q) for q in folder.iterdir() if q.is_file()};rows.append(row)
 assert before=={str(p):sha(p) for p in [ROSTER,BURN]};result={'status':'passed','core':implementation_digest(),'source_guards_before':before,'source_guards_after':before,'actual_roster_members':rows,'source_status_scope':'Actual original initial buffs/statuses are executed and preserved. Current fixed12 definitions have no initial resistance Attribute26 modifier; unrelated DEF/RES/physical-art dodge/native aura effects do not change PURE burn packets. Native selected skill activation/talents not represented in original source remain separate gates. No claim all possible later player-added status combinations are tested.','whole_stage_executed':False,'client_verified':False};out=OUT/'report.json';assert not out.exists();out.write_bytes((json.dumps(result,ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'path':str(out),'sha256':sha(out),'actors':len(rows)}))
if __name__=='__main__':main()
