"""Actual dormant frost device/SP/branch/13-cell Cold consumer on read-only a705."""
import hashlib,json,sys
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RUNTIME=ROOT.parent/'unpack_work/campaign_chapter06_complete_base_v5_candidate';OUT=ROOT/'packages/campaign/chapter06_predefines_consumer';sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from ark_sim.domains.selection import DEFAULT_STATE
from tools.chapter06.cold.policies import providers
CORE='a7059989b9db7f4bc0de954b32cb5c5ba10e6b92ce040c57ea0a193549b9709a'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()==CORE;profile=OUT/'source.profile.json';assert sha(profile)=='129e1dfd8b2ad82101e120c61f009cf02a075cc67ec08a6c423870a21df25b0d';s=json.loads(profile.read_bytes());p=json.loads((ROOT/'packages/campaign/chapter06_cold/model.json').read_bytes());p['abilities']=[];p['selectors']=[];uid='unit/ch6/predefined/frosts/source_level1';aid='ability/ch6/predefined/frosts/source_cold';cfg=deepcopy(s['source_components']['AdvancedSelector']['raw']);default=deepcopy(DEFAULT_STATE);elig={'rule':'rule/ch6/predefined/frosts/eligibility','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':default}};offsets=[[-c['row'],c['col']] for c in s['exact_range_source']['grids']]
 p['rules'] += [{'id':'rule/ch6/predefined/frosts/eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':'rule/ch6/predefined/frosts/source_identity','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'graph','nodes':[{'id':'result','expression':"{'accepted':inputs.source.id == inputs.candidate.id,'reason':'actual_source_identity'}"}],'output':'nodes.result'}},{'id':'rule/ch6/predefined/frosts/area','kind':'rule','contract':'area.members','implementation':{'type':'provider','provider':'ark.area.qualified_cell_offsets'},'parameters':{'offsets':offsets,'eligibility':elig}},{'id':'rule/ch6/predefined/frosts/time_sp','kind':'rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.current + inputs.attributes.sp_recovery_rate * inputs.delta_seconds'}}]
 anchor=deepcopy(cfg);anchor.update(_targetSide=7,_targetCategory=7,_ignoreTargetFree=1,_forceIgnoreCamouflage=1);identity={'rule':'rule/ch6/predefined/frosts/source_identity','parameters':{'source_configuration':anchor,'side_policy':'relative_ally_enemy','neutral_policy':'absolute_mask','defaults':default}};p['selectors'].append({'id':'selector/ch6/predefined/frosts/anchor','kind':'selector','region':{'type':'all'},'filters':[{'state':'alive'}],'limit':1,'eligibility':identity})
 seconds=s['source_components']['AnimatedActionToTargetAbility']['raw']['_preDelay'];p['abilities'].append({'id':aid,'kind':'ability','activation':{'mode':'manual','costs':[{'resource':'sp','amount':15}],'parameters':{'auto_when_ready':True,'auto_only':True,'blocks_new_activations':True}},'duration_seconds':seconds,'selector':'selector/ch6/predefined/frosts/anchor','timeline':[{'at_seconds':seconds,'effect':{'op':'area','center':'source','membership_rule':'rule/ch6/predefined/frosts/area','effects':[{'op':'buff_application','application_rule':'rule/ch6/cold/application','allowed':['buff/ch6/cold/e2c_cold','buff/ch6/cold/e2c_freeze'],'parameters':{'duration_seconds':10}}]}}],'metadata':{'source_skill':'sktok_frosts','source_predelay':seconds,'source_raw':s['source_components'],'no_dummy_target':True}})
 p['entities']=[{'id':uid,'kind':'entity','tags':['device','map_dependent_trap','frost_source'],'components':{'attributes':{'base':{'max_hp':100,'atk':0,'def':0,'mres':0,'sp_recovery_rate':1,'move_speed':1,'block_count':0,'deploy_cost':5,'redeploy_time':5}},'resources':{'hp':{'initial':100,'capacity':100,'role':'health'},'sp':{'initial':0,'capacity':15,'recovery_rate':1,'recovery_rule':'rule/ch6/predefined/frosts/time_sp','recovery':{'mode':'periodic','interval_seconds':1/30},'parameters':{'freeze_cast_modes':['manual'],'freeze_while_cast':True,'pause_at_full':True}}},'selection_state':{'side':1,'category':2,'motion':1,'unit_type':4},'spatial':{'motion_mode':0,'blocking':False},'abilities':[aid],'terrain_overlays':[{'key':'native_frost_trap_mode','priority':0,'values':{'buildableType':0,'passableMask':2,'physicalHeight':.4000000059604645},'preserve':['heightType','advancedBuildMask']}],'lifecycle':{'policy':'policy/ark_lifecycle'}}}]
 native=s['native_predefines'];plan=json.loads((ROOT/'packages/campaign/chapter06_plans/source.plan.json').read_bytes())['stages']['level_main_06-14']['native_document'];rows=len(plan['mapData']['map']);initial=[{'definition':uid,'instanceAlias':v['alias'],'active':False,'registration_key':v['alias'],'position':{'row':rows-1-v['position']['row'],'col':v['position']['col']},'facing':v['direction'].lower(),'parameters':{'native_instance':deepcopy(v)}} for v in native['tokenInsts']];p['manifest']['id']='package/ch6/predefined/frosts/source_consumer_v1';p['manifest']['metadata']={'source_profile_sha':sha(profile),'source_locks':s['source_before'],'required_runtime':CORE,'providers_source':str(ROOT/'tools/chapter06/cold/policies.py'),'providers_sha':sha(ROOT/'tools/chapter06/cold/policies.py'),'native_predefined_profiles':{'level_main_06-14':{'native_predefines':native,'initial_entities':initial,'card_bindings':[],'resources':{}}},'registered_keys':{'level_main_06-14':s['exact_aliases']},'model_policies':s['model_policies'],'raw_native_branch':s['native_branch'],'actual_model_execution_verified':False,'whole_stage_executed':False,'client_verified':False}
 fixture=deepcopy(p);fixture['scenarioDraft']={'id':'scene/frosts/compile','ruleset':'ruleset/ark_standard','map':{'rows':8,'cols':12},'objectives':{},'initialEntities':initial};Compiler(providers=providers()).compile(fixture);out=OUT/'module.reference.json';assert not out.exists();out.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(out),'core':implementation_digest(),'actual_compile':True,'runtime_execution':False,'registered':s['exact_aliases']}))
if __name__=='__main__':main()
