"""Nine source dependency classes, complete raw operands and explicit pending consumers."""
import base64,hashlib,json
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'packages/campaign/chapter07_sources/source.inventory.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 paths={n:ROOT/'packages/campaign'/p for n,p in {'plan':'chapter07_plans/source.plan.json','enemies':'chapter07_sources/native.reference.json','environment':'chapter07_environment/source.reference.json','predefines':'chapter07_predefines/source.v4.reference.json','buff_extra_FB':'chapter07_sources/buff.all_referenced.v2.reference.json'}.items()};data={n:json.loads(p.read_bytes()) for n,p in paths.items()};plan=data['plan'];enemy=data['enemies'];npc=data['predefines'];catalogpath=ROOT/'packages/campaign/mainline_catalog.json';catalog=json.loads(catalogpath.read_bytes());locks={str(p.resolve()):sha(p) for p in paths.values()};locks[str(catalogpath.resolve())]=sha(catalogpath)
 for source in data.values():
  for name,pin in source.get('source_locks',{}).items():
   p=ROOT.parent/name;assert sha(p)==pin;locks[str(p.resolve())]=pin
 binary={}
 for row in catalog['stages']:
  if row['chapter']!=7 or not row['selected']:continue
  refs=[]
  for ref in row.get('original_binary_level_sources',[]):
   p=(ROOT/ref['path']).resolve()
   if not p.exists():refs.append({'status':'source_file_missing','expected_path':str(p),'expected_sha':ref['sha256']});continue
   assert sha(p)==ref['sha256'];locks[str(p)]=sha(p);refs.append({'status':'exact_binary_present_unconverted','path':str(p),'sha':sha(p),'bytes':p.stat().st_size,'raw_source_base64':base64.b64encode(p.read_bytes()).decode(),'typed_layout_alignment_to_fixed_table_verified':False})
  binary[row['level_id']]=refs
 classes=[{'class':'stage_tables_db_and_exact_variants','source_status':'fixed56aee_exact_source_present','items':{v:{'reference':r['native_reference'],'level':r['native_enemy']['native_level'],'resolved':r['native_enemy']['resolved']} for v,r in plan['variants'].items()},'runtime_status':'unconsumed'},
 {'class':'wave_actions_routes_and_checkpoint_geometry','source_status':'full_raw_source_present','items':{n:{'waves':s['native_document']['waves'],'actions':s['actions'],'routes':s['native_document']['routes'],'extraRoutes':s['native_document'].get('extraRoutes'),'used_routes':s['used_routes'],'used_checkpoint_counts':s['used_checkpoint_counts'],'unused_route_motion_modes':[{'route':i,'mode':r['motionMode']} for i,r in enumerate(s['native_document']['routes']) if i not in s['used_routes']]} for n,s in plan['stages'].items()},'runtime_status':'unconsumed'},
 {'class':'enemy_modes_passives_skills_and_animation_frames','source_status':'12prefabs_exact_spine_source_bound','items':enemy['dependency_matrix'],'runtime_status':'unconsumed'},
 {'class':'projectiles_collision_movement_hit_behaviour','source_status':'three_exact_source_prefabs','items':enemy['projectiles'],'runtime_status':'unconsumed'},
 {'class':'buff_inline_bson_and_typed_FB','source_status':'inline+BSON_present_FB_versions_differ','items':{'enemy_BSON':enemy['bson_templates'],'predefined_BSON':npc['bson_templates'],'extra_FB':data['buff_extra_FB']},'runtime_status':'unconsumed','pending':'37 inline key IDs absent in oldFB; raw inline definitions remain authoritative source candidates, no DBlookup substituted'},
 {'class':'terrain_map_cells_options_runes','source_status':'all_six_used_tile_keys_resolved','items':{'environment':data['environment'],'options_runes':{n:{'options':s['options'],'runes':s['native_document'].get('runes'),'hardPredefines':s['hard_predefines']} for n,s in plan['stages'].items()}},'runtime_status':'unconsumed'},
 {'class':'predefined_entities_cards_and_selected_skills','source_status':'source_present_mixed_version_explicit','items':{'stages':npc['stages'],'prefabs':npc['prefabs'],'selected_skill_tables':npc['skill_tables'],'skill_prefabs':npc['skill_prefabs']},'runtime_status':'unconsumed','pending':'ore aliasnull and fifteen mine card cost/terrain/stock/attack/retirement need actual consumers'},
 {'class':'branches_story_display_preview_controls','source_status':'raw_branches_controls_and_story_preserved','items':{'stages':{n:{'branches':s['native_document'].get('branches'),'controls':[a for a in s['actions'] if a['native']['actionType']!='SPAWN']} for n,s in plan['stages'].items()},'stories':npc['stories']},'runtime_status':'unconsumed'},
 {'class':'asset_binary_monoscript_version_and_boss_lifecycle_dependencies','source_status':'raw_sources_pinned_native_method_bodies_unrecovered','items':{'binary_levels':binary,'mono_script_assets':enemy['native_monoscripts'],'predefine_script_assets':npc['native_monoscripts'],'source_version_policy':npc['source_policy_notes'],'boss_variant':[r for r in enemy['variants'].values() if r['native_enemy']['native_id']=='enemy_1506_patrt']},'runtime_status':'unconsumed','pending':'Patriot real modes/RebornTalent/shield/taunt/invincible/releasewave/ore/globalAura source consumers and independent checks required; no name-derived policy'}]
 assert len(classes)==9;builderpins={str(p.resolve()):sha(p) for p in (ROOT/'tools/chapter07').glob('*.py')};locks.update(builderpins);assert all(sha(Path(p))==h for p,h in locks.items());result={'schema':'ark-sim/chapter07-complete-source-inventory/v1','fixed_commit':plan['fixed_commit'],'selected_catalog_ids':plan['selected_display_ids'],'input_source_packages':{n:{'path':str(p),'sha':sha(p)} for n,p in paths.items()},'source_before':locks,'source_after':{p:sha(Path(p)) for p in locks},'source_stages':{n:{'births':s['spawn_count'],'variants':len(s['variant_ids']),'native_slots':s['options']['characterLimit'],'native_DP':s['options']['initialCost'],'native_life':s['options']['maxLifePoint'],'native_move_multiplier':s['options']['moveMultiplier']} for n,s in plan['stages'].items()},'nine_dependency_classes':classes,'asset_version_alignment_verified':False,'runtime_authored':False,'stage_join_created':False,'whole_stage_executed':False,'client_verified':False};assert not OUT.exists();OUT.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'sha':sha(OUT),'classes':len(classes),'source_locks':len(locks),'binary_levels':{k:len(v) for k,v in binary.items()},'runtime':False}))
if __name__=='__main__':main()
