"""Actual exact-source finalzero restore counter; no positive-HP workaround."""
import sys,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT.parent/'unpack_work/campaign_selection_context_clock_v2_candidate'));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler,Engine
from ark_sim.adapters.api import implementation_digest
from tools.chapter08_bsnake.screen_policy_v1 import providers

def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=json.loads((ROOT/'packages/campaign/chapter08_consumers/bsnake/firecommon.module.v2.json').read_bytes());entity=p['entities'][0];entity['components']['resources']['hp']={'initial':50000,'capacity_attribute':'max_hp','role':'health'};p['rules'].append({'id':'rule/bsnake/source_restore','kind':'rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.parameters.capacity * inputs.parameters.ratio if context.rebirth.count == 1 else 0'}});p['buffs']=[{'id':'buff/source/bsnake/reborn_up','kind':'buff','modifiers':[{'attribute':'max_hp','layer':'direct_ratio','value':.5},{'attribute':'atk','layer':'direct_ratio','value':.5}]}];entity['components']['rebirth']={'resource':'hp','max_count':2,'delay_seconds':5,'restore_ratio':.5,'restore_rule':'rule/bsnake/source_restore','retain_buffs':['buff/source/bsnake/reborn_up'],'on_begin':[{'op':'apply_buff','buff':'buff/source/bsnake/reborn_up','target':'source','condition':'inputs.source.components.runtime.rebirth.count == 1'}]};p['entities'].append({'id':'unit/counter/player','kind':'entity','components':{'spatial':{},'abilities':['ability/counter/kill']}});p['selectors']=[{'id':'selector/counter/boss','kind':'selector','region':{'type':'all'},'filters':[{'field':{'path':['id'],'equals':2}}]}];p['abilities'].append({'id':'ability/counter/kill','kind':'ability','selector':'selector/counter/boss','activation':{'mode':'manual'},'timeline':[{'at_seconds':0,'effect':{'op':'instant_kill','parameters':{'cause':'source_exact_counter','skip_rebirth':False}}}]});p['scenarioDraft']={'id':'scene/bsnake/finalzero_counter','ruleset':'ruleset/ark_standard','map':{'rows':5,'cols':8},'objectives':{},'initialEntities':[{'definition':entity['id'],'instanceAlias':'boss','position':{'row':2,'col':6}},{'definition':'unit/counter/player','instanceAlias':'player','position':{'row':0,'col':0}}]};program=Compiler(providers=providers()).compile(p);s=Engine.create(program,providers=providers());s.submit({'action':'skill','source':'player','ability':'ability/counter/kill'},at=1);s.submit({'action':'skill','source':'player','ability':'ability/counter/kill'},at=160);entity['components']['rebirth']['on_begin']=[];entity['components']['rebirth']['retain_buffs']=[];program=Compiler(providers=providers()).compile(p);s=Engine.create(program,providers=providers());s.submit({'action':'skill','source':'player','ability':'ability/counter/kill'},at=1);s.submit({'action':'skill','source':'player','ability':'ability/counter/kill'},at=160);s.advance(155);assert s.ctx.resources.current('boss','hp')==25000;first=s.checkpoint();error=None
 try:s.advance(160)
 except Exception as e:error={'type':type(e).__name__,'message':str(e)}
 assert error is not None and error['message']=='rebirth restoration must be positive finite';out=ROOT/'validation/campaign/chapter08_bsnake_finalzero_isolated_v3';out.mkdir(exist_ok=False);obj={'core':implementation_digest(),'counter_executed':True,'fixture_base_restore25000_before_final0':True,'boost_omitted_for_independent_finalzero_gate':True,'final_source_ratio0_rejected':error,'input':p,'first_checkpoint':first,'final_checkpoint':s.checkpoint(),'scope':'Source maxCount2/delay5/first restore.5/final0. Separate boost-source mechanism deliberately outside this finalzero-only counter. NofakeHP hack. Fullscreen/branch/hint actor graph not included in this isolatedgeneric counter; direct firstsource restoration succeeds, finalpolicy currentlycannotclose.'};f=out/'report.json';f.write_text(json.dumps(obj,indent=2)+'\n',encoding='utf8');print(json.dumps({'sha':sha(f),'error':error}))
if __name__=='__main__':main()
