"""Executable source ballista module on the isolated directional candidate."""
import hashlib,json,sys
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];RUNTIME=ROOT.parent/'unpack_work/campaign_ballista_directional_v1_candidate';OUT=ROOT/'packages/campaign/chapter05_predefines/runtime_ballista'
sys.path.insert(0,str(RUNTIME));sys.path.insert(1,str(ROOT))
from ark_sim import Compiler
from ark_sim.adapters.api import implementation_digest
from ark_sim.domains.selection import DEFAULT_STATE,SWITCHES
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert implementation_digest()=='49af646affbd800b2d65a25634700deb1444fcbc3e0d886516ad9509edab217b';policy=OUT/'source.policy.json';assert sha(policy)=='72a96a17c73554ebd08c622cb590a6fdc7476cec68278c0dff46c0bbdb7ce91c';p=json.loads(policy.read_bytes());source=json.loads(Path(p['source']).read_bytes());planpath=ROOT/'packages/campaign/chapter05_plans/source.plan.json';plans=json.loads(planpath.read_bytes());raw=p['source_components'];cfg={k:0 for k in SWITCHES};cfg.update(_targetSide=2,_targetCategory=1,_targetMotion=3,_professionMask=0,_unitTypeMask=0);defaults=deepcopy(DEFAULT_STATE);eligibility={'rule':'rule/ballista/source_hit_eligibility','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults}};uid='unit/ch5/ballista/source_level6'
 unit={'id':uid,'kind':'entity','metadata':{'native_character_key':'trap_007_ballis','native_level':6,'source_stats_sha':p['source_sha256'],'not_enemy_spawn_lifecycle':True},'tags':['device','ballista','map_dependent_trap'],'components':{'selection_state':{'side':1,'category':4,'motion':1,'unit_type':4},'spatial':{'motion_mode':0,'blocking':False},'attributes':{'base':{'max_hp':100,'atk':600,'def':0,'mres':0,'attack_interval':1,'attack_speed_ratio':1,'move_speed':1,'block_count':0,'deploy_cost':5,'redeploy_time':5,'sp_recovery_rate':1}},'resources':{'hp':{'initial':100,'capacity':100,'role':'health'},'sp':{'initial':0,'capacity':5,'recovery_rate':1,'recovery':{'mode':'continuous'},'recovery_rule':'rule/ballista/time_sp','parameters':{'freeze_cast_modes':['manual'],'freeze_while_cast':True,'pause_at_full':True}}},'terrain_overlays':[{'key':'trap_mode_source','priority':0,'values':{'buildableType':0,'passableMask':2,'physicalHeight':raw['TrapMode']['_rewriteHeight']},'preserve':['heightType','advancedBuildMask']}],'abilities':['ability/ballista/source_shot'],'lifecycle':{'policy':'policy/ark_lifecycle'}}}
 ability={'id':'ability/ballista/source_shot','kind':'ability','activation':{'mode':'manual','costs':[{'resource':'sp','amount':5}],'parameters':{'auto_when_ready':True,'auto_only':True,'blocks_attacks':True,'blocks_new_activations':True}},'duration_seconds':raw['RangedAttack']['_preDelay'],'selector':'selector/ballista/real_caster_anchor','timeline':[{'at_seconds':raw['RangedAttack']['_preDelay'],'effect':{'op':'damage','damage_type':'physical','scale':1,'target':'source','projectile_definition':'projectile/ballista/source_arrow','read_mode':'at_hit','damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False}}}],'metadata':{'source_skill':'sktok_ballis','allow_no_combat_target':True,'real_actor_anchor_not_virtual_target':True,'SP_cost':5,'initSP':0,'cast_predelay_source':raw['RangedAttack']['_preDelay']}}
 ability['timeline'][0]['effect']['read_mode']={'source_attributes':'at_hit','target_attributes':'at_hit'}
 unit['components']['resources']['sp']['recovery']={'mode':'periodic','interval_seconds':1/30}
 profile={'id':'projectile/ballista/source_arrow','kind':'projectile','motion':{'rule':'rule/ballista/cardinal_ray','parameters':{'extent_policy':'map_bounds','speed':10}},'collision':{'rule':'rule/ballista/qualified_sweep','allow_other_targets':True,'parameters':{'qualified_ray':True,'radius':.5,'eligibility':eligibility,'exclude_source':False}},'lifetime_seconds':60,'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'completion_blocking':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'retain_position','target_hidden':'retain_position','finish_on_reach':True,'hit_on_reach':False,'force_reach_on_expire':False,'hit_on_expire':False},'on_invalid':[],'dependencies':['rule/ballista/source_hit_eligibility'],'metadata':{'native_raw_simple_projectile':raw['SimpleProjectile'],'native_raw_hit_behaviour':raw['HitBehaviour'],'native_raw_farthest_point_movement':raw['FarthestPointMovement'],'source_circle_collider_radius':.5,'policy':'Fixed cardinal source direction to map bound; reference geometry replaceable; no wall stop'}}
 rules=[{'id':'rule/ballista/cardinal_ray','kind':'rule','contract':'projectile.trajectory','implementation':{'type':'provider','provider':'model.projectile.cardinal_map_ray'}},{'id':'rule/ballista/qualified_sweep','kind':'rule','contract':'projectile.collision','implementation':{'type':'provider','provider':'model.projectile.qualified_swept_ray'}},{'id':'rule/ballista/source_hit_eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':'rule/ballista/time_sp','kind':'rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.current + inputs.attributes.sp_recovery_rate * inputs.delta_seconds'}}]
 native_profiles={};keys={}
 for stageid,stage in source['stages'].items():
  native=stage['predefines'];rows=len(plans['stages'][stageid]['native_document']['mapData']['map']);initial=[];registered=[]
  for index,item in enumerate(native['tokenInsts']):
   alias=item.get('alias') or f'{stageid}/ballista/{index+1}';hidden=item['hidden'];entry={'definition':uid,'instanceAlias':alias,'position':{'row':rows-1-item['position']['row'],'col':item['position']['col']},'facing':item['direction'].lower(),'parameters':{'native_bucket':'tokenInsts','native_instance':deepcopy(item),'native_ballista_source_sha':p['source_sha256']}}
   if hidden:entry.update(active=False,registration_key=alias);registered.append(alias)
   initial.append(entry)
  native_profiles[stageid]={'native_predefines':deepcopy(native),'initial_entities':initial,'card_bindings':[],'resources':{}};keys[stageid]=registered
 module={'schemaVersion':2,'manifest':{'id':'package/chapter05/ballista/source_consumer_v1','requires':['preset/ark_standard'],'metadata':{'source_locks':{str(Path(p['source']).resolve()):p['source_sha256'],str(policy.resolve()):sha(policy),str(planpath.resolve()):sha(planpath)},'builder_sha':sha(Path(__file__)),'required_runtime':implementation_digest(),'native_predefined_profiles':native_profiles,'registered_keys':keys,'source_consumer_policies':p['consumer_policies'],'source_numeric_level6':p['level_stats'],'actual_module_execution_verified':False,'native_stage_counts_DP_slots':{'level_main_05-09':{'births':51,'variants':4,'DP':10,'slots':8},'level_main_05-10':{'births':73,'variants':6,'DP':0,'slots':9}},'client_verified':False}},'entities':[unit],'abilities':[ability],'selectors':[{'id':'selector/ballista/real_caster_anchor','kind':'selector','region':{'type':'all'},'filters':[{'state':'alive'}],'limit':0}],'definitions':[profile],'rules':rules}
 # Independent synthetic layout carries the actual source consumer, not dummy
 # registration. It is only used to validate the complete content closure here.
 fixture=deepcopy(module);fixture['scenarioDraft']={'id':'scene/ballista/compile_closure','ruleset':'ruleset/ark_standard','map':{'rows':3,'cols':8},'objectives':{},'initialEntities':[{'definition':uid,'instanceAlias':'source_ballista','position':{'row':1,'col':0},'facing':'right'}]};Compiler().compile(fixture)
 dest=OUT/'module.reference.json'
 if dest.exists():raise ValueError('Preserve module')
 dest.write_text(json.dumps(module,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'module_sha':sha(dest),'core':implementation_digest(),'active5_9':len(native_profiles['level_main_05-09']['initial_entities']),'dormant5_10':len(keys['level_main_05-10']),'runtime_executed':False}))
if __name__=='__main__':main()
