"""Freeze explicit source numerics and replaceable mathematical consumer choices."""
import hashlib,json
from copy import deepcopy
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];SOURCE=ROOT/'packages/campaign/chapter05_predefines/source.reference.json';OUT=ROOT/'packages/campaign/chapter05_predefines/runtime_ballista'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def component(p,section,name):return next(c['raw'] for c in p[section]['components'].values() if c['native_class']==name)
def main():
 assert sha(SOURCE)=='10cf48e1550983d192c33243280c764d100e1ac401f11be8d55334b7cf591faf';p=json.loads(SOURCE.read_bytes());frames=p['raw_character']['phases'][0]['attributesKeyFrames'];lo,hi=frames;assert lo['level']==1 and hi['level']==30
 stats={k:lo['data'][k]+(hi['data'][k]-lo['data'][k])*5/29 if type(lo['data'][k]) in (int,float) else lo['data'][k] for k in lo['data']};assert stats['atk']==600 and stats['maxHp']==100 and stats['cost']==5
 expected={level:len(s['predefines']['tokenInsts']) for level,s in p['stages'].items()};assert expected=={'level_main_05-09':4,'level_main_05-10':10};assert all(i['inst']['level']==6 for s in p['stages'].values() for i in s['predefines']['tokenInsts']);skill=p['selected_skill_level'];assert skill['spData']['spCost']==5 and skill['spData']['initSp']==0 and skill['spData']['increment']==1
 profile={'schema':'ark-sim/ballista-source-consumer-policy/v1','source':str(SOURCE),'source_sha256':sha(SOURCE),'actual_level':6,'level_stats':stats,'selected_skill':deepcopy(skill),'source_components':{name:deepcopy(component(p,section,name)) for section,name in [('prefab','TrapMode'),('prefab','MapDependentTrap'),('skill_prefab','CastSkill'),('skill_prefab','RangedAttack'),('projectile','SimpleProjectile'),('projectile','HitBehaviour'),('projectile','FarthestPointMovement')]},'geometry_sources':deepcopy(p['projectile']['geometry_sources']),'source_predefines':deepcopy(p['stages']),'predefined_counts':expected,'consumer_policies':{'level6_stats':'Linear L1/L30 keyframe interpolation, not a level30 ATK substitution','fire_clock':'Real SP resource init0/cost5/increment1, automatic-only skill; native allowSpRecoveryWhenAffecting0 freezes actual active manual cast. Native predelay0.16699999570846558 quantizes upward to6 logic frames at1/30. Actual cast cadence must be measured, not scheduled externally.','target':'Description and native HitBehaviour imply player combat actors, motionmask3/category1, target-free/camouflage not bypassed, first actual collision only. Ballista uses explicit hostile selection side with device tags, not enemy birth/lifecycle accounting.','launch_anchor':'Use the real caster itself as internal trace anchor for allowNoTarget1, never spawn/register a virtual aim actor; trajectory direction captured atlaunch and independent of later target movement','farthest_point':'Replaceable declared map-bound straight cardinal ray, speed10, fixedsourcefacing, projectilecircle0.5, pass through walls, stop after first valid hit via maxHit1; `_withinAbilityRange1` and all raw source parameters retained as provenance, native method body/client comparison pending.','projectile_lifecycle':'Real 60s source lifetime, no duplicate same-target hit, stopAfterMax1, source-invalid retention, no forced trace/self hit on reach/expiry','terrain':'Actual owned active-only TrapMode rewrite buildable0/passable2/physicalHeight0.4000000059604645, preserve heightType/advancedBuildMask under raw rewrite flags0; dormant registration must have no rewrite/charge/tasks before real activation','activation':'5-9 four actual active source instances;5-10 ten aliases truly dormant until Root branch activation, neither source dummy registration nor authored metadata is execution acceptance'},'runtime_authored':False,'whole_stage_executed':False,'actual_client_verified':False}
 OUT.mkdir(parents=True,exist_ok=True);dest=OUT/'source.policy.json'
 if dest.exists():raise ValueError('Preserve source policy')
 dest.write_text(json.dumps(profile,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='');print(json.dumps({'policy_sha':sha(dest),'atk_level6':stats['atk'],'HP':stats['maxHp'],'SPcost':5,'predelay_frames':6,'predefines':expected}))
if __name__=='__main__':main()
