"""Raw C8 source manifest and proposed generic-interface mapping, no consumer claims."""
import json,hashlib,base64
from pathlib import Path
from collections import Counter
ROOT=Path(__file__).resolve().parents[3];BASE=ROOT/'packages/campaign/chapter08_source_prepare/integration'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 paths={n:BASE/f for n,f in {'plans':'source.plan.v1.json','enemies':'enemies.native.v1.json','environment':'environment.native.v1.json','predefines':'predefines.native.v2.json','FB':'buffs.typed.v3.json','supplement':'source.supplement.v1.json'}.items()};data={n:json.loads(p.read_bytes()) for n,p in paths.items()};locks={str(p):sha(p) for p in paths.values()}
 def sourcewalk(v):
  if isinstance(v,dict):
   for name,h in v.get('source_locks',{}).items():
    p=Path(name);p=p if p.is_absolute() else ROOT.parent/p
    assert sha(p)==h,(p,h);locks[str(p.resolve())]=h
   if isinstance(v.get('path'),str) and isinstance(v.get('sha256'),str):
    p=Path(v['path']);candidates=[p] if p.is_absolute() else [ROOT.parent/p,ROOT/p]
    for p in candidates:
     if p.is_file():assert sha(p)==v['sha256'];locks[str(p.resolve())]=v['sha256'];break
   for x in v.values():sourcewalk(x)
  elif isinstance(v,list):
   for x in v:sourcewalk(x)
 for value in data.values():sourcewalk(value)
 for p in Path(__file__).parent.glob('*.py'):locks[str(p)]=sha(p)
 plans=data['plans'];en=data['enemies'];pred=data['predefines'];classes=[]
 classes.append({'class':'exact_tables_and_overridden_variants','items':plans['variants'],'consumer_status':'pending, original useDb/m_defined values are not scalar replacements'})
 classes.append({'class':'waves_actions_routes','items':{n:{'waves':s['native_document']['waves'],'routes':s['native_document']['routes'],'extraRoutes':s['native_document'].get('extraRoutes'),'actions':s['actions'],'used_routes':s['used_routes']} for n,s in plans['stages'].items()},'consumer_status':'pending, unused E_NUM routes preserved separately from used WALK/FLY'})
 classes.append({'class':'enemy_prefab_modes_spine_skills','items':en['dependency_matrix'],'prefabs':en['prefabs'],'animations':en['animations'],'consumer_status':'unimplemented'})
 classes.append({'class':'projectile_collision_hit_movement','items':en['projectiles'],'consumer_status':'unimplemented source7'})
 classes.append({'class':'buff_inline_BSON_FB','items':{'enemy_BSON':en['bson_templates'],'predefined_BSON':pred['bson_templates'],'FB':data['FB']},'consumer_status':'inline loadFromDB0 preserved,24 oldFB missing references explicit; unknown fields remain raw'})
 classes.append({'class':'terrain_options_runes_globalbuffs','items':data['environment'],'stages':{n:{'options':s['native_document']['options'],'runes':s['native_document'].get('runes'),'globalBuffs':s['native_document'].get('globalBuffs')} for n,s in plans['stages'].items()},'consumer_status':'pending sourcevolcano/infection/portal sourcepolicies need actual consumers'})
 classes.append({'class':'predefined_and_mandatory_actors','items':pred,'consumer_status':'JT8-2noinstances;JT8-3tenrawhiddenflame aliases, frozen20250327 mixed version explicit'})
 classes.append({'class':'branches_story_opera_controls','items':{'stages':{n:{'branches':s['native_document'].get('branches'),'hardPredefines':s['native_document'].get('hardPredefines'),'controls':[a for a in s['actions'] if a['native']['actionType']!='SPAWN']} for n,s in plans['stages'].items()},'stories':pred['stories'],'opera':data['supplement']['PLAY_OPERA_source']},'consumer_status':'PLAY_OPERA twoasset roots unavailable inlocalbattle scan, rawactions/referencepolicy pending not blank emit'})
 classes.append({'class':'binary_external_PPtr_and_version_identity','items':data['supplement'],'scripts':en['native_monoscripts'],'consumer_status':'source methods not recovered, oldbinary not aligned to fixedJSON,8externalSkeletonDataAsset actually resolved'})
 components=[];groups={'ordinary_attack':{'classes':['MeleeAttack','RangedAttack','AdvancedSelector','SecondaryFilterAdvancedSelector','SelfSelector','SelectorTrigger'],'generic':'abilities.timeline/target_capture/targeting eligibility/ordering/projectile trajectories/typed live projection','new_capability':'No gap proven yet; captured-live/animation ASPD/movement may use explicit source reference policies; source tests required'},'enemy_skill_and_modes':{'classes':['EnemySkill','UnitMode','ThreePartChannelingAnimation','AnimatedActionToOwnerAbility','AnimatedActionToTargetAbility','EmptyAbility','EmptyAnimatedAbility'],'generic':'behavior state, owned automatic/manual activation, source initial/repeat cooldown, staged timeline/channels/CP/head','new_capability':'Consumer grouping/skill priority/new state machine content required; generic gap only after real counter'},'conditional_and_shared_buffs':{'classes':['PassiveBuffAbility','ToggleablePassiveBuffAbility','ToggleableOnlyOncePassiveBuffAbility','HpRatioToggleChecker','GlobalAuraAbility','BuffDuringCasting'],'generic':'explicit BuffApplication allowed IDs/real permanent duration0, shared lease aura opt-in, predicate/toggle, cast-owned Buffs and application gates','new_capability':'Actual HP threshold once-vsrepeat, multiple parents/BB scopes/source definitions need source-specific content; no guessed stacking'},'boss_rebirth_hint_branch_screen':{'classes':['RebornTalent','BsnakeSummonHint','BsnakeScreenAttack','LevelBranchTrigger','ScreenEffectEmitter'],'generic':'rebirth generation/retained waiting parent-actions, advance_branch/predefined activation/finish_timeline_wave, area.members typed projection/NoSource damage as declared','new_capability':'Bsnake screen geometry/wave linkage/hint-location ordered sets/ignition extensions and triggercancel need real source recipe+counter. Presentation cannot become arbitrary damage'},'presentation_and_motion':{'classes':['MoveController','SingleSpineAnimator','SkeletonAnimation','SpineEffectEmitter','UberEffectEmitter','FaceSwitcher','ShadowController','BoneFollower','SimpleUnitAnimatorHooker'],'generic':'source motion rules/routes/map typed masks; native animation event clock policies, explicit visual-only control consumers','new_capability':'No native methodbody or client pixel equality asserted'}}
 for vid,v in en['variants'].items():
  prefab=en['prefabs'][v['prefab_key']]
  for pid,c in prefab['components'].items():
   match=[key for key,g in groups.items() if c['native_class'] in g['classes']];components.append({'variant_id':vid,'component_path_id':pid,'native_class':c['native_class'],'source_json_pointer':'prefabs/'+v['prefab_key']+'/components/'+pid,'source_file':str(paths['enemies']),'native_fields':c['raw'],'mapped_groups':match or ['sourceonly_unclassified_no_runtime_default'],'consumer_implemented':False})
 plan={'schema':'ark-sim/chapter08-mechanism-plan/v1','source_packages':{n:{'path':str(p),'sha':sha(p)} for n,p in paths.items()},'generic_interface_candidates':groups,'component_field_matrix':components,'exact_variant_DB_BB_SP_and_modes':en['variants'],'reference_strategy':'Only values/BB/flags/frames and rawpointer bindings extracted. Existing generic APIs are candidate reuse, not proof of implementedC8 mechanics. Missing method bodies permit explicitreplaceable policy at later authoring; unknown external asset/typedFB slots/presentation source remain pending. No nativeID conditional core workaround.','runtime_authored':False,'whole_stage_executed':False};out=BASE/'mechanism.plan.v1.json';assert not out.exists();out.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n',encoding='utf8');locks[str(out)]=sha(out)
 manifest={'schema':'ark-sim/chapter08-raw-extraction-manifest/v1','fixed_commit':plans['fixed_commit'],'selected_catalog':plans['selected_display_ids'],'input_packages':{n:{'path':str(p),'sha':sha(p)} for n,p in paths.items()},'mechanism_plan_sha':sha(out),'stages':{n:{'births':s['spawn_count'],'variants':len(s['variant_ids']),'DP':s['options']['initialCost'],'slots':s['options']['characterLimit'],'life':s['options']['maxLifePoint'],'controls':s['control_count_by_type']} for n,s in plans['stages'].items()},'nine_dependency_classes':classes,'source_before':locks,'source_after':{p:sha(Path(p)) for p in locks},'mixedversion_flame':'Localcharpack absent, exactroot from frozenofficial20250327 b9f16 token package; no version alignment asserted','native_method_bodies_recovered':False,'runtime_authored':False,'stage_join_created':False,'whole_stage_executed':False,'client_verified':False};assert manifest['source_before']==manifest['source_after'];out=BASE/'source.manifest.v1.json';assert not out.exists();out.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'manifest_sha':sha(out),'mechanism_sha':sha(BASE/'mechanism.plan.v1.json'),'components':len(components),'pins':len(locks)}))
if __name__=='__main__':main()
