import json,hashlib,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RUNTIME=ROOT.parent/'unpack_work/campaign_world_fork_v2_candidate';PARENT=ROOT.parent/'unpack_work/campaign_projectile_leaf_v1_candidate';OUT=ROOT/'validation/campaign/chapter08_world_fork_author_freeze_v2';OUT.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
kernel=ROOT/'validation/campaign/chapter08_world_fork_kernel_author_v3/verification.json';public=ROOT/'validation/campaign/chapter08_world_fork_public_author_v2/verification.json';comparison=ROOT/'validation/campaign/chapter08_world_fork_public_comparison_v2/verification.json';profile=ROOT/'validation/campaign/chapter08_world_fork_profile_v2/verification.json'
for path in (kernel,public):r=json.loads(path.read_bytes());assert r['guards_equal'] and all(c['outcome']=='passed' for c in r['cases'])
assert json.loads(comparison.read_bytes())['passed']
files=[p for p in (RUNTIME/'ark_sim').rglob('*') if p.suffix in ('.py','.json')];delta=[]
for p in files:
 rel=p.relative_to(RUNTIME/'ark_sim');old=PARENT/'ark_sim'/rel
 if sha(p)!=sha(old):delta.append(rel.as_posix())
assert set(delta)=={'kernel/world.py','kernel/transaction.py','kernel/session.py'}
archive=OUT/'source_delta'
for rel in delta:
 target=archive/rel;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes((RUNTIME/'ark_sim'/rel).read_bytes())
pins={str(p):sha(p) for p in files};assert pins=={str(p):sha(p) for p in files};documents=[kernel,public,comparison,profile,ROOT/'tools/chapter08_world_fork/DESIGN.md',ROOT/'validation/campaign/chapter08_world_fork_old_counter_v1/verification.json',ROOT/'validation/campaign/chapter08_world_fork_kernel_author_v2/verification.json']
report={'passed':True,'author_not_independent':True,'core':'351f4c795be38642b4c428b5848924cd2cd5edfbe221b9bbb73574a589525c16','parent_core':'71d33fa18662ae4f19c326988448e4dbb2764e503eec7bf3058e63c6a1182be2','delta':{rel:{'parent':sha(PARENT/'ark_sim'/rel),'candidate':sha(RUNTIME/'ark_sim'/rel),'archived':sha(archive/rel)} for rel in delta},'all_source_pins':pins,'guard_reports':{str(p):sha(p) for p in documents},'actual_checks':{'kernel_author9_plus_existing70':79,'fresh_public_and_leaf_cases':4,'paired_nodes':json.loads(comparison.read_bytes())['checked_nodes'],'exact_only_runtime_identity_paths':json.loads(comparison.read_bytes())['only_allowed_exact_identity_paths']},'scope':'Authorprivate validatedWorld fork replacesinternalJSON doubleclone incommit/atomic, publiccreate/set/restore/snapshot unchanged. Metadata strsubclasses normalized builtinbeforedeepcopy andtags canonicalsorted matchingoldrestore, no customhook. Ownershipdetachedfork/adoptconsumesstage; nestedrollback restoresWorld/events/RNG/jobs/allocators; threadsession RLock serialized80counter. ActualCP20/head60 retiredsourceATK421/twoflight numericalallvalues compared parent71d 153026nodes includingcontext/value/dictorder; onlycheckpoint/snapshot/replay runtimeFP permitted. Fourcases pairedincludingexisting71d component_view. No sources/no mainpromotion/full/base launched. Root/integration independent reviewrequired.','profile_limits':'4000record7paired proxy only; medianratio2.2663163900091736 measured here, not globalcampaign throughput guarantee. No traces deleted or intent/publicvalidation bypass.','failure_history':'V1 author9 actual3/6failed retainedbe3cd: tagstrsubclass normalizedsort and builder mistakenlyreplacedpublic_state_data.World; newV2 onlyrepair these no loweredexpectation. Kernelformalv2 importlibcollection error zeroexecution retaineda64cd; newverifier explicittests_v2path appendrepairsstandardtest helperimport, originalfiles unchanged. Ownimplementationstillneedsindependenthostileinput/longbaseline audit.'}
(OUT/'freeze.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8');print(sha(OUT/'freeze.json'))
