from tools.chapter08_stage_controls_review.test_controls_v2 import package,make,action,STORY,X,Y,proof,baseline,unchanged

def test_two_same_key_Opera_requests_keep_independent_nodes_completions_and_no_battleRNG():
 p=package([action(X,'first',2,True),action(X,'second',8,True)]);pr,s=make(p);before=baseline(s);s.advance(17);proof(pr,s,p,'samekey_concurrency',105);nodes=[e for e in s.session.events if e['type']=='source.opera.node.observed'];assert [e['time'] for e in nodes]==[2,8,8,11,14,17];assert [e['time'] for e in s.session.events if e['type']=='source.opera.completed']==[92,98];assert s.ctx.state()['timeline']['done'];unchanged(s,before)

def test_actual_defeat_cancels_queued_AV_and_waiting_story_no_fake_ack_completed():
 p=package([action(STORY,'story',3,True),action(X,'x',4,True),action(Y,'y',10,True)]);p['scenarioDraft']['resources']={'life':{'initial':1,'capacity':1}};p['scenarioDraft']['objectives']={'type':'waves','life_resource':'life'};p['entities'][0]['components']['abilities']=['ability/peer/defeat'];p['abilities']=[{'id':'ability/peer/defeat','kind':'ability','activation':{'mode':'manual','on_start':[{'op':'modify_resource','target':'battle','resource':'life','value':0}]},'timeline':[]}];pr,s=make(p);s.submit({'action':'skill','source':'body','ability':'ability/peer/defeat'},at=20);s.advance(12);proof(pr,s,p,'terminal_cancel',30);assert s.ctx.state()['finished'] and s.ctx.state()['result']=='defeat';rows=s.ctx.state()['controls']['instances'];assert len(rows)==3 and all(r['status']=='cancelled' for r in rows.values());assert not [e for e in s.session.events if e['type'] in ('source.opera.completed','control.completed')];assert not [t for t in s.session.scheduler.pending if t['kind']=='domain.control.signal'];assert s.ctx.state()['timeline']['phase']=='stopped';assert s.ctx.resources.current('body','hp')==2345 and s.ctx.resources.current('body','sp')==13

def test_ack_for_Opera_not_awaiting_external_input_rejects_without_shortening90():
 p=package([action(Y,'opera',5,True)]);pr,s=make(p);s.advance(10);r=s.ctx.controls.instance('opera');s.submit({'action':'control_ack','control':r['id'],'step':0},at=10);s.advance(1);proof(pr,s,p,'AV_ack_rejected',100);assert len([e for e in s.session.events if e['type']=='command.rejected'])==1;assert [e['time'] for e in s.session.events if e['type']=='source.opera.completed']==[95]
