"""Exact snow mage normal/Cold replacement, attack SP and actual Ready ownership."""
from pathlib import Path
from copy import deepcopy
import hashlib,json
ROOT=Path(__file__).resolve().parents[3]
SOURCE=ROOT/'packages/campaign/chapter06_sources/native.reference.json'
COLD=ROOT/'packages/campaign/chapter06_cold/model.json'
OUT=ROOT/'packages/campaign/chapter06_units/snmage'
VID='enemy_1068_snmage_2@0/36f9c16582d28dfa'
UID='unit/ch6/snmage/36f9c16582d28dfa';NORMAL='ability/'+UID+'/normal';SKILL='ability/'+UID+'/coldattack'
SELECT='selector/'+UID;PROJECTILE='projectile/'+UID;READY='buff/'+UID+'/ready';PARENT=READY+'_parent'
CORE='4ef955c5d5a7628382fc3d15003bb0a30c749832d210ca50897355568ec8d329'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_bytes((json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode('utf8'))
def provider(ident,contract,name):return {'id':ident,'kind':'rule','contract':contract,'implementation':{'type':'provider','provider':name}}
def defaults():return {'side':0,'motion':1,'category':1,'unit_type':1,'profession':0,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False,'abnormal_immunes':[]}
def source():
    if sha(SOURCE)!='efbf42be4db3ee14b98dcbdba72a516b35e54e2540e77ce64e32b060e8e5e6f3' or sha(COLD)!='e610f9446b077c6df7a86922e6719226e5a352a3826d6fe40c49e3296437b4dc':raise ValueError('Exact frozen source changed')
    s=json.loads(SOURCE.read_bytes());v=s['variants'][VID];d=v['native_enemy']['resolved'];prefab=s['prefabs'][v['prefab_key']];components=prefab['components']
    normal=v['modes'][0]['nodes']['_combat'];attack=v['modes'][0]['nodes']['_attack']
    if normal['path_id']!=attack['path_id'] or normal['raw']!=attack['raw']:raise ValueError('Shared normal PPtr is not identical')
    enemy_skill=next(c for c in v['passive_and_skill_components'] if c['class']=='EnemySkill');ready=next(c for c in v['passive_and_skill_components'] if c['class']=='ReadyEnemySkillEffect')
    skillnode=components['8429431607679684984'];root=next(c for c in components.values() if c['native_class']=='Enemy');mover=next(c for c in components.values() if c['native_class']=='MoveController');cfg=next(c for c in components.values() if c['native_class']=='AdvancedSelector')
    r=skillnode['raw'];n=normal['raw'];sk=d['skills'][0]
    if len(d['skills'])!=1 or sk!={'prefabKey':'coldattack','priority':0,'cooldown':0.0,'initCooldown':0.0,'spCost':2,'blackboard':[{'key':'freeze','value':10.0,'valueStr':None}]}:raise ValueError('EnemySkill exact operands')
    if d['spData']!={'spType':'INCREASE_WHEN_ATTACK','maxSp':2,'initSp':0,'increment':1.0}:raise ValueError('Exact attack SP source')
    if len(v['passive_and_skill_components'])!=2 or enemy_skill['raw']['_castLikeAttack']!=0 or enemy_skill['raw']['_ignoreSilence']!=0 or ready['raw']['_stopBeforeCast']!=1:raise ValueError('Unconsumed skill/Ready source')
    if n['_animKey']!='Attack' or r['_animKey']!=n['_animKey'] or r['_projectileKey']!=n['_projectileKey'] or n['_activeBuffs'] or len(r['_activeBuffs'])!=1 or r['_activeBuffs'][0]['buffKey']!='e2c_cold' or r['_activeBuffs'][0]['loadFromDB']!=1:raise ValueError('Cold payload differs')
    for raw in (n,r):
        if (raw['_waitForAttackEvent'],raw['_affectedBySlowDown'],raw['_atkScale'],raw['_damageType'],raw['_selectTargetSource'])!=(1,1,1,2,2) or raw['_extraDamageType'] or raw['_epDamageRatio']:raise ValueError('Ranged source operands differ')
    if [e['frame'] for e in normal['animation_binding']['events'] if e['name']=='OnAttack']!=[20]:raise ValueError('Exact OnAttack20 missing')
    projectile=s['projectiles'][n['_projectileKey']];simple=next(c for c in projectile['components'].values() if c['native_class']=='SimpleProjectile');motion=next(c for c in projectile['components'].values() if c['native_class']=='AdvancedMovement')
    if simple['raw']['_maxHitNum']!=1 or simple['raw']['_lifeTime']!=10 or motion['raw']['_speed']!=10:raise ValueError('Actual projectile dependency differs')
    dump=ROOT.parent/'Ark_data/dump.cs'
    if 'public const FilterUtil.FilterType HATRED_DES = 4;' not in dump.read_text(encoding='utf8'):raise ValueError('Source enum calibration')
    return {'schema':'ark-sim/ch6-snmage-source/v1','variant':v,'source_sha256':sha(SOURCE),'prefab_source':prefab['source'],'source_locks':s['source_locks'],'unique_nodes':{'normal_attack':normal,'cold_attack':{'path_id':8429431607679684984,**skillnode},'enemy_skill':enemy_skill,'ready_effect':ready,'selector':cfg,'root':root,'mover':mover},'deduplicated_labels':{'_combat':normal['path_id'],'_attack':normal['path_id']},'unique_normal_count':1,'projectile':projectile,'enum_source':{'path':str(dump),'sha256':sha(dump),'HATRED_DES':4},'policies':{'SP':'Only actual normal ability attack.accepted gets increment1; sole Cold replacement cost2/init0/max2. _castLikeAttack0 mapped to no SP recovery on skill impact. No periodic recovery','Ready':'Actual owned toggle child while SP>=2; stop on skill ability.started synchronously, then resource gate keeps child absent. Effect cue native snmage_skill_01_buff is cosmetic metadata','sorting':'HATRED_DES4 source enum exact; effective taunt descending and latest actorID descending are explicit replaceable hatred model','undefined':'Undefined DB immunity wrappers stay preserved; explicit reference getter defaultFalse, never claimed encodedFalse','timing':'Both RangedAttack nodes use same native Attack animation20; actual homing speed10 and lifetime10; source geometry mount offsets remain replaceable map-plane policy','priority':'Sole native priority0 Cold skill replaces normal at next accepted attack opportunity, with cooldown/init0. Silence12 rejects skill and normal fallback remains eligible'}}
def build(src):
    d=src['variant']['native_enemy']['resolved'];a=d['attributes'];nodes=src['unique_nodes'];cfg=nodes['selector']['raw'];steer=nodes['mover']['raw'];frame=nodes['normal_attack']['animation_binding']['events'][0]['seconds']
    trajectory='rule/'+UID+'/trajectory';collision='rule/'+UID+'/collision';eligibility='rule/'+UID+'/eligibility';score='rule/'+UID+'/hatred';gain='rule/'+UID+'/sp';held='rule/'+UID+'/ready_held';behavior='behavior/'+UID
    rules=[provider(trajectory,'projectile.trajectory','model.projectile.trajectory'),provider(collision,'projectile.collision','model.projectile.collision'),provider(eligibility,'targeting.eligibility','model.targeting.eligibility'),provider('rule/'+UID+'/steer','movement.steering','ark.movement.steering_velocity'),
        {'id':score,'kind':'rule','contract':'targeting.score','implementation':{'type':'expression','expression':"-100000 * (inputs.candidate.components.attributes.base.taunt_level if 'taunt_level' in inputs.candidate.components.attributes.base else 0) - inputs.candidate.id"}},
        {'id':gain,'kind':'rule','contract':'resource.recovery','implementation':{'type':'expression','expression':'inputs.current + inputs.parameters.amount'}},
        {'id':held,'kind':'rule','contract':'passive.toggle','implementation':{'type':'expression','expression':'inputs.owner.components.resources.sp.current < 2'}}]
    selector={'id':SELECT,'kind':'selector','region':{'type':'radius','radius':d['rangeRadius']},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{'rule':eligibility,'parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}}
    effect={'op':'damage','damage_type':'arts','scale':1,'projectile_definition':PROJECTILE,'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}
    cold=deepcopy(effect);cold['on_success']=[{'op':'buff_application','application_rule':'rule/ch6/cold/application','allowed':['buff/ch6/cold/e2c_cold','buff/ch6/cold/e2c_freeze'],'parameters':{'duration_seconds':10}}]
    normal={'id':NORMAL,'kind':'ability','selector':SELECT,'rules':{'targeting.score':score},'activation':{'mode':'automatic_attack','parameters':{'auto_only':True}},'timeline':[{'at_seconds':frame,'effect':effect}]}
    skill={'id':SKILL,'kind':'ability','selector':SELECT,'rules':{'targeting.score':score},'activation':{'mode':'manual','forbidden_source_flags':[12],'costs':[{'resource':'sp','amount':2}],'parameters':{'auto_only':True,'auto_when_ready':True,'replace_attack':True,'requires_targets':True}},'timeline':[{'at_seconds':frame,'effect':cold}],'metadata':{'source_priority':0,'source_init_cooldown':0,'source_cooldown':0,'native_cast_like_attack':0,'native_node':nodes['cold_attack']}}
    parent={'id':PARENT,'kind':'buff','toggle':{'rule':held,'buff':READY,'initial_enabled':True,'restore_delay_seconds':0,'events':[{'event':'ability.started','owner_role':'source','condition':"inputs.payload.ability == '"+SKILL+"'"}]}}
    child={'id':READY,'kind':'buff','stacking':{'mode':'independent'},'metadata':{'native_ready_effect':nodes['ready_effect'],'visual_signal':'snmage_skill_01_buff','combat_modifier':False}}
    unit={'id':UID,'kind':'entity','tags':['enemy','ground'],'metadata':{'native_variant_id':VID,'native_reference':src['variant']['native_reference']},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':a['attackSpeed']/100,'move_speed':a['moveSpeed'],'mass_level':a['massLevel'],'block_cost':nodes['root']['raw']['_blockVolume']}},'resources':{'hp':{'initial':a['maxHp'],'capacity':a['maxHp'],'role':'health'},'sp':{'initial':0,'capacity':2,'recovery_rule':gain,'recovery':{'mode':'event','event':'attack.accepted','owner_role':'source','amount':1,'condition':"inputs.event.ability == '"+NORMAL+"'"},'recovery_freeze_rule':'rule/ch6/cold/frozen_recovery'}},'abilities':[SKILL,NORMAL],'buffs':{'initial':[PARENT]},'selection_state':{**defaults(),'side':1,'unit_type':2},'spatial':{'motion_mode':0,'steering':{'rule':'rule/'+UID+'/steer','parameters':{'response_factor':steer['_steeringFactor'],'max_acceleration':steer['_maxSteeringForce'],'arrival_radius':.05}}},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':d['lifePointReduce']},'behavior':{'machine':behavior}}}
    projectile={'id':PROJECTILE,'kind':'projectile','motion':{'rule':trajectory,'parameters':{'mode':'homing','speed':10}},'collision':{'rule':collision,'parameters':{'enabled':True,'radius':0}},'lifetime_seconds':10,'max_hits':1,'can_hit_same_target':False,'stop_after_max':True,'stop_after_first':False,'attach_at_launch':False,'lifecycle':{'source_invalid':'retain','source_hidden':'retain','target_invalid':'cancel','target_hidden':'cancel','finish_on_reach':True,'hit_on_reach':True,'force_reach_on_expire':True,'hit_on_expire':True},'on_invalid':[]}
    return {'schemaVersion':2,'manifest':{'id':'package/ch6/snmage','requires':['preset/ark_standard'],'metadata':{'source_locks':{'packages/campaign/chapter06_sources/native.reference.json':sha(SOURCE),'packages/campaign/chapter06_cold/model.json':sha(COLD)},'builder_sha256':sha(Path(__file__)),'native_variant_id':VID,'native_reference':src['variant']['native_reference'],'source_binding':src,'reference_policies':src['policies'],'independent_reviewed':False,'formal_approved':False,'whole_stage_executed':False,'client_verified':False}},'rules':rules,'entities':[unit],'selectors':[selector],'abilities':[skill,normal],'buffs':[parent,child],'projectiles':[projectile],'behaviors':[{'id':behavior,'kind':'behavior','initial':'active','states':{'active':{}},'transitions':[],'decision':{'rule':'rule/ark_behavior_decision','default_mode':0,'profiles':[{'mode':0,'selectors':[{'key':'ranged','selector':SELECT}],'cast_groups':[{'key':'normal','abilities':[NORMAL,SKILL]}],'parameters':{'target_key':'ranged','stop_on_target':True,'stop_cast_groups':['normal']}}]}}]}
if __name__=='__main__':
    OUT.mkdir(parents=True,exist_ok=True);src=source();write(OUT/'source.reference.json',src);write(OUT/'model.json',build(src));print(json.dumps({'source_sha256':sha(OUT/'source.reference.json'),'module_sha256':sha(OUT/'model.json')}))
