"""Three exact same-actor mode consumers; no fabricated caster normal attacks."""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'packages/campaign/chapter07_boss/demons'
NAMES=['enemy_1084_sotidm','enemy_1085_sotiwz','enemy_1085_sotiwz_2']
LISTENER='buff/ch7/source/ore_listener';IMMUNE='buff/ch7/source/ore_immune'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def defaults():return {'side':0,'motion':1,'category':1,'profession':0,'unit_type':1,'abnormal_flags':[],'abnormal_combos':[],'target_free_flags':[],'target_free_combos':[],'target_free':False,'ally_target_free':False,'heal_free':False,'camouflage':False,'can_select_camouflage':False,'abnormal_immunes':[]}
def build(name):
 src=OUT/(name+'.source.json');s=json.loads(src.read_bytes());v=s['variant'];cs=s['prefab']['components'];db=v['native_enemy']['resolved'];a=db['attributes'];uid='unit/ch7/'+v['variant_id'].split('@')[0]+'/'+v['variant_id'].split('/')[-1];stem='rule/'+uid;reset='buff/'+uid+'/fsm_interrupt';caster=name!='enemy_1084_sotidm'
 p={'schemaVersion':2,'manifest':{'id':'package/ch7/demons/'+name+'/v1','requires':['preset/ark_standard'],'metadata':{'native_variant_id':v['variant_id'],'source_locks':{str(src.relative_to(ROOT)):sha(src)},'builder_sha256':sha(Path(__file__)),'reference_policies':s['reference_policies'],'mode_interface':'Sameactor behavior.mode0/mode1 viaactualtransition, sourceindices0/1','native_never_trigger':caster,'independent_reviewed':False,'whole_stage_executed':False,'client_verified':False}},'entities':[],'rules':[],'buffs':[{'id':LISTENER,'kind':'buff'},{'id':IMMUNE,'kind':'buff'},{'id':reset,'kind':'buff','duration_seconds':1e-8,'control':{'attack':False,'abilities':False,'interrupt':True}}],'abilities':[],'selectors':[],'behaviors':[]}
 p['rules']=[{'id':stem+'/eligibility','kind':'rule','contract':'targeting.eligibility','implementation':{'type':'provider','provider':'model.targeting.eligibility'}},{'id':stem+'/blocked','kind':'calculation_rule','contract':'targeting.eligibility','implementation':{'type':'expression','expression':"{'accepted':'blocked_by' in inputs.source.components.runtime and inputs.source.components.runtime.blocked_by == inputs.candidate.id,'reason':'nativeINPUT_TARGET2'}"}},{'id':stem+'/windup','kind':'rule','contract':'ability.windup','parameters':{'minimum_speed':.01},'implementation':{'type':'expression','expression':'inputs.timing_parameters.seconds / max(inputs.attributes.attack_speed_ratio, params.minimum_speed)'}},{'id':stem+'/duration','kind':'rule','contract':'ability.duration','parameters':{'minimum_speed':.01},'implementation':{'type':'expression','expression':'inputs.duration_parameters.seconds / max(inputs.attributes.attack_speed_ratio, params.minimum_speed)'}}]
 visual=[]
 for c in cs.values():
  if c['native_class']=='PassiveBuffAbility' and c['gameobject_name']=='Effect':
   for b in c['raw']['_buffs']:
    bid='buff/'+uid+'/'+b['buffKey'];visual.append(bid);p['buffs'].append({'id':bid,'kind':'buff','metadata':{'native_template':b['templateKey'],'source_visual_only':b['overrideEffectKey']}})
 initial=[LISTENER,IMMUNE];entries=[];abilities=[]
 if caster:
  interval='buff/'+uid+'/internal_interval';value=next(b for c in cs.values() if c['native_class']=='PassiveBuffAbility' for b in c['raw']['_buffs'] if b['buffKey']=='sotiwz_reset_base_attack_time')['blackboard'][0]['value'];p['buffs'].append({'id':interval,'kind':'buff','modifiers':[{'attribute':'attack_interval','layer':'flat','value':value}]});initial.append(interval)
 for mode in [0,1]:
  aid='ability/'+uid+('/immo' if caster else '/normal')+str(mode);abilities.append(aid);cond="(inputs.source.components.behavior.state if 'state' in inputs.source.components.behavior else 'mode0') == 'mode"+str(mode)+"'";entries.append({'ability':aid,'priority':0,'attack_clock':not caster,'require_attack_control':not caster,'condition':cond,'parameters':{}})
  if caster:
   comps=[c for c in cs.values() if c['native_class']=='MeleeAttack' and c['gameobject_name']==('Immo' if mode==0 else 'Immo[Rage]')];node=comps[0];raw=node['raw'];cfg=cs[str(raw['_selector']['m_PathID'])]['raw'];go=cfg['m_GameObject']['m_PathID'];radius=next(g['raw']['m_Radius'] for g in s['prefab']['geometry_sources'] if g['unity_type']=='CircleCollider2D' and g['gameobject_path_id']==go);member=stem+'/members'+str(mode);p['rules'].append({'id':member,'kind':'rule','contract':'area.members','dependencies':[stem+'/eligibility'],'parameters':{'radius':radius,'eligibility':{'rule':stem+'/eligibility','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}},'implementation':{'type':'provider','provider':'model.area.qualified_radius'}})
   sk=next(x for x in db['skills'] if x['prefabKey']==('Immo' if mode==0 else 'Immo[Rage]'));parent_skill=next(x for x in cs.values() if x['native_class']=='EnemySkill' and x['gameobject_path_id']==node['gameobject_path_id']);p['abilities'].append({'id':aid,'kind':'ability','initial_cooldown_seconds':sk['initCooldown'],'cooldown_seconds':sk['cooldown'],'duration_seconds':0,'metadata':{'native_skill_pointer':parent_skill.get('path_id'),'native_skill_fields':parent_skill['raw'],'native_sp_cost':sk['spCost'],'native_nevertrigger_normal_retained':True},'activation':{'mode':'manual','forbidden_source_flags':[0] + ([] if parent_skill['raw']['_ignoreSilence']==1 else [12]),'parameters':{'auto_only':True,'auto_when_ready':True,'blocks_attacks':False}},'timeline':[{'at':0,'effect':{'op':'area','target':'source','center':'source','membership_rule':member,'filters':[{'tag':'player'}],'effects':[{'op':'damage','damage_type':'arts','scale':1,'damage_flags':{'source_attack_type':'SPLASH','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}]}}]})
  else:
   sid='selector/'+uid+'/blocker';cfg={'_targetSide':2,'_targetMotion':1,'_targetCategory':1,'_ignoreMotionMode':0,'_ignoreTargetFree':0,'_onlyIgnoreSomeOfTargetFreeCase':0,'_needProfessionMask':0,'_ignoreAllyTargetFree':0,'_ignoreHealFree':0,'_forceIgnoreCamouflage':0,'_excludeSomeAbnormalFlags':0,'_checkUnitType':0};p['selectors'].append({'id':sid+str(mode),'kind':'selector','region':{'type':'all'},'filters':[{'tag':'player'},{'state':'alive'}],'limit':1,'eligibility':{'rule':stem+'/blocked','parameters':{'source_configuration':cfg,'side_policy':'relative_ally_enemy','neutral_policy':'reject','defaults':defaults()}}});anim=s['effective_animations'][mode]['source_animation'];frame=next(e['frame'] for e in anim['events'] if e['name']=='OnAttack');p['abilities'].append({'id':aid,'kind':'ability','selector':sid+str(mode),'target_capture':'at_cast','duration_seconds':anim['duration']['seconds'],'rules':{'ability.windup':stem+'/windup','ability.duration':stem+'/duration'},'activation':{'mode':'automatic_attack','settle_blocking':True,'parameters':{'auto_only':True}},'timeline':[{'at_seconds':frame/30,'effect':{'op':'damage','damage_type':'physical' if mode==0 else 'arts','scale':1,'damage_flags':{'source_attack_type':'NORMAL','ignore_for_sp':False},'read_mode':{'source_attributes':'at_hit','target_attributes':'at_hit'}}}]})
 root=cs[v['root_path_id']]['raw'];p['entities']=[{'id':uid,'kind':'entity','tags':['enemy','ground','ore_responsive'],'metadata':{'native_variant_id':v['variant_id'],'shared_listener':LISTENER,'shared_immune':IMMUNE},'components':{'attributes':{'base':{'max_hp':a['maxHp'],'atk':a['atk'],'def':a['def'],'mres':a['magicResistance'],'move_speed':a['moveSpeed'],'attack_interval':a['baseAttackTime'],'attack_speed_ratio':1,'mass_level':a['massLevel'],'block_cost':root['_blockVolume']}},'resources':{'hp':{'initial':a['maxHp'],'capacity_attribute':'max_hp','role':'health'}},'selection_state':{'side':1,'motion':1,'category':1,'unit_type':1,'abnormal_immunes':[12]},'spatial':{},'lifecycle':{'policy':'policy/ark_lifecycle','leak_loss':db['lifePointReduce']},'buffs':{'initial':initial},'abilities':abilities,'ability_arbitration':{'priority_order':'higher_first','busy':'all_casts','entries':entries},'behavior':{'machine':'behavior/'+uid}}}]
 states={}
 for mode in [0,1]:
  enter=[{'op':'apply_buff','target':'source','buff':reset},{'op':'remove_buff','target':'source','buff':reset}]
  leave=[]
  if mode==1:
   enter += [{'op':'apply_buff','target':'source','buff':x} for x in visual];leave += [{'op':'remove_buff','target':'source','buff':x} for x in visual]
  if not caster and mode==0:
   enter.append({'op':'apply_buff','target':'source','buff':LISTENER});leave.append({'op':'remove_buff','target':'source','buff':LISTENER})
  states['mode'+str(mode)]={'on_enter':enter,'on_exit':leave}
 p['behaviors']=[{'id':'behavior/'+uid,'kind':'behavior','initial':'mode0','states':states,'transitions':[]}];return p
if __name__=='__main__':
 for name in NAMES:
  p=OUT/(name+'.module.v1.json');p.write_bytes((json.dumps(build(name),ensure_ascii=False,indent=2)+'\n').encode());print(json.dumps({'name':name,'sha256':sha(p)}))
